### ISSUE TITLE
Community Survey Issue: Show list of lessons in progress

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1021]
Along the lines of this comment:
"Could you display in an easily findable place on the website the list of lessons in development, along with estimated timelines for their release? "

Do we want to showcase things in work? If so, at what stage would that be safe? I'm sure some authors may not complete lessons even after they are submitted on rare occasion?

**Comment by drjwbaker** [comment]
This speaks to who we think we are and what we think we are doing. We are a journal who does peer review in the open. However we aren't a pre-print server (like https://arxiv.org/ or https://wellcomeopenresearch.org/) because the nature of our content means that we need lessons that work, both technically and pedagogically. With that in mind, I'm not against the idea of showcasing work-in-progress. In essence any open issue at https://github.com/programminghistorian/ph-submissions/issues is work in progress, so I'm wondering if there would be a way to use the GitHub API to pull a list of open issues onto a 'Work in Progress' page (where this would sit I'm not sure), then put the results in reverse order (so, oldest issues at the top) to give a sense of which lessons are nearest to completion. I should add that I haven't used the GitHub API, so speculating a little here :smiley:

**Comment by acrymble** [comment]
I guess it could sit here James: https://programminghistorian.org/en/lesson-requests

**Comment by drjwbaker** [comment]
Changing the page to "Lesson Requests and in Progress"?

**Comment by drjwbaker** [comment]
Re #1034, this looks like we have a plan but need someone to take the job.

**Comment by mdlincoln** [comment]
I don't think this needs to be particularly fancy - just link to the ph-submissions tickets page.

**Comment by acrymble** [comment]
Can someone on the technical team take this on?

**Comment by mdlincoln** [comment]
We'll assign it as a task to one of the newer tech team folks at our next call

**Comment by mdlincoln** [comment]
Will discuss on #1358
