### ISSUE TITLE
Data Wrangling and Mng in R: Issue with download data

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1033]
While translating this tutorial I noticed that the data for the exercises won't download directly when "[clicking here](https://programminghistorian.org/assets/introductory_state_example.csv)" as directed. One can double click on the link and do "download linked file" but it could be confusing to some users. 

Also, two typos (haven't read the whole thing yet), "observent" and  "dicennial"

**Comment by jenniferisasi** [comment]
Semi-broken link "We are going to rely on the [history data](
https://www.google.com/search?q=cran%20historydat) a package" opens a search in Google, the site of the package itself being the first result.

**Comment by walshbr** [comment]
Good catches! 

I think you're right on the second note here - that should probably link directly to the history package. 

For the first note -  the direct download vs double clicking is dependent on which browser you're using. It downloads directly in chrome, opens a popup for opening vs saving in firefox, or just opens the file in window for Safari (so I bet you're using safari?). I was just poking around, and it looks like we might be able to force downloading the things by modifying the way it is linked to - https://davidwalsh.name/download-attribute. That'd require using inline HTML rather than the markdown syntax for linking. If it's a thing we really care about it might be worth doing a survey of older lessons to update them accordingly whenever we're having people download assets and updating the author/editor guidelines so that people use the correct syntax. I can do that, but would want to make sure it's something we want since it would an extra thing to the editorial/authoring process to keep track of.

**Comment by jenniferisasi** [comment]
Thanks @walshbr! I didn't know about the browser issue but should have checked cos I'm having Safari-not-updated as of late...It downloads if in zip (as in [here](https://programminghistorian.org/en/lessons/basic-text-processing-in-r#alternative-method-for-loading-the-corpus-optional))  I guess we should discuss it in group? It is not terrible so I leave it to you, since you have also more lessons. 

As I was adding contextual information on my translation, I noticed too that on the[ arrange function](https://programminghistorian.org/en/lessons/data_wrangling_and_management_in_R#arrange) it says that it's organizing the data in descending order from the Civil War but the first year is 1848 - the year the war against Mexico ended with the Treaty of Guadalupe Hidalgo. The data goes from 1636 to 1848, so descending order without filters is 1848 to 1636. Is it a mistake or am I missing something? Thanks!

**Comment by mdlincoln** [comment]
Hi @jenniferisasi just checking in on what needs to be done to close this ticket?

**Comment by jenniferisasi** [comment]
Hi @mdlincoln. The lesson has to be edited to fix the contextual error in the [arrange function](
https://programminghistorian.org/en/lessons/data_wrangling_and_management_in_R#arrang) section, and the typos. The issue I had with the link to download the date is not an issue in other browsers so it should be fine.  Should I go ahead and make the changes?

**Comment by mdlincoln** [comment]
yes, please make a PR. Thanks!

**Comment by jenniferisasi** [comment]
Edited.
