### ISSUE TITLE
Image for about page

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#113]
@ahegel I think we'd benefit from one of the images you've been using on the lessons page for the front page too. Is there something that speaks for the whole project? It's just too text-y on that front page. Thoughts?

**Comment by ahegel** [comment]
Great idea! I did a quick search and found a few possibilities - what do you all think?

Scholars at desks: [option 1](https://www.flickr.com/photos/britishlibrary/11244386275/), [option 2](https://www.flickr.com/photos/internetarchivebookimages/14764047142/), [option 3](https://www.flickr.com/photos/internetarchivebookimages/14591183250/), [option 4](https://www.flickr.com/photos/internetarchivebookimages/14596261850/), [option 5](https://www.flickr.com/photos/internetarchivebookimages/14784384165/)

Scholars with machinery: [option 6](https://www.flickr.com/photos/britishlibrary/11226559263/), [option 7](https://www.flickr.com/photos/internetarchivebookimages/14773057292/)

Library: [option 8](https://www.flickr.com/photos/britishlibrary/11187613374/)

I'll keep my eye out for more pictures, but feedback would be helpful to make sure I'm on the right track. Also, if you have ideas for other directions to go in, please let me know!

**Comment by acrymble** [comment]
I think option 3 is pretty good. A bit of tech. A bit of people.

**Comment by miriamposner** [comment]
Can we get one with a lady and/or non-white guy in it? I know it sounds silly, but I just want to be extra-sure everyone knows they're welcome, given programming's less-than-sterling reputation. But I agree that these are on the right track!

**Comment by acrymble** [comment]
Might be a big ask given the 19th century motif. I wonder if we can find
something other than a lady at a typewriter.

Maybe something with Ada Lovelace?

**Comment by ahegel** [comment]
The only ones I could find with non-white-guys were photographs, which don't quite go with the book-image aesthetic we have for the lesson images, but that might be okay. I could also try to edit the photo to be a bit more sepia-toned in order to fit better, but no promises on how well that will turn out. Let me know if that sounds like a good idea.

Here are some options:
[NASA](https://www.flickr.com/photos/nasacommons/9467782802/)
[Computer](https://www.flickr.com/photos/sdasmarchives/5018415381/)
[Office](https://www.flickr.com/photos/twm_news/9717154582/)

These are great but the copyright is a bit more restrictive:
[Grace Hopper](https://www.flickr.com/photos/101251639@N02/9672667726/)
[ENIAC](https://www.flickr.com/photos/dennissylvesterhurd/6931939010/)

We could also do something a bit more abstract like a banner with this letter from Ada Lovelace to Charles Babbage (unclear copyright restrictions): [letter](http://www.bl.uk/collection-items/letter-from-ada-lovelace-to-charles-babbage)

**Comment by acrymble** [comment]
Maybe we could commission something from an artist, using one of the ones
Allison has found as a guide to give them?

**Comment by miriamposner** [comment]
Do you guys think the bottom half of the book cover would work? It's in
color, which is different from our other images, but maybe?
https://archive.org/stream/How.It.Works.The.Computer.1971.Edition.David.Carey#page/n0/mode/2up

**Comment by acrymble** [comment]
I appreciate the goal Miriam, but I don't think it's a god idea to change the style of the imagery.

What about something that just doesn't have any people in it? The 10-Head Stamp Battery in this image is pretty cool looking:

https://www.flickr.com/photos/britishlibrary/11204383866/in/album-72157639428882575/

**Comment by miriamposner** [comment]
Yes, cool! I like it.

**Comment by ahegel** [comment]
A tip from a peer about the 1890s census led to this image of a woman operating a keypunch that might work well: [image](https://en.wikipedia.org/wiki/1890_United_States_Census#/media/File:1890_Census_Hollerith_Electrical_Counting_Machines_Sci_Amer.jpg).

**Comment by acrymble** [comment]
roll with it.

**Comment by miriamposner** [comment]
Love it!

**Comment by ianmilligan1** [comment]
Chiming in - love it too!






On Tue, Jul 7, 2015 at 9:35 AM -0700, "Miriam Posner" <notifications@github.com> wrote:










Love it!



On Tue, Jul 7, 2015 at 9:12 AM, Adam Crymble <notifications@github.com>

wrote:

**Comment by ahegel** [comment]
I added the image to the /jekyll/images folder as "about.png". I'd happily add it to the about page myself but I wanted to make sure to put it in the right place - should it go the top, below the title, or somewhere else?

**Comment by acrymble** [comment]
Thanks, I've added it in. How do we add a CSS class to it? It's too big at
the moment and pushing the content all below the fold.

Adam

**Comment by ahegel** [comment]
I updated the about page to let you specify the desired pixel height - it's at 400 now but feel free to play with it until it's the right size!
