### ISSUE TITLE
Shadowing milestones

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1149]
As discussed at #1103, it might be useful to somehow standardise expectations and milestones for the shadowing process for new editors. 

Here is a draft text I compiled - I used a couple of very useful tips my shadow editor @walshbr  gave me (thanks ;-) . Please go ahead with suggestions, corrections, comments etc esp from experienced editors, so we could add it to the wiki pages. I was also thinking about covering this text /list to a FAQ- thoughts?

By **shadowing** we mean the informal way for a new editor to learn what it is like to edit a lesson; the new editor follows around / shadows an editor, currently embarked on an editorial process for a lesson. The shadow editor should include the new editor in all communications with the lesson's author, feel free to ask her to help with any editing task during the process so she will get a first hand experience and, most importantly, be ready to answer any questions the new editor might have regarding the editorial process. The shadow editor might also play the role of the mentor during the new editor's first editing lesson.

It goes without saying that everyone has a different background and a slightly different approach to the editorial process (while following the [Editorial Guidelines](https://programminghistorian.org/en/editor-guidelines)), and that's probably just fine. For this reason, it is really difficult to create a definite list of milestones a new editor should make sure s/he is aware of before editing hers first course.

Below is an indicative list:

- choosing the peer reviewers : Its OK if you don't have real expertise in the area that is under discussion in the particular lesson you are editing - this is not a mandatory requirement. Its useful though to try to edit lessons that you have some interest in or even experience based on the topic, as this would make the entire process more easy , interesting and fun.

In terms of choosing the external peer sreviewers, it is useful to have someone read the piece who is engaged and with some relevant background. If these are really meant to be lessons as well as articles, we want them to be legible for a broad audience after all. And you can always try to find reviewers who help to offset your perceived lack of expertise. Seeing yourself and your background as working together with the reviewers might help in that sense - you can each make up for what the others are lacking.
We are having a pool and a spreadsheet of reviewers, mainly in order to keep track of who we 've already asked, but feel free to contact anyone from your personal network of peers or ask for recommendation the PH team. In the past, it has been also a twitter call for reviewers for specific lessons.
While choosing peer reviewers, do have in mind also our diversity policy and try to include people and groups that are somehow less represented in our team.

- communication : try to keep the communication clear and consistent in style all the times, respecting also our [Anti-Harassment Policy](https://programminghistorian.org/en/editor-guidelines#anti-harassment-policy). As for the initial contact with peer reviewers, drop an email to ask them to review and once they accept and provide you with their GitHub name, then move and try to keep the communication entirely on GitHub.  Its important you are guiding the conversation towards the lesson's review progress while trying to keep an overall positive, supportive and relaxed tone with everyone involved in this process.  

- timeline:  in order to keep things in track, you as editor are responsible to make both the author and the reviewers aware of the timeline of the editing . Be clear and realistic about expectations and timeframes and be open to accommodate particular needs and special circumstances .

- things we generally check in a lesson (alongside the reviewers' comments and the [Editorial Checklist](https://programminghistorian.org/en/editor-guidelines#technical-processes-of-review---editorial-checklist)): 
- [ ]  overall structure 
- [ ]  easiness to follow the narrative flow
- [ ] language 
- [ ] cultural inclusivity
- [ ] grammar / syntax
- [ ]  layout 
- [ ]  additional files

**Comment by spapastamkou** [comment]
Perhaps we could also make a small list of things to check in a translation? We have evoked some ideas now and then with the @programminghistorian/spanish-team

**Comment by acrymble** [comment]
I think it's a good idea to have guidelines like this for shadowing. @amsichani did you want to continue working on this?

**Comment by amsichani** [comment]
Thanks @acrymble - I haven't heard any feedback from the team on this and I wasnt sure how to deal with it. I am happy to work on this - how do you think it might evolve? into a wiki page perhaps?

**Comment by acrymble** [comment]
I would go so far as to say this should be a "role" that someone is dedicated to. Effectively training and mentoring new members of the team.

**Comment by drjwbaker** [comment]
@spapastamkou: as we go through editing the Evaluating Topic Model lesson, perhaps you could think about anything I could be doing better and post it here?

**Comment by amsichani** [comment]
That would be really useful @spapastamkou , as I am now trying to put together a set of guidelines/best practices for shadowing.

**Comment by spapastamkou** [comment]
I just came back from Beirut. If not able today, I will contribute tomorrow, James is really helpful and there are surely things to be said here. 

Envoyé de mon iPhone

**Comment by spapastamkou** [comment]
Ok, there I go to report my personal experience of shadow editing with @drjwbaker and maybe you can draw things from here, @amsichani. 

James first asked me **what I expected** myself from shadowing with two **possible options** being: 1) simply being in copy of the messages so that I can follow; 2) in addition of being in copy, receive commentary from James for each step taken so that I have a clear idea of why things are done the way they are. I was also **invited to join the conversation**, if I wished, and watch over the steps taken. 

I personally chose option 1 with the intention to ask for precisions during the process, if something did not seem clear enough. So, a combination of both options actually. I must say James provided the answers before I had the time to ask the questions, for example when he contacted possible reviewers for the lesson. Furthermore, he took care to remind the steps to take one by one, for example, that when answers from reviewers are received, the editor should add info in the reviewers tracking sheet.

The lesson is still edited but here is what I already see as positive points in my experience: 
1) this is a flexible process that is quite light and can be adapted depending what one needs. I appreciate that James is careful to provide info that I might not ask for various reasons (missing what's going on, have the question but wait to see what happens instead of asking right away etc) 
2) personally I found the process reassuring because I opened at the same time the first ticket of review for a translated lesson. I had read the editor guidelines, but still it is better to be in the process with someone who already knows and can be mentor just in case you need an advice. 

If specific guidelines are to be prepared for the shadowing process, I think it would be useful for the parties involved to have a description of the specific steps to take, but also to keep in mind that the needs can be different and, depending the case, these steps can be more or less fleshed with detailed explanations (this is to be agreed between the shadow-er and the shadow-ee).

I'd recommend @drjwbaker, by the way:)

**Comment by acrymble** [comment]
I have volunteered to take on the role of supporting new team members. Did you want help with this @amsichani ?

**Comment by acrymble** [comment]
I have read through the comments on this thread, and they look more like reflections on personal experience rather than guidelines.  Using those as a starting point for guidelines, I would suggest we add the following to the Wiki:

1. The more experienced editor and the shadowee should have a conversation before beginning that  outlines the expectations and needs of both sides. Different people may prefer different approaches. For example, some shadowees may like to watch and be cc'd into correspondence. Others may prefer the chance to take the lead, with comments and interjections from their more experienced colleague. There is no one approach, and the conversation will help you decide what will work best for you.

2. Choosing peer reviewers can be difficult for new editors. A good shadowing experience should include a discussion as well as tips on how to best identify suitable peer reviewers, and how to approach them effectively. Shadowees should be reassured that they will probably not know peer reviewers personally, but need to feel comfortable approaching them.

3. Shadowees may have concerns or questions about tone or style.  They may not be sure how often or how much to post. It is a good idea to discuss this with them, pointing to examples of other reviews as necessary.

4. Troubleshooting technical issues can be difficult. Make sure you discuss who the shadowee can turn to for support if they are editing a lesson and run into trouble.

5.  After the shadowing experience is over, we recommend that both parties discuss the process and learn from each other how they could strengthen the experience in future. This is also a good time to ask further questions.

---

This has already been open more than 6 months so I'm going to add the above to the Wiki and will close this ticket in a few days unless I hear otherwise.
