### ISSUE TITLE
introducing the PH en Français - blogpost in French

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1161]
As we are witnessing the successful  launch of the Programming Historian en français 🚀, it would be great to write a blogpost en français introducing the initiative to our French-speaking readers around the world, asking them to contribute with French  tutorials and/or translating existing lessons. Feel free also to use the twitter in order to post tweets  en français - we are also having sporadically tweets in Spanish.

@spapastamkou @mpuren @fdlaramee are you ready to rock?

**Comment by symac** [comment]
Just adding a +1 there, I have just heard about this upcoming French translation from a tweet, and came there to find more on the best way to join the team and the issues I have found flagged french have not been very helpful. 

So would be happy to find more information on this, as the issues I have seen there are not very helpful for the moment. I had already translated some lessons in the past and would be happy to translate / review more : 

* [introduction-and-installation](https://symac.github.io/jekyll/fr/lecons/introduction-et-installation) (**done**)
   * [mac-installation](https://symac.github.io/jekyll/fr/lecons/installation-python-mac) (partial)
* [viewing-html-files](https://symac.github.io/jekyll/fr/lecons/comprendre-les-pages-web) (**done**)
* [working-with-text-files](https://symac.github.io/jekyll/fr/lecons/travailler-avec-des-fichiers-texte) (**done**)

**Comment by spapastamkou** [comment]
ok @amsichani, we'll work on that with @fdlaramee and @mpuren. 

@symac thank you! Can we take contact by e-mail? I am spapastamkou on gmail, if you write me I can put in copy the rest of the team to exchange all together.

**Comment by mpuren** [comment]
Ok @amsichani !
Thank you @symac, we'll be happy to work with you

**Comment by spapastamkou** [comment]
I put some ideas for structuring a blog post in [this pad](https://mypads.framapad.org/mypads/?/mypads/group/proghist-fr-m56us7cv/pad/view/blogpost-ph-fr-dp32ks7tn). I think this could help us have a text by next week to put here in comment. All ideas are welcome, we can add, change things etc. Maybe @mdlincoln can suggest a formulation for the Mellon Foundation sponsorship?

**Comment by fdlaramee** [comment]
The blog post structure seems good to me. As I mentioned in #1184 I think that a low-key appeal to potential volunteers (in paragraph 2) is a good idea, provided that we make sure to mention that we're not quite ready to send them work right away.

**Comment by spapastamkou** [comment]
Please find below a text project for a blogpost in EN for comment. Once we agree on its final form, we can prepare a FR version as well. Note that we could add names of volunteer translators/reviewers in paragraph 4 depending on the time of publication of the blogpost (if lessons are published by then).  

### Text project for the blogpost in EN

The Programming Historian en français is on air! You can find us on http://programminghistorian.org/fr The launch of a francophone version comes two years after the inauguration of a successful Spanish-speaking edition, and confirms the [ongoing internationalisation](https://programminghistorian.org/en/about#history-of-the-project) of the original English-speaking project. We propose open peer-reviewed tutorials that aim at helping historians and other humanists to gain familiarity with interdisciplinary methods, digital tools, and workflows that enable them to conduct research projects and teaching duties with use of digital data. As diversity is at the core of the global project, all variations of the French language are accepted. Moreover, The Programming Historian en français is committed to the use of the gender-inclusive writing following the principles set by the Office québécois de la langue française.   

We currently work principally on translations of the existing tutorials. If you wish to suggest an existing lesson to translate, for example for use in your classroom, or if you want to contribute yourself either translating or reviewing an existing translation, or even proposing an original lesson, please let us know. You can find more information on how to [contribute](https://programminghistorian.org/fr/contribuer) in the dedicated page of our web site. We are eager to receive your proposals!
    
The francophone project has found spontaneous support from the community since its beginnings. We thank warmly volunteers who acted either as translators or reviewers; students of the master "Digital Technologies Applied to History" of the Ecole nationale des chartes, and their teachers, Thibault Clérice and Meg Roussel, for offering a corpus of translations prepared as an exercice for their English class; and [all friends who contributed in exchanges on the title and logo of the francophone version](https://github.com/programminghistorian/jekyll/issues/850). 

_In-kind sponsorship by CMU/Mellon Foundation_ (hello @mdlincoln:-)).

Last but not least: the launch of The Programming Historian en français is a team achievement in the sense that the intensive work of the French-speaking sub-team was greatly helped by exchanges with its Spanish-speaking counterpart, benefited of continuing support from more experienced members and could count on their technical - and pedagogical! - skills for setting up the necessary infrastructure. We are thrilled to be part of this global project and look forward for what comes next!

**Comment by acrymble** [comment]
I'd suggest adding an image to make it more visually interesting. Otherwise it's your announcement so I'm happy for you to say whatever you like.

**Comment by mpuren** [comment]
Thank you @spapastamkou , I really like the post. Just a minor suggestion : we could add the link towards "the principles set by the Office québécois de la langue française"(http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?Th=1&Th_id=274). That's all!

**Comment by spapastamkou** [comment]
Some updates here: 
- Image for the blogpost: found this image from the Mundaneum archives in Mons, Belgium http://archives.mundaneum.org/fr/versions-digitalisees/schema-de-paul-otlet-documentation-et-telecommunication and have been trying since last week to obtain info (by e-mail, telephone, even Facebook) from the archives if we can use it. I'll continue the efforts, but if someone has other alternatives, please comment! 
- @mdlincoln, do you have suggestions about how to formulate the part of the blogpost expressing gratitude for the in-kind sponsorship by by CMU/Mellon Foundation?

**Comment by spapastamkou** [comment]
image update: the Mundaneum Archives agree that we use the image of Paul Otlet's scheme and proposed to send us a HD image file. We shall of course need to mention the source: "Mundaneum, centre d'archives (Mons - Belgique)", which we would do anyway.

**Comment by mdlincoln** [comment]
>Preparing _The Programming Historian_ to accommodate languages beyond English and Spanish required extended effort from our technical team, in particular from [Matthew Lincoln](https://github.com/mdlincoln), whose development time was supported through an in-kind grant from the [dSHARP lab at Carnegie Mellon University](http://dsharp.library.cmu.edu/) and the [Andrew W. Mellon Foundation](https://mellon.org/).

**Comment by acrymble** [comment]
@spapastamkou Is this ready to publish?

**Comment by spapastamkou** [comment]
@acrymble Yes, I do last checks on the EN text and on the FR translation I prepared. Will post texts here by the end of the day.

**Comment by spapastamkou** [comment]
I reopen this ticket to create a brabch out of it and fix the date of the two blogposts (month/day are reversed in the files naming)
