### ISSUE TITLE
Recruitment of french-speaking reviewers and translators

### ISSUE THREAD

**Issue by mpuren** [programminghistorian/jekyll#1184]
Translators and reviewers are not necessarily members of the PH team, but they can contribute to the project such as authors or reviewers of any journal.

Those who are interested by acting as reviewers or translators for the Programming Historian en français can read : [Consignes aux évaluateurs et évaluatrices](https://programminghistorian.org/fr/consignes-evaluateurs), [Consignes aux auteur(e)s et aux traducteur(rice)](https://programminghistorian.org/fr/consignes-auteurs), [Consignes aux rédacteurs et aux rédactrices](https://programminghistorian.org/fr/consignes-auteurs)

List of actions to recruit French-speaking reviewers and translators:
- [ ] Emailing contacts who can join the project as reviewers and/or translators 

- [ ] Publishing blog post + twitter

- [ ] Sending emails to French-speaking mailing list such as the "DH" mailing list

This recruitment process will start after the official publication of our first lessons in French in the spring.

**Comment by acrymble** [comment]
Can we just clarify that reviewers and translators don't need to join the "team" https://programminghistorian.org/en/project-team. Most authors and reviewers are not on our board. They just contribute to the project in a way similar to authors and reviewers of any journal.

**Comment by mpuren** [comment]
@acrymble Done. And thank you for your comment

**Comment by spapastamkou** [comment]
Thank you for this ticket @mpuren. 
A small question: the blog post you propose would be the same as in #1161 or a separate one? We could perhaps use the announcement of the launch of the FR PH (or not) to say that we are open to reviewers and translators. But in any case, before going further, it would be important to: 
- finish with #1161
- name our Managing Editor (to have a point of contact)
- prepare the wiki that documents the FR translations (to give clear info on our choices and mainly inclusive writing)
- not get lost in our translations:-) and give a clear idea to potential reviewers of what is available. Meaning we must publish a list of translations in our FR repository in ph-submissions, as agreed during our #1136 meeting (following the ES example here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md )

Otherwise, I already prepared this we a very basic readme and a translation of the template for translations in FR for our repository. 
Perhaps @fdlaramee has suggestions as well?

**Comment by fdlaramee** [comment]
My gut instinct would be to include a low-key sentence in the #1161 blog post to say that we will be launching a formal search for translators and reviewers later this Spring and that in the meantime people who wish to volunteer should contact the Managing Editor, who will respond with instructions when they are ready. Something like what @spapastamkou wrote in Paragraph 2 of the pad, but with a qualifier that we're not quite there yet.

What is the Managing Editor's role, beyond being the point of entry? I would assume that this person would maintain the list of translations completed/in progress/available as well? Since there are only three of us and we need both a ME and an ombudsperson, I'll defer to @mpuren and @spapastamkou and take whatever role they don't want, if any.

**Comment by mpuren** [comment]
@spapastamkou: During a meeting with @jenniferisasi, I've written someting like "Lauching the recruitment of French-speaking reviewers and translators with a post and a tweet". So in my mind, it should be a different blog post - what you said in the 2nd paragaph of #1161 blog post is enough for now.

Good question @fdlaramee. But shouldn't it be the editor's role - I mean, maintaining the list of translations? @jenniferisasi : what is your advice?

**Comment by spapastamkou** [comment]
I just sent message to following lists: quanti, dh, accesouvert, enumhist (FR).

**Comment by spapastamkou** [comment]
I reopen this issue just to make a small update on impact after sending the message of announcement of the PH FR and the blogpost link. 
Up until now we had 4 people contacting the FR team: one has already submitted a translation proposal which is in progress (here: https://github.com/programminghistorian/ph-submissions/issues/236); one more will be available to translate from September on (probably on network analysis lessons); and two more propose various translations, contacts are in progress. If they lead to new proposals, I will open tickets in ph-submissions repo.
