### ISSUE TITLE
workflow for announcing new lessons

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#119]
I don't think we've sorted this out yet. How do we want to announce new lessons? I feel like this should be consistent. Something like:

* New blog post containing title, name and 1 sentence bio of author, and abstract
* Tweet on corporate twitter account
* Email to author to encourage they disseminate widely

**Comment by miriamposner** [comment]
That's a good idea. As the Tweeter-in-Chief, I try to catch and tweet the
new lessons, but I'm not sure I always catch them. If someone could @-me in
a Github message thread, I'd be sure to see them.

MP

**Comment by wcaleb** [comment]
Since the RSS feed should now include lessons (see #123), I don't think we need a blog post for every new lesson. But we could periodically have a blog post that features recent lessons, or that explains how one could string together several lessons to accomplish some new task.

**Comment by acrymble** [comment]
As someone who hasn't used RSS for years, I wouldn't say that's enough publicity for a new lesson. I'd like to see something more active given the amount of work that goes into them.

**Comment by wcaleb** [comment]
Fair enough. But if we are going to announce by post every time, then there's no reason to add lessons to the RSS feed, which already includes blog posts. By the way, one of the things you mentioned was an abstract. I think it might be good to add an abstract to the YAML metadata of new lessons; if we do that, I can also incorporate the abstract into the RSS feed.

**Comment by fredgibbs** [comment]
One of my summer fellows (Evan) is working on a set of blog posts for us
(in lieu of a lesson) to show how to use PH lessons in the undergrad
classroom. This was his idea, but I really like it, and I think it suggests
a lot of potentially cool uses for the blog that we haven't really tapped
into so far. It's maybe something we could encourage more on the contribute
page.

I'm not a huge fan of creating blog entries just to announce a new lesson
since they're in the feed now, and they're kind of a pain to keep up on. I
think the lessons should (and most do) introduce themselves, so we can
point people to the lesson itself when first publicizing it via Twitter,
etc, and they can get see the abstract, author bio, reviewers and just skim
the whole thing. I agree we could and should use a more prolonged lesson
launch protocol to garner more attention to new lessons, but I don't think
the blog posts would contribute anything that the RSS feed doesn't already.
So, that's the long-winded way of saying +1 for abstracts in the YAML so we
can standardize them both in content and form--in both lessons and the feed.

On Mon, Jul 27, 2015 at 10:40 AM, W. Caleb McDaniel <
notifications@github.com> wrote:

> Fair enough. But if we are going to announce by post every time, then
> there's no reason to add lessons to the RSS feed, which already includes
> blog posts. By the way, one of the things you mentioned was an abstract. I
> think it might be good to add an abstract to the YAML metadata of new
> lessons; if we do that, I can also incorporate the abstract into the RSS
> feed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/119#issuecomment-125267582
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by acrymble** [comment]
This is now part of the editor guidelines (though it could use some expanding).
http://programminghistorian.org/editor-guidelines
