### ISSUE TITLE
Translators Guidelines

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1199]
In #1189 there was discussion between @programminghistorian/spanish-team and @programminghistorian/french-team whether it would not be better to have separate guidelines for translators in the ES and FR versions of the PH with maybe some info included in the EN version. I open this ticket so we can have a point of discussion in view of the March meeting.

**Comment by jenniferisasi** [comment]
Suggested in #1196: 
- Create a separate, general page with the translation guideline (separated from author a lesson)
- Create a wiki page with translation tips similar to the translation *R for Data Science* that @rivaquiroga coordinates + tips shared between the Spanish and French team.

**Comment by arojascastro** [comment]
It would be cool to build a glossary like this - maybe in the wiki: https://docs.google.com/spreadsheets/d/1EcMX-GtUEp3BODLOzrUOge6j_YfO8X84UivCug0bQYE/edit#gid=2011677898

With several variants, for instance:

computer - computadora - computador - ordenador 

I took it from: https://www.localizationlab.org/glossaries

@rivaquiroga

**Comment by acrymble** [comment]
We need these in English as well. I've had a look at the guidelines that are available on the Spanish site, and from what I can tell the advice reads:

> 
> If you would like to translate a lesson from Spanish or French into English, please contact our managing editor to discuss your language skills and translation experience. We look for translations that are rigorous, readable, and consider the needs of an English-reading audience.
> 
> To avoid delays in publishing, we ask that you submit your translation within 90 days of the editor accepting your proposal.

What else would an author need to know? Can we start making a list?

Do reviewers need to know something different?

**Comment by jenniferisasi** [comment]
I want to start working on this separate translator guideline (we will have guideline for authors, reviewers, editors, and translators in this manner). We can do it first in English (I will translate what we have from Spanish) and then move on to Spa and French so that a few of us can collaborate. 

What would it be the best way or the best folder for me to create the markdown file as a draft and maybe a few of us can edit?

**Comment by arojascastro** [comment]
Great idea! So we can all suggest ideas and contribute to a text in English and then translate and adapt into Spanish and French. I think you can create a branch 1199 and create the file in https://github.com/programminghistorian/jekyll/tree/gh-pages/en and then we do a pull request.

**Comment by arojascastro** [comment]
As I said in a different issue, at present, each language team has to update their list of pending translations by hand.

It is not a big problem, but maybe we could use only and link in this page the concordance created by @mdlincoln : https://programminghistorian.org/translation-concordance 

It is automatically generated, so it is easy to maintain :)

The table should contain only lessons - rather than pages - and it needs some cleaning. The main disadvantage is that it does not reflect our decision on not to translate a number of lessons that are language dependent or that have been archived. 

Is there any way to improve the concordance list?

**Comment by jenniferisasi** [comment]
Ah, and we should have a little paragraph at the beginning of the guidelines to point to this list. Let me check your other comment... on [ph-submissions #238](https://github.com/programminghistorian/ph-submissions/issues/238#issuecomment-489449752)

**Comment by acrymble** [comment]
I would love for the English team to be able to start translating the new lessons from Spanish. Is this being worked on actively?

**Comment by jenniferisasi** [comment]
> I would love for the English team to be able to start translating the new lessons from Spanish. Is this being worked on actively?
We have been working on it on pull request #1260, my [last comment](https://github.com/programminghistorian/jekyll/pull/1260#issuecomment-507300171) from half a month ago that no one responded to, so I will keep working on it.

I hope that was what you meant in your question. Also, to help out on that, do you want to open an issue to talk about how to get translators, reviewers, etc.? You need to set that up as you haven't had it before in the English team.
