### ISSUE TITLE
DOIs for articles

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1205]
This was initially a reviewer 's question on our Insight article: given we now have an ISSN (actually 3) in place, and we are presenting PH as an OA journal with peer-review articles/tutorials, what about DOIs for articles/ tutorials and ORCID iDs for contributors (authors)?

my comments on this:
- I think the ORCiD idea is a good point and it d be an interesting addition to our scholarly publishing infrastructure. 

- As for the DOI, my understanding is that it clashes somehow with our CC policy , as [DOI](https://www.doi.org) is a proprietary service through RAs (DataCite- British Library in our case) and DOIs are mainly for paywalled or Green OA articles in order to be able to locate them in different repos.
I guess if we decide to go for the ORCiD addition, this also needs a couple of technical adjustments (ORCiD field per contributor) as well as a couple of lines in our author guidelines.

**Comment by acrymble** [comment]
Just some historical context. DOIs have been discussed in a number of tickets: #64 #410 to name a few.

We ultimately rejected it on the basis that our lessons sometimes get updated, and this would require a new DOI (you can't change something and keep the same DOI). It also wasn't clear how we could get easy DOIs since we aren't supported by a major library. That may be easier now, I don't know. But I thought I'd share the links to the earlier discussions for those who weren't with us then. I have no strong opinion so happy for anyone to do some digging if they want.

**Comment by drjwbaker** [comment]
Yeah, DOIs are out, but we do have the DOI for the annual releases https://zenodo.org/record/1477854

ORCID is worth pursuing, though we may need to bring in the relevant expertise to make it work.

**Comment by mdlincoln** [comment]
I have some notes on ORCID (tl;dr:  the simple answer may indeed be "orcid doesn't like static sites") but am splitting it off to #1208

**Comment by mdlincoln** [comment]
I'm going to close this because there's not much active discussion and the same roadblocks in place from #64 and #410 still apply - the way we version wepages as the site rebuilds does not match to the way that DOIs are envisioned.
