### ISSUE TITLE
Submodules/Jekyll/page build failure

### ISSUE THREAD

**Issue by miriamposner** [programminghistorian/jekyll#122]
I've been meaning to update the Omeka.net lessons with images for the new version of Omeka. I was able to make changes and push to the gh-pages branch, but I also got an email reading, "The page build failed with the following error: "The submodule `jekyll` was not properly initialized with a `.gitmodules` file." I followed [the instructions] (https://help.github.com/articles/page-build-failed-missing-submodule/) for initializing the submodule (at least I think I did; I did it inside the Jekyll directory), but, sadly, it didn't seem to work. NBD, just want to figure out how to do it.

**Comment by miriamposner** [comment]
Also, I hope I didn't break Jekyll.

**Comment by wcaleb** [comment]
To be honest, I'm not really sure what happened! But I think the root of the problem was that you initially started making changes on the `master` branch. It's better just to work on the `gh-pages` branch (which you can get to locally with a `git checkout gh-pages`. You can always see which branch you are on locally with `git status`.

I've reverted the changes you made to the master branch, so I think everything's back where it was. You'll need to do a `git pull` to bring everything back up to date on your local machine, but let me know if you see other weird messages when you do.

Unrelatedly, it looks like you used standard Markdown syntax for the images in this lessons. When you get a chance, could you update them using our [special figures syntax](https://github.com/programminghistorian/jekyll/wiki/Markdown-Style-Guide#figures)?

**Comment by acrymble** [comment]
I feel your rage Miriam.

**Comment by miriamposner** [comment]
Thanks, Caleb! 

(RAGE!!)

Miriam

**Comment by wcaleb** [comment]
Yes, indeed, git can occasionally be rage inducing!
