### ISSUE TITLE
New Editorial Team Roles assignments

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1285]
As per #1183 we have agreed to implement a series of new "Roles" for the project team. These roles will make it easier for team members to define their contribution, while enabling the team to identify its strengths and where more resoures may be required. All members of the team must have at least 1 role.

All roles marked "leadership" will need to be covered in the case of temporary sabbaticals or leaves of absence. All members of the team please identify which roles you feel you would be interested in taking on. You can express interest in a role even if someone else's name is already next to it.

**Editorial Team**

Managing Editors: First point of contact for their respective publication. Has oversight of the publication and is responsible for overall quality. (**leadership**)

- Managing Editor (English) - @alsalin (@acrymble - temporary)
- Managing Editor (Spanish) - @mariajoafana 
- Managing Editor (French) - @spapastamkou 
- Ombudsperson (English, Spanish, and French - independent of managing editor control) - @amandavisconti @mariajoafana @fdlaramee @vgayolrs @mpuren

Responsible for editing/translating lessons. Reports to the Managing Editor.

- Editor (English) @drjwbaker @acrymble @amsichani @jmparr @walshbr 
- Editor (Spanish) @rivaquiroga @vgayolrs @arojascastro @jenniferisasi @JoshuaGOB 
- Editor (French) @fdlaramee @spapastamkou @mpuren

**Technical Team**

Responsible for the maintenance and development of the website and any technical features.

- Technical Manager (has strategic oversight (**leadership**)) @mdlincoln
- Technical Team (reports to technical manager) @jenniferisasi, @amsichani, @spapastamkou, @ZoeLeBlanc , @arojascastro, @walshbr 
- Archivist ( Manages regular deposits to Zenodo of Programming Historian project and publications. Co-ordinates keeping Directory of Open Access Journals listing up to date.) @drjwbaker
       
**Communication**

- Communication Manager (Twitter, blog, etc (**leadership**)) @jenniferisasi
- Twitter Bot developer @walshbr 
- Education Manager (responsible for the overall education aspect of the project (**leadership**)) @amsichani 
- Research Impact Manager (supports and enhances research impacts cases for all contributors & outputs / coordinates users' analytics production and use (**leadership**)) @amsichani ?

**Global**

Responsible for growing the project to serve a global and inclusive set of audiences. 

- Diversity and Inclusion Manager @amsichani
- Head of PH Global (has strategic oversight of PH Global team (**leadership**)) @jmparr @acrymble
- PH Global - Africa (responsible for promoting the project in a specific region, and listening to the needs of that region to feed them back to the project team) @spapastamkou ?
- PH Global - Europe @arojascastro 
- PH Global - Middle East @spapastamkou ?
- PH Global - Asia / Pacific
- PH Global - North America @jmparr
- PH Global - Latin America @rivaquiroga 

**Project Development Team**

Roles associated with helping aspects of the project and project team to grow.

- Finance Manager (Looks after donations and sponsorship, including reimbursements and payment when money is spent. Point of contact for potential and existing sponsors (**leadership**)) @drjwbaker 
- Team Development Manager (onboarding manager (**leadership**))

**Comment by amsichani** [comment]
Fab @acrymble - thanks so much for this! 
I 'd like to see also a Diversity and inclusion manager and an Engagement and Outreach manager /

**Comment by JMParr** [comment]
Agree with @amsichani 's suggestion of a D&I and an E&O manager. Great suggestions. 

I'll self-nominate for English Editor, and Head of PH Global. Would also be willing to take on PH Global for North America and/or Africa.

**Comment by arojascastro** [comment]
Uhmmm... when did the campaign started? I didn’t realize... :-/ Can you please clarify how many seats are available? I don’t really know where I fit.

**Comment by jenniferisasi** [comment]
Hi all, upon reading the PH Global roles again... I think we need to take into account these points in case they are not clear, and because of geographical vs political/cultural/language distinctions: 

1) North America technically includes Mexico, Central America and the Caribbean. Latin America also includes Mexico, CA and the Caribbean, as well as Brasil but not the English-speaking countries 
- [x] Are we going to make the geographical or the languages distinction? 

2) The person who is PH Global X already has contacts in that region to ease work a little bit (for now at least; I think it could be quite difficult to do outreach in the Asia / Pacific region if you don't know anyone there yet)

3) Somehow the work has already started with Senegal but, in Africa is this person trying to reach the anglophone, francophone, etc. Africa at the same time? (I already dislike the fact that us Westerners mention Africa us a single uniform region so wouldn't like that transferred into here...). My take is, in small examples, that the English team should try to contact people in Nigeria, French team contacts Togo, and Spanish team contacts Guinea Ecuatorial. 

4) Number 3 applies to Asia / Pacific 

I might be stretching it too much, but I thought we need to figure these things.

**Comment by amsichani** [comment]
> Uhmmm... when did the campaign started? I didn’t realize... :-/ Can you please clarify how many seats are available? I don’t really know where I fit.

@arojascastro it was discussed & decided during our last Skype call (today) based on an original proposal by @acrymble . Please go ahead and place your name wherever you see yourself and even if there are more than one names for one role (excl editors) we can sort it out !

**Comment by acrymble** [comment]
@jenniferisasi I think we have to go geographic to keep things simple. But we can make up our own boundaries. Like in this map perhaps
![regionsmap](https://user-images.githubusercontent.com/646647/56912270-d4464080-6aa6-11e9-98bf-dc9b93a2b309.png)

I see the role of the PH Global team as understanding regional factors that we need to be aware of and adapt to, as well as building networks. Ideally each person would actually live and work in that region.

@arojascastro it came from #1183 and at present we aren't appointing anyone. Just finding out who is interested for what positions. This helps us know where we have strengths and weaknesses.

**Comment by acrymble** [comment]
@amsichani please add diversity.

I think of the Communication Manager as the Outreach person, combined with the  Education and Research Impact person. So how is your new suggestion different from those? What will they actually do?

**Comment by arojascastro** [comment]
> > Uhmmm... when did the campaign started? I didn’t realize... :-/ Can you please clarify how many seats are available? I don’t really know where I fit.
> 
> @arojascastro it was discussed & decided during our last Skype call (today) based on an original proposal by @acrymble . Please go ahead and place your name wherever you see yourself and even if there are more than one names for one role (excl editors) we can sort it out !

Ok thanks!

**Comment by amsichani** [comment]
> @amsichani please add diversity.
> 
> I think of the Communication Manager as the Outreach person, combined with the Education and Research Impact person. So how is your new suggestion different from those? What will they actually do?

Added.
OK @acrymble I see your point and I agree. There is no need to add an Engagement and Outreach role, given that Communications& Education&Research  Impact roles will work collectively towards these tasks.

**Comment by acrymble** [comment]
I think we're still waiting for views from the following people:

@walshbr @ZoeLeBlanc @jamotilla @mpuren 

and @alsalin (on leave).

If you haven't already added your name, can you please do so?

**Comment by walshbr** [comment]
I'm still on sabbatical for a couple weeks until mid-May - just hopping in here and there for the Skype call things. I need more time to review the conversation on all this since I've been out of it to have a sense of what I'd be signing up for. But I should at least be good for the English editorial team.

**Comment by acrymble** [comment]
@amsichani can you outline how the Diversity and Inclusion Manager will be different from the Team Development Manager (onboarding manager (crucial))

**Comment by mpuren** [comment]
With @fdlaramee we have decided that there will be 2 ombudspersons for the French team (me and hiem). And I should be added to "Editor (French)"

**Comment by walshbr** [comment]
Since I've been running and patching the Twitter bot, I suppose I should be added to the Communications team with @jenniferisasi?

**Comment by jenniferisasi** [comment]
Hi all. I only now have a bit of time to respond, in particular to @acrymble, but this is a call for everyone here specially @JMParr @spapastamkou @arojascastro and @rivaquiroga as you signed to be part of some PH Global role. 
I want to raise again the inconvenience of dividing these roles into regions rather than languages as it will not keep things simple as Adam claims. Regions doesn't equate/parallel infrastructural and cultural factors, issues, or privileges; nor does language itself but it facilitates communication and cultural awareness at the minimum. Maybe to make my case more clear I want to ask: why are the US and Canada separated from the UK, Australia, India and the English speaking Caribbean? 

Also, do you (plural) see the convenience and easiness of North America being only the US and Canada with practically the same resources, language and Western culture, versus the difficulty and intricacies of potentially building relationships with 54 countries in Africa with radically different resources, languages and cultures in most cases? That complexity is even more apparent than the one for Latin America.  

Hope this is seen as productive conversation for the role of PH Global to bring an even more diverse pool of people into the project.  

I guess we really need to make our own map.

**Comment by acrymble** [comment]
@jenniferisasi I have made a new ticket where we can discuss this further #1296

**Comment by amsichani** [comment]
> @amsichani can you outline how the Diversity and Inclusion Manager will be different from the Team Development Manager (onboarding manager (crucial))

this one was tricky - I think the Diversity and Inclusion manager oversees aspects of our inclusion and diversity strategy in various moments of our workflow, not just when it comes to include new members: guidelines, lessons' content, outreach events, publicity, policy /decision making -- all of these are moments where we need to ensure inclusion and diversity (in their various flavours) are taken into account.

**Comment by acrymble** [comment]
I think it's worth implementing these teams (and documenting what they do) in stages, since some of them are already more established than others, and some are still in discussion.

It looks to me like the Technical team is at a point where we could start (maybe on the wiki) writing up a description of what they do and then updating the Project Team page with the relevant new information?

**Comment by walshbr** [comment]
I mentioned this in #1298, but I can also hop on the technical team. I was already trying to informally help troubleshooting PRs anyway before sabbatical. So I'll add myself to that and to the communications team under @mdlincoln and @jenniferisasi. I didn't quite know where to add the twitter bot bit, so I added it as a new line. But feel free to shift it around wherever you want @acrymble

**Comment by walshbr** [comment]
Note from #1286 - we decided that we'll aim to implement these new teams in shifts, roughly one a month. Those tickets can contain the discussion for the individual groups. We also noted that the technical team appears to already basically be in motion, so we'll consider that checked off. It makes sense to me to move on the communications team next, if @jenniferisasi is up for it, since I see that she's already opened a ticket related to it. How about this for a rough schedule? 

- [X] Technical team - Done! 🎉 
- [ ] Communications team - set up June
- [ ] Editorial team - set up July
- [ ] Global team - set up August
- [ ] Project Growth team - set up September

I'll go ahead and open the tickets for the individual teams and give a few days in case folks have comments on the schedule. Then we can shift the timeline information to the individual tickets and close this.

**Comment by acrymble** [comment]
I'm going to close this issue because I think we've got a clear plan to bring each of these new teams online. Thanks everyone for your contributions.
