### ISSUE TITLE
Improve suggested citations styling

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#130]
The CSS for the suggested citations introduced in #88 looks too much like the author bio blocks. Will try to figure out a way to make it look nicer.

**Comment by acrymble** [comment]
hover in left margin? We don't use the horizontal space well enough. Though I know that makes mobile tricky, but is anyone programming on their phone?

**Comment by acrymble** [comment]
I've added this to the top of posts as well. I think it needs to be shrunk a bit, but it's more useful at the top than the bottom.

**Comment by fredgibbs** [comment]
this is going to be undone in the next redesign, and the citation format suggestion will be returned to the bottom where it belongs.

-- 
Fred Gibbs
History Department 
University of New Mexico
@fredgibbs <https://twitter.com/fredgibbs> || fredgibbs.net <http://fredgibbs.net/>

**Comment by ianmilligan1** [comment]
I agree that I think citations belong at the bottom of lessons – it stands out as a bit obtrusive at the top of the post...

**Comment by fredgibbs** [comment]
Sorry, I didn't mean to sound so gruff in that last message, but obviously I have strong feelings about our lesson typography, which I've been spending a lot of time with recently (and will hopefully have something to demo in the next few weeks). If others think the top is the best place, we should discuss, but otherwise the new layout has it where it was (and hopefully taking up less space as suggested) and compresses the page heading to get more of the lesson in view of the reader right away.

**Comment by acrymble** [comment]
Ok I've removed this back as it was. Getting more above the fold is important @fredgibbs so I'm glad to hear you're working on that.

I look forward to a demo. I think it's important that we get some feedback cycles into your redesign efforts to make sure it's something we and our users are happy with.

Let us know how we can help.

**Comment by acrymble** [comment]
Just noticed this old ticket. It looks like the suggested citation has been fully removed. Is that our intention?

**Comment by fredgibbs** [comment]
I left it off on purpose because i didn't see a consensus on either this issue or the related #404 about whether they should be displayed at all, or what their ultimate purpose is (presuming that people who want to cite an article will cite it according to their own citation formatting requirements and don't need us to tell them how). It's easy to add to the lesson template once decided. 

If one the reasons for suggested citations is to give editors more official credit for their work, it seems like @acrymble's suggestion on #404 to have a history section on the about page might be the best way. We also might start adding active dates to the project team page for emeritus members, so anyone can see who was active when (and could help with citing relevant project editors at a certain time if need be).

**Comment by acrymble** [comment]
I'm actually fine leaving these off for now, if everyone else is. The metadata is a bit easier to see in the new versions. The only case I can see for putting it on is to actually encourage people to cite things on the internet properly. It drives me up the wall when (students) put URLs in footnotes all by themselves. So in that sense it's just a mental reminder to people that they're looking at scholarly work. But unless anyone really wants to see these, let's leave them off and close this.
