### ISSUE TITLE
Project Development team

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1330]
Opening this ticket as a branch off of #1285 for discussion about setting up the project development team. @drjwbaker appears to be the only person associated with this team for now, so it might be a place we need to recruit further? We had discussed staggering set up of all these new teams, and I had ballparked September as a time for us to think about setting this up.

**Comment by acrymble** [comment]
Roles associated with helping aspects of the project and project team to grow.

* Finance Manager (Looks after donations and sponsorship, including reimbursements and payment when money is spent. Point of contact for potential and existing sponsors (leadership)) @drjwbaker
* Team Development Manager (onboarding manager (leadership))

**Comment by acrymble** [comment]
I think I've had to step into the Team Development Manager role in a number of ways. I would be happy to take this on. That does leave this team solely UK-based though.

**Comment by drjwbaker** [comment]
Thanks Adam. Depending on what happens over the next few months, I have a feeling this team may need some additional admin support. So I'm happy to stick as it is for no, on the proviso that we are all aware that we might need to rapidly revisit it.

**Comment by acrymble** [comment]
I'd like to move the setup of this team to July, since @alsalin is currently on leave and we cannot set up the Managing Editor team without her.

@drjwbaker is that ok with you? If so I can start conversations about getting this all integrated into our workflows.

**Comment by acrymble** [comment]
I'd like to add another role to this team. Something along the lines of "ticket master". Someone who keeps an overall view of the tickets on this board and helps by offering support and encouragement, otherwise making sure tickets are actioned. I've been doing this (along with some others) for a few years, but it's becoming a bit too much work, and I could really use the support of having this become someone's dedicated role.

**Comment by drjwbaker** [comment]
I agree. You are the de facto "ticket master" at the moment and this is unacknowledged labour.

**Comment by amsichani** [comment]
I agree on the necessity of the 'ticket master' role. I am happy to help on this alongside keeping tidy the [Ticket scheduling project](https://github.com/programminghistorian/jekyll/projects/1), although I m not sure I can be as master as @acrymble is ;-)

**Comment by acrymble** [comment]
This team needs to be up and operational by the end of July, as per our schedule. To close this ticket we need to decide the following:

- [x] Team leader (I vote for @drjwbaker)
- [ ] Update teamroles.yml with new roles and descriptions for the new roles
- [ ] Update ph_authors.yml so that team members are associated with the new roles
- [x] Update the wiki to more fully explain the scope of this team (https://github.com/programminghistorian/jekyll/wiki/Project-Development-Team)

At the June 2019 meeting @amsichani decided not to take on the "ticket master" role, which I propose we call "Project Manager at Large"

**Comment by drjwbaker** [comment]
Okay. I'll do it. 

- Project Development Manager (manages and develops PHs legal infrastructures so as to support project development; manages the Project Development Team).

Anything else?

I'm happy to do this + the Finance Manager role for now. But I'm hopeful once we get the legal entity bit up and running, that I can offload some of the latter, especially the day-to-day administration of funds.

**Comment by acrymble** [comment]
@drjwbaker just to be clear, I'm taking on the Project Development Manager, and you'll be the Finance Manager. In terms of leader, I'm suggesting that you'd be the point of contact for this team. In practical terms, I suspect it's not really much beyond an expectation that you'd try to come to the skype calls and represent what we've been up to. You do that anyway.

**Comment by drjwbaker** [comment]
I'm confused. What did you mean by "Team leader (I vote for @drjwbaker)" then? Either way, fine with me. But could you please list out the roles you see within this team again because we seem to be at cross-threads. I also think that whoever leads this team should take ultimate responsibility for managing/delegating the tasks that come out of being a legal entity.

**Comment by acrymble** [comment]
I've outlined it more fully here: https://github.com/programminghistorian/jekyll/wiki/Project-Development-Team

Basically each team has a lead contact who will respond when someone says "can someone from Team X ..." even just to say "we'll look into it".

it's to avoid the problem we've developed of no one taking action when teams are asked to contribute in some way (eg, reviewing a pull request).

**Comment by drjwbaker** [comment]
Right. I get it. Apologies for the confusion. I think 'Finance' isn't quite the right title then. More of..

> manages and develops PHs legal infrastructures so as to support project development

..should be in that role as well, for now. But let's leave the title for now. The outcome of #1301 might well create a job title we have to have for someone (probably me) for the purposes of being the type of legal entity we chose.

**Comment by amsichani** [comment]
> At the June 2019 meeting @amsichani decided not to take on the "ticket master" role, which I propose we call "Project Manager at Large"

Hi @acrymble , I m afraid I was misunderstood here - I am happy to take on the 'ticket master role' on a trial basis (I am just thinking I might have too much on my PH plate right now).

**Comment by acrymble** [comment]
@amsichani will take on the Project Manager at Large role. I will. update the Wiki.
