### ISSUE TITLE
Error in Tf-idf code

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1335]
The following has been reported in the Analyzing Documents with TF-IDF lesson

https://programminghistorian.org/en/lessons/analyzing-documents-with-tfidf

> I am getting a python error using the lesson code. The lesson is ‘Analyzing Documents with TF-IDF’.

> The final block of code returns the following.
> TypeError: replace() takes 2 positional arguments but 3 were given

> My environment is:
> Windows 10
> python --version
> Python 3.7.3
> conda --version
> conda 4.6.14

![Capture_tfidf](https://user-images.githubusercontent.com/646647/58858513-9341dd00-869f-11e9-8c5a-c7e0409d11b9.PNG)

@ZoeLeBlanc can you please check that this is in fact an error in the lesson, or let us know if it's a user error instead?

**Comment by ZoeLeBlanc** [comment]
uhhh the error message doesn't make sense. It quite literally says that the replace method only takes two arguments but only two were passed in the code 🤔 

Replace is a built in Python method [https://docs.python.org/3/library/stdtypes.html#str.replace ](https://docs.python.org/3/library/stdtypes.html#str.replace )that actually should be able to take three arguments (though in case the number of arguments is two so that's moot point)

The only things that might be wrong is either a earlier step in the code isn't working right (are there files in that created directory?) or there's something wonky with the conda distribution of python. I tested this in Python 3.7.2 and it's working for me.

Could you check if the directory has files and maybe print out the variable for `all_txt_files`

**Comment by maxsullivan** [comment]
Thanks for looking into this.

I can successfully create the tf_idf_output directory but it is empty.

I have printed the all_txt_files variable and attached it. 
[all_txt_files.txt](https://github.com/programminghistorian/jekyll/files/3259894/all_txt_files.txt)

Cheers

**Comment by acrymble** [comment]
How can we determine if this is a bug or not?

**Comment by mdlincoln** [comment]
I'm closing this out since we've gotten no further updates on this. Re-open if action is necessary.
