### ISSUE TITLE
Page build failure on submisison site

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1339]
I'm having trouble getting the submission site preview to build due to an error with a new submission. I don't see any way to get detailed information on the error like with Travis.

The error occurs upon uploading the file itself: 

https://github.com/programminghistorian/ph-submissions/commits/gh-pages

https://github.com/programminghistorian/ph-submissions/commit/5bb22e17d434a69f4b9d1f5dc79a16182ad15122

Can someone on the technical team help advise?

**Comment by mdlincoln** [comment]
Square brackets are a special character in YAML that indicate that you are submitting an array/list of multiple values. all of the `[LEAVE BLANK]` text is therefore invalid, because Jekyll is trying to interpret it as a list for values that shouldn't be lists. If you put a `#` in at the start of the line it'll comment it out, otherwise just put in dummy values that don't have brackets.

**Comment by acrymble** [comment]
Thanks, that was part of the problem. There were other syntax issues also. I've fixed them now (but it was a lot of work!)

**Comment by mdlincoln** [comment]
I hesitate to change up the editorial guidelines again (#1336) but is it possible that [this section of the guidelines](https://programminghistorian.org/en/editor-guidelines#3-add-yaml-metadata-to-the-lesson-file) needs to be explicit that you actually have to fill in those data? You can't just leave them blank?
