### ISSUE TITLE
add abstracts to each lesson

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#134]
this can be done when updating the YAML for level difficulty and main editor. these will be added to RSS feed when lessons are added.

**Comment by wcaleb** [comment]
Note two things about [the way I formatted the abstract](https://github.com/programminghistorian/jekyll/commit/5c9a01a6ae7db33597a08f901d978d6b60e50898#diff-76bcca8c94c80317afc212c217b7220dR10). After the key `abstract:`, I put a vertical bar (`|`). The paragraph that begins on the next line then needs to be indented four spaces on every line. This is how you insert [literal blocks in YAML](http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines).

(Though, reading over that last link, I notice we could also use a (`>`) instead of a vertical bar, which would make the paragraph word wrap in the output instead of putting a carriage return at the end of each line. Not sure this makes a difference in the RSS feed; will have to wait until my RSS reader gets this latest change to see what it looks like.)

**Comment by acrymble** [comment]
This is an old idea but a good one. We should add this to author guidelines moving forward so that we start collecting abstracts on all new lessons.

**Comment by wcaleb** [comment]
In working on #251, I discovered that Jekyll includes an easy way to generate an "excerpt" of the page for use in the RSS feed and elsewhere. By default the excerpt is just the first paragraph of the page, but it is possible to [customize the excerpt](https://jekyllrb.com/docs/posts/#post-excerpts) and even override it with an explicit "excerpt" value in the YAML front matter. This may be an easier way for us to proceed, though the disadvantage is that the first paragraph of a lesson will be more descriptive in some cases than in others.

**Comment by fredgibbs** [comment]
This is being done following @amandavisconti's excellent work on #193, and recent commits, so closing this here.
