### ISSUE TITLE
Intro to Beautiful Soup lesson failed to work for me on Windows and Linux

### ISSUE THREAD

**Issue by weaverbel** [programminghistorian/jekyll#1347]
There are a few issues with this lesson.
1) Not always clear where one is meant to be - on the command line, in a Python IDE, in a Jupyter notebook, whatever. All the instructions seem to be written for a command line system, but that is not stated, and if you are not in that kind of system, then you need help on where you can run all of this. It is important to say what tools will be used and what environments *won't* work.
2) The first bit of code with `prettify` works fine but once you try the next bit, you get a warning about no HTML parser being specified and something about 'lxml' and so on and then nothing works after that.
3) There is also an error in the `print link` instruction. This only worked when I typed it as `print(link)` but I was not sure if that was what was actually meant. 
4) Building code iteratively is OK, but it is pretty confusingly laid out in this lesson and it isn't clear when to start again. Does `prettify` get chucked out altogether?
5) No advice on troubleshooting is provided, but given how flaky this code is, I think there needs to be *some* advice, even if only to circumvent the error messages I encountered.

I ran it on a Windows machine and then I ran it on a Linux machine running Ubuntu. Both times it all bombed out, and for the same reasons.

Never had this issue with other lessons so I am pretty disappointed today !

**Comment by drjwbaker** [comment]
Thanks for your comments @weaverbel. Sorry you had some problems. On order:

1. The lesson does mention 'terminal' early on and this the implied environment, but I take the point about absolute clarity. It is medium difficulty lesson, so there are some assumptions baked in. Also, I'm not sure Jupyter was that much of thing when the lesson was written in 2012!
2. Okay. This seems like a problem we can fix. @jerielizabeth: are you able to take a look and suggest what is going on here?
3. As 2.
4. @weaverbel: are you able to specific which section of the tutorial you are referring to here?
5. Our tutorials don't tend to do this. They are walk-throughs of a process rather than if/but guides to an approach.

**Comment by weaverbel** [comment]
Thanks @drjwbaker 
The tute starts with the full code so you could just go straight to that. But then it does a step by step thing so you can understand what you are doing as you go. You do the bit with `prettify` and then the next lot of code doesn't have `prettify` at all and it seems that bit is gone altogether. I wasn't sure if it needed to stay in or not as it wasn't in the full code at the start. I wanted to save the code for later so it would be good to clear that up.

I should also mention that to fix the lxml error issue, I installed an HTML parser and another utility that said it would work if the parser didn't - can't remember the name of that - but it all still bombed out every time. I went to the Beautiful Soup homepage to try to diagnose what I was doing wrong and that is where I found out about those two parser utilities. This is on my Linux machine btw - I abandoned the Windows shell asap as it was just too hard to try to do anything on there. I think it is Ubuntu 16.04.

I actually ended up getting a good result on cleaning that data with NoteTabLight (freebie software) - I thought it was worth a comparison. NoteTabLight has a great feature called `Strip HTML Tags - Preserve URLs` which worked a treat and was quicker than doing the same thing in OpenRefine. Just FYI.

**Comment by jerielizabeth** [comment]
Thank you for the feedback on the lesson. It is definitely starting to show its age. 

I can take a look at the html parsers part in August - prepping for a dissertation defense until then. I can run through the whole lesson at that time to make sure it still works. If not, it might be time to consider a new tutorial on beautiful soup using the latest version and python 3.

**Comment by drjwbaker** [comment]
Thanks @jerielizabeth for agreeing to take a look later in the summer. We have a lesson retirement policy these days https://programminghistorian.org/en/lesson-retirement-policy so if fixing is a burden, we can go in a retirement direction.

**Comment by drjwbaker** [comment]
I'll make a note to come back to this in September, just in case you don't find the time @jerielizabeth.

**Comment by jerielizabeth** [comment]
@drjwbaker That sounds great! thank you!

**Comment by jerielizabeth** [comment]
Hi @drjwbaker, I've had a chance to start looking at the lesson and the errors reported. Some initial thoughts and a question.

For the issues raised by @weaverbel: 
2. I can add instructions on installing and calling an html parser (change needed due to an update in the BeautifulSoup library.) That should keep the lesson working. As a side note, it works ok on my local machine - just gives a warning - but that might be due to mac vs linux.
3. The syntax of print vs print() is a Python2 vs Python3 issue. The syntax in the lesson is for Python2 and the lesson states that in the beginning. I could modify the lesson so that it uses the Python3 syntax regardless of version, which would help avoid that error in the future. 
4. Prettify does get dropped, though I could change the lesson to keep it, just commented it out, without too much trouble. 

Looking back through, I would definitely write this lesson differently given what I know now about Python. So the question - would there be interest in a rewrite of the BeautifulSoup Introduction or a second, advanced BeautifulSoup tutorial? I would rather write a new, reframed tutorial than update much more than the three changes noted above.

**Comment by mdlincoln** [comment]
@jerielizabeth just chiming in to say I agree that it'd be better to retire this lesson adn do a new one given that these changes would amount to a significant rewriting

**Comment by drjwbaker** [comment]
So, we are patching this lesson for now and @jerielizabeth you might write a new one later that supersedes this?

**Comment by jerielizabeth** [comment]
I think so. And with these changes the lesson should weather the move to python3 so there is time.

**Comment by drjwbaker** [comment]
Okay. I'll find some time to take a look this week and close this ticket when I'm happy. Thanks for your efforts @jerielizabeth.

Note I've been on leave, hence the slow response.

**Comment by drjwbaker** [comment]
I think we can close this now that the PR https://github.com/programminghistorian/jekyll/pull/1415 is coming along nicely. Any objections, please reopen.
