### ISSUE TITLE
Translator Guidelines Spanish / French

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1385]
Note that the Translator Guidelines have now been published in English only: https://programminghistorian.org/en/translator-guidelines

I have a pending pull request ( #1384 )to make minor amendments, but  I wanted to open  a ticket to let the French and Spanish teams know, in case they decide they want to translate this page for their own use. As each publication will have separate needs with regards to translation, this isn't mandatory to translate and I will leave it up to the Managing Editors to decide.

**Comment by spapastamkou** [comment]
We've been feeling the need to have guidelines for translators ever since we started communicating about the PH FR and each time there are contacts for a lesson. So yes, we ought to translate them. @acrymble you prefer us to open a separate issue or start a pull request from this one? I think it is better to set a timeline and have them ready let's say for the next team meeting (end of the summer).

**Comment by rivaquiroga** [comment]
I agree with the timeline. End of August (the end of winter, in my case :cloud_with_rain:) seems fine.

**Comment by acrymble** [comment]
Since there are 2 separate ones to create, maybe it is best to open two new tickets.  Then neither has to wait for the other.

**Comment by spapastamkou** [comment]
Opened ticket #1389 and PR #1390 for the FR translation. I think there is a slight problem with the anchors and their href in EN file but need to check this better.

**Comment by rivaquiroga** [comment]
I'm closing this ticket as FR and ES teams worked / are working on this in separated issues (https://github.com/programminghistorian/jekyll/issues/1389 and https://github.com/programminghistorian/jekyll/issues/1424)
