### ISSUE TITLE
Who is responsible for Lesson Bugs?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1400]
I'd like to clearly decide who is responsible for managing any bug reports in lessons that come in. Usually these happen on lessons for which the editor is no longer with the team. It is currently unclear if the person responsible should be the Managing Editor of the relevant language publication, or the technical team.

Can we please decide so that this can be implemented, as at present most of these tickets just linger.

**Comment by jenniferisasi** [comment]
Good question! 
Since the editor of the lesson might not be on the team (in the Spanish team we still are but thinking about the future) I think the managing editor should be the one to take a first look at the reported issue. If it is not an essay fix then maybe contact the tech team, however, it could be also the case that no one in the tech team knows how to fix it, so then contact the author? 

I want to add, @acrymble, how do we manage encounters with dead links or obsolete software when we are translating a lesson (so not necessarily when reported as a bug, by a user). See https://github.com/programminghistorian/ph-submissions/issues/173#issuecomment-516893310

**Comment by mdlincoln** [comment]
Hey, I think we need to have everyone look once again at our retirement policy: https://programminghistorian.org/en/lesson-retirement-policy

One class of issues are broken URLs, and we have an established process for this. Whoever triggers this in the PR process should be fixing this link, pointing to a new location or the Wayback Machine if possible, or removing the link otherwise. This goes for translations - if translators run into a broken link that hasn't yet been detected in the original, then it should be fixed in the original.

The OTHER class of bugs are anything from outdated software, to issues like #1181 where the lesson was originally published incorrectly but the problem was not found out for some time. I think we should follow our stated policy, and _not_ be spending any significant time on old software repairs unless there is an explicit volunteer for doing the work involved.

As long as we're all still agreed on our stated policy, I'd say it should be the managing editor for the language to take responsibility for executing that policy:

1. Responding to the ticket
2. Paging the team (or lesson editor, if they are still available) to see if there are volunteers to fix
3. After a period of time (60 days? It may be useful to explicitly state this) if there's no motion towards fixing it, then we archive the lesson.

**Comment by walshbr** [comment]
Also, 2 of the last 3 bug reports I've gotten have been errors in the code the readers were trying to run - not errors in the lesson itself. I think we could do a better job with the prompt for feedback here - https://programminghistorian.org/en/feedback - encouraging people to check their work by copying and pasting the code blocks in before they assume the lesson is broken. The GitHub issue template for submitting a bug report is a little better. Capturing those kinds of human error will help reduce the bug reports.

**Comment by mariajoafana** [comment]
#1408

**Comment by mdlincoln** [comment]
@acrymble What's the action item here? Do you think we need additional documentation in the wiki about this editorial process? Clarifying the feedback page?

**Comment by acrymble** [comment]
I think you're right that this was already covered by existing policies.  Thanks.
