### ISSUE TITLE
New EN Managing Editor Needed

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1406]
I'll be finishing up my role at EN-ME in September as I'm transitioning from full-time work at Emory to contract and consulting work for the time being. I hope to be able to stay on the EN team, but I'll need to see how things land in the next month or so. I will need to step down as ME though and we'll need someone to take up the role starting in September. Anyone interested? Anyone know anyone who might be interested?

**Comment by walshbr** [comment]
A few things:

1) I opened #1407 because I couldn't find actual documentation for what the role entailed outside of an old email, and the position has changed since then. 
2) Since people are getting pulled in a lot of directions with a lot of different roles, we should think seriously about recruiting more folks for the English board that can also help take on lessons. 
3) I can take it on, and I'll just need to reduce my involvement with the technical team accordingly.
