### ISSUE TITLE
software carpentry link?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#143]
I just spoke with Greg Wilson and Jonah Duckles of Software Carpentry https://software-carpentry.org/

Software Carpentry events typically run for 2 days and are paid for by the host institution. Instructor training is encouraged through their system and instructors have their costs covered by the host. Software Carpentry's role is to pair instructors and hosts together and to provide infrastructural support.

They're interested in working with us to reach the digital humanities communities with software-focused workshops as they have much stronger links to the sciences. They note we've got a good set of lessons and good connections with the community.

The system runs world wide, and it looks like good potential for raising the impact of our lessons and getting them out there into the adult classrooms of the world.

They're happy to join us to discuss it at our next board meeting. In the meantime, please share any thoughts on how we might make something like this work.

**Comment by drjwbaker** [comment]
As a related aside, the rationale for running [Programming Historian Live](http://programminghistorian.org/posts/programming-historian-live-london/) and [Library Carpentry](http://programminghistorian.org/posts/programming-historian-live-london/) as part of my Software Sustainability Institute Fellowship came out of a - what I can imagine was comparable - discussion with Greg about humanities and library folks (like me!) showing up at Software Carpentry events and what (if anything) was needed to adapt SC to their needs. My understanding from talking to some of the Data Carpentry folks last year (pre-confirmation of their big grant) was that DC was set-up with a broader conception of scientific research in mind, though the rhetoric - like that of SC - is very much around science/tech/eng/medicine (especially post big grant).

So - from the outside - it seems to me that taking a look at how these two established communities could work more closely together, even if just at the level of pushing folks to materials the other has created for more training materials (I'm semi reliant on their Git intro to jog my mind...) or around sharing models of best practice, could be really beneficial to communities served.

**Comment by acrymble** [comment]
we discussed this at our last editorial meeting, and we're going to pursue. Greg Wilson has been in touch and they're now discussing the same at their own board meeting. Will report when I hear more.

**Comment by ianmilligan1** [comment]
I just had a great chat with Greg Wilson, which I will bring up in more detail at our next editorial meeting. In short, I think there's some great exciting opportunities here to take our existing connections to DH with their long track record of teaching people in this area, emphasis on principles, and instructor training. Given other discussions about broadening PH's outreach and audience, this is great. They also have the infrastructure to pair instructors with people who want workshops, which is invaluable.

One idea for a next step was to discuss running a two-day workshop in March or April, taking some _Programming Historian_ editors/contributors/etc. through their instructor training. We'd learn from them, and they could learn from us.

**Comment by acrymble** [comment]
We should keep our eye on this, which is a related idea: http://history2016.doingdh.org/

**Comment by acrymble** [comment]
Related to issue #246, I think the only way for this to get off the ground is to recruit someone to take it forward as a dedicated task. I'd like to add this to our discussion at the editorial board and I'm very happy to draft a call with @ianmilligan1 to initiate recruitment on that basis. We're too stretched to add this to someone's current portfolio.

**Comment by ianmilligan1** [comment]
Agreed, @acrymble. Let me know when you wanna chat. I'm back Canada-side for the next two weeks starting on Thursday, so schedule is pretty open.

**Comment by wcaleb** [comment]
Things to discuss for #261:
- [x] drafting a call for someone to lead this
- [x] how this relates to other recruitment initiatives for #246 and #252

**Comment by ianmilligan1** [comment]
We discussed this. We're happy for Software Carpentry to use our material, of course, as we discussed earlier (they're doing so).

@jerielizabeth is quite busy, but will try to write something up before our next editorial call in three/four weeks about working with her [DH Bridge](http://dhbridge.org/) project. 

When we recruit a new editor, we will also add Software Carpentry/in-person training into the bullet point list of things that we're interested in (i.e. if you're interested in this, we're interested too).

**Comment by jerielizabeth** [comment]
Hi all,

My apologies - I underestimated the time requirement of DH2016. I won't have something by this call, but I will write something more formal ASAP! But for the short term ...

DH Bridge is a curriculum for 1-2 day workshops for teaching computational thinking and technical skills. The contributions here are that the emphasis on using computation in the service of humanities questions and on learning to think computationally. So, rather than starting with the "fundamentals," such as variables, arrays (lists), and loops, we start with a question, identify data, look at how to get that data, and then look at how to process that data. The first version of the curriculum is up at [dhbridge.org](http://www.dhbridge.org). 

The side for running "in-person" events is similar to software carpentry, but is really focused on pulling from the local community. So there is an MC who helps keep the whole group on schedule, but the participants learn primarily from the tutorial (which is where PH has so much material) and from the coaches who are local community members who are interesting in helping others through. To help them, we have a coaches guide with prompts about when to check with the group about different technical concepts. Overall, we try to focus on reducing barriers, helping people learn how to learn computational work within the context of humanities questions. 

In terms of setup for running a DH Bridge event, the need is for a central curriculum, a coaches guide, some willing coaches (1 coach for every 3 participants) and space! We have provided food, and used t-shirts (and sponsorship) for fundraising for those costs. 

The way forward would be to identify a few lessons to start with, think through any changes that might be needed to fit a "computational thinking" framework, create coaching guides, and pick a place to run a workshop. I have some changes in the near future that will open up some time to work on those things, if it is of interest to the group.

**Comment by acrymble** [comment]
Software Carpentry has started working with someone else to provide their DH tutorials so I think that particular link may have passed.

**Comment by ianmilligan1** [comment]
Responded to this on the editorial thread.

**Comment by jerielizabeth** [comment]
Update on this front. I had hoped to devote some time to thinking through how the Programming Historian materials could be used in DH Bridge workshops and pitch a workshop for DH2017 on that topic. However, my workload with the dissertation is a bit too much to do that justice this year, so I will need to return to this idea for the DH2018 cycle. 

I still think the DH Bridge / PH collaboration is good, but I don’t think it is mutually exclusive to one with Software Carpentry. If anyone want to take over the conversation with the Software Carpentry folks, please do! But I won’t be able to give this issue much attention this year.

**Comment by acrymble** [comment]
I think it's probably best then if we close this issue, and if someone wants to return to it in future then this conversation is archived. We'll obviously be happy to support any community members interested in pursuing in-person events.
