### ISSUE TITLE
Requesting Translation guidance

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1458]
We have a sticking point in our workflow when it comes to requests for translation on pull requests. To make that process easier, I'm going to produce some brief guidelines on our wiki that mean the requester makes a more explicit and clearer request to colleagues for specific translation. I invite comment on these once the draft is up.

**Comment by acrymble** [comment]
I've added a page to the wiki. If a member of @programminghistorian/french-team and @programminghistorian/spanish-team could look at this and approve, we can adopt this method and close this ticket.  If you want amendments, please either post them here or change the wiki page as appropriate.

**Comment by acrymble** [comment]
https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines

**Comment by spapastamkou** [comment]
Looks good @acrymble. 
One remark on the last phrase: _"Once you receive the translations, it is most efficient for you to add these to the appropriate files, as it is your pull request. This simple approach makes it less time consuming for translators to help us with pull requests."_
If the translator cannot for any reason make the change in the corresponding file, it would be good he/she provides the name of the file so that the person who makes the PR knows easily  where to go and add the translation. However, if the translator finds the requested change requires further modifications to adapt the rest of the text (this may be the case in longer texts), it would perhaps be better he/she does these modifications, to avoid mistakes (or state exactly what needs to be replaced by what).

**Comment by acrymble** [comment]
@spapastamkou thanks for the comment. So should we keep it simple and say "Please discuss explicitly with the translator if  you would like to incorporate the translations, or if  you want them to do it? Both parties should be clear and provide enough context to the other to enable efficient publication"?

**Comment by spapastamkou** [comment]
@acrymble yes, I think it covers all possible cases

**Comment by jenniferisasi** [comment]
Thank you @acrymble. I think this works.

**Comment by acrymble** [comment]
Thanks for the feedback from both teams. I will try to police this (politely) for a few months as people get used to it. If anyone wants to continue amending the guidance based on experience, please do so directly on the wiki.

**Comment by drjwbaker** [comment]
Quick question. Do we @ the relevant MEs or the teams (e.g. @programminghistorian/french-team) in the PR?

**Comment by acrymble** [comment]
Sounds reasonable. Can you update wiki?

**Comment by drjwbaker** [comment]
My question is which would the ES and FR teams prefer. I tend to at both teams, but I'm happy to do what each team prefers.

**Comment by spapastamkou** [comment]
Maybe ping both teams AND MEs, what do you think?

**Comment by drjwbaker** [comment]
I'm up for that. For clarity, @spapastamkou + @programminghistorian/french-team on every FR translation request.

Does @rivaquiroga @programminghistorian/spanish-team want to do this the same way or differently? (I should say, different is fine, so long as we all know what it is)

**Comment by rivaquiroga** [comment]
The same way!

**Comment by drjwbaker** [comment]
Added language to the wiki https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines @acrymble: happy to close?
