### ISSUE TITLE
Raise a build error if a post *.md file doesn't use hyphens

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1478]
Because of how Jekyll recognizes dates for posts in our current configuration, the filenames must use hyphens. Any other punctuation and the post _silently_ fails and just doesn't show up.

@programminghistorian/technical-team will add a rule to the build script that will check for this and cause an error during CI checks, so post authors can more easily see what's wrong and how to fix it.

**Comment by mdlincoln** [comment]
re: #1472

**Comment by mdlincoln** [comment]
Annoyingly, if a markdown doc in `_posts` doesn't follow the `YYYY-MM-DD-title-here.md` format, then Jekyll doesn't even load it into the `site.documents` or `site.pages` objects, so I can't even locate it using the `Jekyll::Generator` class that I use to do all our other validation. Will need to find another way to check post filenames...

**Comment by acrymble** [comment]
Should we just run the blog separately? Our current setup seems more work than it's worth. There are platforms that a re designed for blogging. That would reduce your admin time, make it easier for @jenniferisasi, and reduce the bus factor of the site architecture.

**Comment by mdlincoln** [comment]
No, I think that is a horribly complicated idea. You'd be asking us to run TWO separate websites rather than one.

**Comment by acrymble** [comment]
Ok. I hope you won't dismiss it too quickly though. Our blog is not very user friendly, and making it such is going to take far more work than using an appropriate tool. It's been years since I've  had to do anything to update or maintain my blog. It just happens automatically and I never have to remember how to use it.

**Comment by jenniferisasi** [comment]
If I understand this issue correctly, the problem is that if format `YYYY-MM-DD-title-here.md` is not used Jekyll will ignore the file completely. Honestly, if it is only that, and even if @mdlincoln couldn't find a way to validate/check for that error, I still wouldn't want to run another platform. The system here is pretty easy to work with. 
I agree that we don't have a very user friendly blog though, and the more we post the messier it gets to find past posts (that is my only concern).

**Comment by mdlincoln** [comment]
I'm going to close this out as there's no straightforward check that can prevent this mistake by editors. Unfortunately they'll just have to stick to the documented file-naming convention.
