### ISSUE TITLE
Offline archive of bids et al

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1482]
As discussed at https://github.com/programminghistorian/jekyll/issues/1449 and following on from https://github.com/programminghistorian/jekyll/issues/1426, as project Archivist I’ve been thinking of ways to store in a private, offline manner, documents we want to have team access to but don’t want to put on GitHub: so, things like bids, internal surveys, et cetera.

You've now started sending me things to add to this (thank you!). The next step is to create a mechanism for sharing. My proposal is to have a list of directories and files (so the output of `ls -R` in the base directory) that I put on here periodically. You can then consult the list and ask me for the file.

The question is where to put the .txt file with the list of documents. @programminghistorian/technical-team: I don't see the point of adding a new repo, so do you have any objections to me adding a new directory at https://github.com/programminghistorian/jekyll in wich I put these .txt files? It isn't exactly the right place, but presuming it won't be anything to disrupt the jekyll build, it seems the most simple option.

**Comment by walshbr** [comment]
If they're in a directory in this GitHub repo they'd be default public. Anyone could navigate to the pages in the repo or on the site, even if we don't link to them. That'd be the point of adding a new repo I think. We could add a private one so that they weren't publicly available. If you don't mind them being viewable then it's fine to have them here.

**Comment by drjwbaker** [comment]
I just want to make a list of files available. And public is fine. So I'll make a new dir.

**Comment by walshbr** [comment]
FWIW @drjwbaker - you don't need to close the ticket itself when you have a pull request that states "closes #1482" (though the number changes based on whatever ticket you're talking about. The pull request, once it merges in, will automatically close the associated ticket that you've referenced because of that text. Probably best to let the system do it that way, so that we don't close out issues until the work that fixes them actually is completed.

**Comment by drjwbaker** [comment]
Huh. So if you write..

> Closes #ticketno 

.. in PR, it closes the issue automatically when the PR is merged?!

**Comment by walshbr** [comment]
As I understand it yep @drjwbaker!
