### ISSUE TITLE
November 2019 Skype call - 25 November- Editorial Agenda 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1538]
Monday 25th November 2019 . Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET. @walshbr  will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

All team leaders please post a small report on your team's activities closer that day. 

- [ ] Current Research Projects or Submissions Pending about the Programming Historian 
- [x]   Development Team Report
- [x]   Technical Report
- [x]   Communications Report
- [x]  Global Team Report 
- [ ]   Editorial Team 
 - Plan to work through stuck issues / old issues in the next month **Action SM**
- [ ]   ProgHist Ltd report
- [x] EN report - SM
- [x]   FR team Report 
 - 3 candidates applied to join the team, to be interviewed Nov 2019 -  **Action SP.**
- [x]  ES team Report  
 -  RQ in Chile during unrest, may need extra support. **Action JI, JOB contact her**
 - Spanish team capacity query. A lot of long-term missing people. **Action AC to liase with RQ.**
- [ ] Internal Communications #1491 & Decision making #1543
 - **Action: Team leaders to decide together how to deal with internal communication to ensure their team memers are aware of relevant tickets.**
- [ ] Edit governance doc to better fit sub-team structure/powers #1543

Call frequency and subteams.

**Comment by acrymble** [comment]
@amsichani since we now have minutes and actions from the last meeting, can we find a quick way to make sure everyone with an action reports  on it or otherwise lets us know it needs more input? Otherwise the actions are meaningless.

**Comment by amsichani** [comment]
thanks for this @acrymble . I ll work on this and get back to the team as soon as possible

**Comment by jenniferisasi** [comment]
A quick note that Nov 28th is Thanksgiving here so all of us in the US will be out of the office and, most likely, celebrating the day with family/friends.

**Comment by walshbr** [comment]
Would be good to revisit this note - https://github.com/programminghistorian/jekyll/issues/1302#issuecomment-497732161. We had discussed in the past the possibility of staggering full board meetings starting in September once more of the sub boards were in place so that we weren't all planning on both monthly editorial board skype calls and monthly sub team calls.

**Comment by acrymble** [comment]
Related to @walshbr we also said that we only expected team leaders to come to these meetings. Everyone else's participation is o ptional (but we would prefer to know if you aren't planning to come). Do we want to continue with that approach?

**Comment by walshbr** [comment]
I'll mention this on the call, but opt-in for everyone required for leaders does seem to be the most sensible. That way people with the time and energy who want to be as engaged as possible can still have that option. Also in keeping with the general ethos of transparency.

**Comment by drjwbaker** [comment]
# Project Development Team Report

By: @drjwbaker 
Date: 20 Nov 2019

Substantive Actions Completed Since Previous Report:

- Proposal for donation mechanism. Went ahead and started Patreon/Paypal work https://github.com/programminghistorian/jekyll/issues/1457
- Ticket on business models we are happy with for fundraising https://github.com/programminghistorian/jekyll/issues/1487. In sum we agreed:
	- directly monetizing the content through subscriptions or advertising is unpopular with some people.
	- donations are fine within some limits - suggesting charity rather than business is the ethos some people have in mind.
	- workshops and training are a possible route for monetizing activity.
	- other options remain open to us.

Substantive Actions Remaining Open Since Previous Report:

- 2-month funded Impact Manager post. Job now up: [https://www.sussex.ac.uk/about/jobs/research-assistant-impact-manager-prog-hist-2753](https://www.sussex.ac.uk/about/jobs/research-assistant-impact-manager-prog-hist-2753). Deadline 3 Dec. I am receiving queries from potential applicants. https://github.com/programminghistorian/jekyll/issues/1489
- Opened ticket (from discussion at previous call #1491) on editing governance to reflect our team structure **to be discussed today under specific item**
- Patreon plan for next 6 months https://github.com/programminghistorian/jekyll/issues/1554
- start of plan to manage copyediting hires (once we have some £#$¢) https://github.com/programminghistorian/jekyll/issues/1537

Queries for the Team:

- none

6-month focus:

- maturing mechanisms in place for attraction receiving money https://github.com/programminghistorian/jekyll/issues/1457 including reopening conversations around sponsorship and other revenue generating activities (e.g. paid workshops)

12+ month focus:

- understanding forward financial planning so that we can plan spending and hire staff.

Further Comments:

- none

**Comment by amsichani** [comment]
I 've added actionable items from last meeting minutes under related items/teams in the agenda - hopefully, the teams' reports for this meeting and discussion during the call  will address these.

**Comment by fdlaramee** [comment]
Apologies; a medical appointment will keep me away from this month's call.

All the best,
FDL

**Comment by mdlincoln** [comment]
# Technical Team Report

By: @mdlincoln 
Date: 20 Nov 2019

Substantive Actions Completed Since Previous Report:

- Discussed and drafted an issue triage and workload balancing guide: <https://github.com/programminghistorian/jekyll/wiki/Technical-Team#issue-triage-workflow> It will include guidelines for editorial team bug reports and issue requests, and describe how we will assess and prioritize complex feature requests.
- Received report from @ZoeLeBlanc on full-text search of lessons. We decided on a path forward to search lessons within each language group, and Zoe will be working on a draft implementation
- Merged alt text pr #1357 

Substantive Actions Remaining Open Since Previous Report:

- Plan S / DOI mechanics still ongoing #1370 

Queries for the Team:

- Any comments on our issue triage plan?

6-month focus:

- Have a finalized issue triage workflow plan
- Finish implementing site search

12+ month focus:

- Implement article metadata and DOIs compliant with plan S

**Comment by svmelton** [comment]
# EN Editorial Report

By: @svmelton 
Date: 21 Nov 2019

Actions Completed Since Previous Report:

- Recently published - [Beginners' Guide to Twitter Data](https://programminghistorian.org/en/lessons/beginners-guide-to-twitter-data)

- Retired SPARQL lesson #1541 

- Created [kanban board](https://github.com/programminghistorian/jekyll/projects/3) to manage editorial workflow

Issues still in process:

- #1181 is close to being fixed. @svmelton ran into issues while testing the lesson and the author is revising and will submit a PR to fix.

- [Jupyter Notebooks lesson](https://github.com/programminghistorian/ph-submissions/issues/251) is at the managing editor stage, awaiting question on broken links

- [Working with Batches of PDF Files](https://github.com/programminghistorian/ph-submissions/issues/258) is in author revision stage

Queries for the Team:

- Reaching consensus about Jim Clifford proposed lesson and its potential relevance to #1557

**Comment by svmelton** [comment]
FYI, I will need to leave about 30 minutes into the call for another meeting.

**Comment by jenniferisasi** [comment]
# Communications Team Report
By: @jenniferisasi 
Date: 23 Nov 2019

Substantive Actions Completed Since Previous Report:

- #1552, @amsichani has created a 1-6 month plan for her role as Education Manager. We discussed what actions are a priority and what is doable during a half-year timeframe. 

- #1489, @drjwbaker has secured funding for a Funded Impact Manager and is now received applications [I know this is a duplicate action, but it falls under communications as well]

Substantive Actions Remaining Open Since Previous Report:

- #1539, decide the order to incorporate translations into Patreon. 

- #1540, I have started a ticket to collect information for the end of the year newsletter

Queries for the Team:

- Please, add anything I might be missing on the Newsletter #1540. 
- How about we develop a plan/path to promote PH during conferences (besides the stickers). Examples that come to my mind: Print little flyers; contact conference organizers to have a designated space to talk to people (~like vendors do); inform the audience in the conference "X and Y from PH will be attending ABC, talk to them if you have any question"   

6-month focus:
- Publish 2 newsletters.
- Tweet. 

12+ month focus:
- [If group likes the idea] Create promotion "paths" for conferences and events.

**Comment by JMParr** [comment]
### Global Team Report
By: @JMParr 
Date: 25 Nov 2019

Substantive Actions Completed Since Previous Report:

- Contact made with Quinn D. and GO:DH re their multi-lingual work. We have had some initial talks via email, and plan to have a conversation via Zoom after Thanksgiving.
- Initial outreach made with the Amical Consortium, who have been receptive.

Queries for the Team:

- Aside from the bus factor for the technical team, and discussing the primary promotion of multilingual efforts in English, are there are things we should be aware of?
- Any new grant initiatives, aside from what @acrymble reported yesterday?
- What is the team's appetite for collaborating with other platforms on building a sustainable DH model?
- I think we should also consider adding one more Global Team member if expand to doing more collaborations with other projects..

6-month focus:

- Build a robust and working partnership with Amical and GO:DH

12+ month focus:

- Grants in support of developing a sustainable multilingual model, and/or more workshops, modeled after the one in Colombia. 

Further Comments:
None.

**Comment by JMParr** [comment]
> FYI, I will need to leave about 30 minutes into the call for another meeting.

I'm going to have to leave about 30-40 minutes into the call as well, for an appointment.

**Comment by spapastamkou** [comment]
### FR team report
By: @spapastamkou Date: 25/11/2019

Actions Completed Since Previous Report:

- Interviews with candidates completed; will have finally 2 new members (Maëlle Amand, Marie-Christine Boucher); their integration will begin no earlier than December (to give us time and finish with our major goals set according to 3 months planning #1469)

Actions Remaining Open Since Previous Report: 
#1469 
- Translations: 3/3 pending
- Translation editions: under progress 
- Translations reviews: 2/3 done

#1431: PR #1551 to close this week
#1167 Depends on progress on translation editions (one of them currently missing only translator's response to reviews)
Wiki for FR translations guidelines: should be ready by end of month
FR Kanban board: @spapastamkou should be able to start work on in with @svmelton in December 

Queries for the Editorial Board:
none

6-month focus:
Integrate two new members
Prepare proposal for DH Humanistica Conference (workshop)

12+ month focus:
Publish more translated lessons 
Publish original lessons

Further Comments:
none

**Comment by spapastamkou** [comment]
As per doodle, I am not available for the meeting but will follow minutes! Best, Sofia

**Comment by rivaquiroga** [comment]
# ES team Report
By: @rivaquiroga Date: 25/11/2019

Substantive Actions Completed Since Previous Report: 

- Created [kanban board](https://github.com/programminghistorian/jekyll/projects/4) to manage editorial workflow, following the model of EN team
- Bogotá Workshop participants were contacted to inquire about tutorials proposals. Waiting for responses. 

Substantive Actions Remaining Open Since Previous Report:

- 3 original lessons under edition ([#188](https://github.com/programminghistorian/ph-submissions/issues/188), [#212](https://github.com/programminghistorian/ph-submissions/issues/212) & [#254](https://github.com/programminghistorian/ph-submissions/issues/254)) @jamotilla @mariajoafana @jenniferisasi 
- 2 translations under review ([#163](https://github.com/programminghistorian/ph-submissions/issues/163), [#205](https://github.com/programminghistorian/ph-submissions/issues/205)) @jamotilla @vgayolrs @mariajoafana 

6-month focus: 
- Have a 3 months planning as team and for all members, following the model of FR team  #1469

12+ month focus: 
- Will be defined after next team meeting

Further Comments:
- Team meeting invitation will be send this week

**Comment by JoshuaGOB** [comment]
Hi all, sorry I couldn't make it. Got my timezones mixed up and had to attend a meeting here.
