### ISSUE TITLE
adding a new lesson

### ISSUE THREAD

**Issue by miriamposner** [programminghistorian/jekyll#157]
@acrymble suggested I should submit a Palladio lesson I recently wrote, so I created a branch for it and submitted a pull request. I think maybe I didn't do it right, though, because it's not appearing as a pull request.

**Comment by wcaleb** [comment]
I'd be happy to help figure out what went wrong! It looks like you created a [pull request on your own forked repo](https://github.com/miriamposner/jekyll/pull/1), but not one to the Programming Historian repo.

To see if we can get this fixed, first try accepting your own pull request (linked above). Then I'll take another look.

**Comment by wcaleb** [comment]
@miriamposner Actually it may be even easier than what I said above.

If you go to this [compare page](https://github.com/programminghistorian/jekyll/compare/gh-pages...miriamposner:getting_started_with_palladio-1), you can see that your branch is being compared directly with the Programming Historian `gh-pages` branch. Click the green "Create pull request" button on that page, and see what happens.

**Comment by wcaleb** [comment]
Hi again @miriamposner. Ok, I didn't realize it was possible to do this, but I actually was able to make the pull request myself from your branch, and it's now at #158.

You should still be able to update the lesson by making commits directly to your `getting_started_with_palladio-1` branch (notice the 1 on the end).

For future submissions, I'm wondering if it would make it easier on authors if we offer to create the pull requests ourselves after they've created a branch? That could simplify matters, if you think it would be easier.

Also out of curiosity, wondering if you used the documentation I wrote on making pull requests to make yours? If so, then I may need to revise those steps so that others don't land in the same place.

**Comment by miriamposner** [comment]
Hey, @wcaleb! Thank you! Yup, followed your instructions. I'm not sure where I went wrong. I should've probably just done it from the command line but thought it might be faster to just do it in the browser. I need to add the images, too. Anyway, thank you!

**Comment by wcaleb** [comment]
It may have been that you weren't on the `gh-pages` branch when you created your branch? Not sure though. Will investigate ...

**Comment by miriamposner** [comment]
Oh, I probably was. D'oh! I swear, every time I think I understand Github I
break something.

On Wed, Nov 25, 2015 at 9:50 AM, W. Caleb McDaniel <notifications@github.com

**Comment by wcaleb** [comment]
Not at all! You didn't break anything. TBH, I think GitHub could do a better job distinguishing between pull requests made within your own repos and pull requests made to a repo that you have forked. When they use the same button/lingo for both things, it creates understandable and needless confusion.
