### ISSUE TITLE
make a cheat-sheet for editors on escaping quotes / special characters

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1646]
We need to put strings in to a lot of places:

- YAML
- markdown
- html inside markdown
- code blocks
- arguments added to `includes` like with `{% include figure.html caption="..." %}` (which are a special case too b/c they actually get processed as markdown...)

It's not always intuitive how `'` and `"` will interact in which domain, and there are often mutiple ways to do it which can be confusing for newcomers to try and sort it all out. We need a cheat sheet so editors can look this up when working on tricky things like #1644 

i'm tired. but I'll start work on it at some point - if anyone @programminghistorian/technical-team finds some good pre-existing resources that we could link to, that would also be lovely.

**Comment by walshbr** [comment]
Oof I'm not certain I'm really good on all the distinctions either, and I couldn't find any readymade resources for this when googling around - just a thousand stack overflow threads. I could help write this up, but is the following correct? Something like…

YAML - use double quotation marks, with a caveat for escaping the double quotes as necessary
Markdown - should not matter which you use if it's just content
HTML inside markdown - should be double quotation marks with internal quotes escaped as necessary?
code blocks - should not matter for the site since the code blocks aren't being parsed - it would just depend on the language for the code block
arguments - should be double quotation marks with internal quotes escaped as necessary?

**Comment by jenniferisasi** [comment]
I can't find anything that is a one-place guide either, sorry (checked in English and Spanish). Are you suggesting this info to be on the Wiki? 

I am most familiar with html and I would say what you said @walshbr for it is correct.

**Comment by mdlincoln** [comment]
amended the common travis errors section of the wiki to cover this case
