### ISSUE TITLE
Patreon phase 3 plan

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1680]
We are nearing the end of our recruitment plan for Patreon (end of March).

I'm very pleased to report we've gone from $0 to $110 per month, with 36 subscribers (for whom we're very grateful). It looks to me like our subscribers are almost all what we would describe as "DH" people, meaning that our cause resonates most clearly with them.

I'd like to ask if anyone on the team would be willing to help create a new 3-month plan for attracting more donations, as to be honest, I've already used my best ideas. This would involve probably a skype call or two with me and/or @drjwbaker. I can implement the plan, so it isn't an extended commitment.

If any team members are interested in user engagement and sustainable project development, please let me know so we can work together.

**Comment by acrymble** [comment]
I'll leave this call for help open for a few more days, but if no one has the time or interest, I'll close this and we'll let Patreon run as normal.

**Comment by acrymble** [comment]
@walshbr is it possible for us to add a Patreon page to the twitter bot? That would let us tweet out regularly.

**Comment by walshbr** [comment]
This has come up before @acrymble, and we decided against using the bot for things that weren't lesson promotion. The bot is set to regularly cycle through all of our lessons, so it is really best for things where we don't care at all about the frequency/timeline in which things come up. If we did add the patreon to the English sheet a lesson come up once ever 63 weeks. You could add more rows with more Patreon tweets to the sheet to affect the probability, but it would still only come up very irregularly and probably wouldn't satisfy the needs you have in mind, at least as I see them.

**Comment by acrymble** [comment]
Maybe I misunderstood @walshbr. I thought we could add new tabs which would each have their own random tweeting times (eg, one for each language).

**Comment by walshbr** [comment]
Theoretically we can - that is an entirely new use of the thing though that we haven't done in the past, and each added tab requires refactoring of the bot to make it work with the new data. It's not a ton of work, but it is work. I suppose we could add promotional spreadsheet tab that does things once a week, but I think there are probably diminishing returns. If I had to guess, our bot gets engagement right now because, as bots go, it doesn't tweet regularly enough for people to tune it out. Once per day most days and twice one day. But if we continue to add languages and other regularly tweets to it I think it will start to seem more like noise (not to mention more regularly be flagged and shut down by Twitter for _being_ a bot, which has only happened once so far). FWIW - it seems to me like visibility for the campaign isn't necessarily an issue - you've been doing a good job getting the word out and with the banners it's sort of impossible to miss as it's on each page. 

I guess all of that is to say that I can do this if you want, but I'm not sure I think it'd be that helpful. I'm not as plugged into this strategy as you are, though, being as I'm not on the development team. So I can do it if you decide it'd be useful. We should probably have a separate ticket to discuss what the implementation would look like.

**Comment by acrymble** [comment]
OK @walshbr let's not clutter the twitterbot. I will close this issue then and we'll continue with our current plan of tweeting or sharing from time to time.

It seems like one of the most effective way of getting new sponsors is the Monday tweets we do thanking new sponsors from the previous week.

If anyone has an idea for promoting this, please do tell us. It's really helped us get off the ground

**Comment by walshbr** [comment]
I think I've come around more to the idea the more I think about it, for what it's worth. Related desires for the bot have come up from time to time. But I'll defer to you @acrymble. Something that might be more compelling to me is a sheet that gives regular tweets to a series of related, prog-hist meta things, including Patreon:

- Patreon promotion
- Paypal donations and IPP program promotions
- Research people have done with the project
- Events like the Bogota workshop

If we could come up with say…two dozen items I think it could be very worth it, address your goal here, and also have different utility. And I think we could come up with that many.

**Comment by jenniferisasi** [comment]
As the Comm Manager I didn't like the idea of the bot tweeting for money very often either, but @walshbr this plan sounds really nice. I would add: 
- PH mission

**Comment by drjwbaker** [comment]
@walshbr: I like it, especially - outside the patreon, paypal, IPP stuff - promoting work we've done before, things like:

> Did you know in 2018 PH ran a Spanish language writing workshop in Bogota? If you want to propose a Spanish language tutorial to PH, see URL

**Comment by mdlincoln** [comment]
Regarding venues for promoting PR Patreon: after some discussion with @amandavisconti and the rest of the community on digitalhumanities.slack.com, they've opened up a `seeking-funds` channel where it would be appropriate for us to post an occasional message. @jenniferisasi note the guidelines here https://github.com/amandavisconti/DHslack/blob/master/CodeOfConduct.md#messages-involving-money-funding-related

**Comment by jenniferisasi** [comment]
Ok, so now we need a plan to process with: 
- new tweets for the bot (I suggest these are in all our languages, mixed, and let the random timing work)
- plan for slack promotion 1-month
-- @drjwbaker do you want me to take care of the promotion on digitalhumanities.slack.com?

**Comment by acrymble** [comment]
@jenniferisasi James is away but if you could do that I'd appreciate it.

I think the bot really belongs in a new ticket, so I'll open a new one where we can work on that. Do you want to take the lead, as it feels like a communication thing, ultimately?

**Comment by acrymble** [comment]
Given the rather sudden changes in global markets the last week or so as a result of this virus, I think we should hold off on too much promotion of Patreon for a few weeks as people focus their priorities elsewhere, and instead spend a bit of time making our existing patrons feel valued, and focusing on the IPP programming instead. Does that sound reasonable?

**Comment by acrymble** [comment]
I'd already closed this issue but @drjwbaker reopened it, so I'm going to assign the ticket to him if there's more he'd like to pursue.
