### ISSUE TITLE
DOI registration partnership

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1683]
@drjwbaker Any further public discussion of talks about DOI registration partnership should be broken out into this thread, away from #1370 since it's too big to be one issue. I'm opening a separate ticket for the purely Jekyll-related work that would need to be done after we have determined the DOI workflow with our provider.

**Comment by acrymble** [comment]
@drjwbaker can we move towards an agreement in writing on this pratnership? I'm worried that cost-cutting resulting from the pandemic may hit good will promises like this if not nailed down.

**Comment by drjwbaker** [comment]
@mdlincoln and I have a meeting scheduled for the 24th. An agreement is on the draft agenda.

**Comment by drjwbaker** [comment]
Right. @mdlincoln had a meeting today with our DOI provider. It was very positive. A few key notes:

- our provider is University of Sussex Library.
- we will run our DOI minting through the subscriptions our provider has with CrossREF.
- there will be no £ cost to PH.
- we will get our own (that is, PH specific) DOI prefix.
- we will use the content type 'Article in Journal'.
- our provider will mint DOIs for all our current and future publications.

- on our current publications, our provider will send a template for sending them publication metadata so that they can begin the process of registering DOIs.
	- @mdlincoln will fill out the template once received.
	- In the first instance, our provider will work through 10 publications to test the process and estimate effort.

- on our future publications:
	- our provider will get us a field list from CrossREF so - if/as required - @programminghistorian/technical-team can tweak our infrastructure to fit.
	- our provider will make a form to be completed with publication metadata. We agreed that in terms of the PH editorial process this would be completed after a publication has gone through peer review and author/editor are in agreement that it will be published. There will then be a second action in the editorial process to contact Sussex 2 or 3 days before publication so they know when to submit the DOI request to CrossREF (at present, we believe CrossREF needs a live DOI to mint a DOI). @svmelton @spapastamkou @rivaquiroga: I suggest we don't change our editorial workflow until we've tested this process - at some point we'll identify a 'in progress' publication on which to test this process, then we can make the necessary changes.
	- @drjwbaker will draft a document to be agreed with the provider that: a) states what we believe to be an edit that doesn't trigger a new DOI; b) states what we believe to be an edit that will trigger a new DOI; c) outlines our process for contacting Sussex regarding new DOIs for revised publications.
	- we agreed not to do any work on 'in progress' publications until we've cleared the backlog of outstanding publications.

- @drjwbaker will draft a document to be agreed with the provider that outlines our shared responsibilities and commitments (so that this agreement can survive changes in staffing on either side)
- our provider will come up with some wording we can use to recognise our relationship.
- @jenniferisasi: when we write a short blog announcing the partnership, we need to run it past our provider.

@mdlincoln: anything I missed?

As a general note, I've been leading this simply because we are working with my institution and it will involve making an agreement between Sussex and ProgHist Ltd, but I'm happy to take a back seat on editorial and technical matters as they aren't my department :)

**Comment by drjwbaker** [comment]
I've created a draft of the agreement described above. Emailing Ltd Directors and Tech lead for comment.

**Comment by acrymble** [comment]
I think we finished agreeing this, yes?

**Comment by drjwbaker** [comment]
Sorry. Yes. Agreement is in the archive repo.
