### ISSUE TITLE
New Bot Tweets for Communications

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1702]
As per #1680 we're going to start a new tab on our twitter bot spreadsheet to do some random tweeting related to various non-lesson issues (but not too often). @jenniferisasi has suggested doing so in all three languages.

Jennifer, can I ask you to start outlining what this looks like, and if you'd like help I am happy to chip in, but this is definitely your remit so I don't want to overstep my bounds.

**Comment by walshbr** [comment]
@jenniferisasi I'd suggest we keep all this content in a single spreadsheet, even if that means lumping in multiple languages into a single sheet. And then selecting a single day/time for this particular kind of tweet to go out each week. That would mean we have more content (3x because of the various languages, theoretically), which means it would take longer for it to go through a single cycle. 

And besides reducing the overall number of times the bot tweets each week, it's worth noting that there are limits to the number of times the bot can run each week for free on Heroku's free plan. It works on a similar model as Netlify, where it logs how long it takes to run each time it spins up. And then it adds together all those runtimes at the end of the month. The tweet script is pretty quick, so it shouldn't be a problem until we really go wild with tweeting. But still something to keep in mind.

**Comment by jenniferisasi** [comment]
> That would mean we have more content (3x because of the various languages, theoretically), which means it would take longer for it to go through a single cycle.

My idea with the multiple languages was to put them "into a single sheet" to precisely have 1) more content to go through the cycle so it feels less like a bot and, of course, 2) have these messages reach our multilingual community. 

I'll write a few tweets in a separate spreadsheet before adding anything to the bot spreadsheet.

**Comment by walshbr** [comment]
Sounds good! I made a "Communications" tab on the sheet. You can go ahead and add things there. The bot script looks for sheets by name when it goes to tweet, so adding stuff into a separate tab like that is fine until we pull the switch on it.

**Comment by jenniferisasi** [comment]
Ah, perfect then, thanks!

**Comment by jenniferisasi** [comment]
I've started generating a few tweets on the spreadsheet. Will continue with more soon.

**Comment by jenniferisasi** [comment]
@walshbr I have created 21 rows with tweets, so a total of 42; what I have done is create one in English and translate to Spanish and French (which is probably not perfect) to rotate the same ideas but for different audiences. Is that enough to start the bot?

**Comment by walshbr** [comment]
Cool! Yep for sure. I can work on this next week. I'll check back in when it's launched or if I have concerns.

**Comment by spapastamkou** [comment]
@jenniferisasi If you need input or help from the @programminghistorian/french-team, let us know.

**Comment by jenniferisasi** [comment]
Thanks @spapastamkou if any one of you @programminghistorian/french-team have 5 mins to check the French versions, I’d appreciate it just to make sure I didn’t put something terrible in there. And please feel free to add something similar in French that you think would benefit you.

**Comment by fdlaramee** [comment]
@jenniferisasi Sure, I can look it over; can you give me a link to the document please?

**Comment by jenniferisasi** [comment]
Merci @fdlaramee, it's [the same one](https://docs.google.com/spreadsheets/d/1o-C-3WwfcEYWipIFb112tkuM-XOI8pVVpA9_sag9Ph8/edit#gid=1625380994) where we already put tweets on lesson, on a new Communications tab.

**Comment by fdlaramee** [comment]
@jenniferisasi I had never seen that google spreadsheet before; above my pay grade! 😀

I tweaked a few things; nothing major.

**Comment by jenniferisasi** [comment]
Oh @fdlaramee that is probably just because now only the ME does the lesson publishing, so you probably never had to enter tweets. But all of us have access to it. 

Merci for the changes

**Comment by walshbr** [comment]
@jenniferisasi I set this up this morning. Keep an eye in the next week and lmk if anything looks amiss. I'll do the same.

**Comment by walshbr** [comment]
Working!
