### ISSUE TITLE
NEH Infrastructure and Capacity Building Challenge Grants

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1711]
The NEH just announced[ a new round of grants](https://www.neh.gov/grants/preservation/infrastructure-and-capacity-building-challenge-grants), one in particular to support: 
- **Digital Infrastructure** supports the maintenance, modernization, and sustainability of existing digital scholarly projects and platforms. 

It includes a 10% of the grant for fundraising efforts as it has a "matching requirement".  

@acrymble, I skim through the [NOTICE OF FUNDING OPPORTUNITY](https://www.neh.gov/sites/default/files/inline-files/Infrastructure%20and%20Capacity%20Building%20Challenge%20Grants%20Digital%20Infrastructure%20NOFO%202020.pdf) now and this is their rule:  

"Eligible applicants include U.S. nonprofit organizations with 501(c)(3) tax-exempt status, accredited public and 501(c)(3) institutions of higher education, state and local governmental agencies, and federally recognized Native American tribal governments."

I still wanted to share it so that someone with a better understanding of eligibilities can check if we are or not eligible (to my reading, we are not), and also to bring up "lost opportunities" on our status - this helps frame the publications for other grants I think.

**Comment by walshbr** [comment]
To my understanding the Programming Historian itself is not eligible to apply for grants like this, but the individuals in association with the project are. That's my understanding of other granting agencies, in the US at least, as well. In other words, in this case, if you were interested in applying, it'd be Pennsylvania State University applying with you as the PI. But you'd be applying to work on a project pertaining to ProgHist. That's how it always works for us - it's the institution that is awarded the grant, not the individual or the project per se (even though in effect it works out that the individual is the one directing the project). But if we have specific questions the NEH tends to have staff ready to answer questions, and they (or the grant officer at your university) would be the best people to ask because they deal with these things regularly. And it might vary institution to institution - UVA is a 501c3 institution at least.

**Comment by acrymble** [comment]
Looks like exactly what we need. @jenniferisasi are you interested in pursuing it?

**Comment by acrymble** [comment]
@jenniferisasi is this something that's likely to fit within your new job's remit? Are you interested in pursuing, or should we close this? I can't apply as a non-US-based person.

**Comment by jenniferisasi** [comment]
@acrymble, sorry, I am going to have to close the ticket as I am afraid I cannot commit to this grant (re-read it again) at this stage since 1) I need to develop a plan for the position at large and then follow it, 2) I am already working on a few collaborations, and 3) covid-19 made developing said plan a bit more difficult now.

**Comment by acrymble** [comment]
Absolutely. It's a big job, so unless it fits with your own needs and commitments, I totally understand.
