### ISSUE TITLE
summer fellows strategy

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#172]
How shall we run the fellows program next summer?

**Comment by wcaleb** [comment]
Subcommittee: @miriamposner @ianmilligan1 @tapar001 @jerielizabeth

**Comment by ianmilligan1** [comment]
Looking forward to this! Should we set up a call, or have initial conversation here?

**Comment by tapar001** [comment]
Likewise! It's perfectly alright with me if we begin the conversation here,
though if more of us prefer a call that works, as well.

On Friday, January 15, 2016, Ian Milligan notifications@github.com wrote:

> Looking forward to this! Should we set up a call, or have initial
> conversation here?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/172#issuecomment-172096266
> .

## 

sent from a mobile device

**Comment by ianmilligan1** [comment]
Sounds good! Here are some of my quick, introductory thoughts (which I sort of articulated on the call before I had to go).

I really liked the Summer Fellows program, mostly because it put me in touch with my fellow and I got to work with her to put a lesson together (which was great). However, I think if we do another go-around, we'll need to find some opportunity to build more community. This is always tricky with an online project...

Maybe:
- more regular interactions - Summer Fellows join the editorial team Skype calls;
- an online conversation, regularly scheduled.. once a month.. between all Fellows with a few of us editors hanging around?
- maybe we could find some cool joint project for us to all work on.. a blitz for lesson usability, for example, or collectively write a new lesson or something? 
- if we're ever together in one place over the summer (unlikely given geographic dispersion), such as a DH conference or something, make a point to get folks together to have a coffee! Again, unlikely.

**Comment by tapar001** [comment]
I will very quickly chime in here to say I think these are all great
suggestions, and to second the idea of community building.

As a former fellow I can say that anything we can do to encourage structure
might be a good thing. I love the idea of fellows joining Skype calls, and
the idea of an online conversation once a month or so. Personally, because
my summer ended up being busier than I anticipated, I really could have
used more check-ins/community building to keep me on track and to help hold
me accountable for producing a lesson draft more quickly.

In terms of group projects--what if we encourage fellows to organize a
panel for a conference about their experiences as fellows?

Another thing might be to think outside the box of
fellows-writing-a-lesson. Aside from lesson production and editorial work,
how else can fellows benefit from close interaction with the PH editorial
team? This might be making things too broad--but what if a fellow proposes
not a lesson but a project for their campus, i.e. maybe a student wants to
develop a digital storytelling initiative at their university, and they use
their tenure as a fellow to brainstorm with the PH editorial team about the
initiative itself and about how to marshall resources at a university
toward that goal?

And to note here something we discussed on the call--we might think about
where to advertise the fellows program and how to encourage greater
diversity among the fellows.

Looking forward to continuing the conversation, and to hopefully getting
together at some point over coffee!

Evan

On Mon, Jan 18, 2016 at 10:30 AM, Ian Milligan notifications@github.com
wrote:

> Sounds good! Here are some of my quick, introductory thoughts (which I
> sort of articulated on the call before I had to go).
> 
> I really liked the Summer Fellows program, mostly because it put me in
> touch with my fellow and I got to work with her to put a lesson together
> (which was great). However, I think if we do another go-around, we'll need
> to find some opportunity to build more community. This is always tricky
> with an online project...
> 
> Maybe:
> - more regular interactions - Summer Fellows join the editorial team
>   Skype calls;
> - an online conversation, regularly scheduled.. once a month.. between
>   all Fellows with a few of us editors hanging around?
> - maybe we could find some cool joint project for us to all work on..
>   a blitz for lesson usability, for example, or collectively write a new
>   lesson or something?
> - if we're ever together in one place over the summer (unlikely given
>   geographic dispersion), such as a DH conference or something, make a point
>   to get folks together to have a coffee! Again, unlikely.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/172#issuecomment-172577783
> .

## 

Evan Taparata
Ph.D. Candidate, History Department
University of Minnesota
1100 Heller Hall
271 19th Ave S
Minneapolis, MN 55455

**Comment by miriamposner** [comment]
This sounds great. As I recall, there was some talk about enlisting fellows
to do something other than write lessons (e.g., edit them instead). Is that
still something we're interested in?

Shall we also set ourselves a deadline for releasing the call for fellows?
Perhaps that will keep us accountable. Perhaps May 1? Is that too late?

**Comment by ianmilligan1** [comment]
I think both suggestions (editorial roles & May 1st deadline) are fantastic, @miriamposner.

**Comment by jerielizabeth** [comment]
I also like the idea of editorial roles and a deadline. May 1 sounds doable! I also liked your suggestion, @ianmilligan1, of a joint project! I think that would help with the community building aspect and with keeping the work load manageable both for us and for the fellows. 

If I remember correctly, one of the questions from the call was how many fellows we would want to take on. From last summer, how many fellows were invited and how did that go?

**Comment by acrymble** [comment]
I know I'm not on the committee, but I just wanted to flag this to make sure everything is still on track for May 1.

**Comment by ianmilligan1** [comment]
Closed re: #250
