### ISSUE TITLE
Lessons/translated lessons cost estimation

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1721]
This a question for all teams and members. Do you think it is possible to make an effort to estimate the cost of the lessons we produce? This could be useful in many ways, for us and for the grant proposals we prepare from time to time. 
Perhaps we can start to do it by estimating the time we invest in each step: receiving a proposal, decision making, looking for reviewers, publishing, communicating etc. 
Open to ideas on how to organize this.

**Comment by acrymble** [comment]
To add some context to this suggestion, this is in response to the occasional need (often on grant applications) for us to cover a portion of costs of any activity. The suggestion here is to assign a value (£) to our publication of and maintenance of a lesson. In order to be able to say activity X costs £5000, of which ProgHist Ltd will provide an in-kind contribution through publication equivalent to £Y. My own view is that this can be based on typical Article Processing Charges for journals in the humanities, and need not be costed on an hourly basis.

**Comment by walshbr** [comment]
When we do this for grants we usually estimate the hours it will take and multiply it by the salary (inclusive of benefits) of the staff involved. We don't necessarily break out specific hours per se, but we usually estimate a particular chunk of effort, something like 5% of your work week, over the course of the grant. So in other words, not chunking out cost by individual task but rather by the overall amount of perceived effort the particular initiative will take on. That'd be hard to do for individual lessons, though, since they don't take _that_ long to put together. Certainly not working on a single lesson every week for a year. 

For me, if I had to guess, I think it probably takes 3-4 working days to produce a lesson all told. But that gets spread out of the course of 9-12 months, so it happens in bits and pieces.

**Comment by drjwbaker** [comment]
For the record, I'm slightly uncomfortable with estimating what it costs to make a lesson. Sounds too close to the dreaded 'Article Processing Charges' for comfort. But if we need it for grant writing purposes only, I can be swayed.

**Comment by acrymble** [comment]
@drjwbaker I think we should also be aware from a ProgHist ltd perspective, what our costs actually are. It doesn't mean we have to pass them on to authors.

**Comment by drjwbaker** [comment]
By 'actually', what do you mean? An estimate of what it would cost to publish a lesson were we to pay everyone who is customarily paid in journal publishing? (not peer reviewers, not authors, not editors) Or an estimate if we paid everyone irrespective of publishing customs? (so the economic cost of all our collective efforts). These are two different things.

**Comment by drjwbaker** [comment]
(sorry to be picky here, I've just got a nagging doubt about the value/consequences of both making rough estimates and doing a through accounting..)

**Comment by acrymble** [comment]
I suppose I mean full economic cost. But I agree that's difficult for us to calculate at present because we rely on a combination of volunteer labour and paid labour which we don't pay ourselves and don't actually know the value of. A simple measure of full income per annum divided by number of publications might also do the trick.

It's really just so that we can show on a grant that we do provide value, so that we don't have to put any actual money towards the bid.

**Comment by drjwbaker** [comment]
> A simple measure of full income per annum divided by number of publications might also do the trick.

Not sure this measure will work. Every time we get more money, it'll put up the income/publications number.

If we want to do this properly, we could cost all the roles a 'normal' publisher pays people to do (managing editor, tech team, et al) - there must be studies out there that have done this - as a crude metric on the value of our voluntary contributions.

**Comment by acrymble** [comment]
It looks like we're stuck on this. @spapastamkou for the purposes of your grant, do you have a specific amount of work you want us to estimate? Maybe rather than have a cost per lesson we can assign a value to a package of work (eg, editing and copy editing a batch of 10 lessons?). Just want to make sure you've got what you need to submit your application.

**Comment by spapastamkou** [comment]
Actually the discussion here (and the question I had in mind before opening this ticket and discussed with @acrymble ) is how we can estimate the costs of processing a lesson, once it has been written and received, so that we can estimate somehow the work we do. It is really difficult to estimate as comments show and I am less and less sure we'll get a precise idea. Currently, for finalising the grant, my problem is to estimate the before: how much would it cost to ask someone to write one or more lessons - but for this I will go comment on #1659. 

Otherwise, I have found an article relying on a survey made in 2014-2015 in France for costs of editorial work in Humanities and Social Science journals. [The cost can be MIN 500 € and MAX 4 000 €, with an average of 1 330 €.](https://journals.openedition.org/rfsic/1716#tocto3n5) The sum is for editing/copy-editing and in majority (but not exclusively) for publicly funded journals.

**Comment by spapastamkou** [comment]
And for authoring a lesson, on the basis of a work of some 3 weeks for a lesson [as estimated here](https://github.com/programminghistorian/jekyll/issues/1659#issuecomment-613527454 ) in #1659, the estimated cost is some 1 500 € (calculated on the basis of a post-doctoral researcher salary).
