### ISSUE TITLE
Open a wiki page documenting how to start up a new language section

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1737]
- [x] copying existing directory tree for a language to a new named branch
- [x] how to update the snippets file
- [x] adding logos
- ...?

**Comment by amsichani** [comment]
In order to work more efficiently on this, I think it's wiser to create at least three subcategories at this wiki page , mainly corresponding to different teams within the project. The lead of each team should have an overview of the process and check in with the New Publications manager (@JoshuaGOB ) and the managing editor/ contact person of the new publication.
This is a living document and we will update it constantly.
 
- administrative tasks  (team development team) - data mainly from https://github.com/programminghistorian/jekyll/issues/1710

- [ ] register an ISSN with the British Library.
- [ ] translate all core pages.
- [ ] onboard all new publication members - see https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors
- [ ] add all new publication members's bios to the PH Project Team page (including a small black and white headshot).
- [x] Select a new publication Team Managing Editor (should be prepared to serve at least a year)
- [x] Select a new publication Team Ombudsperson (should be prepared to serve at least a year).
- [x] Communicate the Managing Editor and Ombudsperson selections to @acrymble and make sure that they are identified on the website.
- [ ] Create a blogpost and tweets to announce the new publication; this will call for translators/reviewers
- [x] provide managing editor training (shadowing) and partner them with an existing managing editor for mentoring.
- [x] provide shadowing opportunities to all incoming editors
- [x] logo for project
- [x] colour-scheme (sympathetic with our existing colour scheme).


- technical tasks (technical team)

- [x] copying existing directory tree for a language to a new named branch
- [x]  how to update the snippets file
- [x]  adding logos


- communication tasks (communication team)

- [x] link a member of the new publication team with @programminghistorian/communication-team  lead in order to help with translations of comms/ original comms

**Comment by acrymble** [comment]
@amsichani is this a guide for new teams AFTER a publication has been approved? I'm thinking of #1718

**Comment by amsichani** [comment]
hi @acrymble , I think yes, its a guide for new teams after the publication has been approved. I am not sure whether we have decided to have a more formal way of approving a publication at this point, but as far as I know the Portuguese team are now working towards their infrastructure. So I guess #1718 would be step 1 and this ticket /tasklist would be step 2 of an onboarding process of a new publication.  @JoshuaGOB what you think?

**Comment by jenniferisasi** [comment]
Just chiming in as I saw it on my email, I guess it will also serve as a pointer to new teams when they contact us (wiki-see all that you would have to do), and before we do #1718, no?

**Comment by amsichani** [comment]
I agree @jenniferisasi . Its best to have something on our wiki for potential teams willing to undertake a whole new publication instead of answering individual emails every now and then.
I think it will also facilitate the role of the new publications manager @JoshuaGOB , and will formalise procedures and necessary tasks. I am all in favour of making guidelines that will make it easier for our responsible team member to simply follow than re-inventing the wheel - it also adds more transparency and efficiency in our processes.

**Comment by acrymble** [comment]
Is @JoshuaGOB involved in this too? I definitely see that there are technical elements that need documenting, but this also heavily involves his role in onboarding the new team. Can we make sure those conversations across teams are happening? And can you let me know if we need help to facilitate that?

**Comment by amsichani** [comment]
yes, @JoshuaGOB should be /is definitely involved in this, esp with his experience with the PT team and as New Publications manager. 
Also, I want to invite @programminghistorian/french-team  and @programminghistorian/spanish-team managing editors and team members to add here crucial steps/tasks based on their own experience, so we can create a full list of requirements. It would be great if we can collect all comments by 10 June, so we can then draft & proceed with the wiki page. I am also thinking that we can collaborate with @acrymble and also write a blogpost on this, for teams/people willing to initiate a new language publication and also remind them the ad -hoc translation option.

**Comment by mdlincoln** [comment]
Started up the technical page here: https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Setting-Up-a-New-Language


I've covered most of the technical tasks I can think of - @amsichani and @programminghistorian/technical-team please give it a look and let me know what needs clarification or if I'm missing anything.

**Comment by walshbr** [comment]
@mdlincoln I might add at the front of the process opening a template issue on the repository with a technical tasklist that lists each of these things. It seems like the technical task of onboarding a new team should have its own ticket separate from the social/professional task of onboarding them. 

Because my sense is that you've been doing a number of these things for PT because you know to do them, but I'm not certain where we are in the process. If I were to be following this without you here I'd want a roadmap that I can tick things off publicly so that the rest of the technical team has them all in place. Other than that, you'd know best. I wouldn't really know what other technical components this would entail until I ran through the list and noticed that things weren't working. Thanks for putting this together.

**Comment by mdlincoln** [comment]
That's a very good idea @walshbr - will add to the instructions and also open such a ticket

**Comment by mdlincoln** [comment]
done #1802

**Comment by amsichani** [comment]
Hi all, I am now finalising the wiki page on this and I realised that we can also reflect and update the information we have on the New Publications Manager role, currently @JoshuaGOB.
 I guess the role will sit at @programminghistorian/development-team or @programminghistorian/global-team  --- we need to also briefly update the role description, perhaps this is something @JoshuaGOB can do in line with the relevant team lead?  In addition, I think the New Publications Manager should be the first point of contact for new publications, so we should amend the information here On the [New Publications Policy](https://github.com/programminghistorian/jekyll/wiki/New-Publications-Policy) -- if agreed, I will also include this information in the wiki page.

**Comment by acrymble** [comment]
@JoshuaGOB has just joined the global team @amsichani since this made the most sense given our conversations at the last team meeting.

**Comment by amsichani** [comment]
thanks for the update @acrymble , waiting now for a small on the role at the relevant wiki page.

**Comment by amsichani** [comment]
Here we are -- https://github.com/programminghistorian/jekyll/wiki/How-to-start-up-a-new-language-publication . 
Please feel free to add anything I missed out. I see it as a living document

**Comment by JoshuaGOB** [comment]
This is great @amsichani, thank you. Since the process is still ongoing I agree that it should be a living document and I will add any other points as they arise during the rest of the onboarding process. 

I was also considering if we should add a "Helpful Suggestions" section for some of the items. For example, how spread out the onboarding of editors should be, setting up an efficient schedule for the translation of the core pages so they don't fall out of sync with the main branch, and creating documentation along the lines of what the French team provides https://github.com/programminghistorian/jekyll/wiki/French-Translation-Documentation

**Comment by mariajoafana** [comment]
I'll this issue for discussion in our next meeting

**Comment by rivaquiroga** [comment]
@drjwbaker, I was wondering if we should add here a task related to setting up the DOI for a new language publication. For example, when we should inform University of Sussex Library about the new language?

**Comment by drjwbaker** [comment]
@rivaquiroga Yes, we have a MOU with them: https://github.com/programminghistorian/project-and-business-archive/blob/master/project/2020/2020-04_Sussex-DOI-MOU/2020-05-18_ProgHist%20MOU%20w%20University%20of%20Sussex.docx See item 4. under the PH Ltd responsibilities:

> 4.	Notify the University of Sussex Library before adding a new publication to its imprint, so as to not place undue financial or administrative burden on the University of Sussex. The University of Sussex Library reserves the right to refuse to register DOIs for publications under ProgHist Ltd’s imprint that are not covered by this memorandum.

I suspect this falls on me.

In the case of the PT publication, someone (@DanielAlvesLABDH @JoshuaGOB?) will need to tag me with this action on a relevant ticket. I can then ask them on our behalf.

**Comment by drjwbaker** [comment]
On https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Setting-Up-a-New-Language#ask-drjwbaker-on-behalf-of-the-ltd-to-check-with-the-doi-provider-that-they-are-happy-provide-dois-for-a-new-publication-if-the-provider-cannot-supply-dois-the-new-publication-will-run-without-dois-until-the-ltd-finds-a-solution there is not much more to add than what it says, accept that - just in case I fall under a bus - the task should probably be to ask the *someone* at the [Ltd](https://github.com/programminghistorian/jekyll/wiki/ProgHist-Ltd) to ask our DOI supplier.

**Comment by walshbr** [comment]
@JoshuaGOB am I right in thinking this can now be closed? I added the guide that AM put together to the table of contents on the right side of the wiki. Seems like PT is basically up and running - we just need to get the final DOI to launch them. And I updated the technical guidance for setting up a new language publication based on @drjwbaker's suggestion.

**Comment by JoshuaGOB** [comment]
Agreed, thank you all.
