### ISSUE TITLE
Condense multiple translation links for a lesson into one banner

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1738]
This is a visual change: we would like to put all of the various translation links into a single banner. This will mean editing _layouts/lesson.html to put every "related translation" link into the same `div`

**Comment by mdlincoln** [comment]
This is the relevant code: https://github.com/programminghistorian/jekyll/blob/eeb6e1801f97c8ef5edd9439827ec26aba293036/_layouts/lesson.html#L186-L203

**Comment by mdlincoln** [comment]
@amsichani I'm going to put you on this since its closely related to #1525 - as you can see, you will just need to edit a tiny bit of HTML for this. Go ahead and make a PR for this now, doesn't need to wait for everything else to be finished.

**Comment by jenniferisasi** [comment]
@mdlincoln I am not on a race with myself on making you hate me, BUT I am going to suggest something that I believe is easy (on the snippets) and I guess I'll have to change it myself. 

As the banners are right now, in general, they are fine "this lesson is also: title in x lang". Now, from a **language accessibility** perspective, you would have "message in x language; title in x lang." 
Ex. a Fr-only speaker lands in an EN lesson and can only guess something about French because they read the title of the lesson. Or, easier for all, when you get to a website in Chinese, you look for a button that says "language"; if that word is in Chinese characters you wouldn't be able to find it. Makes sense? 

I propose: 

```
In the language of the original lesson: original lesson title | In the language of the translation X: translated X lesson title | In the language of the translation Y: translated Y lesson title
```

@amsichani what do you think? does it make sense to you as also a multilingual speaker?

**Comment by mdlincoln** [comment]
If you and @amsichani like it then make a PR and let's see what it looks like.

**Comment by amsichani** [comment]
> @mdlincoln I am not on a race with myself on making you hate me, BUT I am going to suggest something that I believe is easy (on the snippets) and I guess I'll have to change it myself.
> 
> As the banners are right now, in general, they are fine "this lesson is also: title in x lang". Now, from a **language accessibility** perspective, you would have "message in x language; title in x lang."
> Ex. a Fr-only speaker lands in an EN lesson and can only guess something about French because they read the title of the lesson. Or, easier for all, when you get to a website in Chinese, you look for a button that says "language"; if that word is in Chinese characters you wouldn't be able to find it. Makes sense?
> 
> I propose:
> 
> ```
> In the language of the original lesson: original lesson title | In the language of the translation X: translated X lesson title | In the language of the translation Y: translated Y lesson title
> ```
> 
> @amsichani what do you think? does it make sense to you as also a multilingual speaker?

Hi @jenniferisasi , what you are suggesting makes perfect sense to me and thanks for pointing it out.

I am happy to collaborate on this. Just to make it clear , there are two tasks here:

1. alert messages on lessons' translations: amend the language of the message in the landing page --> change on the snippets
2. include various available translation links into a single banner --> change on the HTML

Let's start with 1 and continue with 2.

**Comment by amsichani** [comment]
I will now close this as the information and discussion is now on https://github.com/programminghistorian/jekyll/issues/1767
