### ISSUE TITLE
training for editors on finding peer reviewers

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1753]
Coming out of #1746 a sugestion for developing strategy for how to recruit peer reviewers. Linked to this is a realisation on my part that a) I don't think we train people on how to effectively and appropriately find expert peer reviewers. b) there must be resources out there for this and we could improve our collective skills by bringing some of those together.

The aim is to create a Wiki page that can be used by MEs in the training of editors.

**Comment by acrymble** [comment]
@spapastamkou @rivaquiroga @svmelton I was thinking about asking 2-3 of us to create a short video that shows our "process" for finding peer reviewers for a lesson, which we can put together into a training video. I suspect we all have different approaches to this, and I'd be happy to share my own approach.

However, I dont' want to interfere in the publications if you think that's overstepping my role. Can you please let me know your view?

**Comment by svmelton** [comment]
I think that would be appropriate and useful!

**Comment by acrymble** [comment]
Building this up a bit. I'm thinking 3 short videos:

- how to identify subject experts for a review
- how to approach potential reviewers
- how to make sure you're doing an inclusive search to identify reviewers with different characteristics to yourself (sorry not sure how to say that more elloquently).

Each one is maybe a 2-3 minute screencast or audio stream-of-consciousness, with the idea that it is helpful rather than a definitive step-by-step guide.

**Comment by acrymble** [comment]
I've drafted something that @jenniferisasi is currently taking a look at as we decide how best to disseminate.

I'm not really able to provide any guidance on finding peer reviewers for translations, or finding translators. I wonder if anyone on the @programminghistorian/french-team or @programminghistorian/spanish-team might be interested in sharing that knowledge? I'm happy to work with someone to turn it into a video by doing the editing work. If anyone thinks this would be something for them, please let me know. But no expectation that you have to feel obliged.

**Comment by fdlaramee** [comment]
@acrymble I'm terrible at asking for favors, which is what recruiting peer reviewers feels like to me, so I can't help you with good strategies. What I can tell you, however, is that finding peer reviewers for translations has been especially hard because there is no reward system for this sort of thing within academia. Peer reviewing an original tutorial *may* justify a CV line, but a translation? Thus volunteers are few and far between, and the reviews seem to end up pretty low on their lists of priorities once they agree. As a result, we pretty much decided to handle as much of that work as possible in house from now on. Very much interested in hearing others' success stories, though!

**Comment by acrymble** [comment]
Thanks @fdlaramee that is a challenge. Would you find it valuable to have some advice or resources to make that process easier? Or perhaps to help try to bring the 'success rate' up on requests turning into actual reviews?

**Comment by fdlaramee** [comment]
@acrymble Yes, very much so.

**Comment by acrymble** [comment]
@fdlaramee if you're free for a call sometime soon it would be great to talk through a little bit so I can think about what best to put together. If you're too busy that's ok, but I'd like to make something useful so input very welcome.

**Comment by fdlaramee** [comment]
@acrymble Certainly; tomorrow (Friday) or next Tuesday, at your convenience. I'm on Eastern time, which is UTC-4 at the moment.

**Comment by spapastamkou** [comment]
Perhaps it is already the case, but it is important to distinguish between review of an original lesson and review of a translation. 
I only have one experience of organizing a peer review for an original lesson of the PH (and 1-2 for a conference); the key elements were:
- knowing the field so to easily identify experts; 
- trust fellow editors advice
- mix reviewers of different disciplines/professional domains (depending the subject of course)
- mix reviewers of different nationalities/languages  
I wasn't able to find women in this particular case. 

For the translation reviews, some key elements were: 
-  identify users who for x reason may need a translation of a tutorial in a domain they are active: students, professors, librarians, archivists etc. Sometimes you are identified bcz the need is there (spontaneous proposals), sometimes people who are not available may recommend others who are. Identify them means following professional lists, Twitter etc.
- it is better to have two, but be ready for one if necessary. 
- use various means to reach people: e-mails, Twitter, personal networks, professional lists...
- in France, established academics may be difficult to make themselves available unless very interested in a lesson or by love for the PH; but younger teachers, doctoral students or engineers, librarians and archivists may be more open 
We had a total of 11 external reviewers up until now; from the 5 or 6 refusals some collaborated in other occasions.
Translation reviews is one of the activities that can be organized in the house, especially for domains where we have internal expertise, as show the ES experience and our decision to work on the series of Python lessons internally. But externalize when possible helps create a community with contributors who might otherwise not be very involved in other roles (authors, translators etc).  Hope this is helpful.

**Comment by acrymble** [comment]
The first video is with the MEs for comment. If it proves ok we'll start sharing it. Thanks @fdlaramee I will be in touch in the coming weeks about the next one, once we sort this out.

**Comment by acrymble** [comment]
Thanks to everyone who gave help and feedback. This is now available on youtube via our channel, and is listed on the wiki under 'Editorial Guidance'.

https://www.youtube.com/watch?v=jp0yCePvX-k&feature=youtu.be

I hope people find this helpful and that it saves time for everyone onboarding new team members in future.
