### ISSUE TITLE
Translating PH to Portuguese

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#1818]
The Portuguese team has translated pages Index.md, Lessons.md, Project-team.md, Feedback.md, Contribute.md, Privacy-policy.md, About.md, research.md, reviewer-guidelines.md, support-us.md and Editor-guidelines.md (https://github.com/programminghistorian/jekyll/tree/gh-pages/pt). We want now to proceed to the other pages of the platform. The notes we get from @acrymble were that we were supposed to contact for advice. Don't know if this is the best way to do that, but since I need to practice on GitHub and with "issues" it sounded adequate.

**Comment by acrymble** [comment]
@DanielAlvesLABDH please remember I asked you to let us know when translation of one of these pages starts so that we can make sure no further edits happen to it while your team are working on it. I said we'd put a 1 month pause on changes to any page you were translating. If you don't tell us this your pages may be out of sync with the rest.

**Comment by DanielAlvesLABDH** [comment]
@acrymble I remember that talk but has I mentioned to @JoshuaGOB and @rivaquiroga the Portuguese team will work a little bit differently because we will have two translations versions of each of the files, one made by a Brazilian colleague, the other by a Portuguese. That was done for the files mentioned above. We will start now the process of revising both files and merging them in a single final version (now on GitHub). For this second phase (that will start probably in two weeks) we will ask you to stop further edits. What I was asking here was advice on the translation of the other files. In the doc that you initially send to us you specifically mentioned "Website data that needs translating (contact Adam Crymble or Jessica Parr for advice)". Because part of the team is working on the revision process I mentioned, and part will start now the translation process of these second set of files, I'm asking advice for this second team. Thanks and sorry for the confusion...

**Comment by acrymble** [comment]
@DanielAlvesLABDH thanks for clarifying.

I think it's best to ask @JoshuaGOB for help on those, and he may need to consult with the tech team. These are the following files:

Activities.yml
ph_authors.yml
snippets.yml
teamroles.yml
topics.yml

Similarly, it might be worth talking to a ME (maybe @rivaquiroga) about:

Translator-guidelines.md
Author-guidelines.md

As these need to be tailored to the specific needs of a publication in Portuguese. She might be able to suggest how the Spanish publication managed those.

**Comment by walshbr** [comment]
FYI - I'm the tech team contact for this, so just let me know if you have questions.

**Comment by DanielAlvesLABDH** [comment]
Thanks both @acrymble for pointing the colleagues I should talk and @walshbr for reminding that you are the person I probably will be asking for more help when we start to upload the translations ;-)

**Comment by jenniferisasi** [comment]
Communications manager here: @DanielAlvesLABDH no pressure and no rush on this idea but it would be maravilhoso if, when we write a blogpost signaling the launch of PH in PT, we have a paragraph on the issues you are facing and decisions you are making on translating to Brazilian/Portuguese.

**Comment by DanielAlvesLABDH** [comment]
Great @jenniferisasi ! Nice to meet you. Already in the agenda! The Portuguese team have some peculiarities, glad to share that.

**Comment by spapastamkou** [comment]
@DanielAlvesLABDH Congrats for the work of your team! A small reminder here for something that could remain unnoticed: once you prepare to launch the site and make a pull request for the PT `about` page, please ping or ask for review from @rivaquiroga @svmelton and me so that we all modify [this part](https://programminghistorian.org/en/about#history-of-the-project) of our respective pages and add info on the PT team and launch of web site. Thanks!

**Comment by DanielAlvesLABDH** [comment]
Hi Sofia! Thanks. Will do that. We already incorporate those changes in the translated versions of that file.

**Comment by spapastamkou** [comment]
Great, thank you very much!

**Comment by DanielAlvesLABDH** [comment]
We expect to start the process of uploading the translations of the first set of files mentioned in my first message during next week. Since my time is very limited until the end of July and I will have my vacations on August, I want to make sure that we finish this first set of files, including the choice of the logo (#1822), during next month. The Portuguese team has two members with a better expertise on MD and GitHub then myself, and they are willing to help in this stage. My question is if they can do it, with my supervision, and how?

**Comment by walshbr** [comment]
@DanielAlvesLABDH - ultimately, you will want to open a new branch where you will upload your translations.  There are instructions here for doing so - https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions - that you should be able to follow, but let me know if you get confused. 

Matt put placeholder versions of all the English texts into a folder here for you - https://github.com/programminghistorian/jekyll/tree/gh-pages/pt. So you'll replace the contents of those files with the contents of your translations. The one tricky thing is that certain filenames should be fine to translate, and some not. And the metadata keys at the top of your file (the first half of each pair of metadata items) will need to not be translated. But either way if you just upload what you have I can take a look and help you to troubleshoot it. And once you have successfully uploaded the files to the branch you will open a pull request and tag me in it to review the contributions. If you wanted to handle a file or two at a time in a particular branch/pull request we could do that so you get the hang of it. But it's also fine if you want to upload everything all in one go - we'll just likely have a lot of errors to deal with in that instance. 

Let me know if any of that needs clarification.

**Comment by DanielAlvesLABDH** [comment]
@walshbr very clear and helpful. Thanks! Just two clarifications. First, after we start the process you will stop editing those files, as indicated by Adam, correct? Second, after I create the branch can I share it with my colleagues so they can make the changes? The second question is due to my inexperience with GitHub. I'm guessing it is possible, just to make sure. In the end I will make the final revision before the PR and tagging you...

**Comment by walshbr** [comment]
@DanielAlvesLABDH 

1. sure, but since we're somewhat decentralized I'm not certain what the best approach would be for us to make sure no one makes changes to those files. @acrymble do you think letting the managing editors know is enough? We could also email the ProgHist list, which might be the most effective way to reach everyone. 
2. Yep - that should be fine. Every pull request gets a link, like https://github.com/programminghistorian/jekyll/pull/1820. So you can share that with your colleagues. And if you or any of them need to make changes to the branch or pull request once it has already been made you can follow the steps in the wiki - https://github.com/programminghistorian/jekyll/pull/1820. I know GitHub just changed their user interface slightly in the last week, so let me know if you have trouble with any of the screenshots there. 

As one other piece of advice, though, I might suggest trying to get the text of the documents set as much as you can before you get down to upload to github. It's not super great for comparing differences in large text paragraphs, and it's easier to do that in google docs or something similar. We can always make changes, but just a matter of what is easier to work with. Ideally, we'd like to be dealing mostly with cleaning up markdown and things on the pull request, because there are always problems like that to address. 

Feel free to ping if you have questions.

**Comment by jenniferisasi** [comment]
@walshbr in reading this, don't we need to grant access / add the other editors to the repo before they can add/change anything on the branch Daniel will create? Since they have not done the onboarding yet, I'm not sure they would have permission to do changes

**Comment by walshbr** [comment]
@jenniferisasi yes that's a good catch! @DanielAlvesLABDH - the people on your team would need github accounts to be able to open pull requests as I described above.

**Comment by DanielAlvesLABDH** [comment]
@walshbr thanks! Very clear. The translation process has been done exactly as you suggested so we are on the right track. As for the comment from @jenniferisasi I can say that they both have GitHub accounts and experience with MD, so I think everything is set for us to start making those changes. Our schedule is next week but I will let everyone aware in advance.

**Comment by walshbr** [comment]
@DanielAlvesLABDH what are the github usernames of your collaborators that will be uploading documents / opening pull requests?

**Comment by acrymble** [comment]
@DanielAlvesLABDH I think we're still not understanding each other fully. The pages you've been translated have already been altered because we never got word that you were translating them, so we didn't pause work on them. You can see on this page the time that's passed since the last changes https://github.com/programminghistorian/jekyll/tree/gh-pages/en.

If you don't say "Please stop work on pages x, y, z" we will continue treating them as pages that can be changed.

**Comment by DanielAlvesLABDH** [comment]
@acrymble we are going to ask you to stop working on those files probably during next week and for at least 3 weeks.

**Comment by acrymble** [comment]
Great. We'll do our best to make that as easy as we can. Thanks @DanielAlvesLABDH

**Comment by walshbr** [comment]
Thanks @acrymble

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> @DanielAlvesLABDH what are the github usernames of your collaborators that will be uploading documents / opening pull requests?

Hi @walshbr They are Aracele Torres, username aracele (aracele@protonmail.com), and Josir Gomes, username josircg (josircg@gmail.com).

**Comment by walshbr** [comment]
I added them both - they'll have to accept the invitation before they can submit a pull request. @DanielAlvesLABDH

**Comment by acrymble** [comment]
@DanielAlvesLABDH @walshbr we really should be onboarding anyone given access to the repository. Otherwise we don't have a clear process for knowing who has access to what. Can we please open onboarding tickets for both?

**Comment by walshbr** [comment]
I opened those tickets @acrymble. It might be worth adding notes in the onboarding wiki about whose job that is in the future - I didn't know who to assign for those tickets or whose job it is to push that onboarding process along. It felt like global/team development, so I added those labels. Can you add the appropriate people and/or change the labels if I did it incorrectly?

**Comment by JoshuaGOB** [comment]
Hi @walshbr, my thinking is that the ME and the new publications manager would be the leads in opening the tickets and seeing them through. I think the labels you added are the right ones as well but please chime in @acrymble since it is the first time I go through this. 

I had emailed @DanielAlvesLABDH as per his last message in #1778 to walk him through the onboarding for a different member. I'll look at the wiki to reconsider the best pacing for onboarding new members considering the needs of translating pages in this way.

**Comment by walshbr** [comment]
Cool @JoshuaGOB - I'll assume that you and @DanielAlvesLABDH are in charge of those onboarding tickets then.

**Comment by DanielAlvesLABDH** [comment]
Hi to all. I have been following this thread but too busy this week because of a project meeting tomorrow. I will do the onboarding both of Aracele and Josir, but also for Danielle, the other editor of the Portuguese team. I will keep close contact with @JoshuaGOB about this process. I want to learn also by doing but my rhythm is slow because of all the other work. Thanks to you all!

**Comment by DanielAlvesLABDH** [comment]
Hi to all. As mentioned in the first message, the Portuguese Team is now on the position to start translating and uploading the core files of the PH platform. For now we will work on these files (Index.md, Lessons.md, Project-team.md, Feedback.md, Contribute.md, Privacy-policy.md, About.md, research.md, reviewer-guidelines.md, support-us.md and Editor-guidelines.md)(https://github.com/programminghistorian/jekyll/tree/gh-pages/pt). Our goal is to have these task (regarding those files) completed by the end of July, so I'm asking if it is possible to stop the editing process of the English originals starting next Monday, 13th, until Friday 31.

**Comment by acrymble** [comment]
@DanielAlvesLABDH can you let us know the status of these pages? You said you wanted us to wait until 31 July, which has passed.

**Comment by DanielAlvesLABDH** [comment]
@acrymble we are still working. As you know we had some problems starting because of the onboarding process, then came vacations, but we are trying to finish until the end of August.
