### ISSUE TITLE
Footnote issue in Sustainable Authorship in Plain Text using Pandoc and Markdown

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1833]
The authors of [Sustainable Authorship in Plain Text using Pandoc and Markdown](https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown) alerted me to an issue with the footnote display. The footnotes cut off, and some of the footnote text appears in the section above.

I've looked through the markdown and can't see an obvious cause for the problem. The footnotes are slightly out of order (.e.g footnote 4 appears before footnote 5 in the text), but that's also the case in the Spanish translation, and the footnote text seems fine.

Would someone from @programminghistorian/english-team be able to take a look?

**Comment by walshbr** [comment]
@svmelton - re: the text getting cut it looks like the footnotes in Spanish are differently formatted because the text of each footnote exists on a single line. Whereas for the English lesson the footnotes have some line breaks artificially introduced in the middle of the notes themselves. That's probably the culprit. Were you going to put together a pull request, or should I do so?

**Comment by walshbr** [comment]
(maybe worth mentioning what it is implicit in my last comment - that whoever translated this into Spanish did a good job of catching the error and fixing it 🥇 )
