### ISSUE TITLE
Idea for PH sponsored workshops

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1867]
A twitter conversation sparked the idea among the Spanish team of organizing an online PH-sponsored workshop about Python for beginners. After discussing it across the Spanish team and with James and Adam, we thought that makes sense to discuss how important this idea might be across the project. 

In Spanish-team we believe that organizing online workshops is a way of reinforcing the presence of PH in the Spanish-language world and that this outreach strategy can help the community grow. We envision this possibly as a yearly initiative. The one particular Python workshop that we are planning is intended to be free for participants but will ask participants to consider becoming PH patrons.

That said, we also discussed that is desirable that we pay a fee (symbolic?) to the person in charge of delivering the workshop. We understand that ProgHist has financial priorities right now and this might not be top of the list. If we want to move forward with this @drjwbaker suggested considering the possibility of finding a sponsor to share costs and to develop a model for these workshops so they are easily reproduced. 

I just wanted to share this idea and see what you all think. We can use the proposed workshop in Spanish to try out the model and if ProgHist funding is not readily available for this we can explore other avenues for paying for the workshop (mainly paying a fee to the person in charge of delivering it).

**Comment by drjwbaker** [comment]
Can I add that given that conference travel restrictions are likely to be in place for some time, one idea is to use funds we would have spent and be spending (~$200 per year) right now on conference stickers https://github.com/programminghistorian/jekyll/issues/1629 on workshops. So there is a short term thing here (replacing some of the sticker goodwill with some workshop goodwill) to go with the longer term thinking (potentially making this a regular thing that we do, and building a light model for delivering these kind of workshops).

**Comment by drjwbaker** [comment]
To add, we don't have enough money right now to subsidise 4x workshops per year as a sustainable activity (spending priorities are at https://github.com/programminghistorian/jekyll/issues/1788#issuecomment-660959706), but if we think it is worth the effort, if we have the capacity to do this, and if it can become part of our income generation activity, the Ltd is there to try to help make things like this happen for [its members](https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Register-of-Members).

**Comment by acrymble** [comment]
@mariajoafana I think a workshop like this would be very 'fundable' from potential donors. Either a research centre or a department. Have you explored that option within the network of your team? I ask because this is also a good way to build relationships with external partners. Especially since the amount of money is quite small.

**Comment by mariajoafana** [comment]
Yes @acrymble this is a good idea. In my case at the university and memory institutions in Colombia, this is not the best time to ask for money, even if is a little amount, because of austerity policies, but other members of the team are assessing this possibility.
It just occurred to me that I can discuss this with the Red Colombiana de Humanidades Digitales

**Comment by acrymble** [comment]
You could set up an event on Eventbrite and 'sell' tickets that people can buy to provide a space for someone else on the course. Sell 10 tickets at £10 and you have your money. I think people would do it with the right messaging.

**Comment by arojascastro** [comment]
Sorry, but I do not understand... Since we have Patreon and donations I do not see why each team can have its own annual budget and use it as each team prefers... can you please clarify this doubt? Thanks.

**Comment by acrymble** [comment]
@arojascastro nobody has said no to the request. We just haven't had a chance to discuss it yet as a full team.

We very recently opened up a discussion for new lines of spending #1790 and are still in the process of setting that recommended service up. It will likely not be fully in place until September, so that's 6 months from idea to implementation. This request is a new one and has implications for spending across 4 teams. So far we've only heard from one team on it so I don't know if there's a wider need here or not, we haven't had a chance to discuss this at a meeting, and we haven't identified how best to fund it.

If other publication teams have a view on this possible service, this is the place to share those views. 

If your timeline is short (no one has yet told me when you want to host this event), I've suggested a few ideas for getting the money other ways, because we don't yet have agreed budgets as you've suggested, and it's not really possible to grant one until we have our bi-monthly meetings.
