### ISSUE TITLE
November 23 2020 Project Team Zoom Call 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1917]
November 23 2020 , Time is 9:00 AM - Mexico, Colombia, Ottawa, Philadelphia, Boston; 11:00 AM Chile and Brasil (GMT-3); 2:00 PM - London; 3:00 PM - Paris and Berlin. @mariajoafana will be facilitating the call. 

Zoom link: 
https://uniandes-edu-co.zoom.us/j/85844610643?pwd=UWl0bitNK1BDWkxqZkhXc3Rjd241Zz09
Código de acceso: 429218

Working agenda in progress. The time and day will be scheduled within the next couple of weeks. Please add in these agenda under "Issues and tasks for discussion" the tickets that you'll like to further discuss in the meeting. You can comment or edit this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [ ] Actions Arising from September 2020 Project Team Meeting: #1907 

- Issues and tasks for discussion: 

 - [ ] 
 - [ ] 
 - [ ] 
 - [ ]  
 - [ ] 

- [ ] ES team issues
   - [ ] Antonio's farewell :)  

- [ ] EN issues

- [ ] FR team issues 

- [ ] Portuguese team issues

**Comment by drjwbaker** [comment]
sadly, I won't be able to make this one.

**Comment by jenniferisasi** [comment]
@mariajoafana looks like it will be 8AM in Mexico; I noticed cos it usually matches with US central time
![Screen Shot 2020-10-29 at 12 18 53 PM](https://user-images.githubusercontent.com/11022533/97601772-ea58f800-19e0-11eb-8aa2-2d9aa20b46c0.png)

**Comment by drjwbaker** [comment]
> sadly, I won't be able to make this one.

I can now.

**Comment by spapastamkou** [comment]
## FR Team Report

By: @spapastamkou 
Date: 22 Novembrer 2020

---

**Actions Completed Since Previous Report:**

2 translated lessons published (Pandoc + Markdown; Jupyter Notebooks)
1 translation (out of a stock of 5) now under review
1 translation proposal (out of 2) now ready to come in (as mailed by the external translator)

**Actions Remaining Open Since Previous Report:**  

FR Copy Editing Chart
1 translation proposed by Sofia coupled to testing a translation tool for GitHub 
4 translated lessons need to be edited for review

**Other**
Did not get funding from the FNSO
1 external translation proposal received and under consideration from the team members (Intro to Beautiful Soup)
Call for editors: Skype interviews from 25 November to mid-December

**Queries for the Editorial Board:**
None

---

**6-month focus:**
Integration of new editors (according to existing candidatures and perhaps after invitation for under-represented areas)

**12+ month focus:**
Continue combined publication of translated and original lessons in FR
More effectively communicate on PH FR

**Further Comments:**


None

**Comment by jenniferisasi** [comment]
## Communications Team Report

By: @jenniferisasi  
Date: 22 Novembrer 2020

---

**Actions Completed Since Previous Report:**

- @acrymble stepped down from the Team Development Manager position to focus primarily on securing IPPs. @mariajoafana has agreed to take on the role, merging it with Project Manager at Large  
- Published the 3rd Newsletter of the year #1903 
- Tweeted weekly about/looking for Patreon supporters

**Actions Remaining Open Since Previous Report:**  

- Update `feedback` page #1908
- [not on ticket] finalize panel proposal for Global DH at MSU

**Other**
- Joined @acrymble in meeting for potentual IPP member
- Will start the last Newsletter of the year at the beginning of December

**Queries for the Editorial Board:**
None

---

**6-month focus:**
New way of communicating our progress with the public to replace Newsletter (or maybe we don't need one since Twitter works very well; but need something to show IPPs too))

**12+ month focus:**

**Further Comments:**


None

**Comment by svmelton** [comment]
## EN Team Report

By: @svmelton  
Date: 22 November 2020

---

**Actions Completed Since Previous Report:**
- 1 [lesson at copyediting](https://github.com/programminghistorian/ph-submissions/issues/285)
- 1 [lesson in PR](https://github.com/programminghistorian/ph-submissions/issues/278)
- 1 [lesson awaiting author's edits](https://github.com/programminghistorian/ph-submissions/issues/301#issuecomment-664571003)
- 3 new submissions under review
- 3 lessons awaiting editorial assignment


**Other**
- Discussion with @walshbr and @hawc2 around [onboarding](https://github.com/programminghistorian/jekyll/issues/1932) and the need to have better systems for editorial shadowing, etc.
- To alleviate some of my time, other members of the EN team will be helping with initial bug queries and other editorial duties. @walshbr has also set up a meeting with the new editors (and me) to get them up to speed on editorial tasks.

---

**3-month focus:**
- Complete onboarding, suggestions for how onboarding can be improved

**Comment by DanielAlvesLABDH** [comment]
## Portuguese Team Report

By: @DanielAlvesLABDH 
Date: 23 November 2020

**Substantive Actions Completed Since Previous Report**

- Translation of the PT platform 
- Round table to present and discuss the impact of the "Programming Historian in Portuguese" in the online event "I JORNADA NACIONAL DE HUMANIDADES DIGITAIS", organized by IBICT, Brazil (October 13th) - Available here: https://www.youtube.com/watch?v=bt-OaMW2Fr4

**Substantive Actions Remaining Open Since Previous Report**

- Four lessons translated from English (waiting for review)
- Started the Onboarding for Jimmy Medeiros (not closed yet)

**3-month focus**
- Uploading the Portuguese version of the PH platform #1818
- Create a blogpost and tweets to announce the new publication
- Onboarding of the last editor of the PT team (Ricardo)

**6-month focus**
- Start the translation of at least 6 lessons from the English originals

**12+ month focus**
- Finish and publish at least 16 lessons translated from the English originals
- Implement some of the lessons in one graduate course at NOVA-FCSH (Lisbon) and in another graduate course at FGV (Rio de Janeiro)

**Comment by DanielAlvesLABDH** [comment]
I will not be present on today's meeting because I have a PhD jury at the same hour

**Comment by walshbr** [comment]
I will not be there today.

**Comment by rivaquiroga** [comment]
## ES Team Report

By: @rivaquiroga  
Date: 23 November 2020

**Actions Completed Since Previous Report:**
- Bug-Assesment: Jairo Melo was apointed as bug tester.
- Copy-Editing: This role will be covered by members of the ES team. Three members expressed their interest (VG, JAM, RQ); we will ask again at the beginning of 2021 (as some members are currently facing time constraint issues).
- Python workshop: possible dates + founding options defined

**Editorial work**

*Original lessons*
- 1 [original lesson looking for a second reviewer](https://github.com/programminghistorian/ph-submissions/issues/286).
- 1 [original lesson awaiting editors's first review](https://github.com/programminghistorian/ph-submissions/issues/313).
- 1 original lesson to be submitted by the end of December.

*Translations*
- 1 [translation awaiting author's edits](https://github.com/programminghistorian/ph-submissions/issues/302). This is a lesson from the Bogotá Workshop that was first published in English.  
- 1 [translation under review](https://github.com/programminghistorian/ph-submissions/issues/303). 
- 1 [translation awaiting editors's first review](https://github.com/programminghistorian/ph-submissions/issues/306).
- 1 translation about to start the editorial process.

**Questions for the team**

- Some ES authors are interested in translaiting their own lessons to English. Do we have/need a workflow for this special cases? 

**3-month focus:**
- Copy-edit first original lesson.

**Comment by acrymble** [comment]
## ProgHist Team Report

By: @acrymble  
Date: 23 November 2020

**Actions Completed Since Previous Report:**
- IPP Pages update (English) (https://programminghistorian.org/en/ipp)
- 2020-21 Goals Adopted
1) Phased end to volunteering on all 'services' provided to pubs (@amsichani)
2) Clearly defined project manager role to advertise (@acrymble)
3) 40 IPP memberes to provide sustainable income support (@acrymble, @amsichani)
4) Fully registered as a charity in the UK (@drjwbaker)

- 2020-21 Goals without a leader (unable to take forward)
5) Leader to ensure paid copyediting takes place on all new lessons across 4 languages
6) Leader to ensure paid bug fixing is taking place and that the system is efficient and fit for purpose
7) Leader to create an outreach budget for each publication.


**Questions for the team**

- Does anyone's university want to join IPP? Can you find out for us or tell us who the best contact is so we can check?

**3-month focus:**
- Help @amsichani get up to speed on IPP sales

**12-month focus:**
- Complete all goals as above.

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc 

Date: 23 November 2020

Substantive Actions Remaining Open Since Previous Report:

- Complete Matt Lincoln's retirement with Cloudflare transfer #1761. Zoe got access to gmail inbox so now need to reach out to GMU.
- For updating guidelines on submitting lessons to PH-Submission we are beginning to implement as we were waiting on PT team to be fully setup #1795 

6-month focus:

- Tech team meeting in December to discuss goals and maintenance for the next few months. Review https://github.com/programminghistorian/jekyll/wiki/Technical-Team#new-feature-backlog to see if we want to undertake any particular feature
- Help support Portuguese team onboarding and any additional new editors that need training

12+ month focus:

- New features?
- Documentation review
- Review of Github issues trends

**Comment by drjwbaker** [comment]
I'm struck by quite how many articles are in process at the moment across the 4 publications. Thanks so much to all the editorial team for continuing to work through these is such a challenging year for everyone.
