### ISSUE TITLE
handling images

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#192]
revise documentation to have authors submit images for their lesson in a separate folder within the master images directory. we won't change any existing image organization for now, but we will begin doing this for new submissions.

**Comment by wcaleb** [comment]
When you make the instructions on naming the images, you may want to suggest shorter filenames. If the whole lesson slug is going to be the name of the directory, putting the lesson slug in the filename of the image again will make for really long, bulky `figure` syntax. (On the other hand, best practice in filenaming is usually to make them more descriptive than just `fig1`, `fig2`, etc., so that if they somehow get moved outside the folder, it's still easy to tell what they are. So not sure what the best style is here.)

**Comment by mdlincoln** [comment]
Suggestion from my experience writing the SPARQL tutorial: ditch naming figures sequentially (`fig1`, `fig2`), and have people name them semantically (`lod_graph`, `highlighted_lod_graph`). This would work well with having separate image directories for each lesson. This convention would allow images to be reordered during the review/editing process without laborious (and totally unnecessary, for this platform) renumbering of image files.

**Comment by acrymble** [comment]
I've just had to go through all of the images, and most people are not
labelling them fig1, etc. In fact, a number of people named them
'Screenshot-2014-01-03etc.'. There are also a number of images in our image
folder that I don't think ended up in any lessons. None of that adheres to
our current guidelines.

**Comment by ianmilligan1** [comment]
Having just fixed a few images, I must admit I liked when they were numbered like:

`geo1.png`
`geo2.png`
`geo3.png`

etc. as it helped me track down errors and tie files to Fig 1, Fig 2, Fig 3, etc.

**Comment by wcaleb** [comment]
Important changes here that you should all be aware of. I have updated our site and our workflow instructions to reflect a new system for handling images:
- All images for a lesson should be placed in a subdirectory within the `images` folder.
- The subdirectory should be named with the same URL slug used to name the lesson.
- The `figure.html` syntax now only requires the image `filename` and the `caption`; the full path to the image will be automatically filled in, as discussed in #244 

Note that since there was some disagreement on this issue about whether to name the images semantically or sequentially, I left that open to editorial discretion in the instructions for authors and editors. But we can discuss further on next call if needed. I will be creating some separate issues for some lessons I found where our `figure` syntax has never been implemented in the first place.

@fredgibbs @amandavisconti @ahegel @jerielizabeth @acrymble @ianmilligan1
