### ISSUE TITLE
Python tutorials series banner in ES

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1945]
The Python tutorials in Spanish don't have the lesson series banner that the lessons in English have. 

![Screen Shot 2020-11-30 at 1 39 08 PM](https://user-images.githubusercontent.com/11022533/100650097-6d87a980-3311-11eb-8ff8-e2d14a0829a5.png)

Why didn't we add it when we added the one in English @amsichani? I can't remember... I think the @programminghistorian/spanish-team should decide to have it or not and then @programminghistorian/technical-team can figure how to implement it.

**Comment by walshbr** [comment]
@jenniferisasi @amsichani. Was just looking at this at the end of the tech call - I think it might be in part because the Spanish lessons don't seem to have the "sequence: X" metadata field, which is what the template uses to see if it should include the sequence information. It looks like it's already translated, right? So I think you just need to add the sequence numbering for the lessons. The banner should pop up.

**Comment by amsichani** [comment]
I somehow knew that this ticket/job (https://github.com/programminghistorian/jekyll/issues/1767 // https://github.com/programminghistorian/jekyll/issues/1525) was never going to end...I will have a closer look at it in the coming days. Thanks @jenniferisasi for the heads up!

**Comment by jenniferisasi** [comment]
Thanks @walshbr for checking on that! I had not had time to look at it other than opening the ticket while I am writing a paper on the translations and wanted to *not* forget. If it's a metadata issue it should be easy to fix, which is good news @amsichani

**Comment by jenniferisasi** [comment]
I am going to add the 'sequence' metadata field in the YAML of the lessons and upload with a PR through GitHub Desktop on branch "python-sequence-spanish"

**Comment by spapastamkou** [comment]
Do all the lessons of the sequence have to be published before adding the banner? We have some published in FR, but are far from having them all (and we have no banner neither).

**Comment by jenniferisasi** [comment]
> Do all the lessons of the sequence have to be published before adding the banner? We have some published in FR, but are far from having them all (and we have no banner neither).

Mmm I don't know what will happen if it needs to "skip a number" ... as I understand it, the banner will "pop" once some lesson has this two fields added in the YAML metadata:   

```
sequence: 10 (the position in the sequence of X lessons that the lesson is at)
series_total: 14 (the total number of lessons in the sequence, in ES I put 14 cos the 15th is not translated)
```

The banner is ready in FR and PT too in the snippets.  

Do you want me to try with the lessons you have? I could always then undo the changes in the same PR. 

(hope that is clear, but also [see PR 1949](https://github.com/programminghistorian/jekyll/pull/1949))

**Comment by walshbr** [comment]
There's also these two fields which are used I believe - 

next: downloading-multiple-records-using-query-strings
previous: keywords-in-context-using-n-grams

Since the "sequence,"  "next," previous," and "series_total" numbers are all hard coded, you could theoretically skip lessons that don't exist yet…but that feels a bit confusing in that you would to document/remember that you're distorting the actual sequence in the hopes of going back to change them later.

**Comment by spapastamkou** [comment]
Thank you @jenniferisasi and @walshbr. It is perhaps better and simpler for everyone to wait until we have all these lessons published, to avoid any confusion for the team but also for readers. I note the issue and the PR, and we'll ask you for reviews - and/or previous advice:-) - once we get there.

**Comment by jenniferisasi** [comment]
Sounds like a good plan @spapastamkou, better for everyone and to avoid confusion in the long run.
