### ISSUE TITLE
HTML bug in rendering lesson's MD source 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1951]
A bug with the HTML rendering of the MD sources has been reported  [#305](https://github.com/programminghistorian/ph-submissions/issues/305) , regarding numbered lists.

**Comment by walshbr** [comment]
@ZoeLeBlanc might have other suggestions, but FWIW my suspicion is that that author's version of Atom and GitHub preview is rendering markdown differently because there are different markdown parsers. We use kramdown, Github uses redcarpet (and since Atom is made by GitHub it probably uses the same one). Changing the markdown parser is probably not something we should do because that might have much broader implications. We can check that the markdown parser is up to date, but the usual way to workaround this sort of thing is described here - https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list. It actually specifically mentions ordered lists separated by code blocks, which seems to be the same thing going on here.

**Comment by walshbr** [comment]
Closing this as, based on the conversation in #305, it appears to have been resolved.
