### ISSUE TITLE
Mac Catalina bug for "Building a static website with Jekyll and GitHub Pages"

### ISSUE THREAD

**Issue by quinnanya** [programminghistorian/jekyll#1955]
I love the "Building a static website with Jekyll and GitHub Pages" tutorial and have it bookmarked in my toolbar for easy reference! Today I tried to follow the instructions on a new Mac laptop running Catalina, and ran into permissions problems that couldn't be solved with any of the tips. What worked for me was, after brew install ruby, running export GEM_HOME="$HOME/.gem". Thought I'd pass it along as an update suggestion!

**Comment by rivaquiroga** [comment]
@JoshuaGOB, what do you think about adding this suggestion to the translation you are editing?

**Comment by JoshuaGOB** [comment]
Yes, Thank you @rivaquiroga and @quinnanya. I've informed the translators so they can incorporate the fix into their lesson. I couldn't replicate the error until I remembered that RVM is handling Ruby on my computer. That happened because of a tutorial on Jekyll from @elotroalex. Could be a more sustainable way of doing the lesson's tasks?

**Comment by walshbr** [comment]
FWIW @JoshuaGOB - RVM got completely wrecked on my machine when I upgraded to a more recent OS. It was basically unusable, but rbenv turned out to be much more reliable. I had used RVM for years. Seems like the bugtesting person might be able to make a recommendation about such things.

**Comment by elotroalex** [comment]
For what is worth, I still swear by RVM for working with any ruby based app. PyEnv for Python, and Volta/Node for JS. That's my story and I'm sticking to it.

**Comment by quinnanya** [comment]
I've never heard of RVM but would love to have it included in the lesson if someone could write it up!

**Comment by elotroalex** [comment]
It's in the docs for Ed. It changes how you run ruby apps. https://minicomp.github.io/ed/documentation/#installing-ed-robust

It allows you to have different environments for your apps. That way if something was working in 2018 you keep it with all those old dependencies and never update. In other words, for groups of projects that run with x setup, you have their own environment, and keep it stable. That can mean also different versions of ruby

**Comment by elotroalex** [comment]
(it's also how I avoid typing "bundle exec jekyll serve", since a simple "jekyll serve" works if you set your workbench right)

**Comment by quinnanya** [comment]
Beautiful! Yeah, that sounds like it'd be great to include in this lesson.

**Comment by walshbr** [comment]
FWIW, RVM broke pretty spectacularly for me when I switched to a newer version of Mojave? But I also think it wasn't a big upgrade - it was like Mojave 1.515 to 1.516 that happened automatically overnight, when suddenly Mac changed all their SSL settings. So I'd be interested to know if it worked for Catalina -  it was great when I used it. I had been using RVM for years and suddenly it was an SSL certificate nightmare and wouldn't install anything, no matter how many times I destroyed and reinstalled everything. I had to switch to rbenv, which wound up working pretty flawlessly right away. That's all to say that I would want the bug tester or @ZoeLeBlanc, who knows more about such things than I do, to investigate before we stick RVM in all our lessons (no matter how much I used to love it).

**Comment by johnpilbeam** [comment]
Same as @quinnanya this is a great tutorial, but it is not working for me on my current machine (Mac/M1/Big Sur). Everything is fine up to the Homebrew install, this is different on M1 based Macs ([https://docs.brew.sh/Installation#macos-requirements](https://docs.brew.sh/Installation#macos-requirements)). 
I could not install Ruby & Ruby Gems/Jekyll according to the instructions, in fact ended up breaking my system Ruby and had to reinstall (my fault, not the tutorial's, but without the right instructions, it is surprisingly easy to trash Ruby). 
This might be an edge case as I had setup the M1 Mac via Migration Assistant from an Intel machine with Homebrew and Ruby installed. However, I do think that Ruby installation on the Mac is fraught with problems which is not helped by the semi-deprecated/out-of-date system Ruby and the Apple Silicon transition, and the guide doesn't take this into account. One alternative route might be recommending a script (e.g. [https://github.com/monfresh/install-ruby-on-macos](https://github.com/monfresh/install-ruby-on-macos)) - I'm sure there are other laptop scripts available too) which standardises and takes some of the pain out of installing Ruby on a new Mac.

**Comment by walshbr** [comment]
Thanks for the info - we are working on this. And FWIW I do think it's worth keeping these as separate issues since they are about different OS on Mac.

**Comment by anisa-hawes** [comment]
Hello there @svmelton. I'm going to work on closing this issue. It seems like a fix has already been implemented on the Spanish version of the lesson. I'm going to work through the English tutorial to make sure the proposed fix works well here too. I'll send you an update when I can confirm what edits are needed.

**Comment by svmelton** [comment]
Thanks @Anisa-ProgHist!

**Comment by anisa-hawes** [comment]
I worked through the early steps of this tutorial today, and have been able to successfully install the Ruby Gems update. However, I am not 100% sure whether it was the snippet suggested by Quinn which provided the fix.  

A couple of thoughts: 

1. _I'm uncertain because I don't think I've isolated this as the only variable._
The notes which open the lesson do specify that "macOS Catalina, zsh has replaced bash as the default shell for Macs. This lesson has not been tested on the zsh shell'". Indeed, upon opening Terminal it displayed the message "The default interactive shell is now zsh. To update your account to use zsh, please run `chsh -s /bin/zsh`."                   

In https://github.com/programminghistorian/jekyll/issues/1669 @spswans wondered if the originally suggested fix (for users who encounter this permissions error) would be sustainable in the long term – knowing that following the release MacOS Catalina, zsh would be the default shell rather than bash (https://github.com/programminghistorian/jekyll/issues/1669#issuecomment-656234283).

Rather than changing the default shell (as guided here https://support.apple.com/en-us/HT208050), I opted to use the command `export BASH_SILENCE_DEPRECATION_WARNING=1` before proceeding. I'm wondering if this could be added to the tutorial as an option? 

2._I'm also uncertain because unfortunately, I think I keyed the snippet Quinn shared with us incorrectly._
The current instructions suggested this fix:

If you get a permissions error at this point, entering `echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile` followed by `source ~/.bash_profile` instead of the command above may help. 

Because the snippet above includes `export`, I interpreted Quinn's suggestion as `export GEM_HOME="$HOME/.gem"`. I then re-checked the Spanish version of this lesson (because it has already been edited to integrate Quinn's fix) but noted that there snippet simply reads `GEM_HOME="$HOME/.gem"` without the word "export".

Next steps: 

I'm going to uninstall ruby, then begin again. I will try:

`export BASH_SILENCE_DEPRECATION_WARNING=1`
`gem install rubygems-update`

I will see if I get a permissions error at this point, then proceed with Quinn's suggestion, without including the word export. 

If necessary, I will uninstall ruby for a second time and try again. It's important that I am only adjusting one variable at a time. 

A warning box at the start of the lesson might be useful, explaining that macOS Catalina users have experienced some issues including links to past tickets here, relevant Apple support pages, etc.

**Comment by anisa-hawes** [comment]
Found this on Stack Overflow: https://stackoverflow.com/questions/14607193/how-to-install-a-gem-or-update-rubygems-if-it-fails-with-a-permissions-error?answertab=active#tab-top

This will fix the issue on MacOS Mojave and Catalina in a clean way:

`brew install ruby`
Then set `GEM_HOME` to your user directory. On the terminal:

Bash:

`echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc`
`echo 'export GEM_HOME=$HOME/gems' >> ~/.bashrc`
`echo 'export PATH=$HOME/gems/bin:$PATH' >> ~/.bashrc`
`source ~/.bashrc`

OR if on Zsh:

`echo '# Install Ruby Gems to ~/gems' >> ~/.zshrc`
`echo 'export GEM_HOME=$HOME/gems' >> ~/.zshrc`
`echo 'export PATH=$HOME/gems/bin:$PATH' >> ~/.zshrc`
`source ~/.zshrc`

**Comment by anisa-hawes** [comment]
N.B. The Spanish version of this section reads:

(Si estás utilizando el sistema operativo Catalina, puede que recibas un error de permisos luego de instalar Ruby. Puedes arreglar esto incluyendo la dirección de Gems en tu sistema. Ingresa el siguiente comando: export `GEM_HOME="$HOME/.gem"`)

Looks like the command to suggest should in fact be: `export GEM_HOME="$HOME/.gem"`

**Comment by anisa-hawes** [comment]
Note to self: Also consider feedback received via email from the Centre for Data, Culture and Society at the University of Edinburgh.
