### ISSUE TITLE
Investigate Travis 400 No error codes on multiple twitter links

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1975]
Now that I'm back from break, I'll actually look into the dozens of 400 error codes we've been getting on travis builds. They seem to resolve when you re-run travis, but it's still weird.

**Comment by walshbr** [comment]
Like I mentioned on the slack, someone else on stack overflow thinks it might be rate limiting (sending too many requests too quickly) - https://stackoverflow.com/questions/7835067/twitter-api-always-saying-400-bad-request

**Comment by walshbr** [comment]
I'm not exactly sure reading the HTML proofer docs if there is a way to address this (adding a delay between each link call or something like that). @ZoeLeBlanc - could you take a  look since you know more about such things? If there's not, we might just accept that it will happen sometimes and have to deal with it until HTML proofer updates their code. 
https://github.com/gjtorikian/html-proofer/issues/131
https://github.com/gjtorikian/html-proofer/issues/558

**Comment by jenniferisasi** [comment]
And I am afraid I am helpless for this issue...other than confirming that it has happened to me every time last week the first time I run a PR.

**Comment by ZoeLeBlanc** [comment]
So just adding a few thoughts here from our Slack discussion.

At the moment, we think the multiple language builds (three, soon to be four) is the likely culprit, with Twitter rate limiting our requests because we are pinging the same URLs (about 62) three times in quick succession.

A few possible solutions:
- ignore all twitter links in our html proofer script in build.sh
- try and figure out how to conditionally only check twitter links if in one of the languages (though this would probably become an issue over time with new lessons)
- update build.sh to ignore 400 errors since those are the ones that we get from Twitter
