### ISSUE TITLE
Various markdown glitches

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#198]
http://programminghistorian.org/lessons/

see bottom of page, the python lessons have XML appearing within the list.

**Comment by acrymble** [comment]
![screen shot 2016-02-26 at 10 20 39](https://cloud.githubusercontent.com/assets/646647/13349698/6e812e96-dc73-11e5-8257-7c31a2ab26fe.png)

Seems to be a wider markdown problem. See the links and images at the bottom of this lesson:

http://programminghistorian.org/lessons/mac-installation

**Comment by acrymble** [comment]
This seems to be something to do with links that were created like this:

`[Text to be linked][]`

...then at the bottom of the page...
`[Text to be linked]: link`

**Comment by acrymble** [comment]
Also with h4 'conclusion' heading in: http://programminghistorian.org/lessons/research-data-with-unix

Shows up as:

`####Conclusion`

**Comment by acrymble** [comment]
Similar for h2 heading in http://programminghistorian.org/lessons/extracting-keywords on line 1.

Seems random.

**Comment by acrymble** [comment]
Seems to be affecting whole lessons but in inconsistent ways. For example: http://programminghistorian.org/lessons/understanding-regular-expressions

The images aren't appearing, but the links are fine.

**Comment by wcaleb** [comment]
The Understanding Regular Expressions lesson has a larger problem in that it looks like the images were never converted into our house syntax for figures; so those need to be fixed.

The problem with the reference links on the other page was that the link definitions were indented by tabs instead of by spaces; if you see that problem again, that may be the solution.

The headers you found were broken either because they were not preceded by a blank line, or there was no space separating the hashtags from the text of the header.

The issue with the `div` blocks on the lesson pages looks more complicated so I'll have to figure that one out.

Thanks for catching these. They are almost all a result of slight differences between `kramdown` Markdown and the original Markdown syntax. Most of those differences were implemented because the original Markdown rules were somewhat sloppy and led to problems for people writing parsers. [Kramdown syntax](http://kramdown.gettalong.org/syntax.html) is stricter in order to avoid ambiguity, but that means that in cases where we've applied the Markdown rules loosely, it's going to bite us.

If you want to get a quick sense of how zany the world of Markdown parsers can be (not sure I recommend it), look at the [CommonMark spec](http://spec.commonmark.org/0.24/), which is basically an attempt to come up with a canonical set of rules for Markdown that will supersede all of the various parsers that have emerged (`redcarpet`, `kramdown`, etc.), each with their own slightly different rules. In some ways it would have been better for GitHub to switch to CommonMark than to Kramdown, though I would guess their attempt to pick just one parser was motivated by the same goal: by allowing lots of different parsers on GitHub Pages, they were constantly having to put out little fires like this.
