### ISSUE TITLE
Updating Initial Lesson Metadata Guidelines

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#1995]
From our Tech Team Meeting #1906 we discussed updating the initial lesson submission metadata to include far fewer fields so that we had fewer user errors and since most of those metadata fields aren't relevant until final submission of the lesson.

Our current template looks like:
```markdown

# Lesson Metadata

**Delete everything above this line when ready to submit your lesson**.

title: YOUR TITLE HERE
collection: lessons
layout: lesson
slug: LEAVE BLANK
date: LEAVE BLANK
translation_date: LEAVE BLANK
authors:
- FORENAME SURNAME 1
- FORENAME SURNAME 2, etc
reviewers:
- LEAVE BLANK
editors:
- LEAVE BLANK
translator:
- FORENAME SURNAME 1
- FORENAME SURNAME 2, etc
translation-editor:
- LEAVE BLANK
translation-reviewer:
- LEAVE BLANK
original: LEAVE BLANK
review-ticket: LEAVE BLANK
difficulty: LEAVE BLANK
activity: LEAVE BLANK
topics: LEAVE BLANK
abstract: LEAVE BLANK
---
```
and we would be proposing cutting this down to:
```markdown

# Lesson Metadata

**Delete everything above this line when ready to submit your lesson**.

title: YOUR TITLE HERE
collection: lessons
layout: lesson
---
```
To do this we would need to update the lesson template for each language, which should be a quick fix but we would also need each language team to update their editor guidelines so that the original fields do get added back in prior to moving the lesson over to the main repository.

**Comment by rivaquiroga** [comment]
@programminghistorian/technical-team, we are currently updating the guidelines in https://github.com/programminghistorian/jekyll/pull/2077. So this could be a good moment to introduce these changes.

**Comment by ZoeLeBlanc** [comment]
Thanks for the heads up @rivaquiroga! Currently I'm planning to email Managing Editors to let them know about this change and then work with them to update their guidelines and templates. But knowing you're already making these changes means I should move faster (pretty much always the case!) since things are already moving.

**Comment by ZoeLeBlanc** [comment]
Now wondering if I should add updates to the lesson submission template to your draft PR @rivaquiroga or create a new PR 🤔 

Probably a new one, unless you think this would make sense to add? Just let me know. Thanks 😊

**Comment by rivaquiroga** [comment]
A new one sounds fine. The update to the template doesn't require translation..

**Comment by ZoeLeBlanc** [comment]
@walshbr wondering if we still think this change is necessary now that editors are the ones uploading submission files rather than authors merging directly into ph-submissions? Mostly just wondering at what stage editors would add the metadata back in 🤔

**Comment by walshbr** [comment]
Most of it doesn't get added until right when it's moved over to the front-facing Jekyll repository, right? So I could see leaving it off the guidelines until that stage.

**Comment by ZoeLeBlanc** [comment]
Discussed at #2216 mostly just on @ZoeLeBlanc to talk with editors. Might also reach out to @Anisa-ProgHist to discuss revamping on-boarding processes and initial lesson submission

**Comment by anisa-hawes** [comment]
Thank you, @ZoeLeBlanc! Let's connect to  discuss this. I am currently revising the on-boarding documentation to run a pilot with the EN team this autumn ahead of wider implementation.

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc. I'm adding this Issue to the Better Editorial Onboarding Milestone, because the revised guidelines include instructions for the (proposed) technical editor, who would be supporting/undertaking this initial set up of the YAML header. Tagging @hawc2 here too, who is supporting me to revise the technical side of the guidance.

**Comment by anisa-hawes** [comment]
As my second draft of our editorial guidelines (including a section on setting up YAML metadata) are now with the English team, I am closing this Issue. 

The revised documentation is going to be tested in a pilot study for new English editors. When their onboarding is complete, I will collate feedback and open a new Issue for consultation.

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga,

As we discussed, this Issue answers the question you've posed in #2360 about which are the minimum required fields for a lesson to be rendered on ph-submissions:

```
title: YOUR TITLE HERE
collection: lessons
layout: lesson
---
```

In our conversation, you explained that the three dashes `---` are needed both above and below the YAML fields. Thinking together, we also agreed that it would be good to keep in the `authors:` field, so that authors can specify how they want their name to appear, for example, if they have published in the past using their initial(s) rather than their forename. 

So, a next step is to update the lesson templates, simplifying the YAML to the minimum + upper three dashes `---` + `authors:` with the understanding that editors / or technical editor will add in the remaining fields later in the workflow:

```
---
title: YOUR TITLE HERE
collection: lessons
layout: lesson
authors:
- FORENAME SURNAME 1
- FORENAME SURNAME 2, etc
---
```

I apologise for closing this Issue, without fully understanding that the updates proposed were to the templates provided within the Author guidelines. 

If everyone is in agreement that this change would reduce early-phase errors for authors and editors, I can generate a PR to update en/lesson-template.md, es/plantilla-leccion.md, fr/modele-tuto.md, and pt/licoes-modelo.md.
