### ISSUE TITLE
Front page redesign 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2020]
Now that we have 4 languages the front page for the project, the format of the front page no longer suitable; most new users will have to scroll down to realize that there are four journals/languages. I am making this a technical and communications issue because how the front page looks also sends a message to our users. 

The technical team will take some time to try to have the journals on the front page on a 2x2 square and/or on a shuffle mode to avoid the feeling of hierarchies (because @ZoeLeBlanc is amazing and she thinks she can make it work). This will require some reformatting of the information that we currently provide for each journal, made on the part of communications. 

It will be a medium priority. 

PD: @acrymble raised the issue on an email, though I believe conversations about it had already been raised up in the past.

**Comment by acrymble** [comment]
I raised this a long time ago, but I would also really encourage us to drop the "(The initial English version)" bit, and just start calling it the _Programming Historian in English_.

**Comment by walshbr** [comment]
I'd suggest not going with a square, since it seems like only a matter of time before another language team comes along. Wouldn't want to have to keep redesigning it. Trying to think through other UX possibilities, since I could imagine having the things shuffle each time you visit would be sort of disorienting. <strike>Maybe…a map? With the language-specific publications keyed to particular regions? That would solve the design issue b/c it would just give us one canvas to layer new language publication descriptions onto, but of course languages don't map perfectly (or even well?) onto geography so it'd be imperfect in that sense. Might be more problematic than it's worth in that sense, but thought I'd throw it out there. </strike> -> talked about how this wasn't a good idea at the tech meeting.

**Comment by jenniferisasi** [comment]
Ideas during the tech meeting: 

- Cut main text; we could do: Novice-friendly, peer-reviewed tutorials for humanists. ?
- Drop the ISSN number

**Comment by walshbr** [comment]
Yesterday I suggested just one card - a logo plus "Enter the Programming Historian" in the various languages as a bulleted list that would lead you into the various journals.

**Comment by acrymble** [comment]
I agree the ISSN can be less prominent. But we've been fighting for years to be taken seriously as an academic publication and that's one of the ways we expressed that. So I wouldn't like us to forget that even if it doesn't stay on the front page.

**Comment by walshbr** [comment]
One thing we noticed @acrymble was that the ISSNs for all publication are duplicated on the front page - they're both in the footer and in the cards. That was part of the thinking I believe.

**Comment by jenniferisasi** [comment]
🤔 have we ever discussed about adding the word "journal" after The Programming Historian here?
![Screen Shot 2021-03-12 at 11 30 28 AM](https://user-images.githubusercontent.com/11022533/110969153-5ac83c00-8326-11eb-959a-abf58535f9a4.png)

I'm not suggesting we do it everywhere, but maybe it wouldn't hurt there? Journal, revista, jornal, revista/jornal (not sure in PT) in the order that corresponds to each language's syntax. Is that too much?

**Comment by DanielAlvesLABDH** [comment]
In portuguese would be revista

A sexta, 12 de mar de 2021, 13:33, Jennifer Isasi ***@***.***>
escreveu:

**Comment by walshbr** [comment]
Going to remove myself from this ticket since I'm leaving at the end of the summer and assume work will be ongoing on it. I'm trying to prioritize finishing other tickets of mine.

**Comment by ZoeLeBlanc** [comment]
Closing this ticket since redesigning front page is now part of broader infrastructure redesign.
