### ISSUE TITLE
May 25 2021 Project Team Zoom Call

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#2103]
May 2021, Time is 9:00 AM - Colombia, Mexico; 10:00AM EDT; 3:00 PM - London, Portugal; 4:00 PM CET - Paris. @mariajoafana will be facilitating the call. The meeting will start with our Annual PH Meeting #2049 

You can use this time converter to double-check the time of the meeting in your time zone: https://www.timeanddate.com/worldclock/

Zoom invitation: 
https://universityofsussex.zoom.us/j/93462421184

Working agenda in progress. Please add in this agenda under "Issues and tasks for discussion" the tickets that you'll like to further discuss in the meeting. You can comment or edit this comment directly.

All team leaders please post a small report on your team's activities closer that day.

- [x] Actions Arising from march 2021 Project Team Meeting: #2090  

- Issues and tasks for discussion: 

 - [ ] Clarification of Global Team and Education manager roles 
- [ ] 
- [ ] 
 
- [ ] Updates on tickets open for a long time with no clear path to completion:  

  
- [ ] ES team issues

- [ ] EN issues

- [ ] FR team issues 

- [ ] Portuguese team issues

- [ ]

**Comment by ZoeLeBlanc** [comment]
# Technical Team Report

By: @ZoeLeBlanc

Date: 25 May 2021

Actions Completed Since Previous Report:

- We closed #1938, so we now have yaml metadata for lesson testing
- We closed #2093 that fixed some of the logic problems we had with lesson banners, removing the yaml field redirect_from and rewriting our translations logic. 
- We closed #2094 that tweaked our nightmode for color contrast (thanks @walshbr!) 
- @walshbr also has done a ton for our accessibility audit and closed four PRs for adding alt attributes to images, improving screen reader functionality, and color contrasts 🎉 #2135 #2136 #2124 #2129 
- @jenniferisasi closed #2002 fixing our translation concordance issues and also coped with some of the underlying infrastructure changes, which meant that her branch became accidentally maybe one of the largest PRs we ever had (314 commits & 143 files changes 😅 )
- We've also had a lot of builds breaking and so we've had to tweak our Github Actions (and also discovered that some of the original code we had was no longer appropriate for the library we use for html checking)

Substantive Actions Remaining Open Since Previous Report:

- Adding PT to Twitter Bot #2006 (though @walshbr has been in contact with PT team)
-  Discussed how to change initial lesson submission metadata at our last tech team meeting and Zoe still needs to setup meeting with managing editors #1995
- We opened #2072 to conduct an accessibility audit and @walshbr has done an enormous undertaking to get us most of the way there. We'll be discussing remaining issues at our next tech team meeting.
- @hawc2 has also done an amazing job leading #2030 which is an assessment of our current archiving of web links strategy. He's worked with @drjwbaker and Temple libraries to get us setup with perma.cc access. Next step is creating documentation for how to use this new service and then helping editors and tech team integrate this into their workflows 🙌🏽 
- @jenniferisasi is leading #2100 to make the menu bar fixed when you scroll
- Lesson sequence banners in ES #1945 is pretty ready to merge but just needs to be refreshed with latest gh-pages version
- #2106 going forward we'll no longer have our html-proofer check the blog for links or html formatting. We still need to discuss in our tech team meeting documentation and processes to ensure that the blog indicates this change and also maintains accessibility standards.
- Zoe is still planning to undertake a redesign our front page #2020 to hopefully make it more user friendly and multilingual friendly though she is waiting until we complete the accessibility audit
- No tickets yet but we need to prepare for @walshbr retiring this summer 😢  and also onboard @hawc2 officially to the Tech Team 🎉 . Also schedule our summer meeting (probably July realistically at this point).

6-month focus:

- Front page redesign
- Finish accessibility audit
- Adding more documentation to the wiki

12+ month focus:

- Review alternatives to Jekyll (is it time for a faster static site generator?)
- Grant application to support tech team activities
- Review of Github issues trends

**Comment by spapastamkou** [comment]
## FR Team Report 25 May 2021

**Actions Completed Since Previous Report:**

1 editor onboarded - total of 4 new onboarded 
1 original-first lesson published
2nd original lesson received - ready to review
3 translations under review
Training workshop for new editors took place on 27 March 


**Actions Remaining Open Since Previous Report:**  
FR Copy Editing Chart: in progress 
1 translation proposal received

**Other**
none

**Queries for the Editorial Board:**
none
---

**6-month focus:**
Accomplish copy editing chart
1 translation editing per each team member (currently 3 in progress, and at least 2 more to come)
Publish 2nd original lesson (rewiew ticket to come) 

**12+ month focus:**
Define priorities for original lessons 
Accomplish translation of Python series lessons 
Achieve more inclusivity for team members

**Comment by rivaquiroga** [comment]
## ES Team Report

By: @rivaquiroga  
Date: May 25, 2021

**Updates Since Previous Report:**
- We received 13 applications for new editors. We are currently shortlisting the candidates. 
- @jenniferisasi and @rivaquiroga gave a talk + workshop at INTELE about PH. 

**Editorial work**
- 3 original lessons being edited (one is currently under copyediting)
- 2 translations being edited
- All the proposals we have been receiving in the past two months are for original lessons. 
- 
**3-month focus:**
- Onboard new editor(s).

**Comment by JMParr** [comment]
**Global Team Report**
By: @JMParr 
Date: May 25, 2021

Updates Since Previous Report:

- Members of the team have presented on The Programming Historian and multilingual DH at NewsEye International (March), Cambridge (CRASSH) Data School (March), and the MSUGlobal DH Seminar.

- Zoe LeBlanc led a meeting to discuss a US-based funds for Programming Historian initiatives.

- Jess has been in conversation with a scholar in Uganda who is interested in some sort of DH workshop for African-based scholars, perhaps modeled on the DHSI, but as a one-time workshop.

- There are possible collaborations with the Cambridge University Data School.

- We would like to add a member from The Portuguese Team.

**Comment by svmelton** [comment]
## EN Team Report

By: @svmelton   
Date: May 25, 2021

**Updates Since Previous Report:**
- We published two new lessons
- Several EN team members participated in the April Global DH panel

**Editorial work**
- 3 new submissions
- 2 pieces back from peer review
- 1 piece ready for peer review

**3-month focus:**
- Offboard @walshbr 
- Finalize onboarding documentation
