### ISSUE TITLE
Ownership of translations **from** ES, FR, PT

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2143]
Branching off from https://github.com/programminghistorian/jekyll/issues/2141, now we are growing the number of original articles submitted in languages other than English, we need to figure out who owns translations of original articles **from** ES, FR, PT into other languages, but especially into English.

In #2141 I observe:

>> 1. My understanding is that the 'missions' of the ES, FR and PT publications are to publish articles (in translation or otherwise) for their language audiences given the historic/systemic under-representations of digital history/humanities methods publications in those languages.
>
>> 2. My understanding is also that none of our publications have 'missions' to amplify historically/systematically under-represented non-Anglophone scholarly voices by translating their works submitted to PH into languages other than their first/working language, typically into English.

@mariajoafana adds:

> those (non-Anglophone) tutorials can make substantial new contributions to the field and to global anglophone audiences and as such are worthy of translation as much as the English language tutorials are worthy of translation into other languages.

To which I add:

> Totally agree! My point is that none of our 4 publications currently have a mission to do just that. I'm suggesting we consider creating a role dedicated to doing that.

My feeling is that we don't want to change 1.: the missions of the ES/FR/PT publications feel right to me (though if you disagree, say!). Which means we attend to 2.

There are some options here:

1. ownership of ES/FR/PT > EN could sit with the English team, with funds from the Ltd to pay for translation
2. ownership of ES/FR/PT > EN could be a dedicated role - perhaps in the Global Team - with funds from the Ltd to pay for translation
3. ownership of ES/FR/PT > EN could be a dedicated role - perhaps in the Global Team - with funds from the Ltd to pay for managing the whole process, perhaps attached to funding drive that taps into the global/development philanthropic ambitions of large anglophone institutions.
4. ownership of ES/FR/PT > OTHER LANGUAGES could be a dedicated role - perhaps in the Global Team - with funds from the Ltd to pay for managing the whole process. This option would free us from using English as the pivot publication (from which all translation go in and out), which feels more global (because we might learn things translating an original ES article to FR) but is potentially more expensive (because translating, say, from FR to EN then enables the ES or PT team to translate to ES and PT based on existing mission/workflows)

My feeling is that we aim to get to 4, but start with 2, choosing https://programminghistorian.org/es/lecciones/analisis-de-sentimientos-r (original ES) and https://programminghistorian.org/fr/lecons/calibration-radiocarbone-avec-r (original FR) as test publications, because absorbing articles in translation may require some adjustment from the EN team to new processes.

On 3. + 4., if we want them, these should be added to the goals of the Ltd in the business plan.

Comments?

**Comment by acrymble** [comment]
I agree wholeheartedly that I'd really like to see the English publication translating from other languages.

I would like to flag some concerns with this approach though.

1. Our service agreement (re-approved for another year just this week) ensures "The Publication Team is granted editorial autonomy of their publication within the limits of the terms outlined above." This suggestion strikes me as one that will interfere with that editorial autonomy if @svmelton decides on behalf of the @programminghistorian/english-team that this is not the direction they want to go. First, therefore, I think a conversation with @svmelton should happen before any policies or ideas are crafted, and that it should happen in the spirit of offering support for expanding capacity.
2. I have concerns about releasing central money to translate into English, given that the same support hasn't been offered to other teams. I think other publications should rightfully expect an explanation if that were to happen. Especially considering they have had to set up translation workflows without access to money.
3. This seems like a good opportunity also to clarify the remit of the @programminghistorian/global-team. As far as I understand it the only real agreed role of the Global Team is to vet new publication teams and support them as they get set up. It would be helpful to clarify its additional responsibilities (https://github.com/programminghistorian/jekyll/wiki/Global-Team) and to make sure they don't overlap with other teams, including ME duties or other activities. Especially if we're suggesting this may also be within their remit.

**Comment by drjwbaker** [comment]
Thanks @acrymble, in turn:

1. Translation proposals can still be accepted/rejected under that agreement, right? (not least as translation involves localisation, e.g. of datasets)
2. On spending £ on this, fair point. I'm was prioritizing not interrupting the missions of the ES/FR/PT publications when I wrote this. On the justification for translating into EN - £ or no - I echo @mariajoafana's point that this work could seen as a way of amplifying the work of ES/FR/PT voices ('adding value' to someone submitting in ES/PT/FR first). This is how a small literary press that publishes English language translation would see it.
3. I said *perhaps* because I don't know what the @programminghistorian/global-team priorities are. Amplifying the ES/FR/PT voices into other languages/contexts could be one of them. But I don't know.

**Comment by rivaquiroga** [comment]
Currently, each team "owns" the translations to their language. I'm not sure why this should be different for the EN team. So the first question we need to ask is if the EN team does have interest in editing translations of original lessons of the other publications to that language. If they don't, then we might explore other options to solve that need. But this is an editorial decision of the EN team in the first place, as @acrymble said.

In terms of workflow, to translate from another language to EN the team only needs an editor that has command of that language. No one is expecting them to do the translations. In the current scenario, the authors of non-EN original lessons are the ones interested in doing them. The issue right now is that an editor is needed to lead the publication process of those lessons in the EN journal. This situation is not new. It has been done before. The FFmpeg lesson was translated to Spanish by the author, and Antonio acted as the editor. I’m not sure why this same process should be done differently if the translation is to EN. 

However, not all authors have the possibility to translate their own lessons to English (due to lack of time or language command). Unless someone (editor/member of the DH community) has interest in having that lesson translated, they will never be published in EN. In those cases, if we see that amplifying the voices of non-EN DH authors is part of the mission of PH, looking for funding to translate those lessons looks to me like a good idea. But this is step 2. Step 1 is what we do right now with the authors that want to submit the translation to EN of their lessons. 

Regarding 4, non-EN teams do not need the original lessons of other non-EN publications to  be in English to translate them to their language. They just need to recruit editors that have command of that other language that can lead the process. This decision will depend on the goals of each team. At least the ES team added as desirable the command of French and Portuguese in the call for new editors. We expect to be able to translate original lessons from FR and PT in the same way we have translated lessons from EN in the past. And just to note,  for someone who also speaks FR or PT, translating from one of those languages to ES might actually be easier, because of the grammatical and lexical similarities between them and ES. So if we have an editor suited for that task, we don't need the lesson to be first translated to EN.

**Comment by jenniferisasi** [comment]
Well I think @rivaquiroga expressed all my thoughts and concerns already, so I won't repeat them. But, specially 4, yes, we are on it and we just need to assign capacity and promote it. 

Similar to @acrymble, perhaps more strongly, I kind of "disapprove" of releasing central money to translate into English, as Adam said, because we have been successfully doing translation work in three teams by way of promotion and volunteering, pulling from the knowledge and interest of our own communities. So I would first and foremost, if the EN team agrees to have translations as part of their mission, plan and promote for submissions of translations from the community.

**Comment by JMParr** [comment]
I agree with @jenniferisasi and @acrymble re: releasing central money to translate into English for the reasons they have outlined. I also agree with @rivaquiroga 's observations regarding 4.  On @acrymble 's point re: the role of the Global Team, it seems worth having a conversation regarding the role of the team (and perhaps discussing it in our next team meeting). Perhaps it would be helpful to draft some suggestions before the next project meeting, and then share them with the team at large, to ensure that we're not stepping on anyone's toes?

**Comment by drjwbaker** [comment]
Thanks all. I hear you. 

> However, not all authors have the possibility to translate their own lessons to English (due to lack of time or language command). Unless someone (editor/member of the DH community) has interest in having that lesson translated, they will never be published in EN. In those cases, if we see that amplifying the voices of non-EN DH authors is part of the mission of PH, looking for funding to translate those lessons looks to me like a good idea. But this is step 2. Step 1 is what we do right now with the authors that want to submit the translation to EN of their lessons.

Let's focus on that then.

**Comment by DanielAlvesLABDH** [comment]
Sorry for being so late into the discussion. I totally agree with the comments of @rivaquiroga and @jenniferisasi. Programming Historian as a whole should has as its first mission to deliver tutorials that can expand knowledge about Digital Humanities regardless of the language. Most PT colleagues already used PH before PT team joined the project. Most use EN lessons, because there are more, but a lot also use ES and FR that sometimes are easier, depending on the academic context of the user. A second mission should be multi-language voices, including all four languages. If the first goal is central, no matter the language of the original lesson we should try our best for a good lesson, an helpful lesson for the global DH community, to be translated to all the other languages. Not as something mandatory, but as a good goal to aim to. About the money to pay for translations, no team should be prioritize. But probably teams could be encouraged to seek for external funding to do that. In the PT team we where lucky get that from FGV, Brazil. With the limited time I have available I can help to translate something from ES/FR/PT to EN, with an EN editor to revise...

**Comment by drjwbaker** [comment]
Thanks for writing @DanielAlvesLABDH: no need for apologies.

To add, as a more general point, I've had this on my mind a lot recently, as I know I went too far in jumping to a solution before hearing to what people wanted and didn't want. Apologies. I sometimes feel slightly stuck between a) an impulse not to allow the labour for making change happen to fall on those less white/male/full-time than me, and b) a need to let those less white/male/full-time than me make change happen on their own terms. Which is to say, I often don't succeed at standing with, at being an ally, etc.

On this specific issue, picking up again on @rivaquiroga, specifically..

> I’m not sure why this same process should be done differently if the translation is to EN.

> However, not all authors have the possibility to translate their own lessons to English (due to lack of time or language command). Unless someone (editor/member of the DH community) has interest in having that lesson translated, they will never be published in EN. In those cases, if we see that amplifying the voices of non-EN DH authors is part of the mission of PH, looking for funding to translate those lessons looks to me like a good idea. But this is step 2. Step 1 is what we do right now with the authors that want to submit the translation to EN of their lessons.

..it sounds like we **might** want resources that support authors submitting in languages other than English (because that is the area we are missing) to encourage them to have a conversation with us about what happens to their articles after publication:

- do they know we translate articles and how we do it (it sounds like @rivaquiroga that ES is doing this already);
- are they willing and able to translate their article to one or more languages themselves (again, sounds like ES is doing this);
- if so, do they know about our translator guidelines (again, sounds like ES is doing this);
- if not, what would they like from us.

This latter point sounds like the gap we **might** want to monitor and respond to (e.g. through recruitment of editors) as a project rather than as individual publications. But, as each publication is editorially independent (as @acrymble reminds me above https://github.com/programminghistorian/jekyll/issues/2143#issuecomment-850341236) and as I'm once again talking rather than listening, I'll shut up now until I've heard what people want/think :)

**Comment by acrymble** [comment]
@drjwbaker is there an actionable item that's come from this discussion that needs doing, or has the conversation come to a natural end?

**Comment by drjwbaker** [comment]
It reads like the third bullet at https://github.com/programminghistorian/jekyll/issues/2141#issuecomment-869147838 provides an actionable direction. So I'll post this thread there for info and close.
