### ISSUE TITLE
pronouns in author guidelines

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2160]
I've been encouraged to suggest a revision to the author guidelines so that authors use the singular 'they' when referring to an author, unless a person has declared their pronouns (and/or refers to themselves as 'she' or 'he' in a public document). I believe this is [good practice](https://eige.europa.eu/publications/gender-sensitive-communication/challenges/stereotypes/avoid-gendered-pronouns-he-or-she-when-persons-gender-unknown) in that it avoids assuming the gender of the person being talked about.

Looking at the EN author guidance, I feel this fits best in the '[Challenging Words Explained](https://programminghistorian.org/en/author-guidelines#challenging-words-explained)' section and suggest that after 'Collective Nouns' we add something like:

> **Pronouns** are the singular 'they/them' unless the person referred to has declared their pronouns in their public writing or communications.

This is in effect an extension of the guidance under capitalisation that reads..

> Proper Names: William J. Turkel – unless the person choses to spell their name otherwise (eg “bell hooks”).

..in that it respects individual decisions about how they are referred to.

@svmelton This feels like an editorial decision to me, so the editorial independence of the EN publication in mind I'm happy for you to treat it as such (if you are happy, I can do the PR)

@rivaquiroga @spapastamkou @DanielAlvesLABDH: I recall (but can't find) an old conversation about gender-neutral language and the ES/FR publications, and the specific challenges around their use is Spanish and French. Again, if EN accepts these changes, I err towards editorial independence of ES/FR/PT to make choices that work for them.

**Comment by spapastamkou** [comment]
@drjwbaker For the FR: we have put all this on the [wiki ](https://github.com/programminghistorian/jekyll/wiki/French-Translation-Documentation) to document the french translation and the part on the inclusive writing is already in the draft pull request for revising the author guidelines in French.

**Comment by DanielAlvesLABDH** [comment]
Hi James! We made the initial translation of the PT platform taking into consideration some of these concerns, but in Portuguese the use of "they/them" is not simple because they translated into pronouns with gender related info: eles/elas; deles/delas. But I will put the topic in the agenda for our next team meeting.

**Comment by svmelton** [comment]
Thank you @drjwbaker! This is a good policy, and I'm happy for it to move forward on the EN side.

**Comment by rivaquiroga** [comment]
The ES Author Guidelines already has a section about inclusive and non-discriminatory language, that covers not only gender: https://programminghistorian.org/es/guia-para-autores#lenguaje-inclusivo-y-no-discriminatorio.
It would be great if the EN team uses the singular "they" only when there is really really really no information about the declared pronouns of an author, or when that is actually the pronoun they use. There is no direct translation of "they" to ES, PT or FR. Al least in ES, the translation would be diferent if the pronoun of choice is unknown, or if the person uses "they" because they identify as non-binary. So everytime it is used we will need to check the reason for its usage to translate correctly. 
I know this is a decision of the EN team, but I'm not so sure if 'Challenging Words Explained' is the best section to include this recommendation. It can be interpreted that as PH we are saying  that respecting people's pronouns or not assuming someone's gender is a challenge. And it is just the bare minimum. Moreover, the use of "they" as a singular pronoun is part of the normative English grammar. Its use can be traced back to the fourteenth century, so there is nothing challenging or new about using it.

**Comment by svmelton** [comment]
That's a good point @rivaquiroga. Perhaps we could place it (with that caveat about using "they" when that's the author's pronoun or when the pronoun is unknown) under the language and style section, since we have a bullet point about using the 2nd person you in that section.

**Comment by acrymble** [comment]
Good discussion. Is it more multilingual friendly to take the smaller step of saying something like “PH acknowledges and encourages the use of alternative pronouns where appropriate”?

**Comment by drjwbaker** [comment]
> I know this is a decision of the EN team, but I'm not so sure if 'Challenging Words Explained' is the best section to include this recommendation. It can be interpreted that as PH we are saying that respecting people's pronouns or not assuming someone's gender is a challenge. And it is just the bare minimum. Moreover, the use of "they" as a singular pronoun is part of the normative English grammar. Its use can be traced back to the fourteenth century, so there is nothing challenging or new about using it.

Totally agree @rivaquiroga 

> Perhaps we could place it (with that caveat about using "they" when that's the author's pronoun or when the pronoun is unknown) under the language and style section, since we have a bullet point about using the 2nd person you in that section.

I didn't see that section. Seems like a good fit.

**Comment by drjwbaker** [comment]
> It would be great if the EN team uses the singular "they" only when there is really really really no information about the declared pronouns of an author, or when that is actually the pronoun they use. There is no direct translation of "they" to ES, PT or FR. Al least in ES, the translation would be diferent if the pronoun of choice is unknown, or if the person uses "they" because they identify as non-binary. So everytime it is used we will need to check the reason for its usage to translate correctly.

@rivaquiroga great point and "[for ES] the translation would be diferent if the pronoun of choice is unknown, or if the person uses "they" because they identify as non-binary" was not something I was aware of (but now I am!). Great example of why doing our multi-lingual work creates richer publications.
