### ISSUE TITLE
Topic Modelling on Windows Instructions

### ISSUE THREAD

**Issue by pao-chuan** [programminghistorian/jekyll#2167]
I've tested the lesson on Mac and the instructions are ok.
But for Windows, the problem is Figure 1 to 3, which can't be followed through Windows 10 because the control panel has changed. One solution may be that we can add some instructions for Windows 10.
The lesson: https://programminghistorian.org/en/lessons/topic-modeling-and-mallet

**Comment by anisa-hawes** [comment]
Thank you, @pao-chuan! Working through these steps, I can confirm that the Windows 10 interface looks identical to Windows 7 at steps illustrated by Figure 2 
<img width="423" alt="Screenshot 2021-09-01 at 14 27 01" src="https://user-images.githubusercontent.com/87070441/131686952-36fc800a-ded1-402d-bb77-f914ab41716a.png">
 and Figure 3
<img width="631" alt="Screenshot 2021-09-01 at 15 05 27" src="https://user-images.githubusercontent.com/87070441/131687050-18f685ba-0474-43e5-88ca-f7b09fc27a9a.png">

The key difference is at Figure 1, where you open the Control Panel and navigate to Advanced System Settings.

Instead of Start Menu -> Control Panel -> System -> Advanced System Settings, the steps are:

1. Click Start (Windows icon) or press Windows key and type "Control Panel"
<img width="853" alt="Screenshot 2021-09-01 at 14 22 42" src="https://user-images.githubusercontent.com/87070441/131684350-c88f0b52-d626-40f9-bb87-e81a85043539.png">

2. Within Control Panel, select System and Security
<img width="1149" alt="Screenshot 2021-09-01 at 15 03 56" src="https://user-images.githubusercontent.com/87070441/131686315-9af09134-d42c-4133-a6e5-1e611791d5db.png">

3. In System and Security, begin to type "Advanced" into the search field (upper right). Choose "View advanced system settings" from the results. 
<img width="1153" alt="Screenshot 2021-09-01 at 15 04 49" src="https://user-images.githubusercontent.com/87070441/131686725-17391c0a-0c80-4ba8-9f4e-a758061d9e5a.png">

So, if anything, I think only a minor adjustment is required here. 

At line 181 of the .md file, where the lesson currently reads:

To create an environment variable in Windows 7, click on your `Start Menu -> Control Panel -> System -> Advanced System Settings` (Figures 1,2,3). 

We could consider making the following change:

Or, in Windows 10, click Start (Windows icon) or press the Windows key on your keyboard then type "Control Panel". Within Control Panel, select System and Security.  In System and Security, begin to type "Advanced" into the search field (upper right) and choose "View advanced system settings" from the results.

What do you think @svmelton? Do you think this change would be helpful?  I can generate a PR if so.
Do you feel it is necessary to replace the three screenshots for Figures 1-3? (we could use the new ones I’ve created)

(I note that the ES version already refers to Windows 10, although the interface looks a little different in the screenshots)

**Comment by svmelton** [comment]
Thank you for your work on this @Anisa-ProgHist! Yes, please generate a PR, and I think it would be helpful to replace the figures with the screenshots you've taken.
