### ISSUE TITLE
Add header-level guidelines to style manual

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#219]
There is inconsistency across the site in how authors decide when to use `h2` or `h3` or `h1` headers. As noted in #217, it would be good to add some guidelines on this to our style sheet.

**Comment by ianmilligan1** [comment]
I think it should be:

`h1`: title only
`h2`: main headings in lessons
`h3`: sub headings, etc.

**Comment by acrymble** [comment]
We had a style sheet in the early days, but it was rather set aside in the shift to markdown (and in fact all of the markup was just deleted).

We used to tag:
- First instance of a technical term (italics + bold) class = 'tech'
- names of programmes / filepaths / menu paths (italics) class = 'filename'
- variables / functions / parameters (italics) class = 'var'
- reserved words, code examples, (if, for, while [but not object, encapsulation, etc]) (fixed width) class = 'reserved'
- names of books / creative works (italics) class = 'pub'
- commands to be typed by the user (constant width + bold) class = 'userinput'

That gave much more consistency to formatting in the earliest lessons, and it's a shame we've lost that. I think this should be part of a wider conversation about increasing the standardisation across authors and editors.

**Comment by acrymble** [comment]
This should go in #244 as well

**Comment by acrymble** [comment]
@fredgibbs to add to http://programminghistorian.org/new-lesson-workflow

**Comment by fredgibbs** [comment]
fixed with 8009339. Regarding Adam's earlier comment about all the various tags we might use to style things (which makes the Markdown considerably clunkier), we're now using the standard GitHub style to handle those cases. We can have more consistent lessons the fewer kinds of the styling we ask authors to think about. I think the new-lesson-workflow page has just about every kind of formatting anyone should need to use, so we have a ready example for them.
