### ISSUE TITLE
Type setting

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2209]
I think it's time we talk about type setting as a service, that's distinct from copyediting in that it focuses on consistent use of layout / structure in new lessons, and does a check on any associated files, image formatting, etc. This is something that can be done even if the typesetter doesn't read the language in question (whereas copyediting requires very strong language skills).

I think this can also substantially reduce the burden on MEs and editors by shifting much of the Editorial checklist work to the typesetter. I also think it will result in significantly more consistency across lessons and publications.

https://programminghistorian.org/en/editor-guidelines

It will take some time to extract this from the editor and author guidelines into a coherent new service. But I welcome any thoughts before we get started. I see this as something we'd ask @Anisa-ProgHist to lead on.

This also links in with one of our ProgHist goals for 2021, "Paid copyediting on all new lessons in all four languages" because it means we can move towards typesetting FR and PT even before they have the styleguides in place for copyediting, and thus making this a more iterative and manageable goal.

**Comment by drjwbaker** [comment]
I'm for this.

That said, semantics perhaps, is 'typesetting' the right word for this? We aren't producing pretty pdfs after all.

**Comment by anisa-hawes** [comment]
Within the Author Guidelines, we sub-divide the tasks of *Step 2. Writing and Formatting a New Lesson* into three parts: 
- Style and Audience
- Specific Style Guidelines
- Formatting Guidelines

Perhaps our typesetting service and workflow can be developed from the Formatting Guidelines section. I think it could also absorb some aspects from the Specific Style Guidelines, such as the instructions for creating Headings and Lists. 

I feel 'typesetting' is quite an appropriate word, as we are thinking about '[the composition of text by means of arranging physical type or its digital equivalents](https://en.wikipedia.org/wiki/Typesetting)'.

**Comment by drjwbaker** [comment]
Okay. Happy to be corrected.

**Comment by acrymble** [comment]
@svmelton has suggested something that sounds very similar in #2223 to support "the technical setup of a lesson. One of the major pain points for our editors is working with the metadata and getting the lessons setup".

@svmelton I'd be happy for you to nominate this as a goal for the coming year if you think this would reduce the workload for MEs.

**Comment by svmelton** [comment]
Thanks @acrymble. Yes, I think this is pretty closely related and I'd be happy to nominate it. @ZoeLeBlanc was there anything that came up in our convo around that paid role that might not be encapsulated here?

**Comment by anisa-hawes** [comment]
Hello all.

Thank you for your thoughts on this. I am adding this Issue to the Better Editorial Onboarding Milestone because I have accounted for this in my re-draft of the Editorial Guidelines (soon to be tested in a pilot with the EN team). 

I see Typesetting as one of the components of the Copyediting process, but agree with Adam that it can be understood as a distinct task which could be done by someone who doesn't read the language.

My proposal breaks the Copyediting phase of our workflow into 3 tasks:

1. **Copyedit for clarity and correctness**
To encourage short sentences, straightforward instructions etc. To correct errors in spelling, grammar, punctuation.

2. **Typesetting**
To review Markdown for syntax errors, and check for consistency in formatting (headings, lists, captions, references).

3. **Generating sustainable hyperlinks** 
To archive links using Perma.cc, then substitute all original links with their stable alternative.

For EN, I can do all three parts. 
For ES, FR, PT, an externally appointed freelance copyeditor can do part 1, and (if you think it is suitable) I can complete parts 2, 3. 

I agree with Sarah that there is a cross-over between the roles of the (proposed) technical editor and typesetter. My thinking is that the (proposed) technical editor would undertake a check of Markdown at an early stage of the editorial workflow (i.e., when new materials are received and the lesson preview is being prepared). Then, the typesetter's task during the Copyediting phase would be to undertake a second review, paying particularly close attention to the lesson’s layout and structure. This would also include a check of the formatting of citations, endnotes and bibliographic references.  Overall, I think typesetting would be very beneficial and could help us to ensure that each new lesson is structurally and visually consistent with those we’ve published previously. 

One other thought (specific to the current live version of the EN Author Guidelines) is that we could move the sub-sections [Headings](https://programminghistorian.org/en/author-guidelines#headings) and [Lists](https://programminghistorian.org/en/author-guidelines#lists) from Section 2b to 2c. This would mean that [Section 2c Formatting Guidelines](https://programminghistorian.org/en/author-guidelines#c-formatting-guidelines) comprises all the information relevant to Typesetting.  My sense is that with this small change, the three parts (a, b, c) of section 2 could be clear reference points for different contributors.

2a Style and Audience - is particularly useful reference for the editor
2b Specific Style Guidelines - is particularly useful reference for the copyeditor
2c Formatting Guidelines - is particularly useful reference for the typesetter

**Comment by anisa-hawes** [comment]
My second draft of our editorial guidelines (including a distinct section on Typesetting) are now with the English team, so I am closing this Issue. 

The revised documentation is going to be tested in a pilot study for new English editors. When their onboarding is complete, I will collate feedback and open a new Issue for consultation.
