### ISSUE TITLE
Project Team Meeting: Thursday 30th September 2021

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2223]
Minutes of our July meeting are [here](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2021/07_2021_ProjectTeamMeeting.md)

Date: Thursday 30th September. Thank you for filling in the [Doodle Poll](https://doodle.com/poll/6rgvfdfuypfpwudp?utm_source=poll&utm_medium=link)
Time: 09:00 COT / UTC−05:00

Maria José @mariajoafana will initiate our call.
Zoom link:  https://uniandes-edu-co.zoom.us/j/88613032117

Team Leaders: please add a brief update of your Team's key activities before we meet. 

Project Team Meeting: Thursday 30th September 2021
---

Hello all,

**I'm creating this issue so that we can begin to draft our agenda for September's meeting.**
Please feel free to edit this agenda, and add further Items for discussion below

- [x] **Updates on Actions discussed at July Project Team Meeting**

- Pilot use of perma.cc @Anisa-ProgHist and @hawc2 #2030 
- Revision of Team Leader Terms and Selection Wiki page @Anisa-ProgHist and @acrymble #1986 
- Expansion of Risk Register across all teams @Anisa-ProgHist and @acrymble
-

- [x] **Programming Historian's Longer-term Objectives**
This is a forum for discussion of ideas about the organisation's future, and how we will work together to achieve our goals. Working document started here: https://docs.google.com/document/d/1Pe2_TZc2cUk4TC8CETFTdK1pB_RHrt0yV7hyFr2xwR4/edit
If you have time, it would be wonderful if members from @programminghistorian/english-team, @programminghistorian/spanish-team, @programminghistorian/french-team and @programminghistorian/portuguese-team could review this document and add ideas/comments. You don't have to be a Team Leader to participate in this collaborative brainstorming – all members are invited to contribute. 
 
-  Investigating a new web infrastructure. Consideration of grant funding opportunities for Tech Team @programminghistorian/technical-team 
- Investigating new communications strategies. Which communities do we want to reach? via which channels/platforms can we reach them? Which strategies are most effective within our different language communities? 
-

- [x] **Issues to consider putting On Hold** (using the new "On Hold" label)
This is a space to discuss Issues that you've noticed have remained open for an extended period of time, but which are unresolved. We can discuss options for resolution, i.e., a new assignee/ dedicated time/ collaborative resource, or to agree to close the Issue and label it On Hold.

-

- [x] **Issues to make Priority Actions** (using the new "Priority Actions" label)
This is a space to decide which Issues discussed in today's Project Team Meeting should be prioritised for progress within the next 2 month period. 

- Proposal by ProgHist ltd to formally transfer "Comms Lead" role to @anisa-hawes as paid work (@acrymble)
- Agree to Publication Outreach budget use conditions #2213 (@acrymble)
- Windows machine for @Anisa-ProgHist to conduct Lesson Maintenance #2195

**Comment by rivaquiroga** [comment]
@Anisa-ProgHist, it is possible to set the date for the meeting in the next few days?

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! This was on my list! Thursday 30th September appears to be the best choice.

**Comment by jenniferisasi** [comment]
Ok, then, I will see to leave a work meeting earlier if I can or join a bit late (we set regular meetings every other Thursday now at 9:30AM)

**Comment by svmelton** [comment]
Thanks all! I will give my update a bit closer to the date, and I'll likely be unable to attend. A couple of items to mention in advance:

- @ZoeLeBlanc and I have been having some conversations about how to help onboard editors, and how a position in the tech team might be able to facilitate that. @hawc2 suggested recruiting a "technical editor" who could help teach some of the initial lesson layout/finalization steps that have given our editors some difficulty in the past. I think this could work well with the onboarding conversations @Anisa-ProgHist and @hawc2 have been having.
- The English team will be recruiting at least 2 new editors, and we really need some Spanish-language expertise.
- Hoping to start [semi-regular managing editor meetings](https://github.com/programminghistorian/jekyll/issues/2255#issuecomment-912818026) to discuss editorial issues more in depth.

**Comment by spapastamkou** [comment]
In the meantime I have become unavailable for at least one hour thirty min after the agreed hour; I will see who can assist on behalf of the @programminghistorian/french-team and update here.

**Comment by JMParr** [comment]
### Global Team Report

by @JMParr  on 28 September 21

- @amsichani and I have had the start of a conversation about converting Global to a solo role, in part to help meet The Programming Historian's larger goal of reducing dependency on volunteer labor. I have had similar conversations with @acrymble about revisions to the role of Global, and this is part of a 6-month goal.

- @nabsiddiqui and I will give a presentation on PH tomorrow (29 Sept) to Lviv's Urban History Center.

- @nabsiddiqui and I have also been in conversation with CRASSH and some African DH colleagues about the creation of a pilot program that supports African DH, but is also a place of mutual exchange.  (CRASSH is a PH IPP)  Our last meeting was on 27 Sept. Currently, Anne Alexander is reaching out to the three African DHers who will be our primary collaborators, and we also have interest from .  We envision this as being a small number of workshops geared either to scholars who are new to DH, or to more advanced scholars who are looking to learn new skills.  Our hope is to have the workshops be in part remote, though we are in the process of learning more about what infrastructure might be available. It is hoped that this could eventually become a more sustained program, but we have determined that it is best to begin more modestly. This is a long-term goal. The initial workshops would likely take place next March.

**Comment by svmelton** [comment]
I'll be unable to attend our meeting, but please let me know if you have any questions about these items.

## EN Team Report 
by @svmelton on 29 September 21

**Actions Completed Since Previous Report**
- 1 new lesson published
- 1 lesson retired
- New [Call for Editors](https://programminghistorian.org/posts/call-for-editors-en) is out (we would love help promoting, especially to non-US audiences!) We're aiming for at least 3 new editors.
- Giulia Taurino will be joining the English team as an editor. At the moment, we're planning on onboarding her at the same time as the other new editors.

**Actions Remaining Open Since Previous Report:**  
- 1 lesson awaiting final author edits before publication

**3-month focus:**
- Onboard new editors

**Other items**
- The English team is planning on meeting quarterly.
- The MEs met and have suggested some improvements to the editor guidelines (#2312)
- In conversations with the EN team (specifically @ZoeLeBlanc and @hawc2) we identified the need for a "technical editor" that could potentially become a paid role. The need we've identified is specifically around the technical setup of a lesson. One of the major pain points for our editors is working with the metadata and getting the lessons setup. We'd like to raise this at the LTD meeting.

**Comment by rivaquiroga** [comment]
## ES Team Report 
by @rivaquiroga on 29 September 2021

**Actions Completed Since Previous Report**
- 1 new original lessons published. 
- We selected theree candidates as new editors: welcome Isabelle, Nicolás and Nicolás :tada:

**Actions Remaining Open Since Previous Report:**  
- 3 original lessons and 1 translation in the pipeline

**3-month focus:**
- Finish the onboarding of the new editors

**Other items**
- Regarding #2213, as a team we plan to spend our budget organizing online workshops

**Comment by jenniferisasi** [comment]
# Comms Team Report

by @jenniferisasi on 29 September 2021

**Actions Completed Since Previous Report:**
- Met with @anisa-hawes to establish actions she can do in her role, and actions to discontinue
- @anisa-hawes and I published the September or third newsletter of the year
- continue the promotion of relevant events/actions on Twitter

**3-month focus:**
- the Comms Lead role will be discontinued, very potentially, unless someone wants to take the lead

**Comment by ZoeLeBlanc** [comment]
# Tech Team Report

by @ZoeLeBlanc  on 29 September 2021

**Actions Completed Since Previous Report:**
- Met with tech team in August to discuss a number of issues #2216
- Officially retired @walshbr #2214 
- Discussed future of rebuilding the site's infrastructure and potentially applying for NEH funding to support the rebuild 

**Actions Remaining Open Since Previous Report:**
- #1995 and #2235 to fix ph-submissions metadata and build processes
- Transfer cloudflare management  #1981
- Perma.cc help PH keep weblinks sustainable? #2030 

**3-month focus:**
- Meet with @Anisa to resolve #1981 and discuss ph-submissions processes
- Start evaluating potential frameworks for rebuilding of site
- Evaluate utility of grant for funding tech team efforts
- Recruit more members for the tech team

**Comment by spapastamkou** [comment]
Can't be there this time and unfortunately no other team member either, please let us know if need for further information. 

## FR Team Report 30 September 2021

**Actions Completed Since Previous Report - New Actions:**
1 translated lesson reviewed and published 
1 translated lesson reviewed soon to be published
1 translation completed by new editor in Python series - now working on a second


**Actions Remaining Open Since Previous Report:** 
1 original lesson under review
1 translated lesson under review paused for bug resolution since July - can be resumed now. In the meantime the editor started review process for another translated lesson - the original has just been retired, so the process will be suspended for this lesson.   
Expecting 3rd original lesson to come in (author writing) 
FR Copy Editing Chart: in progress, now under final check (Sofia)

   
**Other**

**Queries for the Editorial Board:**


**6-month focus:**
Achieve more inclusivity for team members  

**12+ month focus:**
Continue work on targeted outreach 
Accomplish translation of Python series lessons ("task force" of 3 team members)

**Comment by DanielAlvesLABDH** [comment]
## Portuguese Team Report

By: @DanielAlvesLABDH 
Date: 30 September 2021

**Substantive Actions Completed Since Previous Report**

- Publication of 10 new translated lessons

**3-month focus**
- Onboarding of Eric Brasil as editor of the PT team already started
- Publication of 6 new translated lessons

**6-month focus**
- Publication of 6 new translated lessons
- Publication of 3 original lessons

**12+ month focus**
- Publication of 3 original lessons
- Publication of 6 new translated lessons
- Finishing the project "Literacia Digital", a collaboration between Fundação Getúlio Vargas and NOVA FCSH

**Comment by acrymble** [comment]
## ProgHist Team Report 
by @acrymble on 30 September 21

**Actions Completed Since Previous Report**
- Many lesson maintenance tickets closed by @anisa-hawes (system now much more functional)
- @anisa-hawes actively now working 2.5 days per week supporting workflow simplification/improvements
- ProgHist ltd is now fully registered as a charity (thanks @drjwbaker). This saves us taxes
- I'm not sure if it counts as a ProgHist activity, but @drjwbaker has led us through the first workshop of his JISC/TNA grant activity and call for papers around lessons about working with data.

**Actions Remaining Open Since Previous Report:**  
- refined onboarding for new editors is in progress by @anisa-hawes to trial with @svmelton 


**3-month focus:**
- @anisa-hawes to continue to work on improving onboarding processes
- @anisa-hawes to support finishing copyediting / typesetting process for all languages
- @anisa-hawes to consolidate knowledge of services we rely on (eg. passwords, logins, what everything is actually for).
- with Project Team permission, we hope to have @anisa-hawes take over Comms role entirely.
- We will be developing a new set of goals, based on the agenda set by the Project Team via the google doc circulated.

**Comment by drjwbaker** [comment]
@JMParr I just wanted to pick up on..

> @nabsiddiqui and I have also been in conversation with CRASSH and some African DH colleagues about the creation of a pilot program that supports African DH, but is also a place of mutual exchange. (CRASSH is a PH IPP) Our last meeting was on 27 Sept. Currently, Anne Alexander is reaching out to the three African DHers who will be our primary collaborators, and we also have interest from . We envision this as being a small number of workshops geared either to scholars who are new to DH, or to more advanced scholars who are looking to learn new skills. Our hope is to have the workshops be in part remote, though we are in the process of learning more about what infrastructure might be available. It is hoped that this could eventually become a more sustained program, but we have determined that it is best to begin more modestly. This is a long-term goal. The initial workshops would likely take place next March.

..with two comments. First, if you are looking to make this a sustained programme with multiple sources of funding/resource, I'm pretty sure the charity can/should consider providing some of those funds (that is, given our staffing commitments the charity will struggle to fund every initiative we have, but can certainly look at matching/contributing other sources of funding). Second, we have a spending request process https://github.com/programminghistorian/jekyll/wiki/Spending-Requests-and-Reimbursement which we need for audit purposes, but really is a conversation starter. So, when you are ready and think the charity should offer some support, put that in and we can start a conversation.

**Comment by anisa-hawes** [comment]
Dear @mariajoafana and dear all,

Apologies for the delay in uploading the Minutes of this meeting. I have now added them to our private repository, where they are available for you to view via this link:

https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2021/09_2021_ProjectTeamMeeting.md

Please let me know if you feel I have missed any important points, or mis-represented something which you said. I will be happy to make adjustments.

Very best,
Anisa
