### ISSUE TITLE
clarification on rebasing pull requests service

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2227]
We've been all very well treated by @walshbr who has I think quite unofficially been our "I can't get this pull request to work" fixer over the past year or so. Especially helping when pull requests fall behind the main branch.

With his retirement, I just wanted to clarify who or how we're going to manage this moving forward? @programminghistorian/technical-team do we have a plan or a preferred method for requesting this type of support?

**Comment by ZoeLeBlanc** [comment]
Thanks for starting off this thread @acrymble! I think this is an important question especially because @walshbr is just incredibly responsive in a way that I think we would love to continue but we'll hard pressed to do. I think it's important to set reasonable expectations for how quickly everyone can reply to Github tickets, especially considering we are all in different time zones and almost all of us are doing this in addition to our other jobs.

I think what often happens is people don't work consistently and so they'll be a flurry of updates and then nothing for awhile. I don't think this is inherently a problem but it does make it difficult for supporting editorial teams since the tech team gets zero heads up. Long term we need to start integrating more training for editorial members on how to use things like git or read our documentation, since many of the issues the tech team deals with are support questions (though maybe that will increasingly be the work of the bug fixed?).

I think one option is to provide a bit more nuance to our labels for the technical team. Right now almost every PR gets tagged at some point with tech team, but many are just looking for a general sign-off. So I think we need to start to distinguish with things that are urgent versus looking for advice/troubleshooting versus a quick overview to make sure everything looks good.

Finally once Brandon leaves will be down to 3 people, so I think recruiting is also very necessary to ensure that we can keep both supporting editorial teams and actually working on maintaining the tech infrastructure of the site. Happy to hear if you have more thoughts and maybe we can setup a meeting to discuss this further?

**Comment by drjwbaker** [comment]
Thanks for your thoughtful response @ZoeLeBlanc. I'm aware that @acrymble is taking a well earned break, so I thought I'd add a few thoughts seen as this issue is likely to be a slow burn.

> I think one option is to provide a bit more nuance to our labels for the technical team. Right now almost every PR gets tagged at some point with tech team, but many are just looking for a general sign-off. So I think we need to start to distinguish with things that are urgent versus looking for advice/troubleshooting versus a quick overview to make sure everything looks good.

Very much agree here. Ideally tech team shouldn't be tech support but about maintaining/improving our infrastructure, and different tags should be able to distinguish those different kinds of labour.

On urgency, one thing that occurred to me recently is that our site editing is more a flurry of PRs than a managed process. This links to @acrymble's point re @walshbr having been

> our "I can't get this pull request to work" fixer over the past year or so. Especially helping when pull requests fall behind the main branch.

There are very few changes to the site that *need* to be updated/edited/pushed immediately, and so I was wondering if pivoting from a flurry to - say - a scheduled main pushes, with the assumption that stuck PRs would be looked at every - say - Tuesday and Friday morning EST, would help regularise and compartmentalise tech team tech support, and manage expectations given that people are giving up their time for this.

**Comment by walshbr** [comment]
FWIW, there's a range of needs here - a difference between deep technical training to really be able to respond to technical issues and what's needed for some of these things. 

1. Updating a branch because it's out of date before it can be merged.
2. Correcting URLs
3. Things that need more in-depth attention.

I tended to be responsive to 1 and 2 because they were almost always quick fixes that I could do in five minutes between meetings. But 1, especially, is a thing that I think could very reasonably be noted for folks who could then be trained on how to do it. At the bottom of every pull request there are command line instructions for how to do it that update to be specific to each pull request, and you just have to add one command. So I could imagine gathering a team of people who have used the command line before (really you don't have to be super comfortable with it - it's the sort of thing that is really copy and pasted every time and could probably be written down for you) beyond the tech team to help support those PRs. That would allow at least a few more people to service the needs of their own PRs.

Sorry to jump in on a thread discussing my absence, but just wanted to point out that part of why I was responsive was that I was literally copying and pasting things for some of these issues. So with some support others might be able to do that.

**Comment by drjwbaker** [comment]
I would hope most of us can resolve 2, or be shown how: the recent(ish) change to the build fail interface threw me at first, but I got my head around it quickly.

On 1., agree: we need to know who here is comfortable working with git on the command line (I am). There is a professional development angle here as well: it would be lovely to send some of the PH team on a Software Carpentry workshop http://swcarpentry.github.io/git-novice/ https://software-carpentry.org/workshops/ (I am a certified instructor, but not sure I have the time right now to lead a workshop!)

**Comment by jenniferisasi** [comment]
On 1, I have tried several times in the past but was always unsuccessful and gave up because it was not working. However, @ZoeLeBlanc graciously showed me all the process the other day; turns out I needed an SSH connection that, of course, I didn't know about, so the "push" from my terminal was not working. I think if we can set up a few more people with that connection and write a simple instruction page for the Wiki with step by step, we can solve that.

**Comment by ZoeLeBlanc** [comment]
Thanks for chiming in everyone! Completely agree with everything so far and will add that I had never really looked at the git commands generated on a Github issue until yesterday, but I think they are not really the ideal git workflow for our site or editorial workflows, and might be why we tend to have branch conflicts a lot (besides the link checker at least).

I'm happy to take the lead writing up some technical documentation (though full disclosure probably won't get to it for a week or two since I'm about to start teaching a new course) but I think an internal workshop is definitely also the way to go, since live coding is usually easier to grok then copy and paste commands. If anybody else on @programminghistorian/technical-team is interested in working on this as well please let me know since I would definitely appreciate the help!

**Comment by anisa-hawes** [comment]
Hello all. Thank you! Brandon mentioned this workflow for updating a branch to bring it up to date in a previous ticket, but I don't feel entirely confident in my understanding at the moment. There is an option within each pull request to "open in GitHub Desktop" or "view command line instructions".

`git fetch origin
git checkout -b Issue-\#[Issue] origin/Issue-\#[Issue]
git merge gh-pages
git push`

I would certainly be keen to learn more/attend a workshop 🙂

**Comment by ZoeLeBlanc** [comment]
Thanks for letting me know about your interest @Anisa-ProgHist ! I'm not sure when I'll be able to organize the workshop but happy to do a one-on-one git session if you're stuck on a particular branch.

Generally the workflow I use to update a branch from gh-pages is the following:
```sh
git status #to double check what files I have locally on my existing non-gh pages branch
git add .  #to add all the uncommitted files
git commit -m "{where the relevant commit message goes here}"
git push origin branch-name #this one is optional but good for keeping your branch up to date remotely
git pull origin gh-pages #now you can refresh the local branch by pulling the latest copy of gh-pages
```
Once you have the gh-pages locally in that branch you can repeat the steps from git status to git push. 

Now this only works if there aren't any crazy git branch conflicts (which can easily happen if you're following the Github posted instructions), so feel free to try these out but also very happy to schedule a session to work through the problem together. Just lmk 😊 !

**Comment by anisa-hawes** [comment]
Thank you @ZoeLeBlanc! I'm not stuck with a particular Issue at the moment, but I think this would be a good workflow to understand and become familiar with. I'd be really happy to connect in a couple of weeks when you have more scope in your schedule. Shall we put something in our calendars?

**Comment by jenniferisasi** [comment]
@ZoeLeBlanc you two need to make sure @Anisa-ProgHist has that special access :)

**Comment by acrymble** [comment]
@ZoeLeBlanc thanks for the suggestions and everyone else too.

It sounds like a combination of training, and updates to outdated documentation (https://github.com/programminghistorian/jekyll/wiki/Technical-Team & https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions), are good first steps for this specific matter about pull request rebasing.

I think there may also be a mismatch in understanding of what the Tech team thinks its remit is, and what various other parties think it is. Clarifying that should be a priority for our next project team meeting, so that we can ensure the organization can function efficiently and nobody is stuck with tasks they aren't happy performing. That's why we started fundraising, after all.

@ZoeLeBlanc maybe you can suggest someone on the tech team who can help update the documentation (with a reasonable suggested deadline so we can all manage our expectations) and we can close this ticket?

**Comment by ZoeLeBlanc** [comment]
Thanks for the reply and feedback @acrymble. I believe that @hawc2 and @Anisa-ProgHist are already taking the lead on updating some of the documentation, though I believe they are maybe focusing on editorial workflows and ph-submissions initially (feel free to correct me though!). I think having a discussion at the next project team meeting about the remit of technical and how more paid help, or ideally volunteers would help lessen the load (we're now down to three members of the team) would be very helpful.

I'll be creating a Github ticket on setting up Github/git workshops and documentation for editors and I'll add this to the Project Team agenda so think we can go ahead and close this one, unless I've missed anything?

**Comment by acrymble** [comment]
In keeping with our longstanding use of tickets to keep track of tasks not yet finished, I think it's important that we update the documentation and then close this issue. @hawc2 are you happy to action this by updating the documentation so that more of us know how to rebase an out of date pull request branch?

**Comment by hawc2** [comment]
Yes, we can update that portion of the docs. If there are other technical
tasks that should be added to documentation, please let us know.

**Comment by Anisa-ProgHist** [comment]
The [UC Carpentries Fall 2021 Workshop Series](https://ti.to/ucsd-carpentries/uc-carpentries-fall-workshop) looks interesting. I am thinking about signing up for Intro to Git/Github - 09/17 - Day 5.

**Comment by anisa-hawes** [comment]
I think I've finally got the hang of this! I successfully re-based a batch of PRs via the Command Line this afternoon. Thank you all for your patience.
