### ISSUE TITLE
Difficulty on /lesson pages - suggestion from ipp

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2228]
We've had a suggestion from an IPP potential member that it would be helpful to make the "difficulty" rating of lessons visible on the /lessons page so that educators and learners can easily find lessons that are manageable in a workshop setting with users of varied abilities.

It might be worth us doing some focus group work to get feedback on the /lessons page layout more generally, as I've had a few comments along these lines from partners before.

**Comment by anisa-hawes** [comment]
Thank you, Adam. This idea relates to another conversation you & I had recently, about the possibility of exposing further metadata on the Lessons page. One of the other aspects of information which might be useful to see at first glance is the date of publication. Although it is possible to 'sort' Lessons according to their publication date or difficulty rating, this is implicit rather than explicit.

**Comment by anisa-hawes** [comment]
I am closing this Issue, but adding the idea to a list of enhancements/user needs to address as part of a future project.
