### ISSUE TITLE
User notes on Creating New Items in Zotero

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#225]
https://hypothes.is/a/AVLH21UbvTW_3w8Ly16v Clarification on what to do
https://hypothes.is/a/AVLH3b1vvTW_3w8Ly17O Unsolved error message encountered during lesson

**Comment by fredgibbs** [comment]
Because the python library libZotero is only intermittently maintained (https://github.com/fcheslack/libZotero) (although the JS library https://github.com/fcheslack/libZoteroJS seems to be updated more regularly) and because these lessons depend so much on libZotero, our 3 zotero api lessons are strong candidates for deprecation. Although not true when these lessons were created, there are now very good beginner-level tutorials for python and APIs, which may make it easier to let these go. Perhaps the lessons could be revised to use the Zotero API via standard python API calls, but that is more like a new set of lessons than reasonable enhancements of the existing lessons.

**Comment by mdlincoln** [comment]
These seem like very good grounds to deprecate a lesson. It would be good to discuss during the upcoming call.

**Comment by fredgibbs** [comment]
this was indeed discussed and consensus was to deprecate the lessons; done with 91275d1
