### ISSUE TITLE
Patreon new leadership needed

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2257]
I've been running our Patreon donations system since December 2019. But I'm out of ideas and energy for it and it's really stagnated now. We are seeing a slow decline of income via this stream.

https://www.patreon.com/theprogramminghistorian

Since this is a ProgHist task, I will put it on our next Proghist meeting agenda in the first instance.

**Comment by drjwbaker** [comment]
Sorry @acrymble. I really can't right now.

**Comment by anisa-hawes** [comment]
I am closing this Issue because, in agreement with Adam, I am going to take on the week-to-week management of our Patreon account. This will include: replying to messages from our Patreons; adding new Educator and Patron Level supporters to the Supporters pages of our website; collating names of new supporters at all levels for our Newsletters; and Tweeting our thanks for all new support.  

In ongoing discussions about how to [improve our communications with IPPs and supporters](https://github.com/programminghistorian/jekyll/milestone/15) we can agree upon a strategy for maintenance/growth of the scheme and how best to keep our Patreons informed (via our Newsletter, or short bulletins about upcoming events and research activities posted via Patreon's in-built blogging system).
