### ISSUE TITLE
Marie-Christine Boucher sabbatical

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2277]
@mariechristineb will be on sabbatical from October 1st 2021 to March 31 2022 to finish her PhD - sera en sabbatique du 1er octobre prochain au 31 mars 2022 pour finir sa thèse. 
Marie-Christine, tu peux ajouter tout ce que tu souhaites à ce ticket.

**Comment by mariechristineb** [comment]
Merci Sofia! Je reprends ici la checklist du wiki:

- [x] Please make sure that you communicate with the rest of the team how long your sabbatical will last. This should include a specific date at which you intend to return.
- [x] Indicate whether your sabbatical will mean you will be completely away from the project, or if you plan to participate in board meetings, or otherwise continue certain tasks.
- [x] Close out all open reviews and issues before you start your sabbatical, or (where possible) find someone to cover for you.
- [x] Set a reminder for yourself to check in with the rest of the editing team as your sabbatical comes to a close.
- [x] Issue #2297, pull request #2305 

Pour répondre au deuxième point: Je préfère m'absenter complètement du projet pendant ma sabbatique, afin de me concentrer pleinement sur ma thèse.

Et pour ce qui est du troisième point: Je n'ai pas de ticket ouvert en ce moment sur PH Submissions. Sur le Jekyll, il faudra seulement s'assurer que quelqu'un prenne en charge la révision de la section "Écrire pour un public international" des Consignes aux auteur(e)s, dont j'avais préparé la première version.

**Comment by spapastamkou** [comment]
Merci @mariechristineb C'est moi qui assurerai la révision de la sections en question dans les consignes aux auteurs, comme c'était prévu.

**Comment by mariechristineb** [comment]
Parfait @spapastamkou :)

**Comment by anisa-hawes** [comment]
Best wishes with the completion of your PhD, @mariechristineb! 

As all the tasks on the checklist above have been completed, and @spapastamkou and I are working together to revise the Author Guidelines/Consignes aux Auteur(e)s in #2042, I think this Issue ready to be closed.

**Comment by spapastamkou** [comment]
This sabbatical has been prolonged for several months (via email). However, Marie-Christine has no real capacity to reintegrate the team by September, which is why the best solution is currently for her to step down from the team, as we agreed by email. I will open a special ticket to organize this.
