### ISSUE TITLE
PH-Submissions Build Review

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2289]
From our @programminghistorian/english-team team meeting discussions, realizing that we need to potentially review our build process for ph-submissions and whether adding a more robust build pipeline similar to Jekyll's Github Actions html checker would help limit errors when lessons are initially submitted.

Would be good to discuss further with @programminghistorian/technical-team, as well as @anisa-hawes about how this could support efforts to edit current onboarding documentation and processes.

**Comment by jenniferisasi** [comment]
In order to keep track of things we try, I want to add in this ticket that: 

@ZoeLeBlanc updated her Ruby version (thanks to a tip by Brandon Walsh) and it cut the build speed in half; from 7 minutes down to 3 and a half. 

She's now thinking about how everyone can update their Ruby or if we should start trying to created a docker instance. 

More TBD.

**Comment by anisa-hawes** [comment]
I just want to link this to #2360. 

@ZoeLeBlanc wonders if the tools @rivaquiroga and @nivaca are creating could eventually be integrated into checks that the submissions repository runs on new lesson file uploads.

**Comment by ZoeLeBlanc** [comment]
Closing this because we will discuss next steps with build options in #2738
