### ISSUE TITLE
Update "Web Mapping with Python and Leaflet" to Python 3

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2301]
Hi, @anisa-hawes!
Here are @jairomelo's suggestions to update this lesson to Python 3. It looks like there are really major changes to introduce, some of which involve rewriting some parts of the lesson.

## Web Mapping with Python and Leaflet

slug: "mapping-with-python-leaflet"

- [x] ### line 175

`# versions used: geopy 1.10.0, pandas 0.16.2, python 2.7.8`

lesson tested with the following versions:

geopy 2.2.0
pandas 1.3.3
python 3.7.5

- [x] ### line 237

`geolocator = Nominatim()`

raise following error:

```terminal
geopy.exc.ConfigurationError: Using Nominatim with default or sample `user_agent` "geopy/2.2.0" is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`.
```

correction:

You need to include an `user_agent` that could be the http address of your application or a valid email address.

`geolocator = Nominatim(user_agent="email@email.com")`

- [x] ### line 238

`# geolocator = GoogleV3()`

After uncomment, this line will raise the following error:

```terminal
'Since July 2018 Google requires each request to have an API key. '
geopy.exc.ConfigurationError: Since July 2018 Google requires each request to have an API key. Pass a valid `api_key` to GoogleV3 geocoder to fix this error. See https://developers.google.com/maps/documentation/geocoding/usage-and-billing 
```

The easiest solution consist to remove this line and all GoogleV3 mentions through the lesson or ask users to create an API key and enable billing in Google Cloud.

- [x] ### lines 271-272

```python
	def get_latitude(x):
    return x.latitude
```

Markdown error ('no-hard-tabs') that will raise an indent error in Python script.

Resolve it just by deleting the hard tab and replace it with two spaces.

```python
  def get_latitude(x):
    return x.latitude
```

- [x] ### line 308

replace with this line to avoid raise an error:

```geolocator = Nominatim(user_agent="email@email.com", timeout=5)```

### lines 378-379

- [x] uncomment `# geolocator = Nominatim(timeout=5)` and 

- [x] delete `geolocator = GoogleV3(timeout=5)` to avoid raise an error.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga and @jairomelo! I really appreciate your work on this!

I have begun updating this lesson in [a new branch #2301](https://github.com/programminghistorian/jekyll/tree/Issue-2301). You will be able to [review the edits I've made in the commit history](https://github.com/programminghistorian/jekyll/commit/0c3b96827c2e1472975b94bbe8b8917478c9a167). I have also checked off the changes (above).

I have a couple of questions to complete the task. 

1. I am not certain of the best way forwards at line 238.  Do you think it is best to delete all lines mentioning GoogleV3, or to add an alert/information box asking users to create an API key and enable billing in Google Cloud. If the latter option, can we point readers to detailed information elsewhere about how to create an API key? 
2. I'm afraid I am not clear on how to "uncomment". I thought this meant to remove "//", but I don't find this in the syntax. Do you want me to remove the "#" at line 378?  

Thank you for your support.

**Comment by anisa-hawes** [comment]
Hello @jairomelo. Are you able to help me to resolve the two questions above? With many thanks!

**Comment by jairomelo** [comment]
oop! sorry, I thought I already answered :man_facepalming:. I don't know where my head is.

1. I think the best is to delete all mentions to GoogleV3. This could lead to confusion and even frustration for users who could get stuck when tried to use this tool. Also, as a corporative product, they'll trend to update them more often, hindering the lesson maintenance over time.
2. "Do you want me to remove the "#" at line 378" That's right🙂. Sorry, I didn't explain that I suggest to uncomment Python code, not markdown :grimacing:

Thanks, and sorry again for my blunder.

**Comment by anisa-hawes** [comment]
Thank you so much, @jairomelo!

Working on the same branch, #[2301](https://github.com/programminghistorian/jekyll/tree/Issue-2301), I've made the following edits:  

line 238 deleted "# geolocator = GoogleV3()"
line 378 removed "#" so that the line `# geolocator = Nominatim(timeout=5)` is uncommented

line 119: removed GoogleV3
line 130: removed GoogleV3
line 167: removed the sentence "Generally, GoogleV3 is a reliable geolocator choice because of their large geographic data coverage and generous quotas. "
line 174: removed GoogleV3
line 187-188: removed `# geolocator = GoogleV3() # uncomment the geolocator you want to use`
line 194: removed GoogleV3
line 207-208: removed `# geolocator = GoogleV3() # uncomment the geolocator you want to use`
line 221: removed GoogleV3
line 234-235: removed `# geolocator = GoogleV3() # uncomment the geolocator you want to use`
line 256: removed GoogleV3
line 272-273: removed `# geolocator = GoogleV3() # uncomment the geolocator you want to use`
line 287: removed “The error will look like this if you use the GoogleV3 geocoder:”
lines 289-291: removed the GoogleV3 error dialogue "The given key has gone over the requests limit in the 24 geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time."
line 351: removed GoogleV3


One final question: 
For the table at lines 159-165, shall I simply remove the whole of the third column labelled GoogleV3()?

**Comment by jairomelo** [comment]
Sure! All that paragraph and table must be updated too. I suggest something like the following:

Next, select the geolocator .  Here we're creating one geolocator: Open Street Map's Nominatim.  Here's a quick list of characteristics:
| Geolocator                       | Nominatim()                                                                 | 
| -------------------------------- | --------------------------------------------------------------------------- |
| affiliation                      | OpenStreetMap                                                               | 
| application use                  | single-threaded applications, can only run geolocator one process at a time | 
| capabilities for app development | can geocode based on user-input                                             | 
| request limit                    | 1 request/s or timeout                                                      | 
| performance test on census data  | 33.5s                                                                       | 

You can also choose a different geolocator from the list found in [the geopy documentation](http://geopy.readthedocs.org/).  GoogleV3 is a geocoder compatible with geopy, it is a reliable geolocator choice because of their large geographic data coverage. Since July 2018 and API key is required, and you need to enable billing in Google Cloud to use it. For more information about choosing geolocators, you can follow the discussion in the [geopy repository on Github](https://github.com/geopy/geopy/issues/90).

**Comment by anisa-hawes** [comment]
Thanks again, @jairomelo! I will make these final changes tomorrow. Very best for now, Anisa

**Comment by anisa-hawes** [comment]
Enormous thanks, @jairomelo! ✨
Changes are complete.
