### ISSUE TITLE
Banner/tagging of JISC/TNA-funded lessons

### ISSUE THREAD

**Issue by peterwebster** [programminghistorian/jekyll#2336]
As per the project meeting on 19th October, two presentational issues to investigate:

(i) the provision of a banner or other visual indication that these lessons were funded by this route, in the lesson itself;
(ii) (possibly) a new tag such that a listing of the whole group can be retrieved.

In both cases, the language is of a 'special issue'.  

(Tagging @drjwbaker @amsichani  so they can assign/label this (as I cannot).)

**Comment by drjwbaker** [comment]
@peterwebster 'special series' is preferable.

@programminghistorian/technical-team flagging now (as we aren't expecting these lessons to enter peer review until the new year) that on ii) it would be nice to have a way to filter to all the articles published as part of this series: e.g. like `https://programminghistorian.org/en/lessons/?activity=analyzing` but perhaps something like `https://programminghistorian.org/en/lessons/?activity=analyze-at-scale` where `Analyze at Scale` is a hidden option at `https://programminghistorian.org/en/lessons/`. Is that viable?

**Comment by ZoeLeBlanc** [comment]
Thanks for the updates @drjwbaker and @peterwebster ! I think one thing is whether we are planning to do more of these special series in the future? If yes, will it be with other institutions also or always through this same mechanism? Also if yes, would you want future lessons to be grouped with this current batch?

We do have the full text searching so hypothetically someone could find all the lessons if they include JISC for example, but I also hear what you're saying about wanting to indicate how these were funded and developed. In addition to the tagging, I wonder if we should add this to the metadata banner on these lessons 🤔 .

Regardless, we'll need to add in some new yaml fields to handle this but it should be possible. Just let me know the answers to the above questions when you get a chance. Thanks!

**Comment by drjwbaker** [comment]
> I think one thing is whether we are planning to do more of these special series in the future?

Not with the current funders. So I don't know.

>  I wonder if we should add this to the metadata banner on these lessons

That might work. I guess I'm thinking here both of making the funding source clear and providing some binding between articles (they don't follow each other content wise, but they are all on the same over theme - analysing large datasets)

> Regardless, we'll need to add in some new yaml fields to handle this but it should be possible.

Will do.

> We do have the full text searching so hypothetically someone could find all the lessons if they include JISC for example

I'd forgotten that https://programminghistorian.org/en/lessons/?search=jisc would be a URL we could point to. Note, however, that the articles cross between language publications (both likely new articles in multiple languages, plus their translations).

**Comment by jenniferisasi** [comment]
@drjwbaker if I may jump in, I want to offer the example from the workshop in Colombia: 

In [Análisis de corpus con Voyant Tools](https://programminghistorian.org/es/lecciones/analisis-voyant-tools), we added this banner at the end of the lesson:
![Screen Shot 2021-10-19 at 10 17 33 AM](https://user-images.githubusercontent.com/11022533/137928985-83f7384a-abad-4beb-951d-46756f6fad8e.png)

You could add something similar at the beginning of each lesson to acknowledge the "special issue" (this doesn't require tech editing, it's in the markdown file). Personally, I wouldn't go as far as creating a tag just for this funding/program as we have had other programs fund lessons/translations and we have never highlighted them that way; it something to consider, though, if it goes in the metadata, and we would potentially want to expand the rest: Bogotá workshop; Portugal-Brasil funding for translations; JISC; future. 

I think creating a new tag for "large datasets" or similar wording is a "yes", best approach, as it can easily translate to the 4 journals once there are lessons on it. We have discussed briefly about changing/adding to the taxonomy so this could be a good starting point.

**Comment by acrymble** [comment]
It's also feasible to create a (virtually) bound version of the files if you want something you can distribute as a "special issue".

**Comment by drjwbaker** [comment]
"Special series" is better for this, as I don't want to get into a muddle with issue numbers (as these articles may cross over more than one volume/calendar year). But yeah, we could bundle as well.

**Comment by anisa-hawes** [comment]
In relation to what is being discussed in this thread, I'd like to draw a link with a conversation that came up [at our Project Team Meeting earlier this month](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Project-Team-Meetings/03_2022_ProjectTeamMeeting.md) and has since been developing on Slack.

@tiagosousagarcia and @ZoeLeBlanc have suggested that in addition to a 'banner' within each .md file, we could create a new YAML field (i.e., funding_partner). ZLB explains that this can be used to create a separate web page that collates all the lessons which include that field, without interrupting our existing search logic. Their suggestion will also help us when it comes to initiating collaborations with future partners – we'll be able to point to a webpage that pulls together all the lessons produced as part of this partnership to show them what can be achieved. 

@jenniferisasi and I think adding a “funding_partner” field to the YAML sounds like a good idea. But we think that the text which is visible on our website should emphasise the partnership, rather than the funding. For example: “Published in Partnership with”, "Publicado en colaboración con", "Publié en collaboration avec", "Publicado em colaboração com".

**Comment by anisa-hawes** [comment]
Closed by #2616.
