### ISSUE TITLE
Project Team Meeting: Thursday 16th December 2021

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2359]
Minutes of our September meeting are [here](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2021/09_2021_ProjectTeamMeeting.md).

Date: Thursday 16th December. Thank you for filling in your availability in the [Doodle Poll](https://doodle.com/poll/x7uqypnt3rchwwsg?utm_source=poll&utm_medium=link)
Time: 09:00 COT / UTC−05:00

Maria José @mariajoafana will initiate our call.
Zoom link: https://uniandes-edu-co.zoom.us/j/84167770622

Team Leaders: please add a brief update of your Team's key activities before we meet.

Project Team Meeting: Thursday 16th December 2021
---

Hello all, 

Maria José and I are working together to co-ordinate our final Project Team Meeting of 2021. 

Rather than open an agenda for multiple discussion topics, we would like to trial a different approach to our Project Team Meeting this time. 

We propose testing an alternative structure for this meeting, so that it can be more a forum for collaborative and creative thinking. 

Our suggestion is to focus in on two themes:

1. **Our new web infrastructure**

General conversations about this have already begun, but we’d like to create a space for members to discuss our needs, and agree the shared requirements that we’d want the new web infrastructure to fulfill. This would also be an opportunity for members to learn where the Tech Team's current ideas are leading, and to contribute initial feedback.

2. **Our shared goals for 2022**

Collaborative planning has already begun in our [shared Long-term Goals document](https://docs.google.com/document/d/1Pe2_TZc2cUk4TC8CETFTdK1pB_RHrt0yV7hyFr2xwR4/edit), but we’d like to work together to agree our priority objectives for 2022. Maria José and I are in the process of collating ideas from the document to identify where there are overlaps or gaps. We'll devise a practical workshop format that will allow us to continue brainstorming in the Project Team Meeting, and decide the key goals we want to focus our activities towards in the coming year.

3. Miscellaneous

Any members who would like to join us are welcome.

I’m already looking forward to the conversation.

**Comment by anisa-hawes** [comment]
Dear all,

Many of you have already filled in the [Doodle Poll](https://doodle.com/poll/x7uqypnt3rchwwsg?utm_source=poll&utm_medium=link) with your availability. 

If any one who hasn't yet had a moment to do so, wants to add their preference – I can confirm the date this week.

Thank you!

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for filling in your availability in the [Doodle Poll](https://doodle.com/poll/x7uqypnt3rchwwsg?utm_source=poll&utm_medium=link)

We'll meet on **Thursday 16th December at 09:00 COT / UTC−05:00**

**Comment by drjwbaker** [comment]
I'm afraid I'm tentative for this. I'll probably be running some training with people in Syria.

**Comment by anisa-hawes** [comment]
Thank you for letting us know, @drjwbaker. After the meeting, I will share the workshop materials with those who were unable to attend, so that they can contribute ideas too. (Alas, we will miss you).

**Comment by anisa-hawes** [comment]
Dear all,

Ahead of our Project Team Meeting next Thursday 16th December at 09:00COT / UTC-05:00, Maria José and I would like to share a diagram we've created for [Goals_Planning_Dec_2021.pdf](https://github.com/programminghistorian/jekyll/files/7694853/Goals_Planning_Dec_2021.pdf).

![Screenshot 2021-12-10 at 18 43 44](https://user-images.githubusercontent.com/87070441/145625737-c731dba9-b03e-400f-8b10-97df62c3d198.png)

It aims to surface the shared goals discussed in the Google Doc which many of you have contributed to during the past few months, and proposes a starting point for the next phase of our conversations. It isn't definitive, or final, or by any means perfect – simply a first attempt to clarify the various ambitions we (Maria José and I) read within that Google Doc.

In the meeting section **Our shared goals for 2022**, we'll be asking you to collaborate with us, to clarify/refine/challenge/add to/rearrange the Project Team's shared ambitions. The diagram is structured as "bubbles" so ideas can move freely and there's plenty space for new thoughts too!

We think the dialogue next Thursday will be most productive if you've all had an opportunity to review the diagram in advance of the meeting. We're really looking forward to developing these goals with you.

With very best wishes,
Anisa

**Comment by DanielAlvesLABDH** [comment]
Dear all, dear @anisa-hawes, thanks for sharing this schema and the ideas behind that. I'm sorry to say that I will not be able to attend the meeting this time. I will ask some of my colleagues from the editorial board to be present. Best

**Comment by DanielAlvesLABDH** [comment]
Olá @joanacvp e @JimmyMedeiros82, não sei se um de vocês pode ir a esta reunião em representação da equipe PT? Eu tenho compromissos na Faculdade e na Biblioteca Nacional e não vou conseguir estar presente. Desde já agradeço!

**Comment by joanacvp** [comment]
Bom dia. Eu tenho a reunião do projeto Alcáçovas e o mesmo compromisso na BN. Se conseguir estar presente será apenas por 30min no intervalo entre uma coisa e a outra.

**Comment by DanielAlvesLABDH** [comment]
Dia 16, @joanacvp?

**Comment by joanacvp** [comment]
Verdade, enganei-me no dia. Dia 16 tenho uma consulta pelas 17h30, poderei estar presente na parte inicial

**Comment by anisa-hawes** [comment]
Thank you, @joanacvp! We look forward to seeing you then. Happy that there will be a voice from the Portuguese team!

**Comment by rivaquiroga** [comment]
## ES Team Report 

**Actions Completed Since Previous Report**
- 1 original lesson published. 
- We start the onboarding process of the new editors

**Actions Remaining Open Since Previous Report:**  
- 3 original lessons and 1 translation in the pipeline

**3-month focus:**
- Finish the onboarding of the new editors

**Other items**
- We have been working on #2360

**Comment by svmelton** [comment]
## EN Team Report 

**Actions Completed Since Previous Report**
- 1 new lesson published
- We are going to begin onboarding 6 (!) new editors
- 1st lesson in the JISC series has just been submitted

**Actions Remaining Open Since Previous Report:**  
- 2 lessons awaiting editor assignment, 3 lessons at peer or editor review, 3 lessons awaiting author revisions

**3-month focus:**
- Pilot new onboarding process
- Finish onboarding

**Comment by svmelton** [comment]
I'm very much hoping to make it to at least part of the meeting, but there are some things that are popping up with my new role, and I'm kind of on standby for a call.

**Comment by spapastamkou** [comment]
## FR Team Report
Team Name: Editorial, French

By: Célian, Gwenaëlle, Sofia
Date: 16 December 2021

---


**Actions Completed Since Previous Report - New Actions:**
2 translated lessons published published translations
Author guidelines revised
1 forthcoming original lesson in French in the JISC series
1 translated lesson under review put aside because the lesson became obsolete in the meantime

**Actions Remaining Open Since Previous Report:**
1 original lesson under ongoing review
1 original lesson still under development
4 translated lessons ready to review


**Other:**
1 member less (Martin Grandjean left the team)

---  

**Queries for the Editorial Board:**
None

**6-month focus:**
Achieve more inclusivity for team members
Review of 4 translations

**12+ month focus:**
Accomplish translation of Python series lessons (7 translations to conduct out of a total of 15 lessons)

**Comment by joanacvp** [comment]
## Portuguese Team Report

By: @joanacvp 
Date: 16 December 2021

**Substantive Actions Completed Since Previous Report**
- Publication of 5 new translated lessons
- Onboarding of Eric Brasil as editor of the PT team

**3-month focus**
- Publication of 6 new translated lessons
- A presentation on the International Conference Programming in Digital Humanities on the Portuguese participation on the PH
- Apply for a Springer publication with the previous presentation

**6-month focus**
- Publication of 6 new translated lessons
- Publication of 12 original lessons

**12+ month focus**
- Publication of 3 original lessons
- Publication of 8 new translated lessons
- Finishing the project "Literacia Digital", a collaboration between Fundação Getúlio Vargas and NOVA FCSH

**Comment by joanacvp** [comment]
Dear all. 
I am really sorry that I couldn't make it to the meeting, but I was confused about the schedule and thought it was at 5 p.m. UTC. I apologize once again

**Comment by anisa-hawes** [comment]
No problem, @joanacvp. I will email you separately, so that you can contribute to the brainstorming activity.

**Comment by anisa-hawes** [comment]
Dear all, 

Sincere thanks for the energy and contributions you gave to our Project Team Meeting yesterday. 

The minutes are in our private repository [here](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2021/12_2021_ProjectTeamMeeting.md). As always, please let me know if I've missed any important points, or mis-represented something you said. I will be happy to adjust. 

I will keep the collaborative Miro open to you until next Wednesday 22nd, in case you'd like to add any further comments, ideas or annotations.

If anyone* from the Project Team who didn't attend yesterday's meeting would like to participate in the brainstorming activity, please send me an email. I'd be happy to share the link with you and give a brief introduction. 

*I have already shared this with Daniel, Sarah and Sofia as well as Joana. 

All best wishes,
Anisa
