### ISSUE TITLE
Clarify length/scope of pre-pub review process

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#238]
This touches on #237 

I think clarifying the scope and duration of the pre-publication review process​ would be valuable. For example, when developing the SPARQL lesson (#131) I worked through the 2 submitted reviewer reports, as per PH’s stated submission process. On the cusp of publishing the lesson, a third person added some suggestions to the PR, and suddenly I became responsible for adding their changes as well. They had great suggestions! But it threw my own schedule for a loop, as I’d mentally marked that submission as “done” on my to-do list after responding comprehensively to the 2 readers, only to find I had to attend to a third set of comments - something I had not budgeted for.

In the large scope of things, it was minor (and to be totally clear there are no bad feelings involved - it resulted in a better lesson!) but I think it’s worth defining a bit more clearly the pre-publication expectations. I'm not at all opposed to the lesson being open to outside comment above and beyond the two readers. Indeed, that could be a benefit of the open pre-pub review model here. But I wonder if it would help not only authors, but also the editors, to define some_bounded_ period for open comment, so that authors don't have to work through unexpected rounds of revisions?

Perhaps once _both_ reviewers have offered their comments, and the editor and author can figure out their own realistic schedules for working on the changes - a deadline can be set for further outside comments, after which authors will not be responsible for making further changes?

**Comment by fredgibbs** [comment]
Thanks for this suggestion @mdlincoln. You're right: it's always frustrating when you think you're done and you find yourself being _not_ done. We will certainly clarify our expected timelines for reviews and responses. We also need to make sure we have appropriate editorial mediation of reviews and suggestions--a process we're still working to improve and had really just begun to formalize at the time of your lesson--regardless of when they get made. I'm sorry you felt compelled to respond to the extra review, though I'm glad you did. I should have been clearer about that.

This issue also touches on another issue we've been thinking about lately, which is maintaining lessons over time as outside URLs and technologies change. It's not fair to tether authors to their lessons forever, but some authors may well want the chance to make occasional minor revisions and keep their lessons up to date (and therefore perhaps more widely used) or respond to a unsolicited review rather than have someone else intrude on their lesson and thus compromise the original work. Your comment is a good reminder that we need clarification on those longer-term policies as well.

**Comment by mdlincoln** [comment]
Great - I think a light framework for how review will happen in the open, with the appropriately-structured possibility of comments above and beyond reviewers and editors would be dandy. This might be good to mention in the workflow page, and then reiterate and clarify within the issues discussion as the lesson is being developed.

And to the larger point: yep, I love the _opportunity_ to do a PR and update an article on here! But I won't be doing that forever, and many just won't have the bandwidth to do that kind of garden-tending work in the months or years after something gets posted. I think this touches on sustainability at several points in the workflow (this is probably deserving of a whole separate issue, but:)
1. During review: maybe suggesting links be archived via archive.org, software listed with the version number being used, just to get the piece into some minimum level of sustainability.
2. Post-publication: note that the lesson may get "issues" logged against it asking for updates or changes. I think it is fair to invite authors to participate in these revisions and note that you may reach out to them if there is some issue that editors alone cannot resolve. But, IMHO, ultimately it should be up to the editors to maintain the pieces. Maintenance, in the case authors cannot contribute to updating it, may indeed mean the lesson being "archived" as no longer workable. Which is OK by me - a "living" document like these may certainly grow old and die.

**Comment by acrymble** [comment]
Lots of important issues here. I've been doing quite a lot of maintaining other people's lessons lately as I went through some old ones, and it is a big burden (and annoying in many respects). We might need to add someone to the team who wants to take that type of thing on. Like a Wikipedia Gnome, but for PH. A topic for an editorial meeting, I think.

Thanks for raising these concerns @mdlincoln

**Comment by acrymble** [comment]
In response to your suggestion @mdlincoln I tried to address your concern about unending suggestions in our latest submission review ticket, which you can read here: https://github.com/programminghistorian/ph-submissions/issues/11

I'd be keen to hear your reaction to that.

**Comment by mdlincoln** [comment]
@acrymble I think that's a great addition to the introductory text for the review process - clear and succinct!

**Comment by ianmilligan1** [comment]
I think now that #239 is open, we can probably close this. Let me know what ya think.
