### ISSUE TITLE
Add Gold Tier IPP membership option

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2380]
I am adding a Gold Tier IPP membership option to en/ipp, es/pia, fr/pi, pt/ppi.

**Comment by anisa-hawes** [comment]
Thinking about how best to do this....

I suggest we could amend the title of the existing table 'Partnership Rates:' to make that '**Standard Partnership Rates**:'
Then add another table below to set out our '**Gold Partnership Rates**:'. e.g., for EN

| Upper Income Countries  | Middle Income Countries | [ODA eligible countries](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm)  |
|---|---|---|
| £3,000 GBP  | £1,500 GBP | £300 GBP  |
| $4,200 USD  | $2,100 USD | $420 USD  |
| €3,600 EUR  | €1,800 EUR | €360 EUR  |
| $5,100 CAD  | $2,555 CAD | $510 CAD  | 

I have calculated the rates in the table above based on a 3x increase for Upper Income Countries in each currency*, with an offer of 50% discount for middle income; 90% discount for ODA eligible countries. 

*This already takes into account the increase to $1,400 for the USD rate at the Upper Income level, see #2381 

Does this make sense? Or would you like me to double check the exchange rates for each row @acrymble? What sources do we usually refer to when assessing the exchange rates? In the past I've used <https://x-rates.com/>

I have noted the additional currencies that are included in the FR and PT tables. The example table above is based on the table used on the EN and ES pages.

**Comment by anisa-hawes** [comment]
It might be worth us talking about what further incentives we are able to offer our Gold partners. Can we specify what their special benefits would be in the text below?

**Comment by drjwbaker** [comment]
Comparable initiatives don't really offer extra incentives, apart from pretty badges https://www.openlibhums.org/plugins/supporters/, and an extra glow of satisfaction. Going way way back to when we setup IPP, we said we don't want to promise person time we can't deliver, or create extra services (e.g. a workshop service) that adds work and distracts from core mission. So my instinct is that we just add the tier (as you say, below the standard tier on the IPP page), and see what happens as a result. But I'm willing to be persuaded otherwise.

Ultimately, our IPP rates were not a deeply considered price point: it became clear that it was an easier sell for institutions if we had a price point (rather than, a vague give what you can), and so we made one that seemed about right.

**Comment by anisa-hawes** [comment]
Okay, thank you @drjwbaker. This makes sense. Personally, if I was a Gold supported I don't think I would need any extra special rewards other than an acknowledgement of that support.

**Comment by acrymble** [comment]
Thanks @anisa-hawes. I'm aware this will be really visually intensive if we have a second table. And it didn't really occur to me that we'd have a Gold Tier for ODA and Middle Income countries (I was thinking 1 new tier, not 3).

I believe we're trying to encourage high resource groups to give more, rather than create lots of more options across the sector.

**Comment by anisa-hawes** [comment]
I see. Apologies for mis-understanding. 

| Gold Tier Rate  | 
|---|
| £3,000 GBP  | 
| $4,200 USD  | 
| €3,600 EUR  |
| $5,100 CAD  | 

And to avoid introducing another table we could simply add a sentence underneath the existing one:  

_If your institution has resource to offer us even greater support, we also welcome Partnerships at our Gold Tier. Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD._ 

Something like this?
