### ISSUE TITLE
Lesson 'Configurar um ambiente de desenvolvimento integrado para Python (Mac)'

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/jekyll#2531]
Hello @anisa-hawes.
When trying to do the Portuguese version of the lesson [Configurar um ambiente de desenvolvimento integrado para Python (Mac)](https://programminghistorian.org/pt/licoes/instalacao-mac) I found some problems (that I believe can be found in the other versions of the lesson).

I am using MacOS Monterey 12.3 and I couldn't find all the steps to configure Komodo Edit in the lesson. Before creating the command "Run Python", I had to:
- Since Komodo Edit is usually blocked by MacOS, we can't immediately open the software. We have to authorise the computer to run it by going to System Preferences > Security and Privacy > General (not sure those are the names in English) and clicking in the locker in the left down corner. We can then unblock Komodo Edit.

Then, as it is (partially) explained in the Windows version of the lesson, I had to:
- Go to Komodo > Preferences > Python 3. 
- - Access the “bin” (an invisible directory) and find Python 3. The path should be like “/usr/bin/python3”.

Maybe I am doing something wrong and it can be solved out on an easier way.

Thank you for your help!

**Comment by anisa-hawes** [comment]
Thank you, @joanacvp. I encountered this problem in [another Lesson Maintenance task](https://github.com/programminghistorian/jekyll/issues/2343) ... 

Their website explains that Komodo Edit is unstable for users working on any system running on MacOS 10 or later.

There's a Community discussion here <https://community.komodoide.com/t/komodo-and-big-sur-do-not-upgrade/5191> which might be helpful.  I'll look into this and I'll test the steps you suggest above too.

**Comment by anisa-hawes** [comment]
Dear @joanacvp,

I'm so sorry for the long delay. I've returned to this Issue a number of times, but I'm still unable to move past event the first step of this lesson because of the incompatibility of my MacOS (Big Sur 11.5.2) and Komodo Edit 12.

System Preferences > Security and Privacy > General > clicking the lock to make changes >  'Allow'

I had to do this too (and your English is perfect).
 
I then clicked into Komodo's settings using the route you outlined:

Komodo > Preferences > Languages > Python 3 > Use this interpreter > /usr/bin/python3 (from the drop-down menu) > OK

But from there I'm completely stuck because as soon as I select New Command from the Toolbox window the whole application crashes and I have no choice but to Force Quit 🙁 


-- 

@hawc2 I think it could be worth adding a warning box to this lesson to say that Komodo Edit isn't compatible with MacOS Big Sur or earlier. We could also add in a note that specifies the steps (above) Joana outlines (and I've tested) to open Komodo Edit which is blocked because it is produced by an unidentified developer. 

The alternative is that we revise [these instructions](https://programminghistorian.org/en/lessons/mac-installation#make-a-run-python-command-in-komodo-edit) for creating a Run Python command using BBEdit instead. I should probably be able to work out how to do that with basic intelligence, but every command I click on seems to be blocked in BBEdit's Free Mode...

What are your thoughts?
