### ISSUE TITLE
PH/JISC/TNA Banner Text -- translation and generalisation

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/jekyll#2542]
This is an issue in two parts:

- [x] 1) Could I ask @programminghistorian/spanish-team, @programminghistorian/french-team, and @programminghistorian/portuguese-team to look over my (very rough) translations of the banner text for the JISC/TNA articles?

    - EN: This tutorial is part of a Programming Historian special series on computational analysis of large-scale digital collections. This series was supported by the project ‘Programming Historian publications: developing computational skills for digital collections’, a partnership between Jisc[LINK], the Programming Historian, and The National Archives[LINK]. To see the other tutorials published in the series, click here[LINK].
    - ES: Este tutorial es parte de una serie especial de Programming Historian sobre el análisis computacional de colecciones digitales a gran escala. Esta serie fue apoyada por el proyecto 'Programming Historian publications: developing computational skills for digital collections', una colaboración entre Jisc[LINK], Programming Historian y The National Archives[LINK]. Para ver los otros tutoriales publicados en la serie, haga clic aquí[LINK].
    - FR: Ce tutoriel fait partie d'une série spéciale de Programming Historian sur l'analyse informatique de collections numériques à grande échelle. Cette série a été soutenue par le projet 'Programming Historian publications: developing computational skills for digital collections', un partenariat entre le Jisc[LINK], le Programming Historian et le The National Archives[LINK]. Pour voir les autres tutoriels publiés dans la série, cliquez ici[LINK].
    - PT: Este tutorial faz parte de uma série especial do Programming Historian sobre análise computacional de coleções digitais de grande escala. Esta série foi apoiada pelo projeto ‘Programming Historian publications: developing computational skills for digital collections’, uma parceria entre Jisc[LINK], o Programming Historian, e The National Archives[LINK]. Para ver os outros tutoriais publicados na série, clique aqui[LINK].
    - The last link will connect to a page that will gather all the lessons that share the same funding_partner YAML field, as @anisa-hawes outlined in #2336 

- [ ] 2) We were briefly considering adding the banner automatically (like, for example, the donation banner) rather than hard coding it into each lesson, but ended up discarding that option _unless_ this is something we might want to use in the future. From what I understand, this would involve adding a case to snippets.yml and the logic to the lesson template (though, I'm sure the @programminghistorian/technical-team will correct me if I'm wrong). What do people think about this? If that is something worth pursuing, the banner text would change to something more generalisable (This tutorial is part of a special series published in partnership with ...)

**Comment by InesSalome** [comment]
@tiagosousagarcia in my view, for French translation, I would replace " série spéciale **de** Programming Historian" by " série spéciale **du** Programming Historian ", and " l'analyse informatique de collections numériques à grande échelle" by " l'analyse computationnelle de corpus numériques à grande échelle", because "computationnelle" sounds more accurate for me than "informatique" in this context... what do you think @programminghistorian/french-team ? Last, in the final sentence, I would replace "voir" by "consulter". Thank you for your work !

**Comment by rivaquiroga** [comment]
@tiagosousagarcia, the Spanish version está perfecta. Thank you!

**Comment by matgille** [comment]
I agree with you @InesSalome. In addition, I would drop the article "le" before "The National Archives". Thanks !

**Comment by ericbrasiln** [comment]
@tiagosousagarcia the Portuguese version looks great to me.

**Comment by DanielAlvesLABDH** [comment]
Obrigado Tiago. Ficou óptima

**Comment by tiagosousagarcia** [comment]
Thank you everyone!

**Comment by anisa-hawes** [comment]
Hello @tiagosousagarcia.

I wonder if the text could be a little shorter, so that it fits onto fewer lines and makes a slimmer banner? With some minor adjustments and editing a few repetitions, I wonder if this might work: 

_This tutorial is part of a special series exploring computational analysis of large-scale digital collections. It is published with the generous support and partnership of [Jisc](https://www.jisc.ac.uk/) and [The National Archives](https://www.nationalarchives.gov.uk/). To browse other lessons in this series, click here[LINK]._

(40 words).

**Comment by tiagosousagarcia** [comment]
> Hello @tiagosousagarcia.
> 
> I wonder if the text could be a little shorter, so that it fits onto fewer lines and makes a slimmer banner? With some minor adjustments and editing a few repetitions, I wonder if this might work:
> 
> _This tutorial is part of a special series exploring computational analysis of large-scale digital collections. It is published with the generous support and partnership of [Jisc](https://www.jisc.ac.uk/) and [The National Archives](https://www.nationalarchives.gov.uk/). To browse other lessons in this series, click here[LINK]._
> 
> (40 words).

Thanks @anisa-hawes -- sorry, left this here for a while, but happy with changes. I'll do them to the translations and request new reviews as well

**Comment by acrymble** [comment]
In the interest of sustainability and continuity, this 'banner' should take the same form as the lessons supported in 2018 by the British Academy. The one by Sylvia Gutiérrez de la Torre in this lesson is a good model: https://programminghistorian.org/es/lecciones/analisis-voyant-tools.

I think that's also a much simpler technical solution that doesn't require any development.

**Comment by tiagosousagarcia** [comment]
Thanks @acrymble -- from what I can see that example is hard coded, correct?

For what is worth, I have a working, generalisable banner that shows up based on a YAML field on my local machine that I was going to submit as a pull request as soon as I worked out some display quirks. @drjwbaker was keen on that, but if it's not needed, I'm happy to shelve it.

**Comment by acrymble** [comment]
Sorry I just saw this is the wrong place for that conversation, which was on #2336. I thought it sounded familiar.

**Comment by hawc2** [comment]
What's the status of this enhancement? The English team currently has two JISC lessons ready for publication waiting on this feature. Will it be fixed soon? If not, is it necessary?

**Comment by acrymble** [comment]
I dont' think this feature has an owner @hawc2 as Tiago is no longer with us. Can you just add the acknowledgment text to the lessons so they aren't held up? That's the Minimal Viable Product we need from this. Does that work?

**Comment by drjwbaker** [comment]
@hawc2 Indeed. If nobody from the @programminghistorian/technical-team is willing to take on the PR https://github.com/programminghistorian/jekyll/pull/2616 (which seems to be the case), multi-lingual hardcoding will have to be the way forward. @anisa-hawes and I talked about this last week (when we met IRL!). @anisa-hawes: is that still your preference as well?

**Comment by ZoeLeBlanc** [comment]
I can take a look at this later today @drjwbaker ! Apologies for missing this earlier

**Comment by drjwbaker** [comment]
Thanks @ZoeLeBlanc for taking a look at this and approving the PR https://github.com/programminghistorian/jekyll/pull/2616

**Comment by acrymble** [comment]
@anisa-hawes is back from leave tomorrow and can attend to this. It may take her a few days as she's been on leave for a few weeks.

**Comment by anisa-hawes** [comment]
Thanks all! 

I'm back! 🙂 

Just preparing to make some final adjustments to `_data/snippets.yml` and add ES, FR and PT pages equivalent to `jisc-tna-partnership.md' so that we have translations in place.

Following up on [my suggestion above](https://github.com/programminghistorian/jekyll/issues/2542#issuecomment-1091952550) to simplify and shorten the banner text originally suggested, I've prepared the following:

EN: This lesson is part of a special series exploring computational analysis of large-scale digital collections. It is published with the generous support and partnership of [Jisc](https://www.jisc.ac.uk/) and [The National Archives](https://www.nationalarchives.gov.uk/). To browse other lessons in this series, click here[LINK].

ES: Esta lección es parte de una serie especial sobre el análisis computacional de colecciones digitales a gran escala. Se publica con el generoso apoyo y colaboración de [Jisc](https://www.jisc.ac.uk/) y [The National Archives](https://www.nationalarchives.gov.uk/). Para ver otras lecciones de esta serie, haga clic (aquí)[LINK].

FR: Cette leçon fait partie d'une série spéciale explorant l'analyse computationnelle de corpus numériques à grande échelle. Elle est publiée grâce au soutien généreux et au partenariat de [Jisc](https://www.jisc.ac.uk/) et [The National Archives](https://www.nationalarchives.gov.uk/). Pour consulter les autres leçons de cette série, cliquez (ici)[LIEN].

PT: Esta lição faz parte de uma série especial que explora a análise computacional de colecções digitais em grande escala. É publicada com o generoso apoio e parceria da [Jisc](https://www.jisc.ac.uk/) e [The National Archives](https://www.nationalarchives.gov.uk/). Para consultar outras lições desta série, clique (aqui)[LINK].

--

Notes:

- I'm not 100% clear how the banner comes together, i.e., what part(s) of this text comprise the `blurb:` vs the `lesson-partners:` field?

- I noted that Tiago's draft text used the word tutorial rather than lesson, which I have swapped out for lesson/lección/leçon/lição to keep it consistent with the terms we use across our website. 

- Thank you for your comments, Gwenaëlle @InesSalome. I've integrated your suggestion to replace 'informatique' with 'computationnelle'. The National Archives is styled including 'The' so I think we should keep this in, and keep it in English if that makes sense to all.

-- 

@jenniferisasi and I were hoping to review the banner in our Netlify preview by staging a JISC lesson to be published in #2673, but our test didn't work because of the HTML proofer issue. 

Jenn, @drjwbaker and I also talked about the idea of possibly removing our Donate today! banner (which shows on every lesson at the moment) to make space for this one. 

Keeping in mind that we also have our Donate to Programming Historian today! ribbon above the site header across all pages, we are repeating our message. 

Adding in another new banner is perhaps a prompt us to ask ourselves whether there are _too many_ snippets of information getting in the way of our readers being able to see a lesson's contents?
