### ISSUE TITLE
Lesson "Installing Omeka" is not working anymore

### ISSUE THREAD

**Issue by josircg** [programminghistorian/jekyll#2594]
Hi folks, I'm helping the portuguese translation editors and I tried to reproduce the installation procedures and I found that the recent version of Ubuntu 18.04 is not compatible anymore with the suggested omeka version on lesson text.

So here are my suggestions to fix the lesson:

1) Most service providers do not allow ssh connection by root. So, in most of the cases, this is a confunding factor for a newbie. Suggestion to fix:

- Line 47: instead of  `ssh root@hostname`, change to `ssh user@hostname` where `user` is the user informed by the ISP and `hostname` is your server address. 

2) Mysql connection: as you are logged as root, you don't need a password

- Line 89: remove the -p

3) We should install also php-xml and we can use the same line here:

- Line 144: sudo apt install unzip php-xml

4) omeka version. The 2.4 version doesn't work anymore. The first one that is working with Ubuntu 18.04 php is 2.7

- Line 140: wget http://omeka.org/files/omeka-2.7.zip
- Line 148: unzip omeka-2.7.zip
- Line 152: mv omeka-2.7 omeka

5) In order to avoid problems for new users, I would remove "Grab the URL from http://omeka.org/download". Why? Because newer versions will require other packages besides php-xml and user will be frustrated because Omeka will just issue a 500 error and will not help him with a readable error message.

6) There is also a pitfall after installation. The path omeka/file should be writable for apache process:

- after line 184, add this: sudo chmod -R g+w files

If you want to see all fixes implemented, I tested here:

https://github.com/josircg/jekyll/blob/gh-pages/en/lessons/installing-omeka.md

**Comment by anisa-hawes** [comment]
Thank you so much, @josircg! I will take a look and prepare a PR to update this.

**Comment by acrymble** [comment]
@anisa-hawes can we please prioritise this bug for fixing. It looks like we have a full solution here.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. 

Apologies for the long delay, @josircg. I have tried to test these steps several times, and should have written to you sooner to explain that I am unable to set up an SSH connection... 

The first paragraph of this lesson provides links to instructions elsewhere on the web that guide readers to set up a virtual server. I have an AWS account and I followed the (very clear) instructions to set up an EC2 instance which I _think_ was successful. One stumbling point was establishing the key-pair (which was new to me) but I did manage that in the end.

![Screenshot 2022-10-13 at 12 46 39](https://user-images.githubusercontent.com/87070441/216345983-63b2ba25-005c-4449-8b37-51c4e0aac72f.png)

![Screenshot 2022-10-13 at 12 47 50](https://user-images.githubusercontent.com/87070441/216346035-4c877c92-9822-4d16-9d4f-60a2df682c42.png)

![Screenshot 2022-10-13 at 13 01 46](https://user-images.githubusercontent.com/87070441/216346087-bbb1c420-aed7-4c2a-a3ce-c8f22d28703b.png)

![Screenshot 2022-10-13 at 13 02 08](https://user-images.githubusercontent.com/87070441/216346177-ee1d7515-a9e1-4daf-8fd6-62a670f2b817.png)

![Screenshot 2022-10-13 at 13 04 40](https://user-images.githubusercontent.com/87070441/216346202-20eb7ee7-687b-469d-825c-16474393377d.png)

**What I have not been successful in doing is connecting my instance with an SSH client**. I will revisit the [instructions here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html) again this afternoon, and see if I can find a way through. 

(An aside is that this lesson seems (to me) a good example of an [intermediate difficulty](https://github.com/programminghistorian/jekyll/issues/2325#issuecomment-1325155042) lesson because the steps are outlined, and less experienced readers are empowered to gain requisite knowledge from external resources that are identified. Every now and again, I think to myself that I am 'intermediate' by our definition... but then at times like this, I change my mind!)

**Comment by hawc2** [comment]
@anisa-hawes setting up an SSH client can be a huge pain. I can help with troubleshooting this lesson if you want to meet and test together over zoom?

**Comment by josircg** [comment]
Hi @anisa-hawes did you solve the ssh client access?

If not, another option is access the server directly on the web. Just click on "Action/Connect" menu.
You can run all commands from there.

**Comment by anisa-hawes** [comment]
Hello, @josircg. Thank you for following up. I'm afraid I haven't been been able to solve this. Might you have scope to work through / talk through the steps together? I'll email you to organise.

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. It would be a great to organise working on this together. I'll email you to arrange.
