### ISSUE TITLE
Suggested time limit for authors?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#271]
Query for the community & editors. This is not targeted at anyone in particular, so I hope no one feels singled out, but one of our big bottlenecks in our editorial pipeline (if not the biggest) is the time authors take to do revisions after they get feedback. We've got a number of lessons that have now been in the pipeline for almost a year (if not more) and that's not a new phenomenon. I can't speak for other editors, but in my experience this is where ~50% of lessons drop out entirely.

I suspect it's in part because writing a good tutorial is more difficult than people expect (particularly those people used to blogging), or that revisions look more daunting than they actually are, but I suspect it's also in part because we don't impose deadlines for making corrections and so it never gets to the top of someone's to-do list. Most publications I've submitted to have very clear and strict deadlines for revising after peer review, and if you miss the deadline you have to resubmit as a new submission. I give quite short deadlines for reviewers (usually 1 month) and they never complain and so far have always made the cut.

I think we have avoided deadlines in part to contribute to the supportive atmosphere that we're proud of. But there's something to be said for expecting the authors to follow through in a timely fashion when reviewers and editors have given time to their lesson.

I'd be particularly keen to hear from people who have gone through as authors and have published lessons. We don't want a burden on people, but I also hate having to ask 9 times and it means I don't feel I can take on new lessons while I've got some that might spring into action at any moment.

Suggestions welcome. 2 month time limit?

**Comment by amandavisconti** [comment]
I like that you're thinking about keeping the atmosphere supportive. Having an explicit deadline (maybe with a caveat that we're happy to work with authors to come up with an alternative deadline, if they know in advance they'll need more time?) could function as encouragement to finish (e.g. all the DH conference proposals going in at 11:59pm October 31st...).

I'm also wondering about introducing co-authors for lessons that have stalled out (e.g. someone else who knows the method well enough, possibly the editor who's been working with the author and already has a good sense of the revisions needed?). I'm not sure how we'd want to do this, because I'd want to respect authorship and never add a co-author when someone does want to eventually complete the lesson themselves, or was in any way uncomfortable with their work being built on. And we'd want to think through how to attribute the various author efforts involved accurately. But there might be a way to offer a co-author for a stalled lesson that some authors might welcome?

(For what it's worth: when I authored recently, I found very encouraging the idea that the sooner I got my revisions in, the sooner the lesson could be published. @fredgibbs being awesome at quick turn-around contributed to this. Is there a way to have some mutual commitment, like: authors agree to incorporate revisions in a certain amount of time, and if they take beyond that deadline, the editor's time for responding gets longer?)

**Comment by mdlincoln** [comment]
As a general rule, I find deadlines a wonderful help in actually getting work done 😄  And I think setting a general standard (whether it be 1 or 2 months) would not be detrimental to fostering a constructive atmosphere. On the contrary, open-endedness can itself be daunting ("if I have unlimited time, do I need to make an endless set of corrections!?") as was already noted and addressed in #238 re: the open review process.

**Comment by acrymble** [comment]
Thanks @amandavisconti and @mdlincoln. We've discussed this in our editorial call and we've decided to bring this in for lessons that aren't already in the pipeline. The exact details will be added to the site by @jerielizabeth, but it'll involve a 1 month turnaround on revisions to ensure lessons get out in a timely manner. We will revisit this if new problems arise. Will close this once the site is updated.

**Comment by jerielizabeth** [comment]
Let me add this here as well:

Potential language for the "Role of the Editor" section regarding time to revision. Does this capture our conversation and conclusions well enough?

### Managing the Revision Process

With your summary of the reviews and any final instructions for the editor, include a reminder to the author that revisions should be completed within 4 weeks. This is to clearly indicate expectations and to help ensure that tutorials are published in a timely fashion. If the author has trouble meeting the 4 week deadline, the editorial team reserves the right to re-evaluate the lesson.

**Comment by acrymble** [comment]
I think the last line is a bit confusing. I might just leave it off.

**Comment by fredgibbs** [comment]
i agree with @acrymble. i think the last line should be something like "If the author anticipates trouble meeting the deadline, they should contact their editor to establish a more suitable due date."

I keep tripping over "to clearly indicate expectations" (in part because the whole document is about indicating expectations). I'd say something like "This is to ensure that lessons are published in a timely fashion and do not drag on unnecessarily." I think authors will agree that's a good thing for everyone.

Otherwise, you certainly captured what I took away from the conversation!

**Comment by jerielizabeth** [comment]
Great! Thank you and I'll move forward with the adjusted language!

**Comment by acrymble** [comment]
This was fixed by the recent commit by @jerielizabeth .
