### ISSUE TITLE
DH Awards 2022 - Self-nomination

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2794]
Hi @programminghistorian/project-team 

I would like to do a self-nomination of ProgHist for the DH Awards 2022 in the category BEST DH TRAINING MATERIALS
(e.g. talks, slides, exercises, videos or how-to guides in any form).

There is a question in their form that I cannot answer: "What was updated about Programming Historian in 2022?" The awards are for resources that were launched, updated, or have had some significant change in 2022. Is there something in PH that was significantly updated in 2022?

**Comment by spapastamkou** [comment]
The events you organize and the way they are getting articulated with our lessons? Is this not another way to give back to the community the contributions we get from the authors and other contributors?

**Comment by DanielAlvesLABDH** [comment]
Also the fact that we have expand greatly the number of lessons in other languages apart from English??? The publication of a series of lessons focusing on big data in our JISC partnership???

**Comment by GeeAlmeida** [comment]
> Also the fact that we have expand greatly the number of lessons in other languages apart from English??? The publication of a series of lessons focusing on big data in our JISC partnership???

I think expanding the number of lessons in other languages is a great argument. Do we know the numbers of lessons we had in French, Portuguese and Spanish 12 months ago?

Did we already have all four languages 12 months ago?

**Comment by DanielAlvesLABDH** [comment]
In PT, we have published 13 translated lessons in 2022. We have four languages since January 2021

**Comment by nabsiddiqui** [comment]
As others mentioned, I think the JISC partnership, the new lessons in other languages, and just our languages in general that we have added, especially those on machine learning, etc. should be sufficient for the purpose of nomination. Thanks for doing this @GeeAlmeida

**Comment by GeeAlmeida** [comment]
@anisa-hawes is there any way we can quantify the additions in the past 12 months per language? I would like to be able to say "We've been publishing in English since 2012, in Spanish since ??, in French since ?? and in Portuguese since 2021. In the past 12 months we have published x number of lessons in English, y in Spanish, z in French and 13 in Portuguese" - can you help me with this?

**Comment by anisa-hawes** [comment]
Thank you @GeeAlmeida. 

It isn't a number that is at my fingertips, only because metadata isn't visible at a glance from our Lesson Directories. I have a quicker answer when I have just done an update for the Directory of Open Access Journals! But filtering the lessons so that I see the most recently published at the top of each list and clicking in to check the dates, I think these are the numbers you will need: 

We've been publishing in English since 2012, in Spanish since 2017, in French since 2019 and in Portuguese since 2021. In the past 12 months we have published 10 lessons in English, 3 in Spanish, 2 in French and 13 in Portuguese.

**Comment by GeeAlmeida** [comment]
Thank you @anisa-hawes

**Comment by rivaquiroga** [comment]
@GeeAlmeida, you can add one more lesson in Spanish. It is going to be published before the end of the year.

**Comment by GeeAlmeida** [comment]
We've been publishing in English since 2012, in Spanish since 2017, in French since 2019 and in Portuguese since 2021. In the past 12 months we have published 10 lessons in English, 4 in Spanish, 2 in French and 13 in Portuguese.

Thanks @rivaquiroga

**Comment by GeeAlmeida** [comment]
For some reason when I visit the [DOAJ](https://doaj.org/search/journals?ref=homepage-box&source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22programming%20historian%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22track_total_hits%22%3Atrue%7D) and sort our articles per year I get the following information regarding PH publications in 2022:
English 6
Spanish 3
French 2
Portuguese 3

That is bad news, because it means there will be no way of evidencing what we are saying
English 10 
Spanish 4
French 2
Portuguese 13

Any idea why the big difference especially in English and Portuguese? Were there many publications at the end of 2021 for example?

**Comment by anisa-hawes** [comment]
It may be partly because I haven't [updated the DOAJ since September](https://github.com/programminghistorian/jekyll/issues/2678) – I do this twice annually.

Another contributing factor may be that until this August, the PT team had been dating their translated lessons using a different system to the other journals. [We have now agreed a consistent system](https://github.com/programminghistorian/jekyll/issues/2642), so things should be clearer going forwards.

As nominations remain open until 29th January, I suggest we leave this for now and return to it in the new year. I can update the DOAJ then, and we can use those numbers. 

I don't think we should change the publication dates of past lessons because they may have been cited, and in some cases changing the date will change the volume number (which is, the year of publication).

**Comment by anisa-hawes** [comment]
Update: I just need to add our latest lesson metadata to the DOAJ listings. 

I just double-checked what the figures for EN and PT lessons published during 2022 will be:

EN = 10
PT = 13

It will be correct, and we will have this evidence.

I'll set myself a reminder to do this early in the New Year. Thank you, @GeeAlmeida

**Comment by GeeAlmeida** [comment]
great :)

**Comment by GeeAlmeida** [comment]
I'll do the submission to the awards later on, then.

**Comment by anisa-hawes** [comment]
Happy New Year, @GeeAlmeida! DOAJ updates done, #2808.

**Comment by GeeAlmeida** [comment]
OK, I have completed this task. I sued the following blurb:
Programming Historian is a flagship educational resource in the digital humanities. Scholars can use our website to learn a wide range of digital tools, from Python to Augmented Reality using tutorials designed with humanities students and researchers in mind. In the past 12 months we have increased our offer, publishing 10 new lessons in English, 4 in Spanish, 2 in French and 13 in Portuguese.
