### ISSUE TITLE
Getting PH into Google Scholar

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2809]
I am currently on a quest to get PH listed on as many resource databases as possible.

The most visited and most powerful of them is Google Scholar. Apparently 50% of journals visualisations happen through Google Scholar. 

I need help from @programminghistorian/technical-team  to make this happen.

Here is information on what we need to do:
https://scholar.google.co.uk/intl/en/scholar/inclusion.html

[This](https://www.ardaconference.com/blog/how-to-index-articles-in-google-scholar/) and [this](https://www.greenlanemarketing.com/resources/articles/the-current-state-of-google-scholar/) are the best resources I found about getting indexed by GS.

**Comment by anisa-hawes** [comment]
Past Issues #1742 and #190 are relevant here. 

[A quick search here](https://scholar.google.com/scholar?start=0&q=source:Programming+Historian&hl=en&as_sdt=0,5), retrieves ~50 article results from our journals (the first 5 pages) but very few which aren't English.

**Comment by GeeAlmeida** [comment]
Thanks Anisa!
Someone said in the older discussions that once we are indexed by crossref with the doi process then Google indexing would work. Are we now indexed by crossref with the doi process? Do you know?

**Comment by anisa-hawes** [comment]
I'm not sure @GeeAlmeida – I'm not clear exactly how Crossref works. All of our articles are assigned DOIs but it seems like something isn't connecting as Matthew Lincoln expected it to. We can try to find out!

**Comment by acrymble** [comment]
@GeeAlmeida I wonder if this might have to wait until we have a new infrastructure, because it looks like we might have to re-do these changes in whatever system we adopt, and I've promised @ZoeLeBlanc that we'll stop making changes to our current system until we decide on a new one.

Just noting from looking at the advice on the pages you provided, maybe adding PDF versions would help with this, as people can then upload them on their own university pages, which seems to be one of the ways Google Scholar finds content. PDFs are also helpful for offline viewing, which is helpful in workshops / low internet places, so that might just be a good idea all around in future.

**Comment by GeeAlmeida** [comment]
OK I'll make a note of this in the document where we've been gathering website ideas. Close this issue then?
