### ISSUE TITLE
Automated downloading wget - warning suggestion

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2828]
Automated downloading with wget

https://programminghistorian.org/en/lessons/automated-downloading-with-wget

the Windows installation instructions for Wget suggest “you should download the 32-bit binary).” There are both 32 and 64 bit installation files and you need to install the one that matches your machine (which you can Google to find out - is my computer 32 or 64 bit?).

I suggest a warning box telling people to check which one they need and point them to search engines to find out. That way they don’t try to install the wrong one and the advice remains sustainable.

It’s not a bug but tech moving on in the twelve years since this lesson was published. Amazingly it still works!

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. 

You're right, [this section](https://programminghistorian.org/en/lessons/automated-downloading-with-wget#windows-instructions) includes the (very specific, and now outdated) note _To do so, visit [this website](https://eternallybored.org/misc/wget/) and, download `wget.exe` (as of writing it is version 1.17.1, and you should download the 32-bit binary). The file is the second link in the 32-bit binary column, entitled just `wget.exe`._

I'd suggest that rather than create a warning box, we could adjust this section so that it is more general and sustainable: _To do so, visit [this website](https://eternallybored.org/misc/wget/) and download the latest version of `wget.exe` using the installation files appropriate to your computer. You can find out if you need the 32-bit or 64-bit binary by checking your device specifications, or performing an online search._
