### ISSUE TITLE
Offering student placements at PH

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2830]
@programminghistorian/project-team 

What do you guys think about offering student placements at PH for Masters students?

I had a conversation with an IPP this week, and they suggested that we host DH Masters students at PH. At Leuven the internships are unpaid and remote. Students spend 6 months at a DH institution/ organisation and then write their dissertation on the digital learning they have done during that period.

They gave two examples that would suit them: (1) something more theoretical, such as a student working with a PH team member to make a first draft of a tutorial. In this case their dissertation would be around their contribution to the journal. (2) if students are interested in the more practical/publishing side, they could help us with the journal (for example updating retired lessons and other things like that). In this case they could write their dissertation on our open access policy, for example.

Would your institution be interested in this?

**Comment by matgille** [comment]
What follows is my personal position and I have not discussed it at all with the rest of the French-speaking team. It's just my 2 cts.

I am very much against unpaid internships. My point of view is undoubtedly influenced by my situation, my background in the French University and my culture, which is that in my opinion all work deserves a salary, and that an unpaid internship can only reinforce social inequalities; moreover, a salary -- very low indeed, about half the minimum wage -- is compulsory beyond 2 months of internship here in France.

It would be interesting to have students work on PH, but -- in my opinion, again -- it would have to be a research work completely outside our organisation, without direct involvement in the project, or to pay them for their work.

**Comment by drjwbaker** [comment]
Note that unpaid internships are illegal into the UK unless they are connected to a course of study, e.g. the student is a examined in some way on via their internship (which this idea seems to be) https://www.gov.uk/employment-rights-for-interns

Post-Brexit, I *think* such a student worker located an EU country (or indeed, anywhere not in the UK) could not be managed by someone in the UK or do any work that is "Publisher" work (that is, say, working directly with and/or in support of Anisa or Gisele).

In addition to legal issues, my question here would be who would manage student interns: we run a paid student internship programme at Southampton DH, and the interns are amazing, but also require lots of time to manage.

**Comment by jenniferisasi** [comment]
I want to echo @matgille and @drjwbaker's opposition (even by law) to do unpaid internships; but also James' question about who would manage these, as I understand they would be "external" MA students - by external I mean not directly connected to each of our institutions/positions. Not just manage their time but also mentor them, write a lesson with, etc. 

I favor internships on PH because I believe we are a great source for many DH tasks; but I only see it with internal students (to our paid positions). In a way, I actually mentored @JoshuaGOB while I was a postdoc and he was a grad student assistant: how to write a lesson, see how things worked on the editorial side, etc. with the clear goal of him applying to be an editor too (as you know, he was successful on it); but we had permission to use work hours of both our positions to carry out this (less structured) internship, meaning we were both paid to do so.

**Comment by acrymble** [comment]
Great comments so far. I think there are very different cultural views on this type of thing. In some cultures (including quite frequently in the UK) this is seen as a way to bring classroom and 'real world' together, and students seem to like that idea enough that universities keep offering it as a way to attract more people to courses. It's generally recognised that the intern probably is taking more energy than they're giving, as @jenniferisasi outlines. When you're asked to offer a place, I think it's seen as being asked to volunteer your time and expertise to the student, rather than that you're being offered free labour, but that's viewed differently in different cultures.

When I had an internship at Zotero as part of my MA, I was paid $16 per hour and that was 14 years ago.

**Comment by DanielAlvesLABDH** [comment]
Dear all, in the PT team we had both situations, students that volunteered to work with us in the translation of lessons, but most of the time we got some funds to at least symbolically pay the students work. It happen with the Fundação Getulio Vargas project and with the "Verão com Ciência" initiative. In principle I would agree with Adam If the goal is to give the students the opportunity to get in touch with a project that has an international impact and where they can experience in practice some of the theory that we usually give them in classes. But I have applied that in undergraduate classes and in a very limited way, usually no more than one month and as part-time. Best

**Comment by GeeAlmeida** [comment]
@drjwbaker you said that unpaid internships are illegal in the UK - I just wanted to mention / ask if that is the case for registered companies and charities? It seems to me as ProgHist has the two hats, we might have some leeway here.

**Comment by JMParr** [comment]
Hi, All - Unpaid internships are generally legal in the US (provided that they are officially attached to course credit and offer something professionally beneficial to the student), but controversial. My institution is a bit unusual in that it follows a co-op education model. Students have terms in which they undertake paid work that is typically related to their majors - either on campus, or there are a number of local companies and cultural institutions that have co-ops (seeing it as mutually beneficial). I think pay varies, although they do have to pay at least minimum wage (currently $15 / hr in Massachusetts, with some exceptions for things like agriculture and certain food service jobs). I'll note that the US federal minimum wage is much lower ($7.75 /hr, I think?), but some states mandate higher hourly wages in part due to higher local costs of living (alas, still generally insufficient, but states are permitted to have higher requirements). Here's some background on the co-op model: [https://careers.northeastern.edu/cooperative-education/](https://careers.northeastern.edu/cooperative-education/)  We are US-based, although we do now have a London campus (formerly the New College for the Humanities). I can ask my London colleagues how co-op is handled there. We're a little unusual in part because we've had a co-op model for over 100 years, but there are other schools (including another engineering college nearby) that use a co-op model.

**Comment by drjwbaker** [comment]
> @drjwbaker you said that unpaid internships are illegal in the UK - I just wanted to mention / ask if that is the case for registered companies and charities? It seems to me as ProgHist has the two hats, we might have some leeway here.

If you are thinking of volunteering, see https://www.gov.uk/volunteering https://www.ncvo.org.uk/help-and-guidance/involving-volunteers/volunteers-and-the-law/volunteers-and-employment-rights. Note that one of the purposes of setting up the Ltd was to move away from relying on voluntary labour. So I suspect there is little appetite for now expanding the voluntary roles we have.

**Comment by JMParr** [comment]
@drjwbaker agree that it's not ideal to expand voluntary roles.

**Comment by GeeAlmeida** [comment]
I am familiar with the situation Leuven described because as a PhD in Ghent (also in Flanders) we had a Masters student join our research group. She was doing a History Masters (I believe) at Groningen (Netherlands). So I think this kind of thing is very common in that region - Masters students seem to always go somewhere, to do something. I believe they are broadening the scope of students' employability. I am saying this just to explain that there is nothing weird about this from the Flemish perspective.

But I think the above discussion amounts to a "No, thanks" from PH. Right?

**Comment by GeeAlmeida** [comment]
The internship we have been discussing here is explained in full in the link below:
 https://set.kuleuven.be/onderwijs/mdh/current-students/masters-thesis/Internships

**Comment by hawc2** [comment]
Hey all, I'm chiming in here for clarification. I don't know much about how
PH is deciding when to pay volunteers and when not in the future, but I'm a
little confused why we're turning down these interns, when most of our
volunteer editors are not receiving any payment either.

I'm about to do a call for more editors for the English team because we are
over capacity. So we will be expanding volunteer roles for our team unless
there is a plan in place to start paying some kinda of annual stipend to
our majority volunteer team of Editors.

What is different about these interns from all the other volunteers working
on this journal who are not being paid? Accepting non-paid internships at a
for-profit company is clearly immoral, but I don't see why it is so bad for
a non-profit organization, especially one dependant on volunteer labor, to
accept unpaid interns. We currently have graduate students volunteering
their time for our project as editors, so it's not the 'student'
affiliation that is the problem with the interns, right?

If the reason is that we think supporting these student interns will be
more work than assistance for the project, that makes sense. Anyway, just
hoping to get some clarification as to how this discussion about unpaid
interns fits into PH's larger planning around unpaid volunteer labor.

**Comment by acrymble** [comment]
@hawc2 good points.

I think this raises a need for us to be clearer about what we pay for and what we don't. It's clear to me, but I appreciate probably not to everyone, and it's possible that in practice we aren't as consistent as we should be.

We never pay trustees because that's illegal. 
We don't pay MEs or Editors to do editorial work. As far as I know, this is standard for peer reviewed publications around the world, except in some rich science fields. I think individual publications may sometimes pay editors (usually students) through grants, but we don't get involved in that and they aren't our funds. We call this 'volunteering', but in most of higher education it's called 'academic service'.

We pay for just about everything else. Or should be if we're not.
copyediting, substantial translation (beyond a few lines), professional services, consulting, lesson maintenance, managing/supervising interns, anything else really. No one should really be doing this unless they've been paid to do it, and if you are, please get in touch so we can fix that.

Exceptions would be if someone gives us money to do something specific (translate a specific lesson), and then we're just passing their money along. Or if someone decides (not asked) to run an event / do a piece of research / give a paper at a conference. We'd regard that part of their scholarly activity for their day job or research. If we're asking for it, it should be paid for.

@anisa-hawes maybe you can help make sure we're doing this consistently, moving forward and everyone understands it?

**Comment by drjwbaker** [comment]
That is my understanding @acrymble. Thanks for summarising the situation with such clarity.

**Comment by hawc2** [comment]
Thanks for clarifying @acrymble!

**Comment by nabsiddiqui** [comment]
I think @acrymble sums it up well, but I would like to bring attention to the fact that there is some movement on trying to change these standards. For instance, Reviews in DH has recently put out a call that has a stipend for editors:  https://reviewsindh.pubpub.org/topic-editors-wanted

While this is something that isn't common, given Programming Historian's reputation, I believe it may be possible to get a grant, etc. I don't know if something in the UK prevents an organization like ours from doing it though.

**Comment by drjwbaker** [comment]
> I think @acrymble sums it up well, but I would like to bring attention to the fact that there is some movement on trying to change these standards. For instance, Reviews in DH has recently put out a call that has a stipend for editors: https://reviewsindh.pubpub.org/topic-editors-wanted
> 
> While this is something that isn't common, given Programming Historian's reputation, I believe it may be possible to get a grant, etc. I don't know if something in the UK prevents an organization like ours from doing it though.

This feels like something we can/should aim towards (I don't see a legal impedement, so long as much payments are honoraria rather than salary). Doing **better than** the norm does indeed feel very us.

**Comment by acrymble** [comment]
@nabsiddiqui I believe Reviews in DH has a large grant to pay for this. That's quite unusual, and I'm not sure if they intend to continue this practice after their grant runs out. If we did do this, we'd have to probably put caps on the number of editors in a team (else, how can you budget?) and that's more meddling in teams than we've done till now.

We currently don't have the money to start something like this though.

**Comment by GeeAlmeida** [comment]
I have communicated to our partners that our discussions have erred towards not offering student placements at PH for Masters students. I wonder if we can close this issue now?

**Comment by jenniferisasi** [comment]
It just occurred to me, given the conversation here and my concern of an editor of X institution mentoring a student from institution Y: could one professor from the institution that is requesting the internship join as an editor who could then act as mentor for their own internship? 

What do you all think? Like I said before, I am not against internships at PH per se, but given we are all volunteering our time, I would only favor editors mentoring students in their own institution so that it is part of their daily job (indirectly paid as 'academic service')

**Comment by GeeAlmeida** [comment]
Jenn @jenniferisasi I think part of the idea of the internship is for students to "get out there" and establish new (hopefully working) relationships with people other than the staff at their University.

I think people who had a view on this topic have spoken and the consensus has been to not offer internships at PH. I believe this closes this issue.
