### ISSUE TITLE
broken links in From Hermeneutics to Data to Networks

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2862]
[From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources](https://programminghistorian.org/en/lessons/creating-network-diagrams-from-historical-sources) & Spanish translation https://programminghistorian.org/es/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas

The lesson gives links to 4 other network analysis tools at the end. 2 of the 4 are now moved to new websites.

NodeXL should point to: https://www.smrfoundation.org/nodexl/
VennMaker should point to: https://www.vennmaker.com

The screenshots are a little out of date now, but it was still working fine otherwise, so I guess it depends what the view is on out of date screenshots.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble! I've prepared a PR to adjust these links in the EN original and ES translation. 

Thank you also, for raising this question about updating screenshots: 

My sense is that updating screenshots of older lessons might lead to a temporal dissonance between the writing and the figures. 

Unless we are significantly updating the lesson during 'maintenance', that is, fundamentally changing the instructional text (alongside the screenshots) to make it possible for readers to follow the lesson. 

But I will seek the perspectives of Riva and Alex on this when I am requesting their review.

**Comment by hawc2** [comment]
@anisa-hawes I approved the pull request for this issue since it's fixing the links. 

For the screenshots, I think it depends...

If the instructions in the lesson are being updated, then screenshots should be updated so there isn't a contradiction between them. Otherwise, I can't think of a dire reason to update the screenshots.

If it's something like a screenshot of a website for a Tool that has changed, and we're updating the links, I don't see a problem with updating the screenshot, but it's not necessary. If it's any other kind of website related to a historical data source, we probably shouldn't change it, since it would change the lesson's context

**Comment by anisa-hawes** [comment]
Thank you, @hawc2.

> If the instructions in the lesson are being updated, then screenshots should be updated so there isn't a contradiction between them

I agree. My thoughts are that if we are fundamentally changing the instructional text then we might also need to update the screenshots to make it possible for readers to follow the lesson.

What do you think, @rivaquiroga?

**Comment by rivaquiroga** [comment]
I agree with @hawc2 and with what you are saying, @anisa-hawes: if we are changing the instructional text then we need to update the screenshots if the current ones make it difficult to follow the lesson.
