### ISSUE TITLE
Managing Editors’ Meeting: Thursday 16th March 2023

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2875]
Hello @DanielAlvesLABDH, @rivaquiroga, @hawc2, @marie-flesch and @jenniferisasi.

I am opening this Issue to agree an agenda for the forthcoming meeting of MEs.

Date: Thursday 16th March
Time: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230316T140000&p1=1440): 09:00 Philadelphia / 11:00 Santiago / 14:00 Lisbon / 15:00 Paris
Minutes of the last meeting: [12_2022_ManagingEditorsMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Managing-Editors-Meetings/12_2022_ManagingEditorsMeeting.md)
Zoom details: see email.

**March Managing Editors' Meeting**
---

Please add items you'd like to put on the agenda for discussion:

- Welcome to @jenniferisasi
- Re-considering the [frequency and focus](https://github.com/programminghistorian/jekyll/issues/2762) of ME meetings @hawc2   
- Guidelines + Templates for [Managing Editor handover process](https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover) @anisa-hawes 
- Guidelines + Templates for Onboarding and Offboarding new editors @anisa-hawes 
- Discussion about proposed new editorial guidelines + workflow @anisa-hawes
- Suggestion to use Google Workspace tools, including Drive @hawc2 
- Diagrams and figures created for original lessons: how to make them easier to translate? @rivaquiroga

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes, dear colleagues, unfortunately I'm unable to attend the meeting this time. I have to represent my university in an international jury in Madrid on that day. Sorry.

**Comment by hawc2** [comment]
@anisa-hawes, fine by me if we need to reschedule. One topic I'd ask we discuss at the next ME meeting, is standardizing the use of Google Workspace across all four journals. Now that we've got access to all the Google Workspace features, we should take advantage of them.

I've set up a Shared Drive for the English team that I'm hoping to use going forward. I think we could have a general Shared Drive for PH Admin Team, some of which files would be available to the MEs and Project Team. Then each journal could also have a Shared Drive for their language.

It will ensure more sustainability and ease of access for editors when tracking the editorial process over time. I'm happy to show how I' veset it up at the ME meeting, and I'd be happy to hear people's feedback/thoughts

**Comment by anisa-hawes** [comment]
Thank you for this suggestion @hawc2. I've added it to [our agenda](https://github.com/programminghistorian/jekyll/issues/2875#issue-1609091672).

**Comment by rivaquiroga** [comment]
@anisa-hawes, I added an item to the agenda regarding the use of figures and diagrams in original lessons. We need to discuss how to make them easier to translate. Here are a couple of examples:

- https://programminghistorian.org/en/lessons/computer-vision-deep-learning-pt1#creating-a-model
- https://programminghistorian.org/fr/lecons/transcription-automatisee-graphies-non-latines#le-fine-tuning-it%C3%A9ratif-des-mod%C3%A8les-sur-calfa-vision

One option could be that a "mute" version of the diagram or figure is submitted for later reuse on translations.

**Comment by anisa-hawes** [comment]
Excellent idea, @rivaquiroga. 

@marie-flesch and I also spoke about the complexity of the figures/diagrams in the recently published FR lesson, and how we could approach writing alt-text that is sufficiently detailed to describe them for non-sighted readers – each one could almost operate as a section of the lesson in itself.

**Comment by acrymble** [comment]
> 

@hawc2 what are you using this Google space for? It feels to me like journal infrastructure should have self-contained workflows that do everything an editorial team needs, and if we need to use other things like Google, then our infrastructure probably isn't fit for purpose.

**Comment by hawc2** [comment]
@acrymble  since I've been working at PH, the Google Suite (gmail, docs, sheets, forms, and colab) have been regularly used to deal with communications/planning outside of Github. I'm not sure what publishing platform would fulfill all our needs so comprehensively that we wouldn't still want to make use of Google Workspace products. Plus we get them through our non-profit status I believe for free? We could even switch from Zoom to Google Meets and centralize more around Google products, but I do understand some people on the team are wary of Google...

When I took over as ME, the prior ME had been managing things through personal gmail. The advantage that Google Workspace accounts brought for the team is that I'm now managing everything through english@programminghistorian.org. So whoever takes over after me will have records of all my emails with contributors as well as the editorial team, and any google docs, forms, etc. we use for internal discussions, preliminary reviews of lesson proposals, etc will be stored and preserved in a Google Shared Drive.

Since Github only serves as our open peer review and publishing platform, we'll need something to handle the rest of the editorial operations, and Google seems solid to me. It sounds like some languages on the PH team do preliminary proposal review through email, and the PH English team used to do that. I've recently set us up with a Google Form for each proposal that allows for more structured feedback from editors to new proposals, and we're keeping a record of that in the English Team's Google Shared Drive.

Hope that makes sense?

**Comment by acrymble** [comment]
@hawc2 the email address seems really important. Glad we got that sorted.

The rest looks like things we could just be using out-of-the-box publishing solutions for, if the MEs are interested. Most journals use publishing solutions like Manuscript Central/Manuscript Manager rather than building their own workflows. I suspect it would save everyone a lot of time in the long run if we did too. @anisa-hawes has already done some research into these and I'm sure she can speak to them if the view on this has shifted since last year.

We don't need a free solution. We need one that works well for people.

**Comment by hawc2** [comment]
@acrymble most elements of the current workflow seem to be working fine, but I'm open to other options. 

Even if we switch to Manuscript Central, I think it's likely Google Docs, Sheets, and Forms will prove useful to the PH editorial teams, and it's better, in my opinion, if they're managed through Google Workspace. 

Right now many google documents/files pertaining to PH work, like the Twitter bot and our current spreadsheet of prior peer reviewers, aren't stored in a shared folder, but instead owned by different people's Google accounts, many of whom have been involved with the project at various stages, but aren't currently active. This can make it tough to find stuff, especially as new managing editors and editors get onboarded. 

So I'd still be in favor of centralizing our current collection of Google docs. It will make migrating to another platform easier as well.

**Comment by DanielAlvesLABDH** [comment]
Hello everyone and sorry for being late in this discussion. I agree with @hawc2 and I use the Google products to work and communicate with the team. Except Zoom because I have a pro account in my university. I didn't yet started to use the portuguese@programminghistorian.org but will start soon. We are in a process of selecting a new ME and that would be the perfect timing to initiate this. Regarding other tools to manage the work and the communication I confess that I will not use them for now. Managing the email is hard enough and I don't have time to get to know and manage other tools.

**Comment by anisa-hawes** [comment]
Apologies for the delay. Minutes of this meeting have been uploaded to our private Project and Business repository: [03_2023_ManagingEditorsMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2023/Managing-Editors-Meetings/2023/03_2023_ManagingEditorsMeeting.md).
