### ISSUE TITLE
Create and post call for editors for English team

### ISSUE THREAD

**Issue by hawc2** [programminghistorian/jekyll#2876]
Hi @anisa-hawes, starting this issue so we can move forward with posting a call for editors for the English team. We discussed this already via slack, and it sounded like you we're working on it for a couple of the languages for the journal at once, but let me know if you need anything from me. 

As soon as you can share a draft with me I can give you any feedback and we can post it. Fine by me to use a similar process to last year with Sarah. 

Ideally we can post this call by mid-march and start interviewing in April

**Comment by hawc2** [comment]
@anisa-hawes sorry to bug you about this, but we had originally planned to post this call back in January of this year. We've now had multiple more English editors say they need to step back, so this is a high priority action item for the English team. Can you let me know what I need to do to post this call?

**Comment by acrymble** [comment]
@hawc2 we made a separate page for these. You can find how other ads were written in the 'history' for the page: https://github.com/programminghistorian/jekyll/commits/gh-pages/en/vacancies.md

I'd encourage you to bring one person on at a time. In the past there have been panicked attempts to rebuild teams quickly, and it usually ends up with the whole cohort feeling a bit disconnected. Better to build one relationship at a time and do so more regularly if needed.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. This relates to some conversations we had at the Managing Editors' meeting last week. We are planning to re-think the way we recruit editors, so that we do so on a rolling basis and build a multi-lingual cohort community. I propose running orientation/onboarding sessions in pairs, interwoven with cohort meet-ups. More details to follow!

I'm onto this @hawc2, but the FR team are our highest immediate priority – with only one active editor currently.

**Comment by hawc2** [comment]
@anisa-hawes if you're busy with French team I'm fine with moving this forward myself, I just didn't know procedure and if that was more your job than mine. 

I'm ok with onboarding one editor at a time, but it sounds like a lot more work on the hiring end to do one at a time. It would be ideal if I could interview a number of applicants at once and select a few people to onboard, even if that process is scaffolded one at a time. 

I was hoping to bring on a few more editors in the next six months, if that seems feasible. Most importantly, if we can estimate some kind of schedule for how many new editors can be brought on at a rolling basis, that will help me plan better for our future capacity. If I'll only be onboarding one editor this year, for instance, that would change our broader plans and require me to start telling submitted lessons we prob can't edit their pieces until ~2024 due to backlog.

**Comment by acrymble** [comment]
@hawc2 the advice is to make sure you form solid support relationships with the people you bring in, and not that you can only bring in 1 person this year. We've had several mass onboardings in the past. None of them went well, and very few of the people recruited in that way stayed long enough to edit more than 1 lesson. You might consider doing exit interviews to find out why so many of your editors are leaving, and then we can address that.

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. That is certainly feasible, and it is within my remit to support you with this.

I'm completing the minutes of last week's meeting and I will follow up with a fuller proposal, but to summarise our conversation last week and my thoughts for re-thinking the way we recruit editors:

- Recruit on a rolling basis, across 4 teams
- Build cohorts of ~8 per year (2 from each EN, ES, FR and PT)
- Orientate editors in pairs
- Coordinate multi-lingual cohort meet-ups to build community (so that the 2023 cohort get to know each other, and benefit from networking/opportunities to collaborate within PH and beyond/learn from each other) -- The aim here is to develop longer-term relationships (at least 2 years) with editors, by giving them a fuller and more rewarding experience within our community. 
- Introduce a system of reviewing editorial teams annually, to see who still has capacity to commit, and who may wish to step down as an active member

Let's talk more about this at our one-to-one next week, and make a plan for the next phase of EN recruitment.

--

As we put these proposals into action, it's important to ensure we have at least minimum capacity across all teams. FR do not have this at the moment, so for within the 2022 cohort FR are recruiting 4 editors. 

- Orientation of the first FR pair will take place next week (29th March)
- Orientation of the second FR pair will take place in May/June (date TBC)

**Comment by hawc2** [comment]
@anisa-hawes this sounds great to me. As long as we do a wide editor call and ensure a large number of applications from diverse applicants, a rolling process of onboarding new editors is fine with me. 

What's more important is having a game plan and schedule. If the English team needs to subsist with its current level of editors for six months, that's fine. I just need to know how long we'll be at this capacity. So if we don't expect the first editors to be onboarded until July 2023, that gives me something to work with. 

If the current submission pattern for PH English continues, I will be open to putting a moratorium on new submissions, and/or setting up a submission period that recurs on an annual basis. The rolling submissions, when at a higher number than we have capacity to support, can cause a lot of stress and traffic jams in the publishing pipeline, and it also can lead to more contributors feeling annoyed/impatient with PH, especially when we are losing editors on active lessons. It would be easier if I could point to a publicly available policy when telling new contributors we might not be able to get to their lesson until 2024 or whenever. This is also where it comes in handy to have an up-to-date list of English editors on the website, and only include on that list people who are actively contributing to editing. Otherwise, people may look at our editorial board and think we have more capacity than we do. 

I agree with @acrymble that exit interviews would be good to standardize as part of the offboarding procedure for editors. Would that make sense for the ME to do those exit interviews, or should it be a more neutral third party?

**Comment by hawc2** [comment]
One additional thought/question on this issue. We've had editors step back from lessons they are currently in the process of editing. No other editors are available to pick up this slack. Do we have any policy for how to deal with this situation? I can tell the contributors their lesson will be delayed, but in an ideal world, there are some elements of the process as ME I could help move forward. For example, one lesson is at the stage of needing peer review. I could see it being the ME's job to step in to help move forward lessons in situations like this, contacting reviewers and getting the lesson under review. But from my conversations with the other journal's ME's, it sounds like we have a policy (which makes sense) that ME's should stay out of editing as much as possible so they can be neutral. Anyway, I'm just wondering if there's any wiggle room here, or if my hands are tied so to speak until we onboard more editors.

**Comment by anisa-hawes** [comment]
Thank you for these thoughts, @hawc2. 

When it comes to initiating a dialogue with editors who step down after ~less than a year/~editing only one lesson, I'd be happy to take that on as part of the workflow for off-boarding. I can devise a system for asking about their experiences on the project, and make it possible for a departing editor who communicates a specific concern to speak with one of our ombudspersons.

Let's revisit your question about how to best reallocate a lesson if an editor steps down mid-way through the process at our next Managing Editors' Meeting. It seems to me that this very much depends on the progress of the lesson, how much
the author has already invested, and whether reviewers are already involved. 

For now, and in this case, I think the most sensible option is to write to the author and explain the situation. You could consider providing a rough estimate of when you or another member of your (existing) team could take it on. Or, make a commitment to contact them again in ~2 months with an update on capacity.  After that, you could write a short statement/comment in the Issue to briefly state what is happening. Finally, either close the Issue (to be reopened at a later date) or label it as 'On Hold'.

Next steps:

- I'll draw up a draft schedule for the rolling recruitment programme, and share it with you + the other MEs
- You and I will meet for our one-to-one next week, and make a plan for the next phase of EN recruitment

I'm going to close this Issue now.
