### ISSUE TITLE
The parameter `{pretrained_param}` is deprecated in /en/lessons/computer-vision-deep-learning-pt1

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2901]
A reader has got in touch to report an error warning they encountered when working through the Kaggle notebook associated with:

Computer Vision for the Humanities: An Introduction to Deep Learning for Image Classification (Part 1)
/en/lessons/computer-vision-deep-learning-pt1

The error occurs at the section titled [Creating the model](https://www.kaggle.com/code/davanstrien/ph-computer-vision-tutorial-part-1-and-2?scriptVersionId=102447794#Creating-the-Model) and is associated with the function `vision_learner`. 

The full error reads: 

```
/opt/conda/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/opt/conda/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg) 
```

The reader explains that this is followed by a timeout error. They suspect that could be a firewall issue, but are unsure.

They also note that they are unable to switch accelerator from CPU to GPU [as described in the section titled Kaggle](https://programminghistorian.org/en/lessons/computer-vision-deep-learning-pt1#kaggle) because the accelerator option no longer exists in settings). Meanwhile their CPU shows 101%.  

I'm aware that the figure image which shows the Kaggle notebooks settings menu [has already been replaced once](https://github.com/programminghistorian/jekyll/issues/2754) since publication.

**Comment by hawc2** [comment]
@davanstrien I wonder if you might share any thoughts on this bug report we received for your lesson?

**Comment by davanstrien** [comment]
>/opt/conda/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/opt/conda/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg) 

This is only a warning, and the code will still run. I will see if this is going to get fixed upstream, but otherwise, I can pin the requirements in Kaggle to avoid readers seeing this warning in the future. 

>They also note that they are unable to switch accelerator from CPU to GPU [as described in the section titled Kaggle](https://programminghistorian.org/en/lessons/computer-vision-deep-learning-pt1#kaggle) because the accelerator option no longer exists in settings). Meanwhile their CPU shows 101%. 

I can't say for sure but it's likely they don't see this option because they haven't verified a mobile number with Kaggle yet. If you signup via a Google account, this won't be done by default. Kaggle doesn't ask you to do this, but it won't show the GPU options if this step hasn't been done. However, even with the GPU is active, the CPU is likely to be running at 100% since the CPUs on Kaggle aren't very powerful, and there is some processing happing in Python code that can't be offloaded to a GPU. This isn't a problem usually. 

As an alternative, Google Colab can also be used (https://github.com/davanstrien/Computer-Vision-for-the-Humanities-an-introduction-to-deep-learning-for-image-classification). This also requires a google account, but AFAIK doesn't do any other checks before giving access to a GPU accelerator.

**Comment by anisa-hawes** [comment]
Thank you, @davanstrien! This is useful information. I think we should try to specify the requirements within the lesson itself too, as we are directing readers from the lesson to the codebook (as I understand it). Indeed, the function `vision_learner` which our reader cited does not appear within the lesson code as published on this page [/en/lessons/computer-vision-deep-learning-pt1](https://programminghistorian.org/en/lessons/computer-vision-deep-learning-pt1), (or, at least, not that I have located). 

Let me know what you suggest the wording of the requirements/dependency statement could be? I'm happy to co-ordinate adding a warning/information box at a suitable point in the lesson.

@hawc2 this Issue feels to me as though it prompts a broader conversation within the team, about how we ensure the sustainability of codebooks that are hosted beyond our site. What do you think?

**Comment by davanstrien** [comment]
>Indeed, the function vision_learner which our reader cited does not appear within the lesson code as published on this page [/en/lessons/computer-vision-deep-learning-pt1](https://programminghistorian.org/en/lessons/computer-vision-deep-learning-pt1), (or, at least, not that I have located).

I've opened a PR to update the naming of this function https://github.com/programminghistorian/jekyll/pull/2910

> Let me know what you suggest the wording of the requirements/dependency statement could be? I'm happy to co-ordinate adding a warning/information box at a suitable point in the lesson.

I'm personally not sure it makes sense to specify the requirements in the lesson file since this pushes the burden of getting a working environment for the lesson onto the user, whereas, at the moment, both the Kaggle and Colab versions of the notebook run without the user having to know how to set up the environment themselves. These may occasionally require tweaking in the future, but this is preferable to leaving the user to battle with Python environments which can be challenging for deep-learning libraries.

**Comment by hawc2** [comment]
@davanstrien your note about the isues with Kaggle and Colab might be good to mention at the start of the notebook themselves. I agree this sort of secondary information about getting the web-based notebooks working doesn't make sense in the PH lesson in alot of detail, but it's possible a brief note about what readers should expect of those notebooks and their sustainability over time might be a good idea.

@anisa-hawes agreed its time for us to discuss as a team the sustainability of these cloud-based notebook environments. I think what @davanstrien has done here is a good model for what we would encourage others to do, but there's still some details/guidelines to iron out. It's going to be a constantly changing situation so there's only so much we'll be able to do to help readers and standardize how we handle this part of publishing code

**Comment by anisa-hawes** [comment]
Thank you for your thoughts @davanstrien and @hawc2.

I appreciate you preparing the update PR, Daniel. Our site is updated so frequently, that the forked branch your created is already behind our master branch so I've replicated these updates to computer-vision-deep-learning-pt1.md in PR #2919, replacing the function name `cnn_learner` with `vision_learner` throughout.

These wider conversations about sustainability and lessons written for use in notebook-environments are something that @hawc2 and I can take forwards in dialogue with the other Managing Editors and the Project Team.
