### ISSUE TITLE
Broken link report in Displaying a Georeferenced Map in KnightLab’s StoryMap JS

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2914]
I am reporting a broken/not working link within a lesson, reported by my colleague:  

- [ ] [Displaying a Georeferenced Map in KnightLab’s StoryMap JS](https://programminghistorian.org/en/lessons/displaying-georeferenced-map-knightlab-storymap-js)
- [ ] Checked on Safari and Chrome 
- [ ] The link is in Step 1: https://mapwarper.net/maps/tile/40217/%7Bz%7D/%7Bx%7D/%7By%7D.png
 
![Screenshot 2023-04-05 at 2 12 56 PM](https://user-images.githubusercontent.com/11022533/230167997-532c4c8d-e29e-4903-9277-21fdbf90ad94.png)

It doesn't seem to have a permalink attached to it either.

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. This is very strange, but I think remember something about this.... Let me check my notes and come back to you.

**Comment by anisa-hawes** [comment]
![Screenshot 2023-04-05 at 19 21 28](https://user-images.githubusercontent.com/87070441/230169860-8773900c-ccc6-4e5d-acdb-ad25edbbfe58.png)

Yes: I believe what is shown is only a template (example) of how the link would be formatted. Frustratingly, I can't locate my notes about this...

![Screenshot 2023-04-05 at 19 27 53](https://user-images.githubusercontent.com/87070441/230171429-e08d0292-d9da-49a5-883c-4b57d76b39d1.png)

In the .md it looks like this: `[https://mapwarper.net/maps/tile/40217/{z}/{x}/{y}.png](https://mapwarper.net/maps/tile/40217/{z}/{x}/{y}.png)`

But when we click or paste `https://mapwarper.net/maps/tile/40217/{z}/{x}/{y}.png` into our browser, the `%` signs and numbers automatically replace the special characters `{ }`, because they aren't valid in http.  

So maybe I should just remove the link? (so it isn't clickable)

@hawc2 do you by any chance remember how these Tiles (Google/OSM scheme) URLs were intended to work here?

**Comment by anisa-hawes** [comment]
Okay: it was a different lesson (Introduction to Map Warper /en/lessons/introduction-map-warper) that I was remembering. It featured this same link. At the time of publication, this link directed to a (very tiny) map tile image. I asked the author about it, because I'd noticed during copyediting that the linked image was so small I could almost not see it ! and then that the link generated a page error. In the end (on that occasion) we agreed to put the URL into `back ticks`.

You can read the exchange [here](https://github.com/programminghistorian/ph-submissions/issues/426#issuecomment-1263939384) and [here](https://github.com/programminghistorian/ph-submissions/issues/426#issuecomment-1265923114).

@hawc2 Are you able to advise? (Is this is an example of how the map tile URLs are formatted? Or is there an intended tile missing?)

**Comment by hawc2** [comment]
Yes I'm pretty sure that does not need to be encoded as an actual hyperlink in the markdown.

**Comment by jenniferisasi** [comment]
I have had time now to read through the lesson and, indeed, the sample URL being hyperlinked is quite confusing, for a few reasons: 
1. it gives the impression that the reader has to download something from it, not just because of the hyperlink but also because of the sentence "The one you will need for this tutorial is the Tiles (Google/OSM scheme) URL: [link]"
- [ ] "In this tutorial we will be using the Tiles (Google/OSM scheme) option with the help of an URL that follows the next order: [include link without hyperlink and explain right away what x, y and z are]
2. In Step 3, again the URL is hyperlinked (though it is much clearer that it only reflects a format) to note where the URL (from MapWarper) needs to go in StorymapsJS.
3. The sample map used in the lesson: 
- [ ] is introduced too late in the game, imho
- [ ] has no context
- [ ] as a visitor (not the creator in Map Warper) to the map on the David Rumsey Collection, I cannot seem to export the URL in said format so I cannot try the lesson without making my own map (I think?)

As a first time reader of this lesson, I find myself rather confused (and I've used StorymapsJS extensively); it seems to assume the reader has created a map in MapWarper (with the help of the lesson we have) in advanced, but it only suggests reading it because "If you haven’t yet created a georeferenced map, the Programming Historian lessons on [Georeferencing in QGIS 2.0](https://programminghistorian.org/lessons/georeferencing-qgis) and [Introduction to Map Warper](https://programminghistorian.org/en/lessons/introduction-map-warper) offer detailed tutorials". 

Thoughts?

**Comment by hawc2** [comment]
I don't have time at the moment to go back through this in detail but it is probably worth bringing the authors into the conversation and planning some revisions to the lesson. It was published before the Spanish translation of the Mapwarper lesson so some updates could be made to sync the two, as well as to clarify the issues @jenniferisasi identifies here

**Comment by anisa-hawes** [comment]
I've written to the authors for clarification about: 

- the Map Tile export URL associated with this lesson
- whether visitors to the map on the David Rumsey Collection can expect to be able to export the URL in the specified format or if it is only creators in Map Warper who can do so.  It may be worth us adding a note to the lesson here.

--

Meanwhile, I've generated a PR #2927 to remove the live hyperlink syntax from the Map Tile export URL. My sense is that I made an error here by formatting it as a link.

**Comment by anisa-hawes** [comment]
Apologies that I have left this Issue hanging. I wrote to the authors of the lesson and they agree that this URL should not be hyperlinked as it doesn't load in a web browser. They explained that it will only load in StoryMap JS or other GIS software. They tested the URL to ensure that it still loads in StoryMap JS and it does, so the URL is not broken.

The authors suggested an adjustment to line 45 for improved clarity, which I have implemented in PR #2977.

--

In relation to the David Rumsey Collection, the authors explained that this is an example only. If readers want to, they can download a scanned image of the historic map from David Rumsey’s website then upload it to Map Warper to geo-reference it. After that, they will be able to export the URL in the specified Tiles format, then load it into StoryMap JS.
