### ISSUE TITLE
can I add a eventContributor.yml file?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#314]
Related to the 'PH is People' post, I realised that we've failed to systematically keep track of people who contribute to physical events but not necessarily the editorial process. We've had a few workshops around the world now and it would be good, I think, to keep track of the people who helped organise at least.

http://programminghistorian.org/posts/ph-is-people

Are there any technical things I should beware of before starting a new yml file for this?

**Comment by wcaleb** [comment]
You can, but I'm not sure a YAML is needed. The main reason for the YAML directory is because someone listed there might need to appear several times in several different places on the site, and it makes sense not to have to hard-code their biographical information every time. It sounds like this will just be a single list in one place, so that programmatic feature might not be necessary.

**Comment by acrymble** [comment]
Thanks @wcaleb, very fair point. Do you have an opinion on this then? Should I hard-code on the project-team page?

**Comment by acrymble** [comment]
Ok, I've hard coded this on the project team page. @fredgibbs I don't know who's been involved in facilitating your event at UM. Could you add their names to the list?
