### ISSUE TITLE
Linking technical and conceptual vocabulary of the lessons between linguistic versions -- Humanistica2024 paper and more

### ISSUE THREAD

**Issue by matgille** [programminghistorian/jekyll#3146]
Dear all, 

I hope you're doing well. 

 I've been planning to work on linking the lessons in Programming Historian, and more specifically the. technical and conceptual vocabulary of the lessons between linguistic versions

The idea I have is to create a concordance table for certain selected terms, which would have a prescriptive value (like a sort of guide for translators), or even in the longer term a glossary that would define a given term in each language. The example that always comes to mind is that of "template" (for XSLT in particular), which is very difficult to translate into French (and Spanish, I think); this translation problem is a major obstacle to understanding how XSLT works, which has a very specific logic. The idea also originated in the Portuguese team, which has produced a translation table for technical terms ([https://github.com/programminghistorian/jekyll/wiki/Achieving-Sustainability-Agreed-terminology-PH-em-português](https://github.com/programminghistorian/jekyll/wiki/Achieving-Sustainability-Agreed-terminology-PH-em-portugu%C3%AAs)).

With a few members of the French team (@marie-flesch and @davvalent + @datalogism), we want to submit a paper to the Humanistica2024 conference, with a fairly short deadline (in 2 weeks) but requiring only a 750-word abstract to start with.

The idea would therefore be to produce or try to produce these tables automatically, by aligning the lessons using the most up-to-date alignment tools (word embeddings / sentence embeddings) -- that's something I'm working on for my postdoct, and it works quite well with historical states of languages --, and to try to use the conceptual terms identified in one of the languages to find the translations of these terms in the other languages (we could start using the table produced in Portuguese).  I think this could also give us an idea of the homogeneity of translations of technical and conceptual terms. There are 65 lessons that have at least one translation, so we have data and we should have results!

Are any of you interested in joining us? The paper will have to be in French, but our working language may well be English throughout the production process.

Matthias

**Comment by jenniferisasi** [comment]
Bonjour, Matthias et à tous! 

This is a very tempting project to work on as I have been, for quite some while now, pondering in many ways about the ways in which we have been translating in the ES journal (see [this](https://muse.jhu.edu/article/842253) for example) and I am sure @rivaquiroga will have something to say regarding her collaborative translation of R for Data Science as they developed a [vocabulary](https://github.com/cienciadedatos/documentacion-traduccion-r4ds/blob/master/orientaciones-traduccion.md) that we very frequently check on PH-ES and that I am sure you find useful. 

Not sure if I have enough time this semester to work a lot, but I would be happy to collaborate any way I can if it is useful and/or no one else on the Spanish team can join you. Also, sadly, I wouldn't be able to present in-person at Humanistica2024, nor in French 😅

**Comment by anisa-hawes** [comment]
Hello Matthias @matgille,

Thank you for sharing this idea with us! It sounds incredibly interesting and useful. @charlottejmc and I would be pleased to offer you support 🙂

**Comment by ericbrasiln** [comment]
Hello @matgille and colleagues!

The project is very interesting! I won't be able to participate directly in Humanistica2024 either, but I can contribute some insight from the experience of the Portuguese team.

In our case, we seek to standardize and facilitate translations and general understanding for speakers of the various "Portuguese" around the world, as some terms were incomprehensible depending on whether you were Brazilian or Portuguese, for example.

**Comment by rivaquiroga** [comment]
Hi @matgille! This looks great. 
Happy to contribute, although I don't think I'll be able to participate in-person at Humanistica 2024.
I'm ok reading in French, but I can't write 🥲 
Also, you might want to take a look to https://glosario.carpentries.org/ 👀

**Comment by matgille** [comment]
Thanks for the feedback and the links you've provided !! 

I have tons of other deadlines this week, I won't be able to work on this project before friday but I'll keep you informed. 

Our first draft is here:  https://annuel2.framapad.org/p/7szcmr270o-a5dt?lang=en
Please do not hesitate to participate and comment the notes we've been taking; and if you're interested in being on the paper, the fact you can't participate in person to the conference is not a problem I think. 

Best, 


Matthias

**Comment by matgille** [comment]
Small update: in the pad cited above I've put a link to an overleaf document (I don't put it here to avoid any trolling), feel free to participate. We can add you as author if you're interested.

Thank you again to all of you, the different glossaries and links you indicated are of great help, thank you very much. I didn't know the Carpentries project !

@ericbrasiln do you have some example of concepts/terms that would need a translation adapted to each variety of portuguese ? I would have the same question for you, @rivaquiroga and @jenniferisasi.  I can think of  the translation of computer into "computadora" in some countries of South America (at least, Argentina, maybe Uruguay too but idk)  and into "ordenador" in Spain... But this term wouldn't appear in the table, I guess, it's too simple. As for French, unfortunately we are not really educated to linguistic diversity and I don't have any example. We'll find out some examples with David !

**Comment by anisa-hawes** [comment]
Bonjour @matgille. How are you? 

I wondered if you managed to submit your proposal to the [Colloque Humanistica 2024](https://humanistica2024.sciencesconf.org/resource/page/id/2)? 

Please let us know if there's anything Charlotte and I can do to support your next steps.

Thank you,
Anisa

**Comment by jenniferisasi** [comment]
Sorry that I didn't see you comment/question last week @matgille! @anisa-hawes tells me you are working on it today again, with @charlottejmc looking at it. Would be happy to read an abstract in between my meetings though I don't know about time differences.

The example you propose has three varieties: la computadora (most of LatAm), el computador (Chile and Colombia per google), and el ordenador (Spain). El móvil y el celular (mobile phones). 


btw I frequently use https://iate.europa.eu/home to check for terminologies EN-ES(Spain) and then I search for/confirm the word in Latin America, because we have more or less agreed to using that variety when possible.

**Comment by matgille** [comment]
Thanks ! I think we will submit the abstract on Monday, you have some time to comment and/or modifiy text if needed !

Best, 


Matthias

**Comment by rivaquiroga** [comment]
Hi @matgille! I recall two other examples of variety-related issues when translating or writing in Spanish. 
1. The author of the TEI lesson (Colombian) translated the TEI term "milestone" as "mojón." The problem is that for people in the south of South America (like me), the only meaning of "mojón" we use is _stool_ 💩 (and it's not very formal). So, finally, we decided to use "hito".
In this case, it was not a translated lesson from English. It was an original lesson about a tool whose documentation has been primarily available in English.
2. The translation of "cheatsheet" is different in every Spanish-speaking country. So in every R lesson that mentions this resource: https://posit.co/resources/cheatsheets/ we have to agree to translate it as "hoja de referencia". For example, in Spain a cheatsheet is called "chuleta", in Chile "torpedo", in Argentina "machete", in Mexico "acordeón", etc.


P.S. @jenniferisasi is right about the three varieties of _computer_.  For me is "el computador" 💻

**Comment by matgille** [comment]
Great ! Thanks, Riva.  That will be great examples to add to the abtract.

Have you something to recommend/comment about the document more generally ? Did we miss something important ?

**Comment by jenniferisasi** [comment]
> P.S. @jenniferisasi is right about the three varieties of _computer_. For me is "el computador" 💻

Thanks for confirming what google told me :) What about the laptop? I say "el portátil". 

I had always imagined that "chuleta" was not universal so this is very interesting. I bet we can think of more examples that show up on lessons. 

@matgille I am going to read the document today - but wow the magic on Overleaf with LaTex 🤓 If I think of more terms, I will edit this comment: 
- "to run the code" - ejecutar el código, correr el código
- "to apply" - aplicar, solicitar, postularse
- "script" - usually not translated, but could also be "secuencia de comandos"

**Comment by jenniferisasi** [comment]
I've now read the proposal and it looks great! I must say it is much more detailed than what I am used to submitting or evaluating for conference proposals so I want to congratulate you all. Here are a few suggestions of things to include and I'll copy them on the document with ideas: 

1.4.2 Référentiels linguistiques existants
-  IATE (Interactive Terminology for Europe) https://iate.europa.eu/home as another (bigger) resource, that can filter to "information technology and data processing [EDUCATION AND COMMUNICATIONS]" or/and "technology and technical regulations [PRODUCTION, TECHNOLOGY AND RESEARCH]" 
- And yes, I would mention "R para ciencias de datos" as you suggest on note 4
2.2 Identification des concepts
- On the BERT family, we have BERTin for Spanish https://huggingface.co/bertin-project (Never used it but in case it is useful as an additional model to EN and FR)

A references from the PT team, that I would cite, is Daniel Alves, ‘[Ensinar Humanidades Digitais sem as Humanidades Digitais: um olhar a partir das licenciaturas em História](https://novaresearch.unl.pt/files/32228034/Ensinar_Humanidades_Digitais.pdf)’, Revista EducaOnline, v. 15, n. 2 (2021). He argues (in the last part) about the importance of having these resources in Portuguese (very much, on ones own language) for teaching the methods: "Uma vantagem para quem vai aprender, mas também para quem vai ensinar, podendo todos concentrar-se numa utilização sistemática e crítica das lições sem a preocupação de as traduzir ou de poderem ser mal-interpretadas" (p. 20)

I wanted to also mention this resource of TEI in Spanish, in which translation pays an important role and from which we could draw some information as well: https://tthub.io (by Alles-Torrent and del Rio Rained, who you already cite)

Also, I already see a PH lesson with the method used to do the paper? :) 

I will stay attentive during the weekend to help as much as possible with the proposal, as I am really interested in participating.

**Comment by ericbrasiln** [comment]
Hi @matgille and colleagues

Firstly, apologies for the delay. The academic semester started this week, which took up a lot of my time.

I've listed some of the most prominent examples in the Portuguese case, where we had to deliberate on which term would be most comprehensible to Portuguese speakers.

## File

- `Ficheiro` in pt-PT and `arquivo` in pt-BR.

In this case we opted to keep `ficheiro`, because `arquivo` in Portugal has the idea of an archival institution or a collection; and `ficheiro` in Brazil, although not used, can easily be understood as `file`.

## Screenshot

`Captura de Ecrã` in pt-PT and `Captura de Tela` in pt-BR

In this case we chose to keep `Captura de Tela`, as in pt-BR. Because the word `Ecrã` is not used in Brazil.

## Research (academic) and Researcher

`Investigação` and `Investigador` in pt-PT and `Pesquisa` and `Pesquisador` in pt-BR

Here we have also opted to keep the pt-BR version, as `investigação` in Brazil has a broader meaning and is rarely used for scientific or academic research. `Investigador` in Brazil is mostly used for police officers.

**Comment by rivaquiroga** [comment]
@matgille: the proposal looks great! I left a comment directly on the overleaf doc

**Comment by matgille** [comment]
Many thanks for your feedback ! 

I'll submit in the afternoon, and I will integrate your suggestions. 


Best, 


Matthias

**Comment by matgille** [comment]
@jenniferisasi @rivaquiroga many thanks for your remarks, I've read them and I'll try to answer this afternoon

**Comment by jenniferisasi** [comment]
Merci @matgille!

**Comment by matgille** [comment]
The proposition has been submitted !

Thank you all ! Should we create a new discord server to have a specific space to work on the paper?

**Comment by rivaquiroga** [comment]
Thanks!! 🎉 
Sure. Could be a new channel on the PH Discord

**Comment by anisa-hawes** [comment]
Congratulations on submitting this proposal @matgille! ✨ And thanks to all who have contributed here. 

I've created a Discord channel on our PH Discord Server to continue this conversation: **#colloque-humanistica-conf**. All in the Project Team are welcome to join if they'd like to contribute!

**Comment by amsichani** [comment]
Hi @matgille and all , this is terrific news ! Well done !  I won't be able to participate directly in Humanistica2024 either, but I am more than happy to contribute to this and to any future outputs from it - its such an interesting piece of work!
