### ISSUE TITLE
Revisiting our editorial policy on the use of Wikipedia links in lessons

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3207]
I am opening this Issue to continue a discussion which [originated within an exchange](https://github.com/programminghistorian/ph-submissions/pull/601) following Copyediting of a forthcoming EN lesson. As part of this edit, we suggested the addition of some Wikipedia links (as we do regularly, and have always done) to provide readers with quick access to definitions of terms and concepts that are mentioned. 

However, in dialogue with authors @rmostern and @grunewas, we learned that for some academics (specifically history departments in the United States) the integration of Wikipedia links is considered unprofessional. Critically, the authors expressed that this practice would cause them to rethink publishing with us. 

I expressed an understanding that while it isn't usual practice to reference Wikipedia in articles, as a scholarly form, we (as a publisher) have thought about lessons differently. I also clarified that the suggested additions were inline hyperlinks rather than additional bibliography items. But with respect for the authors' request, I removed the links in question and tagged @hawc2 to ensure he knew why this has been done. 

--

I think this is a valuable opportunity to revisit our policy on Wikipedia links, and agree upon our working practices going forwards to clarify what editors and copyeditors may suggest, and what authors/translators can expect from us.

--

Within the [Write for a Global Audience section](https://programminghistorian.org/en/author-guidelines#write-for-a-global-audience) of our author guidelines, we set out our position in the following bullet points:

>**Technical Terms**: should always be linked to Wikipedia or a suitably reliable dictionary or sustainable website in the first instance. A technical term is any word that a person on the street may not know or understand.
>
>**Cultural References**: mentions of persons, organisations, or historical details should always come with contextual information. Assume no prior knowledge, even of widely known cultural references (eg, the Beatles). Use generic terms rather than trademarks (tissue rather than Kleenex). Links to Wikipedia should be used liberally. Be aware that historical events often have different names in different countries.

--

I'd particularly like to invite the thoughts of our Managing Editors, @hawc2, @jenniferisasi, @ericbrasiln and @marie-flesch. I am grateful for the contributions and perspectives of @rmostern and @grunewas.

**Comment by hawc2** [comment]
I'd be curious to hear people's opinions on this issue. Two immediate questions that I have:
1) Can examples be given where a peer-reviewed article that cited wikipedia was viewed as less professional and damaged the scholars' reputation? Are there real cases where a tenure-track professor's tenure process was imperiled by an article that cited wikipedia according to the journal's conventions?
2) What other options are there for citations referring to relatively new forms of technology? Lots of software, tools, algorithms, packages, methods, are so new that there aren't standard encyclopedias to cite, and most articles about those methods are likely to either be grey matter, blog posts, or highly specialized academic articles. Wikipedia often is a neutral place to provide citations for this type of emerging concept, and since Wikipedia is updated often, it can stay relevant in the future. I can see how wikipedia posts to established historical events may be unnecessary when other sources are available and easier to use, but for alot of generic concepts and alot of technology I'm not sure what would be a better alternative.

**Comment by scottkleinman** [comment]
I can't think of any examples of a tenure process being imperilled by a Wikipedia citation. As you say, there are reasons why Wikipedia should be cited in some circumstances. Perhaps it would be useful to craft an editorial statement on when PH considers Wikipedia posts appropriate, which tenure candidates can present to committees.

That said, it seems to me that most PH tutorials link to Wikipedia to define technical terms when the need to do so is deemed outwith the scope of the tutorial's discussion. This is a convenience for our particular audience who need a fast reference and may not have access to traditional disciplinary scholarly discussions. Any complaints about Wikipedia citations may be a proxy for complaints about the target audience of the publication. I'm not sure what, if anything, we can do about that...

**Comment by rmostern** [comment]
As someone who has been involved in many tenure decisions, I can say that I think it would be highly unlikely for one to spell out "we're not tenuring this person because of a Wikipedia reference," and even more unlikely that such an assessment would become public.  However, it is quite routine, at least in US history departments, for committees to spend a lot of time evaluating whether candidate files reflect disciplinary standards of scholarly rigor overall.  As an author, I've had an editor demand that I remove a wikipedia citation from an article.  As a teacher, given the standing of wikipedia in the field, I request that my students not include wikipedia citations in their submitted work.  I warmly advise them to use wikipedia to get oriented to a topic and to get started on a bibliography, but not to cite it.  This is typical (in fact more friendly to wikipedia than is typical) among US historians.

**Comment by rmostern** [comment]
The above is my response to the request for contextual information in the above comments. My coauthor @grunewas may have more to add.  Beyond that, I would say that a hallmark of good writing - and the PH editorial process has been exemplary in this regard - is that all relevant terms are defined within the article itself.  In my opinion, it undercuts the author's authority and craft to add links to a crowdsourced encyclopedia rather than having confidence that the author has defined terms effectively.  In any event, if a reader is confused or curious about any term, wikipedia and the rest of the internet is just a search away, link or no link.

**Comment by rmostern** [comment]
Finally, I think there may be a compromise solution at hand, which is for PH articles to include a Glossary section at the end with keywords and links, which would make links to wikipedia easily available if the editorial team thinks that's desirable, but which clearly offsets those links from the authored part of the text.

**Comment by jenniferisasi** [comment]
Hi all! I would like to add my view on this, specially adding to @scottkleinman point here:

> This is a convenience for our particular audience who need a fast reference and may not have access to traditional disciplinary scholarly discussions. Any complaints about Wikipedia citations may be a proxy for complaints about the target audience of the publication. I'm not sure what, if anything, we can do about that...

1. A link to a Wikipedia article on a term that is not discussed in the lessons not only gives a fast reference in general, but potentially allows our global audience to access the definitions/backgrounds/etc. of the term in their own language, furthering the accessibility that we seek on PH.
2. The target audience is global in the sense of people located all over the world, but also global in the sense of capacities, knowledges, technical infrastructure levels, interests, a multiplicity of career fields, etc. Links to Wikipedia (that is in most cases not cited/referenced in the bibliographic section of the lessons) opens the scope of readability further for all our readers. 

Looking forward to reading what others think.

I forgot before: I see how adding the links by editor or copy editor in the copy edit phase might be a tad late in the process, so I wouldn't mind having a check-up for this earlier in the editing process.

**Comment by hawc2** [comment]
I found this interesting article, "A Study of Citations to Wikipedia in Scholarly Publications," published way back in 2016. Would be great to find a more recent study, but even this one is very illuminating, including the ways it challenges assumptions about where wikipedia gets cited most often in academic journals: https://www.tandfonline.com/doi/full/10.1080/0194262X.2016.1206052

**Comment by grunewas** [comment]
I can't speak for any other institutions, but in my case my department
chair said it would not be a good idea to have links to Wikipedia in
publications in my tenure and promotion portfolio. It is possible that he
was being overly cautious. However, given that I want to advance my career,
I took this as a warning. There are still many skeptics of digital tools,
methods, and projects in US based history programs.

I also personally don't like Wikipedia as a linked source for the same
reasons that Ruth pointed out above.

I understand the ethos of linking to something that is stable and that also
has the ability to rapidly provide elaboration in a different language than
that of the lesson publication. However, I think the addition of links for
technological terms should be done in conversation with the authors as part
of the publication workflow. Identify which terms have not been properly
defined and then ask the authors to revise the prose to define them or
provide links for further information elsewhere.

In the case of the article I worked on with Ruth, it was troubling to see a
link to a technical term in Wikipedia despite that very sentence defining
the term with references to traditional scholarly publications to back up
the definition in that section. I also found an instance where the provided
Wikipedia link was an incorrect definition for a technical term elsewhere
in the article. The author(s) of an article should be tasked with finding
accurate sources and definitions to advance the tutorials given that they
are presumed to be experts in a particular tool or method.

All this being said, though, I don't think there needs to be a major change
to the contributor guidelines, which already stipulate the use of Wikipedia
OR another reputable or sustainable source. Different authors come from
different disciplines and institutional bases. Each one might have
different opinions about Wikipedia. As long as the authors are involved in
a conversation about the process of defining the technical terms and
selecting the links, it shouldn't be a problem.

**Comment by adamcrymble** [comment]
I think the editors have expressed very well why these links to Wikipedia are so valuable to our readers and for sustainability purposes.

I'd like to point out two things.

1. These aren't references and aren't included in a works cited list. They're inline links for people who need additional information. I don't know the author's lesson, but some lessons have a lot of technical terms and defining them would significantly increase the length and reduce the readability of the text for a typical reader. It's also really difficult to define some technical terms - 'if statement', etc. I'm also not sure what scholarly paper you'd cite in your definition of an 'if statement'. If authors want to suggest links instead to the dictionary, that's fine, if they do the work to find them. I don't suggest we make that any more clear because this is the first time in a decade anyone's had a concern and I don't think that's evidence of a wide problem.
2. If authors choose not to publish with us because of our editorial policies, that's their choice. It's not our job to create a publication that everyone thinks is perfect in every way. No matter what we choose, someone will always think it's not good enough, and we need to be confident saying no to requests rather than always trying to tweak a guideline or change a policy at our own expense, because we have finite resources.

**Comment by hawc2** [comment]
Thanks @adamcrymble. I agree, and in particular with #2. 

One thing I wanted to flag is that whatever we decide, it is not a solution to simply remove the Wikipedia links and leave nothing in their place. This was done recently for the Gazateer lesson at the time of publication, which prompted this issue ticket. I don't think it was the right decision to simply remove and not replace those links.

As Adam points out, these are not the same as normal references, but rather 'inline links.' In my opinion, reading the Gazateer lesson now, it seems short on these in-line links for important concepts and terms, and the reading experience is less pleasant for me than other PH lessons where I see the difficult terms standing out on the page as links which I can easily access at the click of a button. It is important that PH communicates to the reader that we are aware these terms are difficult, and that is what these links serve to do, providing a helpful pointer in the process to a useful external explanation. In addition, by removing links from one lesson and not the others, it just makes the journal as a whole look less consistent. 

I think we all agree we should be leveraging the power of digital publishing on the web by using hyperlinks. Going forward, I would advocate that if for whatever reason it is decided that 'wikipedia' links are not the best fit for any given link, when a link is requested and/or suggested by the ME, the Editor, or the Publishing Manager, the author should be responsible for finding an appropriate alternate link to Wikipedia to use. Publication should be dependant on the author doing this work.

**Comment by rivaquiroga** [comment]
According to our author guidelines, it is clear that:

1. Links to technical terms are a requirement for publishing a lesson; they are not optional.
2. Wikipedia is suggested, but authors can choose other suitable reliable dictionaries or websites.
3. Adding them is the responsibility of authors (which is why this is included in the Author Guidelines).

What this particular case shows us is that at some point we stopped enforcing this requirement during the reviewing process and started placing the burden on the publishing team. 
I don't think there's any new decision to make here except to align with our past decisions (reflected in our guidelines).

**Comment by rmostern** [comment]
@rivaquiroga 's point makes a lot of sense to me.  @grunewas and I were taken aback when the links were added late in the process, and by the publishing team, without involving us as authors.  If we had been reminded much earlier in the process that PH expected us to add appropriate and reliable links for key terms, we would have been happy to do it.

**Comment by hawc2** [comment]
We can definitely be more upfront with authors about how they should be linking, and encourage them to do so from the start. 

But there will still be final stages of review by the Managing Editor, Publishing Manager, and the copyeditor, where additional links will be requested, and authors will have to be prepared to either accept the wikipedia links we default to, or provide alternatives where wikipedia isn't satisfactory. 

This is a normal part of the final stages of the revision process; it's unavoidable that links will be identified as necessary after all other edits have been made. We should make it clear to authors that they should expect at the later stages of publication they may still be required to do this sort of work based on our final review.

**Comment by anisa-hawes** [comment]
Thanks to all who have contributed to this discussion. I think we are in agreement that no changes are required to our policy on the use of Wikipedia links in lessons. We share collective responsibility for shaping resources that are accessible to our global readership of diverse learners. 

A summary of my understandings from the points contributed: 

- Authors are required to include links that support readers to understand key specialist or technical terms. Authors may choose links to Wikipedia articles, alternative online encyclopaedias, or other technical dictionaries.

- Editors are encouraged to help authors by highlighting points where links that support readers to understand key specialist or technical terms would be usefully added (as appropriate to a lesson's difficulty level).

- Copyeditors may suggest points where links that support readers to understand key specialist or technical terms could be usefully added. All copyedits are shared in `rich diff` so that all suggested changes are transparent, edits can be discussed openly, and authors have the opportunity to provide links to Wikipedia articles, alternative online encyclopaedias, or other technical dictionaries.

- In their final review, Managing Editors may highlight points where links that support readers to understand key specialist or technical terms are required. Authors will have the opportunity to provide links to Wikipedia articles, alternative online encyclopaedias, or other technical dictionaries.
