### ISSUE TITLE
German / French for Gazetteers?

### ISSUE THREAD

**Issue by Ape3** [programminghistorian/jekyll#325]
Studying "Using Gazetteers to Extract Sets of Keywords from Free-Flowing Texts" on Windows 10 and with Python 3.6 I was so far successfull by building my own gazetteer and by loading the example text. However, as soon as I try to work with the German and French caracter sets I get somehow useless code.'ï»¿bã¤rn' for Bärn or 'genã¨ve' for Genève.

I wonder if that is a fundamental problem limiting the use of the gazetteer to English texts or how I could overcome that problem.

As I'm the first time on this platform I just hope I have described my problem the right way.

**Comment by acrymble** [comment]
This is almost certainly a problem with character encoding. As I mentioned to you in email you have to make sure that the inputs are in UTF-8 format, as this is what the software is configured to read. There are many ways to save a letter in a computer's memory. The letter A may look the same to us no matter which way it's saved, but that's not how the computer sees it.

I'm not an expert on character encoding, because I only ever work with English texts. But that's what you'll have to look into to solve your specific problem.

**Comment by acrymble** [comment]
Alternatively, you could do a find-replace on your input text and change any accented characters to standard English unaccented characters. That might let you find the matches you're after.

If you try this, make sure you're searching on a copy of your texts; not the original.

**Comment by acrymble** [comment]
If anyone in the community has a good character encoding solution for python (converting text from unicode to UTF, etc) please let me know and I'll add a quick note to update this lesson.

**Comment by vgayolrs** [comment]
@Ape3 : Maybe you can use the solution we applied in Python lessons in Spanish. Put, at the beginning of your program-file.py:

```pyton
# -*- coding: utf-8 -*-
```

Don't forget the hash... Tell us if that resolves something.

**Comment by acrymble** [comment]
@Ape3 can you let us know if this fixes your problem? If we don't hear, I'll have to assume you've moved on and we'll close this ticket.
