### ISSUE TITLE
404 Error for CSV files on Geocoding Historical Data

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#328]
It looks like a recent fix to Geocoding Historical Data using QGIS broke the links to the CSV files. I will correct that first one, as that just seems to be a name change error. However, I am not sure where the second file (AlumniCounties.csv) is.

http://programminghistorian.org/lessons/geocoding-qgis

**Comment by acrymble** [comment]
Thanks, this wasn't moved over from the submission site. Fixed now.

**Comment by acrymble** [comment]
I just had to re-upload this file and the data file for http://programminghistorian.org/lessons/extracting-keywords (which got renamed above). It should all be working now, but it raises issues of assets getting muddled because chances are we won't notice for weeks/ever. I don't suppose we've got a good way to solve this, but it would be good perhaps to have details of all assets associated with a lesson to prevent this problem in future.
