### ISSUE TITLE
Editorial Meeting Agenda 24-02-2017

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#335]
Please suggest any topics you think we should discuss at our editorial call.

Some suggestions from me:

* New Lesson page #193 #333 - @amandavisconti lead.
* Various CSS/styling updates #130 #273 #303 #308 #321 - @fredgibbs lead.
* Spanish lessons soft-launch #330 #332 #333 - @mariajoafana @arojascastro @vgayolrs leads.
* New editorial applications @acrymble lead.

Other ideas?

**Comment by wcaleb** [comment]
Just putting her for reference that while we do have a rough version of some of the Spanish lessons working, we may want to hold off on implementing bigger changes suggested in #322 until the changes that @amandavisconti and @fredgibbs are working on are incorporated into the live site.

For example, if we switch to working with collections, as @mdlincoln suggested in #322, my initial testing suggests that could break some things and would need to be paired with an overhaul of our Jekyll templates (since I think that references to Liquid variables in the templates would need to change). Perhaps it would make sense to try bigger changes like the ones Fred is working on (and the `collections` implementation of the Spanish site) on Amanda's development repo, so that we can see how it works over there before pulling everything into the live repo and spamming our RSS subscribers (as I fear I may have inadvertently done earlier today!).

In the meantime, holding off on further changes means that not everything is working quite yet on the live Spanish pages, but I guess that's why it's a "soft" launch!

**Comment by jerielizabeth** [comment]
Hi all,

Since I won't be able to attend tomorrow, a couple of thoughts from my side of things:  

I have received only one response to the call for editors and one response to the call for lessons (Spatial Cluster Analysis), both of which I circulated on the google list (let me know if there are any questions on those.) 

In terms of the style updates, it looks like the user testing generated some really useful feedback and I look forward to seeing the next iteration! Thank you, @amandavisconti and @fredgibbs, for all your work!

One thing to add to the CSS/redesign conversation is how to acknowledge any subsequent contributors to different lessons, per #304. I will be working on outlining how people might submit contributions to existing lessons as soon as I can (sorry -- I've been slammed with dissertation-related work of late). If not this meeting, perhaps we can add that to the agenda for next month. 

Thanks, all!

**Comment by ianmilligan1** [comment]
I'm co-hosting an event at Internet Archive today/tomorrow.. Friday is mostly small groups working on projects, kicking off at 9am, so I am pretty sure I'll be able to hang out in a corner and call in. But I might be a few minutes late in case of logistical issues.

I don't have too many thoughts, but some updates. The last two months have been challenging workload wise. 😫

**Comment by vgayolrs** [comment]
Hi everybody...! I'm terrible sorry.... This Friday I have two academic activities that could not be scheduled for another date (15:00 & 17:30 London time). But in the Spanish team, - @mariajoafana  @arojascastro  and I - we are working hard to give you this Friday an idea of the progress. All the best!

**Comment by acrymble** [comment]
@mariajoafana and @arojascastro to update the spanish lessons page for soft launch next week. And to provide a blog post / blog.md translation to advertise. They are going to make lots of tickets when they notice things we need to fix. We expect there will be lots of small things.

**Comment by acrymble** [comment]
@fredgibbs reported on his tinkering with our css and layouts. It's been suggested that he make a new ticket that outlines what he's working on, as there was some confusion. This mostly affects streamlining rather than design. He's hoping to launch some of the updates incrementally before the next call.

@amandavisconti is going to work ahead on the revisions to the lessons page as per the user feedback. She hopes to do this before the next call.

@acrymble updated on new editor responses. To follow up as needed.

New ticket #339 started to discuss boilerplate text for keeping track of proposed lessons. Please contribute.

**Comment by wcaleb** [comment]
I worked on a refactoring of the layouts based on @mdlincoln suggestions in #324  and also created the language snippets file we discussed. See https://github.com/programminghistorian/jekyll/commit/6e12c50d43fcc0d3de546dccbeeb986d23bfb0f5.

@fredgibbs @amandavisconti Take note of new templating logic. Using the "defaults" variable setting in the `_config.yml` makes me think we might not need to use collections after all, and Amanda you might also look to see if "defaults" in the config file would accomplish everything you need, too, without having to turn `lessons` into `_lessons`. Just a thought.

@mariajoafana @arojascastro @vgayolrs I translated "Reviewed by" as "Revisado por" but let me know if a different translation would be better. I also noted that "Give Feedback" needs to be translated in `_includes/footer.html`.

**Comment by wcaleb** [comment]
Also another follow-up to our discussion about the `redirect_from` field in the translated lessons' YAML headers. Another reason we need to be able to connect the English lesson to the translated version is because of the way our `images` directory is structured (images for a particular lesson are in a subdirectory with the English slug). Our `figure.html` include was using the English page URL to find the images, which is why images in the Spanish lessons were broken. I've fixed this for the moment in https://github.com/programminghistorian/jekyll/commit/6ad42814c3fa32a72ce7d06939d45278b686dceb, which uses the `redirect_from` value to figure out where the images are. Just flagging this because if we implement a different solution (like a `_data` file that matches English slugs to Spanish ones), we will have to adjust this figure include.

**Comment by vgayolrs** [comment]
@wcaleb : "revisado" is fine! Thanks.
