### ISSUE TITLE
Potential issue with Setting Up an Integrated Development Environment for Python (Windows)

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#3396]
I have a report that this https://programminghistorian.org/en/lessons/windows-installation article doesn't work. I'm not totally sure what the issue is (I was told it second hand) but it may be that the article suggets learners use Komodo Edit when they need Komodo IDE. 

I have also marked this article for possible retirement as it does not make a clear methodological contribution, which - as @anisa-hawes is aware, though I appreciate this hasn't been communicated to MEs yet @hawc2 @jenniferisasi @marie-flesch @ericbrasiln - is a threshold the publisher like to introduce for lesson maintenance given that our publishing estate is now very large and we do not have sufficient resources to fix issues with lessons that replicate information easily found elsewhere or through AI/LLM pair programming (which may mean, that in some cases EN articles are retired whilst ES/PT/FR articles stay live).

**Comment by hawc2** [comment]
@drjwbaker this sounds good to me, I agree lessons like these are best to retire at this point unless they are fully functional and fill a special niche not otherwise available on the web

**Comment by drjwbaker** [comment]
Thanks @hawc2 - I may borrow that phrasing!

**Comment by charlottejmc** [comment]
Hi @drjwbaker,

Thank you very much for passing on this report. From a first look through, I think one of the issues may be that downloading Komodo Edit is not as straightforward anymore. The link given in the lesson ("You can download a copy from the Komodo Edit website <http://www.activestate.com/komodo-edit>") just redirects to a comparison between Komodo Edit and Komodo IDE: <https://www.activestate.com/products/komodo-edit/>. 

I tried to download Komodo Edit by following a series of (relatively unintuitive) links that led me to [this page](https://downloads.activestate.com/Komodo/releases/12.0.1/index.html), where I imagine the correct link might be `Komodo-Edit-12.0.1-18441.msi`. (A quick Google search told me that `.msi` indicates a Microsoft installation file (so this would be the right link for Windows) but, again, this wouldn't be very intuitive for a total beginner.)

Another workaround I found was through the [OpenKomodoIDE GitHub repo](https://github.com/ActiveState/OpenKomodoIDE) > Installers > `Komodo-Edit-12.0.1-18441.msi`.

In the [Mac version of this lesson](https://programminghistorian.org/en/lessons/mac-installation), we replaced the instructions for Komodo Edit with instructions for BBEdit and Sublime Text. This was because Komodo Edit is unstable on Mac – but it's also being retired by the developers more generally, and is probably not the best option out there anymore.

We could either:
- Make adjustments to the lesson so it uses another text editor instead
- Follow through with the retirement of the lesson altogether, if this seems more appropriate to you @hawc2

**Comment by drjwbaker** [comment]
@charlottejmc - thanks for picking this up. If making adjustment is a quick job, please go ahead as I think we'd always rather have functioning articles. Conversation about retirement is a bigger issue that would take longer to work through.

As a related side note, do we have a generic banner for articles we know do not work fully but are working on resolving? (that as, as we work through options, including possible retirement) I know we have flagged specific articles, like the Old Bailey Online ones, as having issues, but it strikes me that step 1 of the maintenance process should be a flag an article as under maintenance so readers know what to expect (but maybe we do and I missed that we do!)

**Comment by charlottejmc** [comment]
Hi @drjwbaker, our [Lesson Maintenance Workflow](https://github.com/programminghistorian/jekyll/wiki/Maintenance-Workflow) mentions adding a warning box to the lesson _if we cannot identify an immediate fix_. However, this workflow is not perfect, as every situation is slightly different and it's not always as easy as just following these steps.

We could work on a general warning message, but we do tend to tailor them in order to give readers an idea of what might go wrong, why, and how they could potentially work around it. 

In the case of this lesson, I would say the immediate, quick fix would be to edit the links to the Komodo Edit installer. I'm happy to work on this now. However, we're not sure here whether this would fully solve the problem, since we don't know whether the user had an issue with Komodo Edit in general. If that's the case, editing the lesson to centre it around a different text editor (perhaps BBEdit or Sublime Text, as with the Mac installation) would be a slightly more time-consuming task.

Unfortunately I'm working on a Mac, so I can't make any Windows-specific tests at the moment. It would be great if we could get a bit more detail on whether Komodo Edit does work well for users!

**Comment by drjwbaker** [comment]
@charlottejmc Okay. Thanks for clarifying on the workflow point. I'll pick up with @anisa-hawes, as  from a user experience perspective my view would be a holding message of something like 'This article is under maintenance' would be good practice to use in most cases.

On this article, I agree to edit links a quick fix. From the conversation I had with a colleague, it sounds as though the person who couldn't make this work got confused about what to install as the link we have no longer points to quite the same thing.

**Comment by anisa-hawes** [comment]
Thank you, @charlottejmc. I think the changes you've prepared in #3401 are very clear.

Thank you, @drjwbaker. I think your idea of adding a general interim banner is a good one which we can create for the future.
