### ISSUE TITLE
way to validate yamls?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#340]
It's obviously really easy to make mistakes in our lesson YAML metadata blocks. If you look at the two lessons below, the first uses 'reviewer' to list the editor, and the second uses an 'editor' tag for the same.

https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/topic-modeling-and-mallet.md
https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/editing-audio-with-audacity.md

Is there a way we can validate these before publication somehow so that editors are prompted when they may have made a mistake? Consistency across lessons is obviously what we're aiming for.

**Comment by wcaleb** [comment]
I'm not sure there is a way to do this: maybe there is if you are trying to build the site locally, but I don't know of a solution that would also prompt editors if they are making edits here on GitHub Pages. In this case, I'm assuming we should fix the one that uses an "editor" tag and just include her within the reviewers?

**Comment by jerielizabeth** [comment]
We will need to update the editor guidelines line (http://programminghistorian.org/editor-guidelines#3-add-reviewers-and-editors-to-the-yaml-file) then as well. 

I thought we had decided for clarity's sake to give editors a separate key, so that we could isolate the data in the future if we wanted. I am happy to fix the lesson if the consensus is to include editors as reviewers.

**Comment by wcaleb** [comment]
@jerielizabeth Now that you mention it, I have a vague memory of our discussing that as well. I think we could easily adjust the `include` so that it combines editors and reviewers.

**Comment by wcaleb** [comment]
Aha. The reason I have a vague memory is because ... [I suggested it!](https://github.com/programminghistorian/jekyll/issues/244#issuecomment-229091091) :-P

So what we really need is a new ticket for going through and breaking the "editor" out from the "reviewers" on all the lessons and adjusting the layout accordingly, if in fact we want to stick to the decision we made last summer.

**Comment by acrymble** [comment]
I've opened a new ticket for this #370
