### ISSUE TITLE
Adding gallery images to Python lesson directory in Spanish site 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#350]
I'm trying to figure out how to do this. In addition to adding the images to each Python lesson some css changes need to be made so it looks exactly like the English site. I was going to copy an paste the code from the English Python lesson directory into this file jekyll/es/indice-de-lecciones.md
Is this the file that I should be modifying? I don't want to mess anything up

**Comment by vgayolrs** [comment]
I will do it.

**Comment by fredgibbs** [comment]
do we have two efforts working on the lessons page at once, @mariajoafana and @amandavisconti?

did we decide which will launch first?

**Comment by fredgibbs** [comment]
if we are more or less duplicating the code of the existing english lessons page, we should spend minimal time on that because i have been waiting to re-style that after the new lessons page is set. i will also refactor the page so that we don't have duplicate code for each language.

**Comment by vgayolrs** [comment]
no @fredgibbs : it is just to update the Spanish version to make it like the English one.
ADD: sorry, I didn't see your last post. That's wonderful. So, how do we proceed?

**Comment by fredgibbs** [comment]
right, but the english one is about to change with category functionality and so on, so the spanish one will need to be revised again. maybe the new lessons page is still far enough away that it doesn't matter, but i wasn't sure what the timeline is.

**Comment by wcaleb** [comment]
Even on the English site, the Intro to Python lessons don't have images. I would either wait until the newly redesigned lessons page is ready or until you want to launch some translated lessons that are not within the "Introduction to Python" series.  The Spanish version of the existing lessons page can be found [highlighted in red here](https://github.com/programminghistorian/jekyll/commit/1bdc598c42e84b08435a2c2e85f88755d4d90d85#diff-c9ee43a8e3b6e649bdcc0868e0691d45); all that will need to be adjusted are the `img` links because the relative paths don't work from within the `es/` subdirectory.

As far as I can tell the file that @mariajoafana referenced (`jekyll/es/indice-de-lecciones.md`) isn't doing any work for us anymore; should I just delete it?

**Comment by vgayolrs** [comment]
@wcaleb @mariajoafana  yes, the file could be deleted because the working one is `lecciones/index.html`

**Comment by acrymble** [comment]
@wcaleb the intro to Python lessons do have images now:
http://programminghistorian.org/lessons/

**Comment by amandavisconti** [comment]
I'm hoping to have my lessons page work done by the end of this weekend (this will just be functionality, not the styling Fred is doing)

**Comment by wcaleb** [comment]
@acrymble Ah, somehow I missed that. Sorry for the oversight! I'll try to get the images over to the Spanish version this morning.

**Comment by wcaleb** [comment]
@amandavisconti I'm going to go ahead and make the Spanish index like the old one for now; that way they can proceed with their soft launch while we test out the functionality of the new lesson page over on English. Especially since they really only have a few lessons translated right now, it might be overkill to implement the new lessons page over there, and I know they are eager to announce the site. Does that sound ok?

**Comment by amandavisconti** [comment]
@wcaleb Absolutely!

**Comment by wcaleb** [comment]
Closed with b002ad1bcaf87836d60f87ceb72a7c912a7dacd2
