### ISSUE TITLE
Spanish Lesson - code in English

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#358]
The following lesson has an example "I can't eat pickles" which should presumably be translated to something like 'No puedo comer pepinillos', as all of the other strings have been translated.

http://programminghistorian.org/es/lecciones/trabajar-con-archivos-de-texto

**Comment by vgayolrs** [comment]
@acrymble : There is a good reason for it. In Spanish we do not use apostrophe as in English, to contract two words, i.e. "Can not = can not". As the idea of the example is to show the way to escape the apostrophe in a text string, there is no way to do it with a sentence in Spanish. So I decided to leave it in English. A note could be included. Any thoughts? @mariajoafana @arojascastro

**Comment by arojascastro** [comment]
I think a note would work, yes. Otherwise we can use an English word within a Spanish sentence: Su nombre es John O’Connor. Or use Old Spanish word such as d’aquel (por de aquel), l’aspereza (por la aspereza), qu’es (por que es). More examples: http://lema.rae.es/dpd/?key=ap%C3%B3strofe 

As I said in other threads I still need to revise your lesson. I promise to read when I finish translating the guidelines for authors.

**Comment by acrymble** [comment]
Ahh of course. The "John O'Connor" example sounds like a good one.
