### ISSUE TITLE
Spanish code, same filename as English code?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#366]
This is a question for sustainability purposes. I notice that the obo.py files have been translated for the Spanish lessons, but the file is still being called obo.py. Should we not call these obo-es.py or something like that? Just to make it easier to tell them apart? It may be that we continue to add languages, and I can see that getting messy eventually.

If this is a bad idea, please reject it.

**Comment by vgayolrs** [comment]
Good catch @acrymble and I agree with the reasons for sustainability. But I must point out that this involves replacing the name of the obo.py file in the whole code since there are modules that call it to work. I like the idea and I can do it, but it would take several days not only to change the code in the lessons and in the program files but to check that everything works.

**Comment by vgayolrs** [comment]
I am reconsidering the viability of @acrymble 's proposal, and the sustainability argument is a strong one. In a case (distant) that we lost the integrity of the repository structure, it would be easier to reconstruct things by specifying the names of the program files adding a respective language Identifier (i.e `obo-es.py`, `obo-fr.py`, and so on). In the next few weeks I will work with this separately in my git, but I would still like to hear what others think.

**Comment by acrymble** [comment]
I suspect this can now be closed, as these lessons have been translated? Is that true, @vgayolrs ?
