### ISSUE TITLE
Spanish soft launch to do

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#368]
Just looking to get a sense of what's left before we soft launch the Spanish material? I was confused previously because I thought they were ready to go.

- [ ] @arojascastro to proof read everything
- [x] guidelines for authors/editors being translated.
- [ ] anything else?

**Comment by arojascastro** [comment]
Yes, I still need to proof read some Python lessons... maybe I can split with @mariajoafana ?

As you noted we also need to review paratextual pages like the guidelines for authors/reviewers that I just uploaded to our repository: https://github.com/PH-espagnol/borradores/issues

**Comment by vgayolrs** [comment]
@arojascastro  I take that.

**Comment by vgayolrs** [comment]
@arojascastro please, can you relocate "guia-editor.md" (editor guidelines) from ph-es to ph/jekyll?

**Comment by arojascastro** [comment]
I would but it has not been reviewed by anybody yet... should I?

**Comment by vgayolrs** [comment]
I have.

**Comment by arojascastro** [comment]
But that is not the workflow... according to the guidelines for editors. We are supposed to review texts on our own repository using issues and then once its been supervised by two editors move it to jekyll. if this is not the workflow then we should change the guidelines for editors and reach an agreement.

**Comment by acrymble** [comment]
maybe we need some guidelines on the English site for this workflow too. Just so we all know how it works.

**Comment by arojascastro** [comment]
Maybe a workflow diagram would clafify the process. I also think that the roles of the authors, editors and reviewers could be visualized using a table or a diagram about tasks, roles, times and workflow... I translated it both the guidelines for authors and editors and also the workflow page and I must confess that I got lost into such a detailed account. I still do not see the whole picture unfortunately. So yes I think a few diagrams would help a lot.

**Comment by vgayolrs** [comment]
@arojascastro I agree with you. But it is the translation of a page of the website, not a translation of a lesson. In that sense, I have already done a first proofread but I would like to see it "work" in the context of the rest of the pages of the "live" site.

However we have to make important decisions about how to handle the lessons translations or forthcoming lessons, if we keep the repository PH-is separate or integrated into PH, since there are many technical details (as we have seen these days) in which it is very Important the collaboration of the whole team. We could treat it at the next meeting with proposals.

**Comment by arojascastro** [comment]
yes i agree with you @vgayolrs that they are not lessons but still they need to be reviewed using issues. we must start acting as authors, editors and reviewers, document our suggestions using issues and moderating the conversation with summaries on our repository. I dont think the reviewing process of our lessons should take place in the ph main repository because notifications are very annoying. but thats my opinion. In any case we have published on jekyll all the pages without reviewing them and that's not the right way to go, i think. Because since we havent used issues we cannot track changes, discuss or just find out which page has been reviewed and by whom. and all this is driving me crazy to be honest. it is a mess -- of course im taking responsability because when i uploaded my translations i didnt creat issues or ask for an editor and a reviewer. so mea culpa.

**Comment by acrymble** [comment]
I've opened a new ticket to discuss the workflow #369 because that's an aside to the purpose of this ticket.

**Comment by acrymble** [comment]
As per discussions here and elsewhere, the blog post has been posted by @mariajoafana .

Final reviews of each lesson are going on right now at https://github.com/programminghistorian/ph-submissions and each lesson review ticket will be closed as they have been approved by all members of the Spanish Team.

**Comment by acrymble** [comment]
Does anyone mind if I tweet this? I'd really like to share, even if this is still in progress (as are all digital humanities projects!)

**Comment by mariajoafana** [comment]
Yes, I'd like to share as well! Lets see what the rest of the team think. 
I'll do the tweet in Spanish after you tweet in the English site

**Comment by arojascastro** [comment]
No problem from my point of view.

**Comment by amandavisconti** [comment]
Sounds good to me!

**Comment by acrymble** [comment]
Ok, tweet away @mariajoafana .

I'm closing this ticket because the rest of the activity is dealt with elsewhere.

**Comment by arojascastro** [comment]
I checked both versions of the announcemente and this link "[how to make Omeka exhibits] (http://programminghistorian.org/lessons/creating-an-omeka-exhibit)" is not working on the website. The Markdown encoding, however, looks fine to me. Any idea why is not working?

**Comment by acrymble** [comment]
fixed. Can't have spaces between links like that.
