### ISSUE TITLE
Spanish Team Roles

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#375]
I think it might help to start thinking about the different roles that the members of the Spanish team might fill. On team projects like this, I think everyone needs a clear space to call their own where they know what their contribution will be. We do this on the English team (only one person is ever formally involved with a given lesson, to avoid any clashes between editors), and I think it has helped us work well together.

What are the roles that we need to fill to make the Spanish project successful?

Some ideas:

1. A community lead who actively promotes the project through blog/social media/workshops/outreach
2. A person who solicits translations from the community and acts primarily as editor.
3. A person who solicits new lessons from the community and acts primarily as editor.
4. A person who writes lessons relevant to the Spanish community and submits them for formal review.

Let me know what you think of this idea.

**Comment by mariajoafana** [comment]
Great idea Adam. If @arojascastro and @vgayolrs agree, I'll like to be involved with the promotion of the project. I was thinking on writing a piece in Spanish for the blog about why Python can be useful for historians. 
Also, I'll like to write a lesson eventually, but I'll need to mature this idea before I can propose something concrete. I could also support the rest of the team with the other functions when needed.

**Comment by vgayolrs** [comment]
I think it is a very practical idea that will allow to organize the collaborative work. Maybe we have to adapt it a little at first, since we are only three in the team and we have some pending tasks, but I think we can cover them in a short time. We're learning fast thanks to @acrymble (thank you very much)! Here some commnets.

1) *Community lead and promotion*. I think @mariajoafana has the appropriate profile to promote the project actively. I do not know if you have thought about giving workshops and lectures. I'm preparing several, and I could help you in that sense.

2/3) *Editor(s)*. Since I believe that, for the moment, we will have more translations rather than new lessons A) If @arojascastro agree, I think he could be the Main editor, as we had agree that he appears on PH-es as the main contact (just like Jeri is collaborating right now, you can see [here](http://programminghistorian.org/es/#contacto), [here](http://programminghistorian.org/es/contribuciones#%C3%9Anete-a-nuestro-equipo-de-revisores) and [here](http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones) what I mean). I can work as a secondary editor and support him. B) But in case we had a similar amount of translations and lessons, I would propose Antonio as a translation editor and I would prefer to get involved with new lessons proposals. But, of course, we can discuss it later.

4) *Lessons writer(s)*. This is *mare ignotum* to me. I came for the first time to PH because I didn't find answers to my needs of increasing my technical skills in the Spanish-speaking community. But there must be someone out there. I think part of our goal in PH-es is to attract them and encourage others to get involved with programming and to produce relevant and accessible tools.

**Comment by arojascastro** [comment]
I agree with the proposal @mariajoafana @vgayolrs @acrymble. However, I would like to clarify a few things:

1. If I become the main editor, I won't have time to translate, I am afraid. 
2. Is there any way that the editor of the translation can be given credit in the YAML header?
3. Until now I have translated one lesson, which has been proofread without creating a review ticket i think. If I act as a translator, I understand that @vgayolrs should be the main editor of my tranlsation and that someone else will proof read the text, right? 
4. How often I will have to look for external reviewers? By that I mean that if you @mariajoafana @vgayolrs still want to proo fread the lessons that have been already submitted and future submissions.

**Comment by arojascastro** [comment]
Should I close this?

**Comment by acrymble** [comment]
I don't think you've received answers to your questions. But you can close it if you decide you don't need them.

**Comment by vgayolrs** [comment]
Sorry, I missed this one.
@arojascastro 

1. Do not worry. I think the role assignment serves to better organize the work but doesn't mean having absolutely fixed tasks and we can exchange. Every time you need to delegate the edition of something I think you can lean on @mariajoafana or me.
2. I think there is no problem with that. In fact, several lessons have it included.
3. Quite so!
4. I think it would depend on the difficulty of translation and revision. There are translations that are quite good and only need slight corrections, but there will be others that we'll need external reviewers. In addition, seeking outside reviewers would greatly benefit PH-es because we would involve more people: if you have already reviewed you will want to translate or write a new lesson. What do you think?

**Comment by acrymble** [comment]
I definitely agree about the benefit of involving more people. You've got a translation in the making, but making more people feel like it's 'their' project helps the user-base grow.

**Comment by acrymble** [comment]
I don't think this needs to stay open. But if it does, reopen it.
