### ISSUE TITLE
Editorial Board Meeting Agenda 31/03/2017

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#394]
Any suggestions from the team of issues to discuss at the meeting? I suspect there are a lot. Some that stand out to me are:

Welcoming new team members (@JMParr welcomed and given ideas on getting started)
#387 - Standardising github/website contributions @mdlincoln (postponed due to travel)
#379 - Separating Project Team from Editorial board? @fredgibbs (postpone due to travel)
#383 - Spanish workflow @mariajoafana @arojascastro @vgayolrs (ticket closed)
#193 - Lessons page progress @amandavisconti ([see this comment for latest status] (https://github.com/programminghistorian/jekyll/issues/193#issuecomment-290591188)) (ongoing but looking good)
#398 - should published lessons be moved from Submission site? @wcaleb (agreed to implement)
Internationalised project team needs (will open a ticket - #403)

Anything else? Looks like we've had a busy month.

**Comment by arojascastro** [comment]
My apologies I can make it this time. I'll be in a conference in Chicago! I only can add that two new translations were comissioned to external collaborators: 

1. cleaning-data-with-openrefine to María Jesús Colmenero
2. data-mining-the-internet-archive to Jairo

Plus we should get a new translation (graph-databases-and-SPARQL) by Nuria Rodríguez Ortega by 17 April.

**Comment by wcaleb** [comment]
What to do with old lessons in `ph-submissions` that have been moved over to the main repo? 

I suggest we put them in a "published" folder and edit the YAML to include a `redirect_from` the original URL (without `published` in the path) so that the live previews mentioned in review tickets still work.

**Comment by mdlincoln** [comment]
Unfortunately, I'll also be in Chicago (👋 @arojascastro) so I will be missing this call, too.

I'm very interested in #387 (related, more detailed #381) - most of my thoughts on it have already been captured in those issues, but i will add any additional thoughts early this week so that they're documented.

**Comment by acrymble** [comment]
Maybe we should hold off on #387 and #381 until next month if @mdlincoln is not available? Since you've been quite involved in those discussions.

@wcaleb did the submissions thing have a ticket? I can't find it. Or was that just via email?

**Comment by arojascastro** [comment]
@mdlincoln I just saw that you are delivering a paper at the RSA too. Hope to be able to attend and say hi.

**Comment by wcaleb** [comment]
@acrymble I believe it was just discussed over email.

**Comment by walshbr** [comment]
I'll be flying to Ohio at this exact time - sorry to miss my first one! 

I'll comment on project tickets as I have thoughts. I have a couple newbie questions that are probably easily dispatched about how best to go about soliciting lessons, whether I should give a game plan to the editorial board first, etc. I'm happy to correspond on the here, list, off GitHub, etc. Whatever takes up the least time for people.

**Comment by amandavisconti** [comment]
With the new year and new teammates, is it time to update how we cite the PH site? (listed at the bottom of the homepage)

Attempt at updating (please correct):

Afanador-Llach, Maria José, Antonio Rojas Castro, Adam Crymble, Víctor Gayol, Fred Gibbs, Allison Hegel, Matthew Lincoln, Caleb McDaniel, Ian Milligan, Jessica Parr, Evan Taparata, Amanda Visconti, Brandon Walsh, and Jeri Wieringa, eds. _The Programming Historian_. 2nd ed., 2018. [http://programminghistorian.org/](http://programminghistorian.org/).

Wasn't sure if we were including all current editors vs. all current board members (I'm only in the former, though I may be editing Sam Abrams' lesson in the near future).

**Comment by acrymble** [comment]
It's the current active team. So:

Afanador-Llach, Maria José, Adam Crymble, Víctor Gayol, Fred Gibbs, Matthew Lincoln, Caleb McDaniel, Ian Milligan, Jessica Parr, Antonio Rojas Castro, Amanda Visconti, Brandon Walsh, and Jeri Wieringa, eds. The Programming Historian. 2nd ed., 2017. http://programminghistorian.org/.

**Comment by fredgibbs** [comment]
i would like to make a VERY STRONG argument that we remove the suggested citation. there are a few main reasons:
1) anyone needing to cite PH will be publishing it somewhere that will have a citation style that must be followed. so people can figure out how it makes sense to cite PH given whatever paradigm they are using. 
2) it's misleading. if i cite an article published from 2014, i should be citing the editors who produced that publication, not the current editors who maybe don't know anything about it. 
3) i have not seen anywhere ever a convincing argument for why an entire project team should be all listed as editors, which has a fairly specific meaning for cited publications.
4) it's kind of meaningless: what is a second edition of a constantly changing website? we're not a published book that has discrete editorial interventions and printings. the date is also wrong, since we have an ongoing publication. it should be 2012 (or whatever) with an open-ended date (so 2012-).

**Comment by acrymble** [comment]
I have to say I'm surprised by this, and it might be a difference between the needs and pressures in different jurisdictions. Does it hurt anyone to leave it? Because I think it poses challenges for me in the UK research environment to say what this project is and to ensure it 'counts' in an appropriate way.

I can't say I was convincing, but I did put forth an argument for why project teams should be named in project citations:

http://www.digitalhumanities.org/dhq/vol/7/2/000164/000164.html

I found at the time that American colleagues were seemingly least interested in this, which again suggests to me there's just a different need for representing work in different countries.

I also use these types of citations to teach my students about collaboration and to teach them to distinguish between the content (eg a lesson) and the project. So I think dropping it would be a step in the wrong direction. I'd be much happier to revise it. We discussed project version numbers previously, which I think are more meaningful and maybe could be linked to cohorts of team members.

**Comment by amandavisconti** [comment]
Some compromise possibilities:

1. Replace the hardcoded author list in the citation with a call to the current editors (may need to add a field to data sheet to do this, which is yet another thing to remember to update...)
2. Replace "x edition" with "accessed on date" or "accessed on [pull in today's date]" (possibly with link to /jekyll repo for that date?)
3. If you're citing an individual lesson, the citation on that page should be hardcoded with the names of the editors at the time of its publication.
4. If you're citing the whole project (using the citation at the bottom of the home page), we could provide a dropdown menu of years updating the list of editors. This would be a little incorrect given we have changes within given years, and I'm also not sure many people would want to cite the whole site from a given point in the past, rather than when they're most currently accessing it. So alternatively, we could provide a small link under the citation: "Want to cite an older version of the project?" that connects to a page listing each year next to all the editors active in that year.

**Comment by acrymble** [comment]
This sounds like a conversation we should have about the different working cultures we're operating in and what that might mean for us. Obviously we want the project to work well for everyone as best it can. I've added an item to the agenda. Thanks for raising it.

**Comment by fredgibbs** [comment]
regretfully, i've had to change my travel plans at the VERY last minute and now i won't have internet access during the call. sorry to miss this conversation. quick update: site design work is going well; now that @amandavisconti is basically done with the lessons page coding, i can apply the design i've been implementing for that page as well. i've also been creating a real home page as distinct from the about page. i haven't had time to move everything up to my online fork for live preview, so i'm attempting to attach a mockup of the new lesson header, if anyone has any comments on that. (translators and translation reviewers will appear on the same line as the reviewers.)
<img width="1005" alt="screen shot 2017-03-31 at 9 07 29 am" src="https://cloud.githubusercontent.com/assets/515448/24551739/a2049cc2-15f1-11e7-8893-f2aec951cdcd.png">
And here's the footer:
<img width="984" alt="screen shot 2017-03-31 at 9 18 44 am" src="https://cloud.githubusercontent.com/assets/515448/24552098/30056b68-15f3-11e7-8356-6abbfb6f36b8.png">

i've spent quite a bit of time experimenting with some new typographic features that we can begin to use in the lessons, but those will be integrated over a much longer period of time, but they also require slightly changing the way we encourage authors to write lessons.

**Comment by fredgibbs** [comment]
a sample of the lesson page format, though i still have work do to on the buttons given new functionality added yesterday.
<img width="732" alt="screen shot 2017-03-31 at 9 24 10 am" src="https://cloud.githubusercontent.com/assets/515448/24552312/f1625532-15f3-11e7-9b66-5adaa5c58a40.png">

**Comment by acrymble** [comment]
Cool mockups @fredgibbs. I like them. I've postponed our discussions you raised, since you're not able to join us. We'll pick up on those next time. Safe travels.

**Comment by amandavisconti** [comment]
@fredgibbs These rock! Let me know if there's anything on the functionality side I can help with.

**Comment by walshbr** [comment]
Love new design/mockups! @fredgibbs

**Comment by mariajoafana** [comment]
I love it! 
I can't connect to the meeting, sorry for the short notice. @vgayolrs will represent the Spanish team

**Comment by wcaleb** [comment]
Hey everyone, at the risk of beating a dead horse from the call or appearing obsessive, here is a [helpful guide to writing good Git commit messages](https://chris.beams.io/posts/git-commit/) that I have personally found useful. While aimed at developers, the "Seven Rules of a Great Commit Message" could be useful to us, as well, especially as we have more and more people interacting with the codebase.

**Comment by acrymble** [comment]
I've moved the comments about the Project Citation to a new ticket to continue the conversation so that I can close this: #404
