### ISSUE TITLE
Schedule regular tweets of older lessons

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#402]
Write an enticing description of the skills taught & schedule these in Tweetdeck to go regularly (twice a month?).

**Comment by acrymble** [comment]
I think we could do this weekly. I find links to lessons with the accompanying image tend to get retweeted quite a lot, suggesting there's an appetite for this.

**Comment by fredgibbs** [comment]
because our lessons often teach far more general skills than what the lesson title indicates, mentioning these in a tweet--maybe at the expense of the title itself--may be a very effective way of getting new eyes on some old lessons.

**Comment by walshbr** [comment]
Strongly support all this. And @fredgibbs - I agree. And I think that approach is less likely to be thought as of spam than just consistently retweeting the title. Maybe a few different types of canned tweets:

1. Title and image
2. Skill description
3. Outcome description (so a bit a more descriptive of content than 2). 

To use the Audacity lesson as an example:
2 - "Learn to edit audio with Audacity with this lesson..."
3 - "Mix together a short podcast using this lesson…"

I can also help with this if you want @amandavisconti

**Comment by amandavisconti** [comment]
Great ideas! What are y'all using to schedule tweets? I'm using Tweetdeck, and I think we may be able to view @proghist tweets anyone on the team has scheduled that way. That would let any of us add a couple tweets as time allows, without redundancy.

@walshbr That would be great! If you schedule any (instead of just tweeting them out directly), could you let me know so I can verify those scheduled tweets are also visible to me in Tweetdeck?

**Comment by walshbr** [comment]
@amandavisconti I wonder if it's with worth writing up the content for the tweets all at once and saving them in a .txt file in the repo? That way the process for scheduling tweets would be more work up front but less longterm. 

I scheduled a tweet about the Audacity lesson to go out April 15th as a test. Let me know if you can see it.

I use Tweetdeck too - was just looking around to see if there were options for scheduling recurring tweets, but I couldn't find anyway. Seems like a lot tedious labor to re-up on the scheduled tweets each month, though I'm happy to do this/take part in it. Theoretically we could whip together a Twitter bot that uses the PH credentials for logging in and tweets from that account a few times a week with the compiled list of tweets. That seems more sustainable longterm, gut I'm not sure if people want to defer that much control. Open to whatever you think!

**Comment by acrymble** [comment]
I may not be patient enough because I see you just posted @walshbr but I don't see this in my scheduled tweets. So perhaps its local.

**Comment by walshbr** [comment]
If that's the case @acrymble we should probably have one person dedicated to the scheduling to prevent overlap/duplicating work. 

If people are amenable I can stub out a bot that will tweet out the lessons regularly. I can just use a dummy account for now.

**Comment by acrymble** [comment]
I agree with your idea that we should write these out (maybe a year's worth?) in advance. We might also talk about a strategy, like a marketer would do. What do we want out of this? More eyes on lessons that don't get noticed as much? Broadening the audience beyond historians?

**Comment by amandavisconti** [comment]
I do see @walshbr's scheduled tweet! (A bot sounds cool, too.) Like the idea of a shared file in the repo (maybe using [x] to mark off tweets when you've scheduled them).

**Comment by acrymble** [comment]
I can see this now scheduled, so this approach seems like it will work. I'd suggest branding with the lesson image where possible. Makes it pop more on Twitter, I think.

**Comment by fredgibbs** [comment]
i don't know a thing about scheduling tweets, but i am all for more consistent branding (obviously related to recent design work, too). at least for now, the images are central to this. i hope we can use them!

**Comment by acrymble** [comment]
That scheduled tweet went out fine, so this seems to work. How should we focus this in future?

**Comment by walshbr** [comment]
Thanks for pinging me @acrymble. Was going to mention this at the monthly skype call, but can do it now. I've got a bot up at https://twitter.com/codingarchivist that I've been playing with. It's running through Python/heroku, and it is pulling from a CSV that looks like this:

```
lesson-id,message-one,message-two,lesson-link
1,"Get started with the Zotero API using this tutorial.","Want to access your Zotero libraries from Python? Learn how with this lesson.",http://programminghistorian.org/lessons/intro-to-the-zotero-api
2,"Learn how to use Python to add things to your Zotero Library with this lesson -","Use Python to modify your Zotero collection with this tutorial -",http://programminghistorian.org/lessons/creating-new-items-in-zotero
3,"Count word frequencies in your Zotero items with this tutorial-","Analyze your Zotero items with this beginning tutorial.",http://programminghistorian.org/lessons/counting-frequencies-from-zotero-items
4,"Learn how to preserve your research data with us-","Structure and document your research data to make sure they last. More here-",http://programminghistorian.org/lessons/preserving-your-research-data
```
etc. So that CSV could live in the repository. Started off running it pretty frequently as I was troubleshooting, but now it's running daily. Through Heroku I can run every 15 minutes, hourly, daily, or weekly, so I could do two different weekly jobs at different times to get the kind of scheduling we had been talking about. 

There are a couple things that would make improve the bot:

- Rather than just randomly cycling through the lessons, would be better if it would randomly cycle through but not repeat. There were a few days where it kept pounding on the same lesson just because the thing was random. Though i suppose that wouldn't be as much of an issue if all the lessons were on there.
- Sanitize the script so the credentials are hidden through Heroku and it can be properly version controlled for you all.
- I think rather than having two English tweet options, it would make sense to have one English and one Spanish?
- Should really also get the twitter usernames of the authors in the tweets as well, since I think part of the goal here would be to promote the authors as well as the lessons.
- Include some error reporting and testing for catching when things go wrong.
- Documentation
- Use the Programming Historian credentials rather than the dummy account I've been using.

Just haven't gotten a chance to revisit this, but all of that is doable (besides the Spanish translations, which I would need help with). If this is a direction we want to go I'm happy to take these polishing steps and account for any other feedback. And if it is something we want it might be time for a new ticket?

**Comment by acrymble** [comment]
This sounds great to me. I would suggest 2 English language ones that spread across a wide time difference. Our team covers 9 time zones, and our readers even more than that.

**Comment by wcaleb** [comment]
I wonder what the method is to get Twitter to automatically create a "Twitter card" using the image lesson whenever a link to the lesson is included. There may be a way to do this in the header HTML to our lessons, which would make the images in the resulting tweets look more "native" to Twitter?

**Comment by wcaleb** [comment]
Here's what I mean by [Twitter cards](https://dev.twitter.com/cards/overview).

**Comment by walshbr** [comment]
Ah @wcaleb that'd make the twitter bot process a bit less brittle - one less thing to pull out and add into the tweet. It looks pretty reasonable, based on the description [here](https://dev.twitter.com/cards/types/summary-large-image). Something like - each post gets an image URL variable, which the header partial dumps into the appropriate meta tag?

**Comment by wcaleb** [comment]
Exactly, though I was thinking just the summary card, which has a thumbnail image, though that can be easily changed. Working on a prototype now.

**Comment by wcaleb** [comment]
OK, I think I have a prototype working. [See example here.](https://twitter.com/ProgHist/status/856623097612566528) Right now, it's not ideal because it just excerpts the first 200 characters for the description. But that will look better once we have all the abstracts @amandavisconti created (I think I'm remembering that she made abstracts!) merged into the main site.

Right now the Twitter card assumes that there is a gallery image and goes looking for that to create the thumbnail. So I'm not sure what will happen when we link to a page that doesn't have a gallery image (like the Lessons directory or Contribute page), but this seems like a start ...

**Comment by amandavisconti** [comment]
@wcaleb Cool! I did add abstracts to all the lessons in my fork.

**Comment by fredgibbs** [comment]
and i have all those abstracts in my fork as well that i hope we can push in the next few weeks that combines all the lessons work from @amandavisconti and the new design stuff.

**Comment by walshbr** [comment]
@wcaleb looks awesome! If the tweets can just have cards associated with them I can chuck the bit of Python for the images in the bot.

**Comment by fredgibbs** [comment]
very professional looking @wcaleb!! i haven't looked at the code, but once the spanish language lessons get updated YAML, and a translated abstract from @amandavisconti's work, will we be able to tweet from both en and es versions?

**Comment by ianmilligan1** [comment]
This looks fantastic!

**Comment by wcaleb** [comment]
@fredgibbs Yes

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Magister
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by walshbr** [comment]
Will leave open for now until the tweets are scheduled. But the updates from #412 -

- @walshbr will finish out the twitter bot.
- Tweet contents will be migrated to a google spreadsheet shared with the group instead of CSV in the repository.
- Update editorial workflow so that we know to add new lessons to the spreadsheet in the future.
- Initial twitter bot data will only consist of English tweets. We'll do Spanish later when there are more lessons.
- We'll have two different English messages for the lesson, and we'll be sensitive to the different time zones of our readership.
- The scheduling of tweets in this way won't replace the usual, scheduled promoting of tweets that takes places whenever a new lesson is published.

Pulled the task of completing the bot into its own ticket to organize those tasks - #418.

**Comment by walshbr** [comment]
Moved the twitter bot to the PH credentials this morning.
