### ISSUE TITLE
Framing project for international scholarly credit cultures

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#403]
This ticket is for project-level issues relevant to the project team (as distinct from authorship / reviewer credit), and relates to a brief exchange about the project citation in our editorial meeting ticket #394 .

Since our team operates in the USA, Canada, Mexico, Spain, and the UK, we've got a lot of different national ideas of what 'counts' or what academic work should look like. Since we're a bit of a unique project (I'm never really sure how to describe us), I think we need to consider the competing needs and expectations of those national contexts, if only just to make sure we're working together rather than against each other when it comes to presenting the project.

--

For example, in the UK-context (as far as I understand it), the elements on the 'Research' page are most valuable academically to me. This is because our 'Research Excellence Framework' or REF tends to emphasize research (as in a question answered via a sustained argument based on an analysis of evidence) above other forms of contribution.

As that's the case, tone, and elements that remind people that we are producing an academic project (rather than a blog) are helpful for me. For example, the ISSN number, the Worldcat entry (thanks @amandavisconti), clear citations, etc, equally help to demonstrate that we are academic because we share the language/tone/apparatus of academic projects.

Internationalisation is also highly regarded because it's linked to an emphasis on 'impact' that's a common buzz-term here.

It would be helpful to get a sense of how others' contexts are different, so that we can make sure we're working towards the most useful project from the perspective of our team members' needs (in addition of course to our authors, reviewers, and readers).

**Comment by ianmilligan1** [comment]
OK I can kick things off here. In my context, this is really more part of my service role than research. While the lessons may have some currency, my sense is that they aren't really considered in my annual reporting compared to journal articles, books, and grants. But my research pipeline is healthy and I've been awarded tenure, so I have the chance to shape my job to include this work. 

I'm happy for the project to take shape to meet other people's needs, as I don't really have many in this respect.

**Comment by walshbr** [comment]
In addition to what you've expressed above, here are my two cents - not about national context but rather about an institutional one. I'm based out of libraries, not an academic department like the one that trained me. So while I'm pretty confident that the English department I came from might be a tougher sell, my library reporting structures have been very savvy about the legibility of both my lesson here as well as the new addition of the editorial work. My annual report at W&L, for example, had a pretty extensive publications component beyond the traditional articles/books grants. Significant blog posts were counted, there was a section for other resources, and it was clear that the idea of peer review and publication was more important than the format. So I actually felt comfortable listing the Audacity lesson as a peer-reviewed publication. That's partially because it was very similar to other kinds of publishing that I was doing for the library - documenting workflows, building and curating datasets, publishing workshop materials. My library cared more about the idea of making the work public and useful than about the format. That being said, here are some things that were helpful in making the case to the library administration:

- The [extensive peer review documentation](http://programminghistorian.org/#peer-review) is good evidence of the project's rigor.
- The commitment to transparency and access, both through open access and its reliance on GitHub, is a pretty clear articulation of librarian-y values
- Since I was coming from a small liberal arts college, they also really value academic work that tightly intersects with pedagogy. So the fact that we're publishing lessons that are teaching elements is useful.
- And documenting workflows is valued by our library as well.

So, to me, all of this kind of work is clearly explainable as academic to my library colleagues. But then, I'm a PhD working in a library without a library degree. So others with explicit library training might have better, more informed perspectives.

**Comment by acrymble** [comment]
I think this largely is covered now by #410 and other related tickets.
