### ISSUE TITLE
Editorial Meeting Agenda 28/04/17

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#412]
Suggestions for our upcoming meeting. Please make suggestions.

These two were postponed last time, so bringing forward:

#387 - Standardising github/website contributions @mdlincoln
#379 - Separating Project Team from Editorial board? @fredgibbs
#402 - Scheduling Tweets @walshbr 
no ticket - do we need a new meeting time? @acrymble
#405 - project title

**Comment by ianmilligan1** [comment]
Unfortunately I'm leading a workshop down at Penn State on Friday, so I won't be able to make it.

**Comment by mdlincoln** [comment]
👍  for #387 

The details of #387 could be wide-ranging, and we could easily get stuck in the weeds during the call - which would be a waste of the larger editorial team's time. I suggest we focus on

1) Specifying which members of the team will be responsible for technical aspects of this project
2) Decide if there needs to be a single individual who coordinates and makes final decisions about merging in that working group's contributions (I say yes! But if so: who?)
3) Determine how to coordinate work on technical contribution docs/processes with pending @amandavisconti lesson page overhaul and @fredgibbs design overhaul

Does that sound feasible?

**Comment by acrymble** [comment]
I think we should discuss the static vs updating discussion, which affects the following tickets:

#410 #408 #407 #393 #304 #207 #225 #223 #222 #64.

I put forth a proposed solution that I think will work in #410, which I welcome feedback on.

**Comment by ianmilligan1** [comment]
Was the 🎉 because I won't make it, Adam? 😉  Or go Nittany Lions go? (sorry about this.. the travel schedule this term has been brutal)

Re: #410 I think that you've outlined a really thoughtful process. And having a link somewhere to the Zenodo 'version of record' is helpful too. As somebody who sometimes sticks with older versions of software because not all dependencies/etc. are updated yet, I think this would be useful to me as a researcher too!

**Comment by fredgibbs** [comment]
i will be driving from michigan to new mexico beginning on friday, and will try my best to find wifi during the call (which generally overlaps with lunch) but it's awfully hard to predict. 

i think this semester has suggested that although fridays seem like good times for a team call according to usual schedules, it might have proven a too-popular travel time for conferences and other relocations.

i generally like the #410 solution, but one of the difficulties is deciding how much we want to make sure someone can see an article in its truly original format (which is part of a traditional publication), even if we've changed the layout, typography, design, functionality, etc, of the site in the meantime. My inclination is to promise to make available only the markdown file that was ultimately published. In other words, I guess we have to decide if the DOI points to a lesson URL or a GitHub commit. 

my ongoing design work is visible (but not always with the very latest commits) at http://fredgibbs.net/jekyll/. i'm working on some of the spanish pages now, and generally those don't work yet.

**Comment by walshbr** [comment]
Will be there. Would be good to touch base on #402 - but shouldn't be a long conversation.

**Comment by arojascastro** [comment]
Love the new presentation @fredgibbs. See you on Friday.

**Comment by ianmilligan1** [comment]
Yeah, my last Friday of May just filled up with an unavoidable event too (a lunch/reception in honour of my retiring doctoral supervisor). Maybe we can find a new slot. Or maybe a doodle poll as it turns out my schedule is too unpredictable with travel obligations to commit to a time slot months in advance. ☹️

**Comment by acrymble** [comment]
@ianmilligan1 I will add this to the agenda:

- New meeting time required?

I don't think there's going to be a time that works for everyone, but we'll see if there are others with a similar problem. We certainly don't hold your missing a meeting against you.

**Comment by ianmilligan1** [comment]
Sounds good! I'd be in favour of scheduling meetings a week or two in advance using Doodle, which gets confusing but it's becoming clear that I now have too much flux in my schedule to know what's going on a month in advance, let alone multiple months. (That said, getting control of my schedule again is one of my professional development goals for 2018 😉 )

**Comment by arojascastro** [comment]
Is it possible to get any web analytics (traffic) for the Spanish translation? I would be interested in the number of visitors and main referrals.

**Comment by acrymble** [comment]
@arojascastro I have added everyone now to the Programming Historian google analytics acc't. You should have received an email. Except @walshbr because I need a google-enabled email address for you. Anyone who didn't get the email/doesn't have permission, please let me know.

**Comment by arojascastro** [comment]
Thanks @acrymble, very interesting data. I have two question additionally about how to manage collaborators -- you don't have to answer now, we can talk on Friday, but I do not want to forget: 
- after collaborators have reviewed the lesson assigned, should we cancel their permission to write in our repository? 
- is there any way to impede that collaborators get all the notications by default? I am asking this because if you are not familar with GitHub, and an editor adds you as a collaborator and you start receiving many notifications at day, you may get lost. I mean, I want my reviewers to get updated only with the comments related with a concrete issue. 

Thanks

**Comment by mdlincoln** [comment]
re: #387 (and all other technical work): @mdlincoln has volunteered to be a coordinator for all technical contributions to PH. I'll take first responsibility for any issues/PRs specifically about the technical side of the site. I will also act as a general coordinator (and code reviewer, if that's wanted?) for big projects like @amandavisconti and @fredgibbs dev forks.

@amandavisconti raised the possibility of creating a "proghist-dev" process/repo so that we have a more formalized way of developing, testing, and deploying major changes to the site. I agree we need a process for that - I'll create an issue for discussing what implementation of that might look like.

**Comment by acrymble** [comment]
All of the above tickets have been updated as per our discussions in the meeting.
