### ISSUE TITLE
PDF versions-of-record

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#417]
I'm splitting this out as the technical (as opposed to documentation/communication) task for #410 

- [ ] Create pandoc script to produce PDF from lesson markdown
    - [ ] Adds header with date of original publication
    - [ ] If translation, adds header with date of original translation (#415)
    - [ ] Must play nice with pulling in figures from `/assets`
    - [ ] Incorporate a lesson-specific DOI (#64)

@wcaleb since I know you do a lot of work with pandoc, are you interested in taking a first pass at this?

I also initially thought that this belongs as a separate repo within [programminghistorian](https://github.com/programminghistorian). Since it'd need to have reliable access to `/assets`, though, maybe it makes sense to put it in a `bin` folder in this repo? Otherwise, we'd need to give editors super-clear instructions about cloning both repos into the same directory, etc... what do you think @wcaleb?

**Comment by wcaleb** [comment]
I'm happy to play with the Pandoc script as a first pass.

I'm not sure I understand your question about repos. Is this because of the way the DOIs would work?
 Why not just have another folder in `jekyll` called `pdfs` where we store the generated pdfs? The pandoc script itself could either be placed in the root directory or in a separate directory for `bin` if we think that we will have other maintenance scripts like this in the future.

**Comment by acrymble** [comment]
Version-of-record better than PDF for folder for semantic reasons

**Comment by mdlincoln** [comment]
No, sorry, I was thinking development of the actual pandoc template and conversion script in a separate repo. But that's prematurely making things complicated 😝  And so I agree, for now place the template/script files in `bin` in this repo.

**Comment by mdlincoln** [comment]
re: #414 we can proceed with writing up a pandoc script, but let's hold off on any edits to `_templates/post.html` until we merge @fredgibbs major changes to the site templates.

**Comment by acrymble** [comment]
if we're doing this, is there any reason all lessons can't always be downloadable as PDF? seems like a useful feature.

**Comment by ianmilligan1** [comment]
PDFs are awful for cutting and pasting, for what it's worth - a cautionary note from lesson development.

**Comment by mdlincoln** [comment]
@acrymble, do you mean having the latest versions available as PDF? Not just the version-of-record?

That would be annoying. GitHub pages won't run pandoc for us each time the site rebuilds. We'd need to tie in some outside service to do that. I agree with @ianmilligan1, while they're good for archiving, I don't see the desire for having every version as a PDF outweighing the effort to produce it.

**Comment by ianmilligan1** [comment]
My vote for what it's worth would be to just have one version for the version of record.

**Comment by fredgibbs** [comment]
@acrymble suggested some text in #414 about how to explain to our readers what the version of record is. The new about page has a slightly edited version as follows (which I mostly made a bit more vague but kept the general spirit in place). Once we decide the text I can add it into the about page.

## Versions of Record
Once a lesson has passed through peer review been published, a 'version of record' will be created which will be assigned a DOI and made downloadable via a PDF. This is the author's contributed work. In order to promote long-term sustainability, the editors may choose to update the lesson as needed in future. In this case, the live version of the lesson will differ from the 'version of record'. The revision history of each lesson, as well as the version of record, is accessible at the bottom of each lesson.

**Comment by mdlincoln** [comment]
@fredgibbs thanks for working up this text. As I [noted above](https://github.com/programminghistorian/jekyll/issues/417#issuecomment-298373309) I don't want to implement versions of record until we merge in yours and Amanda's changes - there's just too many moving parts. 

So before putting any hint of this feature in our published text, let's get your changes merged _without_ this text, and give ourselves some breathing room to figure out our real motivation/audience for doing versions of record (as you note in #428)

**Comment by fredgibbs** [comment]
agreed! actually, now i remember my motivation for putting the text in the ticket was to delete it from the impending about page!

**Comment by acrymble** [comment]
I'd say it's principally for the following groups:

* Authors who need to demonstrate to someone 'their' work (eg, employers)
* Anyone running a seminar / workshop that wants their students working from a known and unchanging text
* Anyone writing a future history of methods in digital history who wants to cite what the author originally created
* Anyone who wants a citeable reference to their method in a research article. Eg, to see what we did: read X.

There may be others, but that's what I can think of off the top of my head.

**Comment by acrymble** [comment]
If the pdf is a pain, I suppose we could always just have the equivalent of the live lesson view, but one marked as 'version of record', maybe with a different colour background and a warning note at the top to make it clear? It doesn't need to be a pdf.

**Comment by acrymble** [comment]
I think that rather than invent a new system we should just duplicate the /es/ folder idea for this, using /record/ where a copy of the files will be kept. As it's a version of record, only the original lesson in the language it was originally written would need to be stored. If there are future Spanish-first lessons then they'd be the versions of record. 

Then we have a separation between the pubishing arm of what we do, on behalf of authors, and the ongoing audience-focused work we do on behalf of readers. And without adding a new technical system for PDFs

**Comment by mdlincoln** [comment]
Saved as _what_ in the `/record` directory? Raw MD files? They'll have no images. As rendered HTML files? How do we make those? If we use jekyll, then they'll get regenerated every time and changed as we make sitewide updates and fixes? And then where do we put their images anyway? And what happens once we change our visual layout or do some other change that then impacts the way the lesson is rendered?

If you want it to be preserved as an HTML page, then just have the editors cache the published page in <https://web.archive.org> and add a link to it in the lesson YAML so it displays on the live site. Done. (example: <http://web.archive.org/web/20170627184230/http://programminghistorian.org/lessons/graph-databases-and-SPARQL>)

Otherwise, I'd say use PDF. It's a known, standalone format that _feels_ like a published article, which seems to be the main point of doing this. We could also forgo any fancy PDF generation, and just have the editors "print" the published web page as a pdf and upload it to the repo - as long as we are comfortable adding that step to the editorial workflow.

**Comment by mdlincoln** [comment]
FWIW my vote is for web.archive.org - it respects the fact that these lessons were conceived as HTML pages rather than printed documents. But I can see arguments for PDF as well.

**Comment by ianmilligan1** [comment]
I'm happy with either option, and I think if doing PDFs having them manually "print to PDF" and upload isn't too onerous (rather than scripting a workflow). Saving to the archive is probably the most organic, but PDF might be the best way to make it "count" in the scholarly context?

**Comment by acrymble** [comment]
@mdlincoln saved as a file no one updates, using the same setup as the /es/ system. I don't think it's a big deal if the page design changes over time. That's like changing the font on an old article.

The key point is that we've got a publishing process, but no actual process to save the results of that published work.

I spoke to one of our past authors whose view was that if the lesson were updated in future that the original would still be available and that it would contain some kind of note that the updated one was 'based on' the original. The Royal Historical Society had an entire symposium on this issue of using CC-BY to change someone's argument and re-publish it as if it was their work. That's precisely what we risk doing, so separating 'published' from 'most recent' into two activities just as we have separated Spanish from English, lets us serve both groups.

**Comment by wcaleb** [comment]
I think Matthew's question, though, is whether we need a duplicate file if all you want is the Markdown file preserved. We can actually link to the original markdown file of any lesson right now by linking to that specific "commit" on GitHub, but it would not be rendered as HTML. But if all an author wants is some record of the original text they wrote, that is already there in our current system and just needs to be surfaced with a link. 

On the other hand, if you want the original to be rendered as HTML, I think that could get confusing for search engines and the like because we would appear to have duplicate lessons that in many cases will be very similar.

PDF might still be the best bet for this, especially if we are worried about depending on git. But the question is how much time we want to expend creating them. The pandoc method could make fancier products, but at a higher cost of time and labor, and it would require anyone making the PDF to have Pandoc, LaTeX, etc. set up on their local machine. The "print to PDF" option might be best, and perhaps we can even use CSS to make sure that a PDF printed from the browser looks very "article like" and professional.

**Comment by acrymble** [comment]
@wcaleb what's 'print to PDF' mean in this context? Is that a tool?

**Comment by wcaleb** [comment]
@acrymble On a Mac (and I believe also on Windows 10), there is usually a built-in way to create a PDF from a website. I'm most familiar with the Mac way, which involves going to the "Print" dialogue within Chrome or Firefox or whatever, and then looking for an option within that dialogue menu to save the page as a PDF. There are a variety of ways to do it within Windows [according to this](https://www.howtogeek.com/150891/how-to-print-to-pdf-in-windows-4-tips-and-tricks/), including some [websites that will do it for you](http://www.web2pdfconvert.com/), though the latter is less ideal for us because it generates a "watermark" in the footer of the file.

I'll add another point to my last comment, which connects back to something Matthew said. Maintaining an "HTML version of record" that doesn't change may be harder than it seems at first glance, especially when you take into account the images that need to be bundled with it. The virtue of a PDF is that it will "flatten" everything about the lesson---images and text---into one file that literally cannot be edited. And since not being able to edit it seems to be part of the goal here, I think PDF would be the way to go.

**Comment by acrymble** [comment]
I see what you mean.

One outstanding issue is any lesson with attached files. Data and code libraries. These aren't accounted for with the PDF. I'm not sure how many lessons that affects.

**Comment by acrymble** [comment]
I think I have a solution for an HTML version of record, which is better able to keep associated files together than PDF and can handle long lines of code. This is what people want to read anyway, rather than the .md file.

We can do a 'save-as' on the HTML page, which also means a standalone set of files that will render prettily. This can be bundled with any associated files (see attached 'versionOfRecord.zip' as an example) and then published in a long-term repository (I prefer Zenodo which is backed by CERN: https://zenodo.org/record/31026#.WVTbmYqQyi6) and linked back to our site in some simple way via the interface (list, link on lesson, etc).

Workflow:

* once published, 'save as' to download all files in easy-to-render format.
* add any code / data / image dependent files to the same directory (possibly update internal links to point to local dependent files using find/replace template)
* add a read me file (will need a template)
* zip it up
* post to Zenodo and get DOI
* Integrate with our own site (however we want to display these - via /versionofrecord page?).

I would suggest this be someone's 'role' like @jerielizabeth currently does the managing editor role. I could be done every 6 months or so (I can take the first shift since it's my idea).


[versionOfRecord.zip](https://github.com/programminghistorian/jekyll/files/1111728/versionOfRecord.zip)

**Comment by wcaleb** [comment]
Adam, thanks for outlining this alternative method. I think it gets us back to the question of what we most want these records for. I think we face a tradeoff between (a) design and aesthetic appeal, and (b) comprehensiveness of the snapshot.

The PDF method satisfies (a) but not (b).

Your method satisfies (b) but not (a), at least in my opinion. The HTML file in the zip won't be "styled" by our CSS sheet.

One thing that would help us better choose between (a) and (b) is trying to figure out what an author really will want from these records. If all the author wants is something that "looks like an article" to include in a promotion dossier, etc., then (a) may matter more, but on the other hand, and author can easily print her own lesson to PDF and achieve the same effect. On the other hand, if you think what most matters to an author is getting a comprehensive snapshot of the text and data associated with a DOI, then perhaps (b) is more important.

So I think our discussion today should focus back on the "what do we want these for" question, which will help make the decision about the trade-offs we are most comfortable with.
