### ISSUE TITLE
Validate lesson YAML with Travis CI

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#426]
Re: discussion in #425 

~Will hold off serious development until #414 is merged.~

**Comment by mdlincoln** [comment]
Some thoughtful additions for YAML frontmatter defaults in `_config.yml` would also ensure that all pages in `lessons` default to being `type: lesson` etc.

<https://jekyllrb.com/docs/configuration/#front-matter-defaults>

**Comment by mdlincoln** [comment]
After some fiddling about, it looks like it's not to hard to configure this using regular liquid tags alongside a little plugin that lets us intentionally raise errors that will cause Travis CI to fail.

[This is what the logic could look like](https://github.com/programminghistorian/jekyll/blob/validate_yaml/_includes/validate_lesson_yaml.html).

[And here's what the error report looks like in Travis](https://travis-ci.org/programminghistorian/jekyll/builds/230853076#L299).

I'm bothered that this currently stops the build immediately on the very first YAML error it encounters, rather than checking _all_ lessons before reporting back a list of YAML errors... but [I'm hoping someone in the larger Jekyll community might have an answer for this](https://talk.jekyllrb.com/t/how-to-properly-indicate-an-error-during-site-generation/447).

**Comment by mdlincoln** [comment]
A second alternative is to write a Generator plugin, in which the logic is defined in Ruby, rather than in liquid tags.

[What the code looks like.](https://github.com/programminghistorian/jekyll/blob/generator_validation/_plugins/validate_yaml.rb)

Pros: This allows us to run a check on all pages before stopping with an error, which [makes the build results](https://travis-ci.org/programminghistorian/jekyll/builds/231608895#L301) read much more like html-proofer.

Cons: We need to state the logic (which fields are required on which pages) within Ruby, rather than in liquid inlucdes. I have no personal issue with this, but I do wonder if it will make it more difficult for future maintainers to take over this repo.

**Comment by mdlincoln** [comment]
I'm leaning towards the Generator solution, but any thoughts @wcaleb @amandavisconti ?

**Comment by wcaleb** [comment]
Those results from the Generator do look very nice! Once the basic script is written, how easy would it be to document the process of adding new YAML checks to add? I'm presuming just adding a line or [modifying an existing one](https://github.com/programminghistorian/jekyll/blob/generator_validation/_plugins/validate_yaml.rb#L24)? If relatively easy, then that seems as sustainable as explaining to future maintainers how to add tags via the other method.

**Comment by mdlincoln** [comment]
Yes, if we document it well, I think it should be ok.

The logic might end up being a little more complicated than is in the present script though. For example, there might be different required fields for Spanish lessons, so there'd be an additional if/else loop. Not a deal breaker, but at least something to be mindful of.

**Comment by mdlincoln** [comment]
Given the number of new YAML fields required for lessons under the redesigned lesson plans, I think it would be good to merge this with the redesign, if only to make sure we've finished configuring each of the lessons for the new page.

I'm setting the current fields as "required" for all english lessons:

- title
- date
- authors
- reviewers
- editors
- difficulty
- activity (must belong to activites listed in snippets.yml)
- topics (must belong to topics listed in topics.yml)
- abstract (are we requiring this be done?)

**Comment by mdlincoln** [comment]
see below for latest build update checklist

**Comment by mdlincoln** [comment]
@fredgibbs Several lessons have `beginning` as an activity right now - do we think this should be added as an activity? Or a topic?

A series of older lessons do not have editors or reviewers listed. @acrymble @wcaleb should these be exceptions to the rule, or do they indeed have reviewers/editors that need to be added?

**Comment by fredgibbs** [comment]
i think most of the "beginning" lessons are more appropriately labeled as python lessons, as they are predominately about setting up for python coding. i don't like beginning as a category because there are too many things that someone might want to begin.  perhaps it would be useful to have a "basics" topic that could include stuff like the markdown lesson and command line, etc--generic stuff that many lessons might want to refer to (i don't think this applies to the lessons currently labeled as beginning, though)

**Comment by fredgibbs** [comment]
some of the offending lessons are the zotero ones, and they might be going away (i was the editor for these but they weren't really externally reviewed outside of a dh class context). some of the oldest lessons might not have external reviewers, but they should all have an editor.

**Comment by mdlincoln** [comment]
@fredgibbs Yes, I agree that "beginning" is not a meaningful term. Do all lessons _need_ to have both an activity and a topic? One or or the other? Neither? If they don't need any, I'll modify the plugin to not error on that.

For the older lessons, let's add the appropriate editor. I can also add a special YAML flag to them that releases them from being checked for having their reviewers.

**Comment by fredgibbs** [comment]
I would say that all lessons should have both, based on the possibly irrational principle that if someone were to click through all the buttons in each set, they should eventually see all the lessons (and wouldn't have to click through both sets to ensure that). i realize probably no one will ever do this, but it makes sense to me anyway. Also, this may have the advantage of, over time, revealing to us lessons that have been assigned to a category or topic that are not an ideal match (because there was nothing better), and that could be now grouped into a new category/topic (or that we need to tweak the existing categories/topics). That's harder to see when we can just leave the field blank because there isn't a great match when the lesson is published. Having neither would seriously compromise the visibility of the lesson; you'd have to scan through the entire set (less of a problem when first published, maybe, but something to avoid I think). This was obviously our approach from years ago but I think we have too many lessons now.

**Comment by mdlincoln** [comment]
@fredgibbs yes, I tend to agree with all that.

There's already a `get-ready` topic, so they're covered there. Most of the python lessons are under `transforming`, so I suspect I'd just put the installation lessons under that activity.

**Comment by mdlincoln** [comment]
Updated results:

* In /lessons/getting-started-with-markdown.md:
  - [ ] 'editors' is missing.
* In /lessons/googlemaps-googleearth.md:
  - [ ] 'editors' is missing.
* In /lessons/installing-python-modules-pip.md:
  - [ ] 'editors' is missing.

We either need to add editors, or I need some positive confirmation that these should _not_ have editors.

**Comment by acrymble** [comment]
Just checked the second one and it does have:

![screen shot 2017-06-23 at 08 54 45](https://user-images.githubusercontent.com/646647/27471998-a7da1892-57f1-11e7-9799-aac86cbb1175.png)
![screen shot 2017-06-23 at 08 54 23](https://user-images.githubusercontent.com/646647/27472000-a9822676-57f1-11e7-9b25-5732a7dc11f7.png)

**Comment by acrymble** [comment]
Markdown one was @ianmilligan1 (https://github.com/programminghistorian/jekyll/pull/61).

And the pip one has no editor. @fredgibbs posted it as a bridge for another lesson.
