### ISSUE TITLE
DH 2018 presence?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#430]
DH 2018 conference is in Mexico City. Since we've got a number of people fairly nearby, is there a way we can take advantage of that to promote the project?

I believe they do workshops in addition to papers. Thought it would be worth seeing if anyone is interested in representing us there in some way?

https://adho.org/announcements/2017/announcing-locations-dh-2017-and-dh-2018

**Comment by mariajoafana** [comment]
I'll be happy to explore this possibility! By the way, I'm moving back to Colombia this summer so I'll be even closer. 
What do you think @vgayolrs ? We could plan to do a workshop together?

**Comment by wcaleb** [comment]
I might be interested, too.

**Comment by acrymble** [comment]
It could be a good venue for a paper as well. Maybe thinking about how the needs of the Spanish and English communities differ in a DH pedagogy space?

**Comment by vgayolrs** [comment]
I plan to present a paper, and yes, we could put together a workshop too.
I think there will be a lot of discussion about the different ways of approaching HD in "northern countries" and "southern countries".

**Comment by arojascastro** [comment]
I'm not 100% sure if I will be able to attend. In any case, I think we should submit a paper proposal, work *everybody* who wants/can on it, and whoever can attend the conference should present the paper -- we all should get credit for the work we have done. At least that was my previous experience. When I have collaborated with other reserachers in digital projects, we usually draft a proposal together and submit it with multiple authors - it doesn't matter who is presenting it.

**Comment by acrymble** [comment]
I'd be thrilled to see us submit more research papers. Obviously no one should feel compelled to take that on if they can't or don't want to, since it's a big job.

The DH conferences tend to expect research though (as in a thorough examination of a question using evidence, leading to a conclusion), rather than opinion pieces or 'me and my project' papers.

If we did want to present research, we'd have to start doing some. A survey of Spanish community needs might be a good way of doing that. Or an analysis of the types of lessons people are trying to bring to us over time. Or a traffic analysis. Or something else entirely.

**Comment by arojascastro** [comment]
Yes, I agree. If we are presenting a paper it should be solid and present some interesting results. I tend to conceive the project as a bilingual corpus in English and Spanish because I am interested in language. Maybe we could present the project, political or cultural challenges, and then analyze a sample of lessons (available in EN/SPA) as linguistic data (grammar, vocabulary, syntax, etc.) using quantitative tools (R, Python, AntConc). For me the most interesting aspect of this project is how translators make choices about language.  But of course that is my approach as a philologist :). Otherwise, if that is not ok, we can submit a workshop proposal. In that case since Im not sure I will attend, I would not participate and no credit should be given, I think.

**Comment by acrymble** [comment]
That sounds like a fine research project to me, but probably one you'd have to take the lead on (as a philologist). You might face questions about whether or not you can analyse your own language choices, since you're involved in the project.

**Comment by arojascastro** [comment]
I can take care of the analysis of the Spanish language with @vgayolrs and @mariajoafana. Maybe we could invite a linguist to analyze texts in English? It would be nice to compare the corpus before and after the peer review process to find out what reviewers dislike and suggest to "delete" or "change" (specially when dealing with translations). In any case, the method should be similar for both corpus. We also need people to contextualize the project, give some background, provide interpretations, collect examples, etc. So in my view, this kind of research needs a multidisciplinary team. Anyway, let's reflect on this. I guess there must be more proposals and different approaches. Let's discuss!

**Comment by acrymble** [comment]
worth noting also that 2018 is 10 years since William Turkel published the first PH edition.

**Comment by arojascastro** [comment]
Any updates on this?

**Comment by vgayolrs** [comment]
Well, here is the call of papers [DH2018](https://dh2018.adho.org/cfp_english/).

**Comment by acrymble** [comment]
Is anyone actively interested in putting in a proposal? I think this is going to be too expensive for me.

**Comment by drjwbaker** [comment]
I might be going (if a panel we are plotting gets accepted)

**Comment by arojascastro** [comment]
I don't think I can make it, but I am interested in submitting a paper.

**Comment by ianmilligan1** [comment]
I’m trying to cut down on travel - having been on the road too much (gotta have time to do work!) - so I’m probably not going to go to DH 2018.

**Comment by walshbr** [comment]
I'm putting in another proposal or two on other projects, so I'm theoretically planning on being at the conference.

**Comment by acrymble** [comment]
I was more asking if anything wants to present PH at the conference.

**Comment by ianmilligan1** [comment]
Yep, although knowing if people are going to be able to attend or not does let us see if anybody could present it.

**Comment by vgayolrs** [comment]
@acrymble I would like to present something about PH. Could we work on it? What format do you think of? I want to propose a short paper to show my work in progress about the legal corpus, but up to two works can be proposed by author or co-author.

**Comment by mariajoafana** [comment]
I'm planning to attend as well. I can co-author a proposal about PH with you @vgayolrs if that sounds good. I might send another proposal as well

**Comment by vgayolrs** [comment]
Great @mariajoafana : "echémonos el trompo a la uña"! I wonder if anyone else wants to join us as a co-author and help define the presentation form. I think @acrymble , @ianmilligan1  and other team members have a lot to say. We have until November 27 to present the proposal.

**Comment by acrymble** [comment]
The theme is 'bridges', and I think this is a good opportunity to share our experience of bridging the PH project into the Spanish Speaking World. It's not a research paper, but more a reflection paper, so I don't know if they'd be interested in that.

**Comment by vgayolrs** [comment]
@acrymble we can try. I am in contact with several of the local organizers. We can see if they are interested. An interesting point is that this time the conference is bilingual (English-Spanish)

**Comment by vgayolrs** [comment]
Any other interested in participating as a co-author in the presentation of PH apart from Maria and me? Any suggestion of format? I'm meeting with the local organizers next week. Obviously taking into account that we will decide on this at the next editorial meeting, I would like to bring some idea of the collective voice at the meeting next week, if possible.

**Comment by acrymble** [comment]
If it's helpful to what you want to talk about, I can work with you to analyse our traffic statistics to get a sense of where in the Spanish-speaking world we've got people visiting from. If you're going a different road though I don't need to be involved as a co-author. I won't be able to present due to cost.

**Comment by ianmilligan1** [comment]
Hi all - I'm happy to bounce ideas around on the ticket or help with a set of eyes on an abstract, but I don't need to be a co-author. As noted I'm probably not going to DH 2018.

**Comment by vgayolrs** [comment]
Thanks a lot @acrymble  and @ianmilligan1  . I didn't writte anything yet, I just send @mariajoafana an email this weekend to start exchanging ideas. Hope this week we could have something clear. But here is what I have been thinking, and I think that socializing it with both of you (and anyone who wants to throw some ideas) is very important as I believe that we need build this together. I apologize because I am thinking aloud as I write, so please be patient!

I agree with Adam in present a reflection paper about the experience of bridging the PH project to the Spanish Speakin World. This is very interesting because there is a lot of reflections around about the digital gap between "north and south" countries. I don't want to get into the argument now about what we mean by that: developed-non developed countries, etc. But, indeed, there is a very important difference in the use of digital tools by academics in the social sciences and the humanities, between the Anglo-Saxon countries and the Spanish-speaking countries. It is certainly something that has to do with the level of development of the countries, but also with the cultural context and the idiosyncracy of the academies. Although historians have been using computers since the 1980s, there is not a single historian of my generation in the Spanish-speaking world who has a profile like Bill Turkel (I am only two years older than him). Let's not say a R. Rosenzweig or a D. Cohen. While there are colleagues who talk about "the digital in the academy" and reflect on their scope and limits, and others use various data analysis tools and many want to make nice web pages of their projects, no one or almost anyone writes code or understand how computers really work, thus losing a valuable research tool. So, here is an interesting question: Does the PH project act, or can it work as a bridge over this digital divide?

Now I know that there are many people in spanish-speakin countries who have been using PH tutorials in their university teaching for some time. So, it will be an important fact, @acrymble ,  know how much traffic has been derived from the site in English to the site in Spanish since its launch in March 2017, and from where they access. Of course, also know if the traffic of these countries has increased significantly. Besides, I just learned today -thanks to your issue # 624- that India is the second country that generates traffic on the PH website. So I entered Google Analytics and was not surprised that the first three Spanish-speaking countries were Spain, Mexico and Colombia (7th, 9th, 10th). But there are other data that would be interesting to analyze.

While we will not be able to know the real impact that this traffic has on the acquisition of skills until we know that the project was an aid or starting point for some research in the Spanish speaking countries, can we analyze the behavior of the users and draw some conclusions? Are there differences in behavior between English-speaking and Spanish-speaking traffic that we can measure? For example, I imagine that someone who continuously uses the website will throw a number of repeat visits and with long connection times. But I don't know, I have not become familiar with the analytical possibilities of this tool.

On the other hand, taking into account the digital divide and the absence of a consolidated digital culture, what is the perspective of the PH project in Spanish? In the short term, complete the translations will benefit the Spanish-speaking academic community with more access to learn digital tools. But, will we be able in the medium or long term to create our own lessons and contribute in another way to the project? I have always been a dreamer and I think it is possible. The route of the bridge is drawn, but it is necessary to consolidate strategies to strengthen it.

Well... some things to provoke brainstorming.

**Comment by acrymble** [comment]
In terms of India, from what we can tell it looks like there are a lot of
people using it in the equivalent of India's Silicon Valley to teach
themselves Python. I suspect it's not being used by historians.

Statistics on the Spanish lessons would be a good way of directing our
future efforts. Maybe prioritizing lessons that are similar to popular
lessons.

**Comment by arojascastro** [comment]
I decided to retire from this. I am hoping to submit a proposal for the EADH conference to be held in 2018.

**Comment by mariajoafana** [comment]
Víctor, you raise some important questions here. In terms of the presentation for DH2018 we could divide it in three parts: 
1. Bridging PH into the Spanish speaking world: larger picture: identify challenges to create a DH community of practice in terms of the history, culture and institutional settings in Spanish speaking countries.  Smaller picture: strategies to build Spanish speaking community around PH, results and challenges. (maybe compare and contrast the initial challenges of PH in the English speaking world? here some input from @acrymble and @ianmilligan1 would be great.) 
2. Traffic analysis of PH en español since we launched it: popular lessons, less visited lessons, country of origin of visitors, time spent on the tutorials. I guess there would be more things to analyze here... 
3. Future goals and challenges: Towards digital history lessons produced in the Spanish speaking world.

**Comment by vgayolrs** [comment]
Thanks @mariajoafana . I'm going to review the document you sent me. As the DH2018 meeting will be in Spanish and English, I suggest that we can make the abstract in Spanish with an English version so that @acrymble , @ianmilligan1  and everybody else who wants can comment and suggest how to improve it.

**Comment by mdlincoln** [comment]
I believe this discussion has moved to email / other channels right now? I'm going to close it - but please re-open if needed, and post a status update.
