### ISSUE TITLE
404 on a Scholars' Lab link

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#436]
Intro to Beautiful Soup is now reporting a 404 error on a Scholar's Lab link:

https://travis-ci.org/programminghistorian/jekyll/builds/233911805#L312

Before swapping it out for a Wayback Machine link, I thought maybe @walshbr or @amandavisconti might want a heads up 😄

**Comment by walshbr** [comment]
Ah thanks for the heads up! That is my fault - I rebranded/restructured a lot of that site earlier in the week. Hadn't occurred to me that I might be destroying a lot of external linking. 😄 

I want to get rid of the "scratchpad" branding for all those resources (I don't think scratchpad is too suggestive of the actual contents - they're just resources). I'll update our 404 error page to be more suggestive of where people can go to look for more info since you're probably not the only one linking to the old domain. That URL has just been updated to http://praxis.scholarslab.org/resources/bash, which should resolve fine.

Also - that URL checker is a pretty nifty addition to Travis! I'll have to look into that for Praxis…
