### ISSUE TITLE
how many editors do we need on the active list?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#460]
Question arising from meeting. How many editors should we have actively accepting lessons?

At the moment we have 4-5. @jerielizabeth

**Comment by walshbr** [comment]
A related question I have been kicking around in my head - what is a reasonable workload for an editor? Measured in lessons? Potentially impossible to say, since it has to vary person to person and situation to situation. But as a newbie, I keep wondering whether to volunteer for more things or whether (since I don't have a sense of the full scope of the work editing a lesson entails just yet) I already have enough. Hard for me to assess my capacity since I don't know what capacity is, I guess is what I'm saying. Feel like I could take on more, but I'm open to the idea that I don't know what I'm getting into.

Really difficult question, but it might help get to an answer for Adam's question as well.

**Comment by acrymble** [comment]
I have a personal policy of never having more than 2 active lessons in review at once.

**Comment by JMParr** [comment]
I have 1, and have volunteered for 2 that are not yet active. I think limiting myself to 2 or 3 active lessons at once sounds ideal.

**Comment by jerielizabeth** [comment]
I have had up to 3 in various stages of active development and review and that is definitely max for me -- I would agree that 2 is more sane.

**Comment by JMParr** [comment]
I could potentially take up to 3 active lessons if we're really in a pinch, but would prefer to keep it to 2.

**Comment by walshbr** [comment]
Thanks - that helps a lot. I've got two active, one audio one solicited that is getting its proposal revised, and then a blog post I'm helping push through.

**Comment by JMParr** [comment]
Perhaps one other way to look at it is to see how well we're doing with matching submission and current project team expertise. If we start to see similar lessons that sound great, but aren't a great match for the strengths of the current team, it may be time to put out a call for editors with those specific backgrounds.

**Comment by walshbr** [comment]
It sounds like 8-9 active lessons is our current capacity, then, with a bit of play if we're also trying to solicit lessons around specific areas of interest (geospatial, audio).

**Comment by acrymble** [comment]
I'm of the opinion that we should aim for 6 active editors by the end of the year. That gives us flexibility and, as Jess notes, potential for specific backgrounds.

**Comment by acrymble** [comment]
Picking up on @JMParr comment, it strikes me that we don't have any editors with a public history focus to their area of interest, and a few lessons have been pitched in that vein lately. Likewise with web development.

**Comment by JMParr** [comment]
I am able to do either, but have two active tutorials right now. It might
be worth a call for an editor or two to cover these areas.

**Comment by jerielizabeth** [comment]
By my count, our current max editorial capacity is 10 active lessons. We have 2 editors with multiple (capping at 3) and 3-4 editors who can take on 1 lesson (b/c they have other PH obligations). 

In a related note, we are currently at editorial capacity (all 10 slots are taken).

**Comment by acrymble** [comment]
Decision is to add 1 more editor at this time, via a subcommittee of @acrymble @JMParr and @walshbr .
