### ISSUE TITLE
Increase inline documentation

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#470]
As @acrymble noted in #469 

> I suppose I'm also wondering if our technical documentation is robust enough that if you got hit by a bus we'd still be able to understand the website.

In addition to the general getting-started notes in CONTRIBUTING.md, I'd like to work through most of the layouts/includes files and add some inline comments like I have written out in the [build.sh script](https://github.com/programminghistorian/jekyll/blob/gh-pages/_build/build.sh).

Broadly, this means documenting how the following work and interconnect:

- [x] All layout files (what does each one do, which YAML fields does it require to work, which includes does it point to)
- [x] All include files (what does each one do, which layouts does it impact?)
- [x] lessons.md and its includes need particularly good documentation.

I think these comments need to assume that the person understands the basics of how Jekyll and Liquid work - there's no point recreating 3rd party documentation. But some signposting as to how each layout file talks to each include file, and which data files it pulls from, would be incredibly helpful.

**Comment by amandavisconti** [comment]
@mdlincoln I'm working on the lessons.md commenting right now

**Comment by amandavisconti** [comment]
Any formatting rules for how we're commenting within markdown? I've seen:
`[//]: # "Comment"` (which I used in commenting lessons.md)
or
```
{% comment %} 
    Text
{% endcomment %}
```
or
`[](Comment text goes here)`

**Comment by mdlincoln** [comment]
oh HUH, I was naively using `<!-- -->`... but then I suppose HTML comments would get faithfully copied into the published files by Liquid/Jekyll.

**Comment by mdlincoln** [comment]
FYI @amandavisconti, we're now committing directly to the [`redesign` branch here on programminghistorian/jekyll](https://github.com/programminghistorian/jekyll/tree/redesign) so don't worry about sending PRs to Fred's repo.

https://github.com/programminghistorian/jekyll/issues/474

**Comment by wcaleb** [comment]
Here's a fairly extensive [discussion of commenting in Markdown](https://stackoverflow.com/questions/4823468/comments-in-markdown).

I think it would be best not to go with the HTML comments because then they will show up in the HTML source, where it won't make sense to someone viewing it because all of the Jekyll stuff will be gone. (An exception would be an HTML comment where you do want the end user to be able to view what the output below the comment is coming from.) But I think this issue is referring to Jekyll documentation to help us understand what's happening on the backend.

The Jekyll built-in comment tags seem like they would work well for this purpose, though they are somewhat clunky. Another possibility might be to use YAML metadata blocks with YAML comments, which would look like this:

```yaml
---
# Comment comment comment.
# Comment comment comment.
---
```

I haven't tested that out on GitHub pages to make sure it works, though. The virtue of the Jekyll comment tags is that it will be very visibly documented in Jekyll docs, making them easy to understand even in the "everyone who has ever worked on the Jekyll site gets hit by a bus" scenario.

**Comment by mdlincoln** [comment]
OK, that makes sense. Let's stick to the liquid comment tags:

```
{% comment %} 
    Text
{% endcomment %}
```

I'll go back and convert some of the additions I've already made to be liquid-compliant

**Comment by fredgibbs** [comment]
the liquid comments have the advantage, i think, of not spitting out the same HTML comments each time an include file is called. for instance, comments in the lesson_describe.html include file are repeated on the lessons.html once for each lesson--a lot of unnecessary data. whatever method we adopt, we should be sure that our final HTML output doesn't have more comments than we intend.

**Comment by mdlincoln** [comment]
@fredgibbs will add remaining comments to _layouts

**Comment by fredgibbs** [comment]
started with 9b5425c; others should scan to see if everything makes sense. directory.html was not commented because it will be removed in a future commit (30f55f8).

**Comment by mdlincoln** [comment]
@fredgibbs I think this reads very well. I'm happy with it if you are.
