### ISSUE TITLE
Refining Pitch to Proposed Lesson workflow

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#472]
Following up on an editorial email conversation, as a point for discussion at an editorial board call:

There is a bit of difficulty implementing the new proposed lesson tickets on the submission site. Pitches are coming in without learning objectives or a clear scope. The subsequent email exchanges between editors and prospective authors are taking a long time, resulting in Proposed Lesson tickets being delayed.

This is adding to editorial load without leaving a paper trail, and affects #460 and #461 so we should clarify how to use this more effectively.

**Comment by walshbr** [comment]
I can imagine having a second, off-GitHub space for tracking all contacts with authors in any stage. Say, a Google Doc where we just log our current engagements. But I worry that would duplicate the work of the tickets on this repo and that having an extra thing to keep track of and log on might complicate things too much. I think there used to be a wiki page where editors logged all of these things as well, but my sense is that was deprecated in favor of the Proposed Lesson tickets - someone who has been on the project longer could confirm. 

The only reason I could see for not making a GitHub ticket right away from first contact with the cultivated/engaged authors would be if a lesson proposal gets rejected - my sense so far was that we move to the transparent, open review process once we're sure things are accepted. We could make a third category - the "Potential Proposal" / "Potential Lesson" ticket, or something like that, that tracks these things but keeps the identity of the person we're in talks with anonymous. The template could be pretty minimal, something along the lines of:

"The Programming Historian is in communication with an author about a potential lesson on the subject of X. Y will be the point of contact with them. Z was the date of first contact. When appropriate and if the proposal comes to fruition, they will close this ticket and create a Proposed Lesson ticket for the lesson."

Another thing to do and keep track of, but at least things would be collected on GitHub.

**Comment by acrymble** [comment]
You're right, we did use the Wiki, but opted to go with tickets so that all activity was using the same system (github).

I'm in favour of your template idea. It doesn't name the author in case it doesn't move forward, but it would keep things recorded. We don't even really need to close the ticket if it goes through to full proposal stage. We could just continue the thread.

Let's discuss at the call.

**Comment by jerielizabeth** [comment]
Working from @walshbr suggestion -- If we want a ticket for everything that is proposed, regardless of the decision of the editorial team, we could change the workflow so that whomever received the initial email would make a new ticket right away. I think we could keep it as a "proposal" ticket but be even more minimal in the description. Something along the lines of:

"The Programming Historian has received a proposal for a lesson on [X]."

Subsequent comments on the lesson (or an edit to the ticket) would then document the assigned editor, the agreed upon submission date, the lesson outcomes, etc. When an editor agrees to the lesson, they would be assigned to the ticket. If the lessons does not work out, the ticket would be closed. 

If we do that, I feel strongly that we should keep the conversation about the proposed lessons in email, and not on Github.

**Comment by acrymble** [comment]
This is implemented, no? Can close? @jerielizabeth
