### ISSUE TITLE
Error with SPARQL lesson

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#478]
Re http://programminghistorian.org/lessons/graph-databases-and-SPARQL I think the BM SPARQL endpoint has updated. The line..

> Let’s find out how they store the object type information: look for the predicate `<bmo:PX_object_type>` (highlighted in the figure above) and click on the link for `thes:x8577` to navigate to the node describing the particular object type “print”

.. does correspond to the output of http://collection.britishmuseum.org/sparql?query=SELECT+*%0D%0AWHERE+%7B%0D%0A++%3Chttp%3A%2F%2Fcollection.britishmuseum.org%2Fid%2Fobject%2FPPA82633%3E+%3Fp+%3Fo+.%0D%0A++%7D&_implicit=false&_equivalent=false&_form=%2Fsparql

**Comment by mdlincoln** [comment]
@drjwbaker yes, it does look like they've done a slight restyling of their results page, and also that they are no longer `PREFIX`ing the BM thesaurus namespace. Therefore, instead of it looking like

```
thes:x8577
```

it looks instead like 

```
http://collection.britishmuseum.org/id/thesauri/x8577
```

The data are still the same.... but they do look different. I won't re-do screenshots, but it may be worth noting that both of those strings mean the same thing. 😧
