### ISSUE TITLE
translation needed for "deprecated" text

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#487]
https://github.com/programminghistorian/jekyll/blob/redesign/_includes/deprecated.html

n.b. I don't think this text is used yet on Spanish-language pages, but it will be at some point!

- [x] Translate text
- [x] Move text over to snippets, and implement it via lessons.html

**Comment by acrymble** [comment]
I think we could do better on the text in English. Something like:

This lesson was published on {% Date% }. The Programming Historian editors do their best to maintain lessons as minor issues inevitably arise. However, since publication, changes to either the underlying technologies or principles used by this lesson have been substantial, to the point where the editors have decided not to further update it. The lesson may still prove a useful learning tool and a snapshot into the techniques of digital history when it was published, but we cannot guarantee all elements will continue to work as intended.

**Comment by fredgibbs** [comment]
i think this is very nice @acrymble. 

i would also vote to remove the text (and page language logic) from a separate deprecated include file and put this directly in the lesson layout page, since it will only appear there (right?). i think we should reserve include files for code/text snippets that will appear on multiple pages. this will mean adding the text and its translation to the snippets.yml file as well, and this will make the lessons page code more consistent as well.

**Comment by mdlincoln** [comment]
I have put the new deprecation text in to this line in the snippets.yml file: <https://github.com/programminghistorian/jekyll/blob/redesign/_data/snippets.yml#L190>

It's ready for translation now.

**Comment by arojascastro** [comment]
Done! @mdlincoln @fredgibbs

**Comment by mdlincoln** [comment]
👍
