### ISSUE TITLE
Installing QGIS lesson needs update

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#503]
I'm in the process of translating the "[Installing QGIS](http://programminghistorian.org/lessons/qgis-layers)" lesson. Following the instructions, I tried to download QGIS 2.0.1 following this link to the [QGIS Download Page](http://hub.qgis.org/projects/quantum-gis/wiki/Download) but it redirects me to the QGIS [issue page](https://issues.qgis.org/login?back_url=https%3A%2F%2Fissues.qgis.org%2Fprojects%2Fqgis%2Fwiki%2FDownload)
Also, for the Mac instructions the [KyngChaos Qgis download page](http://www.kyngchaos.com/software/qgis) have changed and I can't find the link to download the GDLA framework package. 
The links and screenshots for installing QGIS2.0.1 and plugins need to be updated for the correct ones. @acrymble Should we contact the authors for this? As I keep going with the translation more issues might appear.

**Comment by acrymble** [comment]
if you haven't already gone through the whole lesson it probably makes sense to collect all problems before we decide how to address them. This looks like a minor change needed to some broken links, but there may be more substantial problems.

**Comment by mariajoafana** [comment]
Ok, sounds good

**Comment by vgayolrs** [comment]
@acrymble  @mariajoafana : As the current QGis version is 2.18.13, there are many deep changes since v.2.0.1. I suggest to follow the spirit of the lesson but to update everything to the latest version of the program to have an accurate and useful spanish version (not a strict translation). By example, I don't think the old GDAL versions (and GRASS) will work fine on Macs with El Capitan or Sierra.
All the historical GDAL (and GRASS, GEOS, etc) download versions are at [KingChaos archive](http://www.kyngchaos.com/software/archive)

**Comment by mdlincoln** [comment]
Does this mean that the original QGIS lesson should be considered for archiving? Or can these few broken links be fixed on the original?

**Comment by vgayolrs** [comment]
@mdlincoln , @mariajoafana , please give me a couple of days. I think that if we fix some links the lesson will work ok.

**Comment by vgayolrs** [comment]
@mdlincoln @mariajoafana , Lesson works fine with some minor changes.

Links in  original lessons must change:

Actual [QGIS Download page](https://issues.qgis.org/login?back_url=https%3A%2F%2Fissues.qgis.org%2Fprojects%2Fqgis%2Fwiki%2FDownload)

Must be: [QGIS Download page](http://qgis.org/en/site/forusers/download.html), in Spanish:  [Página de descarga](http://qgis.org/es/site/forusers/download.html)

For Mac users we need to change instructions a little:

You have to click on the link [KingChaos QGIS download page](http://www.kyngchaos.com/software/qgis). Once there, click on `QGIS 2.18.13-1`. It downloads version 2.18.13. Then go to "[Download Archive](http://www.kyngchaos.com/software/archive)" (left Software menu at bottom in the same download page). Under "Active Frameworks" chose GDAL `Complete 1.11` (for OSX10.8 to Sierra, at the top of the list).

Install Frameworks first, then install QGIS app.

Once installed, everything in the lesson works ok.

**Comment by mdlincoln** [comment]
@vgayolrs thank you for researching these changes. Can you please change the files yourself?

**Comment by vgayolrs** [comment]
Sure @mdlincoln . Only, I want to know the policy that we'll use in this case. The lesson generally works, but there is an upgrade in the software version and minor modifications to the text that do not harm the authorship or moral rights of those who wrote the lesson. Should we indicate in some note or some other way those changes or just make them? I think it would be the second because it is only an update edition. But I want to be sure. Thanks in advance.
