### ISSUE TITLE
guide for translators (es) not on menu

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#508]
I presume this is a minor oversight, because all of the other ES contribute links are:

http://programminghistorian.org/es/guia-para-autores.html

**Comment by arojascastro** [comment]
The guide for translators and the guide for authors are the same page. However, in that link there are two sections missing.

**Comment by mdlincoln** [comment]
@arojascastro What sections are missing?

**Comment by arojascastro** [comment]
Sorry! I was wrong. The problem is that the current list of steps looks a bit confusing to me. They look like headings so I was expecting some text after each step, but I only found text after the third where it actually the text starts. 

I think this could be solved if the spacing between the steps was reduced and also if we add a heading for step number 1, which is missing at the moment. Does it make sense?

**Comment by mdlincoln** [comment]
@arojascastro I just modified the headings for the instructions - hopefully it's more clear now.

**Comment by arojascastro** [comment]
@mdlincoln perfect! many thanks :)
