### ISSUE TITLE
Configure display of editor & translation-editor fields

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#522]
Once #517 has been fixed, we need to ensure that both the editor and translation-editor fields are displayed.

Quick fix?: concatenate both and display as multiple editors

Longer fix?: Create a separate translation editor display heading in the lesson layout.

**Comment by arojascastro** [comment]
The second? I would say that we should distinguish between the original editor and the translation editor because our work as translations editors is less important than the original editor's work. I mean, we only guide the conversation but we do not improve the lesson substantially because we must stick to the original content. Right? @vgayolrs @mariajoafana

**Comment by mdlincoln** [comment]
The lesson layout is now fixed to display this. @arojascastro lesson `editors` still need to be added to many of the ES translations. See #517
