### ISSUE TITLE
Programming historian as en epub?

### ISSUE THREAD

**Issue by symac** [programminghistorian/jekyll#531]
Hello,
before the holidays I was thinking about getting a copy of the website as en epub to read it offline during the summer. This does not seem seem to be an option at the moment, is this something that is planned or should I write my own parser if I want to have PH on my e-book reader?

**Comment by acrymble** [comment]
There is a downloadable version from 2016 available on Zenodo: https://zenodo.org/record/49873#.WXcAgNPyui4

Some of the lessons will have been updated, and obviously it doesn't include the newer lessons, but that might be useful to you.

If you don't mind the formatting, you can download all of the lesson files and accompanying images:

https://github.com/programminghistorian/jekyll/tree/gh-pages/lessons
https://github.com/programminghistorian/jekyll/tree/gh-pages/images

Otherwise, we haven't got an e-book option available at the moment.

**Comment by symac** [comment]
Thanks @acrymble for the fast answer, if I find time this summer, I will try to write a ph-epub exporter then!

**Comment by mdlincoln** [comment]
Closing because this has been answered - but @symac do be in touch if you end up writing an exporter!

**Comment by symac** [comment]
It has been a long time but I have been working on a first draft of something that would answer this request for an epub export. You can see a live version at http://phepub.geobib.fr/ 
The scripts used are available on github at https://github.com/symac/phepub

The most important thing to do at the moment would be to improve the CSS of the epub and check that it looks nice on various devices. At the moment only english lessons are taken into consideration, should be expanded to spanish. 

I will try to improve that in the next few weeks.

**Comment by drjwbaker** [comment]
Thanks @symac! Does any of the editorial team regularly use an epub compatible device (I don't). If so, could you take a look?
