### ISSUE TITLE
Difficulty is not displayed as metadata in Spanish lessons

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#535]
The YAML block contains that information though.

**Comment by fredgibbs** [comment]
the problem is in the difficulty.html include file, which is coded to display only in english. the proper solution is to move what's in that file to the _snippets include and code the difficulty.html file to pull from there as is the process for displaying other translation snippets (see the lessons.html template for examples).

**Comment by arojascastro** [comment]
I am sorry, I am afraid I am not enough profiency in Github pages to understand the problem. Maybe @mdlincoln can help us?

**Comment by fredgibbs** [comment]
I can fix this today if @mdlincoln hasn't already started on it.

**Comment by mdlincoln** [comment]
It's all yours @fredgibbs

**Comment by fredgibbs** [comment]
should be working with 8408b52
