### ISSUE TITLE
New Editorial Call coordinator

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#538]
I'd like to pass the baton on organising and leading our editorial calls. I've been doing it for a couple of years and I think it's time to let someone else have a go. I've also got a pretty punishing teaching schedule coming up this term, so I may not be widely available and that shouldn't hold the project back.

The role involves:

1) Sending out a doodle poll each month to find a date we can hold the call (traditionally in the last week of each month).
2) Setting up a ticket to set an agenda and solicit feedback from the group on issues to discuss.
3) Starting the Skype call and facilitating the discussion
4) Making notes on the agenda ticket and closing it when finished.

If anyone is willing to take this on, maybe likewise on a 1 year term as with the Managing Editor, I'd be very grateful.

**Comment by walshbr** [comment]
Have been doing the math on this in my head, and it seems like the options for it are pretty limited - maybe only me? Minus people leaving, stepping away for a bit, or heavily involved in technical/managing editor/translation parts of the project I think that would leave @alsalin and myself. Since @alsalin just started, I can take this on.

**Comment by acrymble** [comment]
Thanks @walshbr.
