### ISSUE TITLE
Spanish /lessons to filter by translation date?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#548]
Just noticed that /es/lecciones auto-sorts by the publication date rather than the translation date. If the purpose is to highlight new contributions from time-to-time, then surely we'd want the translation date to be the default sort column?

**Comment by arojascastro** [comment]
True! Yes, I noticed but I thought it was intentional. I agree that maybe it is better to sort by date of translation.

**Comment by vgayolrs** [comment]
Sounds good to me in order to highlight the new stuff. But I'm worried about the new automatic sorting system. For example, the Python lessons lost their organization as a series to follow step by step. I think that was a good guide for beginners in the old design of the website, because it was covering the procedure consecutively. Thoughts?

**Comment by mdlincoln** [comment]
Let me look in to modifying the code to sort by translation date - I'll have some time next week to work on it.
