### ISSUE TITLE
Conversation about goals for PH

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#552]
Issue to flag a conversation for our Editorial Meeting agenda.

With the change over in editors and with an increase in lesson proposals, it seems time to have a conversation as an Editorial team about what we want to build with _The Programming Historian_. I see this as important given our recent conversations about new lesson proposals and our recent conversations about updating lessons.

Some of the possible paths I can see or have been mentioned are: 
* _The Programming Historian_ as a curated curriculum for learning DH (similar to Software Carpentry); 
* _The Programming Historian_ as a methods publication (where you publish how others can reproduce your work);
* Something in between.

It would be useful to get a sense of the different goals the publication has had over time, and then clarify what this editorial team wants to push toward.

**Comment by acrymble** [comment]
I've dragged out the original pitch from 2011. The project very quickly evolved, but this is what it was originally pitched as (by me to Bill Turkel):

---

Academic publishing, meet the Internet. Most academics are suspicious of online work. The criticisms are justified; online publishing lacks peer review, the writing tends to be unpolished, and works are impermanent or frequently changed, frustrating attempts to cite. Those who support open access publishing – of whom there are many amongst digital humanists - dismiss the cost, sluggishness and rigidity of the academic publishing model. And yet relatively little work has been done to bring the two sides together. Instead, the conversations are dismissive and divisive. Digital humanists publish to their blogs or Twitter feeds, and traditional academics ignore them, while opting for more respectable places to publish. Rather than perpetuate the divide, a positive solution-based model is needed, one that addresses the concerns of those who support academic publishing and leads by example. This solution is a collaborative, open access version of The Programming Historian, which maintains rigorous standards, peer review, and relative permanence, while taking advantage of the flexibility of Web 2.0, Drupal and an engaged community.

This web-based project, of which NiCHE will be the “publisher”, will provide an infrastructure to allow members of the community to contribute modules (chapters) for review under a Creative Commons “by-sa” license. The editor(s) will try each module to ensure it is accurate and work with the author to ensure the lesson is comprehensive for our target user: an educated but non-specialist researcher interested in learning new techniques. Approved modules will then added to the collection. Quality modules will be sought over quantity of content.

To ensure the site does not become a code repository, mechanisms will be put in place to promote a linear learning model similar to a book, but with a bit of choose your own adventure thrown in. Authors seeking to make submissions will be required to build directly upon an existing module, or to ensure that their module is entirely self-sufficient. In this way readers can always find the beginning of a set of lessons, and contributors are encouraged to work within the existing structure. The image to the left shows how this collaborative building might look, colour-coded by contributor. The entire project may have several starting branches, depending on what type of project the authors seek to contribute: physical computing, text mining, website building etc.

**Comment by drjwbaker** [comment]
New person two-penneth.

This isn't Software Carpentry. SWC is - really - about the **in person** soft software skills taught in the gaps between the `grep` this and `pull` that bits (it is illuminating that SWC Instructor Training is a 2 day workshop on pedagogy that doesn't teach you how to teach SWC lessons but rather how you should approach teaching SWC lessons).

This - it strikes me - is about historians (or at least those in the historical humanities) publishing slightly-to-heavily genericised version of their method for other historians (or at least those in the historical humanities) to adapt, build on, take inspiration from.

The main useful thing it has lost over the years is "To ensure the site does not become a code repository, mechanisms will be put in place to promote a linear learning model similar to a book". I totally get why this hasn't remained a focus as PH has grown. But dedicated work to write in bridges between lessons might be a valuable task that could begin to fix the lack of "where next" that (some) learners may feel.

**Comment by jerielizabeth** [comment]
Thank you @acrymble for sharing that! 

@drjwbaker I agree -- it's not Software Carpentry, though we have had a few conversations with Greg in the last year about whether the lessons could/should be a base for a Carpentry-style curriculum. And I do like the idea of creating bridge pieces, and perhaps blog posts that help identify a "path" through the lessons.

Myself, I have been thinking about PH as a peer-reviewed collection of the variety of ways one can solve computational problems in history, in part because we have talked about PH as a journal for my tenure here. It sounds like there is also an "edited collection" vision of PH in the mix.

**Comment by walshbr** [comment]
To riff on the responses so far, I think my sense of PH has always been somewhere in between - an "edited collection of documented computational solutions to problems in the study of history that can also serve as a curriculum of study." Virtually nothing new there except that I put the proposed parts in the same sentence. I've always thought of PH as an important model for how teaching and professionally legible publications can work hand-in-hand.

If this is a conversation about the goals for the project as a whole, seems that these are distinct from the short-term goals that we might have at any one time in making the content of the project reflect that vision. Some ways in which we've tried to manifest that vision seem to be by cultivating particular lessons or bringing on particular editors. Seems like @JMParr and I were brought on to try and poke the project in particular directions, and calls like [this one](https://programminghistorian.org/posts/call-to-action) from @acrymble seem like another gesture towards trying to make the lessons themselves fit the vision of what the project should be. Seems like that post was at least partially successful, given the types of lessons that we have in the pipeline. And of course the efforts by the Spanish team towards internationalization and by the tech team towards redesign and sustainability both reflect particular sets of values and concrete actions towards them.

So I agree with @jerielizabeth that part of the conversation about what we would like the PH to be seems to require a discussion of the intermediate goals that we've had and the steps we've taken to address them. Also worth a discussion of which steps seemed to have been the most successful or meaningful, and what concrete things we might be able to do to enact our future vision - cultivating particular types of authors and lessons, for sure, but I also wonder how many on-the-ground one-off events we've done over the years? Am thinking of [this page](https://programminghistorian.org/research) in particular, which seems like evidence of opportunities we could explore. Thinking more about what kind of services, workshops, or events PH could offer in-person for people could be interesting. What might a bootcamp in open-access publishing or documenting workflows from us look like?

More thoughts from a new person, so someone with a richer sense of the institutional memory of the group might have reactions.

**Comment by acrymble** [comment]
My view is that this project should be a publication of workflows and methods that are peer reviewed. These should be preserved as are any publication throughout higher education. Any additional activity should, in my view, be a spin off initiative.

Sorry that's blunt, but I think we've gone around the houses quite a lot.

**Comment by walshbr** [comment]
Thoughts from #596 were that looking to specific actionables could help move this forward. #576 and #579 are options, in terms of gauging community feedback on our own sense of the PH goals, but open to other suggestions if anyone has them. Also aware that not everyone has been able to weigh in on this by skype yet, so we can revisit at the next call as well.

**Comment by mdlincoln** [comment]
@walsh I want to clarify what I said during the #596 call: this larger discussion is about the mission of PH, and @drjwbaker points out our mission statement appears to be on the front page:

>We publish novice-friendly, peer-reviewed tutorials that help humanists learn a wide range of digital tools, techniques, and workflows to facilitate research and teaching. We are committed to fostering a diverse and inclusive community of editors, writers, and readers.

I argue: **let's pin this large, abstract convo to substantive changes to that text in particular**, otherwise I agree entirely with @acrymble that we'll just keep going in circles for no reason. Does anyone propose changing the wording there? Is it (in)sufficient to communicate our shared intent? If so, then let's propose concrete edits to it. 

Items like #576 and #597 offer possibilities for evaluating such ideas, but first we need to articulate those ideas, such that they can then be opened to community discussion.

**Comment by mdlincoln** [comment]
FWIW, I find myself in agreement with that mission and have no changes to propose - but I could be easily convinced otherwise. I'd like to see those suggestions channeled into realized text, however.

**Comment by JMParr** [comment]
I find myself agreeing with the mission as well.

**Comment by ianmilligan1** [comment]
Sorry to have missed the call. For what it's worth, I really agree with the mission statement as published there. My vision has really been that we're a collection of high-quality tutorials that help students, scholars, researchers, etc. learn the basic ropes of digital tools and methods. By keeping it broad, that let's us do bread-and-butter stuff (text analysis) but also more fun stuff (signification!).

I do miss some of the connective tissue of the first edition, so coming up with more tangible pathways through lessons or some "lesson plans" for learners, but I think those are niche details that aren't incompatible with our mission statement.

**Comment by drjwbaker** [comment]
My suggestion at https://github.com/programminghistorian/jekyll/issues/596 for https://github.com/programminghistorian/jekyll/issues/576 (the survey, if we choose to allocate resources to do one, per https://github.com/programminghistorian/jekyll/issues/579) would be to have feedback ask those who complete the survey to check (or not) boxes that **directly** reference / pertain to the current mission statement. So, for example:

> I like the way the Programming Historian:
> _publishes novice-friendly tutorials
> _publishes peer-reviewed tutorials
> _publishes tutorials for humanists
> _publishes tutorials for historians
> _publishes tutorials on a wide range of digital tools, techniques, and workflows
> _publishes tutorials that facilitate my teaching
> _publishes tutorials that facilitate my research
> _ is committed to fostering a diverse and inclusive community of editors, writers, and readers.

> I would like the Programming Historian to:
> _publish advanced level tutorials
> _drop peer-review of its tutorials
> _target all humanists
> _concentrate on historians
> _focus on fewer tools, techniques, and workflows
> _focus on more tools, techniques, and workflows
> _concentrate on facilitating teaching
> _concentrate on facilitating research

Or something like that. You get the idea :)

**Comment by acrymble** [comment]
I don't think we can drop peer review without having to take on a substantial new workload ourselves. So I'd rather not ask that. I like the idea though of the list.

**Comment by drjwbaker** [comment]
@acrymble Agreed.. If we do a survey we won't put anything in that we are wedded to and/or don't want to do: I didn't put "I would like the Programming Historian to .. **not be** committed to fostering a diverse and inclusive community of editors, writers, and readers" for that reason :) 

My only thought here then - and this is getting into the specifics of a survey we haven't agreed to do so is probably a conversation for another day.. - is that if we have a 'I like..' for something (eg peer review) we should probably have an 'I would like..' that is a the opposite or builds on it (eg should have better peer review / should also publish non-peer reviewed lessons). Otherwise there is little point asking people if they like that we do something.

**Comment by JMParr** [comment]
I agree with Adam and James on not dropping peer review.

**Comment by alsalin** [comment]
I wonder if the "I like" section should instead let users rate the importance of all of these factors in their use of PH. a 1-5 system, one being "I don't care" and 5 being "this is so important and why I read PH." Then we can have a list of features and perhaps be better able to gauge what users find important. I think we could do a similar thing for the "I would like" - out of all these features, which do users want to see more. Some might not care about some features, while others would like to see multiple features added but with varying priorities.

**Comment by drjwbaker** [comment]
Maybe. I'm just adapting from an existing template I know of. The advantage of yes/no is that it is quicker and easier to fill out for those taking the survey and that it is easier for us to interpret (1-5 ratings are notoriously hard to interpret).

**Comment by mdlincoln** [comment]
@alsalin @drjwbaker since you're mostly talking about survey design now, please put those comments over in the appropriate issues.

**Comment by mdlincoln** [comment]
I certainly do not mean to cut off any discussion, so please by all means please reopen if anyone has more to say... but it seems that there aren't any fundamental changes being requested of our front-page statement as it stands now.

Let's keep that statement in mind as we go forward with things like community engagement and our sustainability/archiving discussions.
