### ISSUE TITLE
Host Audacity Example in Assets

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#591]
Given the recent tickets about moving linked assets into the repository itself, I was just investigating the file that the Audacity lesson uses for mixing. The track I use there is in the public domain, so we should be good for hosting it ourselves. I'll move it into the assets folder when I get a chance and rewrite the text of that portion of the lesson so as to link internally rather than from MusOpen.

**Comment by arojascastro** [comment]
@walshbr wrote:

Hosts the asset for the Audacity lesson locally instead of on Musopen. Should be more sustainable this way.

Also pinging @arojascastro as this lesson just came up for translation - programminghistorian/ph-submissions#134. Just a couple paragraphs changed in the beginning.

Changes visible here: https://github.com/programminghistorian/jekyll/pull/610/files
