### ISSUE TITLE
Update Spanish Omeka lesson with new captions

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#598]
The English version of this [lesson](https://programminghistorian.org/es/lecciones/poniendo-omeka-a-funcionar) has been updated with new captions as can be seen here: https://github.com/programminghistorian/jekyll/pull/593

We need to check for changes and update the captions.

**Comment by acrymble** [comment]
Are these English updates being sent for re-translation? Or are we relying on @arojascastro to notice?

**Comment by vgayolrs** [comment]
@acrymble : I think @arojascastro realized that the update was made because it was announced at #593. But we need a more precise mechanism to know wich translation needs updating.  Is there no ongoing discussion on this? It would be good to define a workflow for updates that includes a direct warning to Spanish editors (i.e. when somebody make an update, please mention a spanish team member in the "commit" window and this will allow us to keep track of everything).

**Comment by mariajoafana** [comment]
I'll take care of this update

**Comment by mariajoafana** [comment]
Done

**Comment by arojascastro** [comment]
Muchas gracias @mariajoafana ! Exactly, @vgayolrs, please take into account our lessons when you make updates! @acrymble @mdlincoln
