### ISSUE TITLE
Datasheet

### ISSUE THREAD

**Issue by MrMethodmanMAN** [programminghistorian/jekyll#608]

**Comment by walshbr** [comment]
Hey @MrMethodmanMAN - I got an email with this content about the issue here. Did you sort this out? I'm suspecting yes, since the issue was edited to have no description. If not, I might need more information. It looks like both links are going to the correct data files to me, so if you could point me to a particular paragraph I can investigate further.

```
Hi,

I was attempting to follow your tutorial but I have trouble with the link to the two datasets.
One dataset should be for Person and the other for Relations. However both links direct me to Relations. I suspect that you have linked sheet 2 twice as apposed to linking 1 and 2. Or I am misreading them.

Thanks in advance
Stephen
```

**Comment by MrMethodmanMAN** [comment]
Hi Brandon,


Apologies  for the bogus notification.

Yes both links are correct. I was unfamiliar with the format of google docs and did not realise that there was a tab

on the bottom left of the screen for navigating between datasets. I attempted to remove my comment not to distract future commentators, however I could not delete so instead I removed the content. I have just finished the tutorial on community detection and I found it very informative. Thanks again for the tutorial , your manner of explanation is very clear and to the point and the links and footnotes provided were very edifying.

Keep up the great work.

Best

Stephen

________________________________

**Comment by walshbr** [comment]
Glad you found the lesson helpful! I'll close this then as the issue is resolved.
