### ISSUE TITLE
Snipets of Spanish new lesson page must be translated

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#623]
@mdlincoln : there's a little detail on the new Spanish lesson page, which you could possibly help me sort out: https://programminghistorian.org/es/lecciones/

When I choose a filter for the types of lessons (by date or by difficulty or by topic), some of that information appears in English and some in Spanish.

For example, "filtering results" should be translated to "resultados de filtrado", "all lessons" to "todas las lecciones", "date" to "fecha" and "difficulty" to "dificultad", and so on. When I filter by `data management`, I get the correct sentence in Spanish (`gestión de datos`).

I tried to find if there is a code file to do it, but I only found the animated gifs in this folder: https://github.com/programminghistorian/jekyll/tree/gh-pages/images/new-lessons-page

If you tell me where I can go to translate these fragments, I will thank you very much.

**Comment by mdlincoln** [comment]
Thank you for pointing this out. I can see where the issue is: right now, lessonfilter.js tries to reference the snippets.yml file in order to get the proper language terms for these buttons. This does not work like it does on other HTML pages, however - because although lessonfilter.js gets called by both lessons.html and es/lecciones.html, Jekyll only renders the js file once - and when it does, it defaults to the english snippet terms. If you actually visit the [rendered javascript file](https://programminghistorian.org/js/lessonfilter.js) you'll see most of the `text()` components have filled-in english terms.

A solution would entail somehow defining all the necessary javascript terms in the respective HTML pages first, and then calling those variables using lessonfilter.js. That way, the snippets are rendered correctly, and lessonfilter.js doesn't have to "know" what the page language is, or use any Liquid `{{}}` includes at all. 

I don't know enough JS right now to do this myself, unfortunately. @amandavisconti do you think you might be able to help out here?

**Comment by amandavisconti** [comment]
Realized I'm not going to have time to look at this soon, so if anyone else is willing to take a look—please do!
