### ISSUE TITLE
Spanish Team and Editorial Responsibilities

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#636]
Based on a conversation at #617 - several people thought it would be useful to clarify the responsibilities of the Spanish team as they relate to the editorial duties of the rest of the board more generally. 

1. Is the assumption that the Spanish team can also take on regular editing of lessons?
2. Is their work exclusively on translation?
3. Is there a possibility for them to edit lessons originating in Spanish and then move them to English?

My own sense has been that point one was true in theory, but that point two has been true in practice as a courtesy. The magnitude of work remaining on translation is such that those responsibilities take up their time. And it seems like, ultimately, we would want to move in the direction of points one and three anyway, if the goal is to offer a journal that truly works across languages and uses either as a point of entry. But would love to hear thoughts from those who have been with the project longer.

**Comment by arojascastro** [comment]
I am very pessimistic about this. Translating lessons, reviewing, editing and mantaining the web is already a lot of work. I mean: take into account that not only one of us is acting as an editor, but also as a reviewer, since our pool of reviewers is very small, and sometimes even as translators. 

Ideally, yes, it would be great to be able to edit lessons and to work on original content -- although I do not think we will get any proposal. In any case we should expand our team with new members if we are taking it seriously. I barely can keep the track of all the review tickets, web maintance changes and pull requests.

I think we need at least 3 editors that review and edit lessons -I insist we all three usually edit and review translations- and 1 member who is focused on the maintenance of the website only and can deal with pull requests and changes that you make.

**Comment by drjwbaker** [comment]
@arojascastro Thanks for your input Antonio. That is what I feared. From the outside I always thought the ES translation work was *awesome*. And I still do. What has become clear to me since I joined is that your labour is perhaps not fully understood or accounted for, and your workload bordering on unsustainable.

In the call I suggested we take some time to think carefully about what we think the ES work is and what we want it to be. After having a think on the drive home last night ere is where I am:

- I think at the moment (to use @walshbr's bullets) the ES work is 2., the way we talk about it externally is more like 1., the way we behave about it as editors is more like 2. (the phrase "ES team" I keep using suggests as much), but where we want it to be is a combination of 1. and 3.

- The question from this becomes: do we add to the ES team to ease the existing translation workload (so everyone on the ES team does less work) or to spread the load so that the ES team be more fully integrate and do more of 1. and 3. (so everyone on the ES team does about the same amount of work)?

**Comment by arojascastro** [comment]
I am happy with function number 2. I am very pessimistic about 1 and 3 because a. we are not native English speakers; and b. we have not received any offer to edit original content so far. I do not see any problem with number 2 function, for me translating content is already a great work and I learn a lot from editing. We do not have, however, a unified vision of this topic because we (Victor, María and I) have not discussed at all so far. 

I do believe we need more Spanish members, as I said. Three or four editors, that only translate, edit and review, and one person who is in charge of the maintance of the web. At the moment, we are all three working as translators, editors, reviewers and at the same time doing maintenance work. I do not know what @vgayolrs and @mariajoafana think about this either, because we have not had the chance to talk about -- so this is uniquely my personal view.

**Comment by acrymble** [comment]
The original job spec (if I can use that term) was to build a community, not just to translate. https://programminghistorian.org/posts/spanish-editor

It took us years to build up a pool of reviewers and authors. There was no English-language community for this either when we got started. But we know how we got where we are, so we can help advise on building a Spanish community too. 

If the project stays as translation only, then I fear we won't have English and Spanish on an equal footing. English will always be dominant.

**Comment by arojascastro** [comment]
Yes @acrymble nothing against building a community, but that is easier to say than to do... my point of view is pragmatic - it is a lot of work for three people.

**Comment by walshbr** [comment]
Thanks, @arojascastro. Much of that resonates with what we were discussing on the call. Part of the goal of this conversation, I think, was to try to assess what is realistic for all of you, what might be aspirational, and what steps we can take to connect the two more. Also to more clearly articulate what were assumptions vs. reality. So this is all helpful for me. 

And the need for more people seems totally reasonable to me, and certainly a way to offset the English dominance that @acrymble is suggesting. A related question I was thinking about when writing the issue: we've talked about what might be considered a typical capacity workload for those of us taking on lessons, and the consensus seemed to be that two active lessons at any one time was capacity. Do you three have an operating sense of what might be a reasonable workload for translations for the Spanish team? That might help us get a clearer and more quantifiable sense of just how overworked/understaffed you are. Looks like in practice it is translating about one lesson at any one time. And to echo @drjwbaker - I'm endlessly impressed by the amount of work that you all take on, the quality of what you produce, and the speed with which you do it.

**Comment by arojascastro** [comment]
Thanks @walshbr .  We do not have any policy about how many lessons we can take. But for instance, this last October I did the following tasks:

- Review the lesson edited by Victor on Data mining: https://github.com/programminghistorian/ph-submissions/issues/59
- Review the lesson edited by Maria on Google Earth: https://github.com/programminghistorian/ph-submissions/issues/130
- and I am currently acting as editor of the lesson on Audacity: https://github.com/programminghistorian/ph-submissions/issues/134

In addition, I did some maintenance work, I think. On the other hand, I have three lessons assigned for translating that are awaiting for me and that I will not finish in time because I do not have enough time.

**Comment by drjwbaker** [comment]
@arojascastro Just so I am super clear. When you say about "it is a lot of work for three people". What is the goal of "it"?

1) Is the aim to translate all the lessons? 
2) Or are you being selective? (that is, some will not be translated)

If 1), do you have a monthly/quarterly target and would one way of reducing workload - whilst still getting a new ES editor - be to reduce the targets for lesson translation given that other translation matters arise as well (site wording, revisions to translated lessons, et cetera)

**Comment by arojascastro** [comment]
I think our aim is to translate all of them... but honestly we @vgayolrs and @mariajoafana have not talked about this. We do not have any monthly or quarterly target, we just contribute to as many as tickets we can. Of course, it would be good to control somehow our work, because I tend to review and edit, and I would like to translate sometimes. The problem, I think, is that if I say *No, I have reached my target*, then Víctor or María's lessons -where they are acting as editor or translator- are blocked for weeks. The same applies to lessons edited by myself. Somehow we all three are contributing to each others tickets; otherwise, if we depend on external collaborators, lessons are blocked for months. 

On the other hand, I do not know if my colleagues agree with me.

**Comment by mariajoafana** [comment]
Hi all, thank you for bringing up this discussion. As mentioned before, Víctor, Antonio and I have taken up different roles: website maintenance, translating, editing, revising, and reaching out for the Spanish speaking to bring in new collaborators.  I've felt tempted to participate in discussions about incoming English lessons but to be honest, timewise this is difficult. 

I agree with @arojascastro , our aim is to translate all lessons and also, as @acrymble mentioned, to help build a community. This last part has been very challenging. The digital divide is real, and It will take some time to build this community. One step at a time. For now, translating the lessons and starting to use them in the classroom (which I'm doing in the DH classes that I'm teaching) is a starting point. I also agree with Antonio, It will take some time to start getting lessons in Spanish. 

Translating is a time-consuming task (I've started to work on the QGIS lessons and haven't been able to comply with my own deadlines, even more since I moved back to Colombia, I've been very busy), but finding people to revise the lessons has been challenging as well. So, looking for another Spanish editor to collaborate with us sounds like a good idea to me.

**Comment by acrymble** [comment]
Someone based in the US could apply for funding through ACLS to bring in a community builder (http://www.acls.org/programs/digitalextension/). I'd apply, but it's only open to US-based scholars. That would free up some energy to build the Spanish user base so that others could focus on the translating.

The scheme is meant to "Extend existing digital projects and resources with content that adds diversity or interdisciplinary reach". Up to $125k and 18 months.

**Comment by acrymble** [comment]
I think we should add another Spanish speaking member of the team to contribute to the activities described above.

I also agree with @drjwbaker that it would be good to set clear limits on how much everyone intends to do each month so that no one feels overburdened. We want everyone to feel valued, not exhausted.

**Comment by mariajoafana** [comment]
The Spanish team agrees with this. I already wrote the call for a new member of the Spanish speaking team. We can plan on publishing on the blog this week. Shall we publish it in English as well? I guess this will allow the call to circulate more broadly

**Comment by acrymble** [comment]
Can you circulate it via the email address so we can see it first?

**Comment by mariajoafana** [comment]
Yes, I'll translate and send it during the weekend.

**Comment by mdlincoln** [comment]
Are there any further changes to policies or descriptions that need to be made to the website now? Let's close this issue unless there is some other deliverable that needs to come out of this discussion other than the new editor call.

**Comment by mdlincoln** [comment]
@mariajoafana @arojascastro @vgayolrs are there any other changes we need to make to site text as a result of this? Or can we close?

**Comment by arojascastro** [comment]
I think it can be closed @mdlincoln. However, in the Spanish version of [team] (https://programminghistorian.org/es/equipo-de-proyecto) there are two contact persons for Spanish. I think we should have only one because otherwise it is confusing. What do you think @vgayolrs and @mariajoafana ?

**Comment by vgayolrs** [comment]
@arojascastro , I agree.

**Comment by arojascastro** [comment]
Ok, quieres ser tú @vgayolrs o yo?

**Comment by mariajoafana** [comment]
I agree, puede ser yo también si quieren.

**Comment by arojascastro** [comment]
Gracias @mariajoafana, de momento puedo hacerme cargo. Si acaso, más adelante podemos turnarnos por temporadas. 

Should I close this?
