### ISSUE TITLE
Edinburgh Geoparser translatable?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#647]
Comment on Twitter:
<img width="296" alt="screen shot 2017-11-04 at 13 20 07" src="https://user-images.githubusercontent.com/646647/32405728-aa9afc2e-c162-11e7-98f0-fd6d0dc2c56b.png">

https://programminghistorian.org/lessons/geoparsing-text-with-edinburgh

Just wanted to check, is this going to be translatable into Spanish? Or is the geoparser language-specific?

**Comment by ianmilligan1** [comment]
I’ll check with the author.

**Comment by arojascastro** [comment]
I may be wrong but the point is that Geoparser only recognizes named entities in English; I have never used it but I checked the website and I did not see any way to change the language parameter or whatever. So if anyone translates this lesson, s/he will have to use the text in English - because it will not work with texts in Spanish. 

What do you think? @vgayolrs @mariajoafana 

On the other hand, maybe it would be good pracrice to accept the publication of lessons that takes into consideration how dependant the content is on language. 

Examples:

- is it possible to use texts in different language other than English? Then it may be accepted
- can you use resources that are transnational (for instance Europeana)? Fine!
- are you using tools that are available in different languages? Perfect!

In my opinion, if the PH is committed to open access and free tecnologies, it may be good idea to extend its committment to multilingual tecnologies as well... of course a first step could be tecnologies that are localisation friendly...

**Comment by bea-alex** [comment]
Hi,

Thank you for your comments. 

The Geoparser download only works with English texts at the moment.  I'm sorry for the oversight.  We'll change the title to specify English text.

We have supported other research groups to adjust it to work with French text in the past but this functionality is not available in the default download.  To change the Geoparser to work for text in a different language you'd first need to change the tokeniser (e.g. to recognise accented characters, if the language uses them) and would need to use a different part-of-speech tagger (the model used at the moment is trained on English text).  You'd also need to translate some of the rules for matching names in text.  This would take a bit of time but technically it is possible. While the lesson does not cover how to do this, it could be something I could focus on in a more advanced lesson.  We are also interested in developing the Geoparser with new uses in mind.  We have ported it to French for another project, so if there is demand then this functionality definitely is something that we can look into making available more widely.

**Comment by ianmilligan1** [comment]
We can have the discussion re: "good pracrice to accept the publication of lessons that takes into consideration how dependant the content is on language" in a different thread (my own vote would be while it's a consideration, I don't think it should be a final determining factor).

I will change the title and close this.
