### ISSUE TITLE
need clean way to add 'suggested next lesson' link

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#67]
some of the lessons are part of a logical chain of lessons. But we've lost those links. How do we want to reinstate that? Yaml?

**Comment by acrymble** [comment]
@wcaleb, do you have a preference for how I do this? Just a straight HTML link at the end of a lesson?

**Comment by wcaleb** [comment]
I liked your idea of handling this with YAML, since it's a structural metadata issue that should be separated from styling. I would go through the relevant lessons and add key/value pairs to the YAML block that look like this

```yaml
next: code-reuse-and-modularity
prev: counting-frequencies
```

Where the value is the page slug of the relevant lesson. Once these have been added, I can add something to the Jekyll template that will produce links to them at the bottom.

**Comment by acrymble** [comment]
Ok.

**Comment by acrymble** [comment]
I think I've added this all. @wcaleb, when you add this to the template, can you use suggestive language (suggested next lesson, or you may find this lesson easier if you have completed X)? That way we don't enforce a pathway on people but give them signposting.

**Comment by wcaleb** [comment]
OK, I've changed the layout with 4c8db16119b5b09bab3ab11facb7138d0cbd8635. Feel free to adjust the wording if you want. If we want to improve the "look" of these links later, we can do that with CSS.
