### ISSUE TITLE
Adding collaborators to "Equipo"

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#695]
As noted by @acrymble here https://github.com/programminghistorian/jekyll/issues/684, at the moment in the spanish version of the [team page](https://programminghistorian.org/es/equipo-de-proyecto) the information is not updated and we can only find English speaking collaborators (under the section "community participants"). We should udpate the list and add the reviewers and translators of the Spanish edition. 

However, should we keep them the En and Spa independent? Should we remove the English collaborators in the Spanish version of PH and viceversa? Or make two sections? Or mix the whole list? 

This issue is related to issue https://github.com/programminghistorian/jekyll/issues/600

How can we keep track and give credit to all our collaborators? Are we duplicating efforts? Excel, Team page, list of translations... etc.

**Comment by mdlincoln** [comment]
The "community participants"/"Participantes de la comunidad" texts are produced by collecting all the names in `_data/ph_authors.yml` and `_data/reviewers.yml`.

Looking at the way these are structured now, from a technical perspective, it's probably better for us to generate these lists directly from the lesson metadata, so that we don't have to maintain separate running lists at all. I can fix that, and then all the names on both the English and Spanish lessons will be collated together automatically.

I think both the English and Spanish lists should be the same, as a way of highlighting the truly massive and diverse community that powers the _The Programming Historian_. One question for the Spanish team: do we want the translators to have their own special section of acknowledgement? Or list them alongside the other reviewers and contributors?

**Comment by arojascastro** [comment]
Great! @mdlincoln It would be great if we could collect them automatically. I agree we should list translators, authors, editors and reviewers all together. Let me know if I need to do anything.

**Comment by acrymble** [comment]
This sounds fantastic, but @mdlincoln just remember that this would mean updating the editor guidelines (not a problem, we just can't forget).

**Comment by mdlincoln** [comment]
Also @mariajoafana I've noticed in doing this that we have two different variations of your name around the site. Is the first one, without the `í`, correct?

1. `Maria José Afanador-Llach` 
1. `María José Afanador-Llach`

**Comment by mdlincoln** [comment]
I made a PR #704 please see the small bit of translation needed there.
