### ISSUE TITLE
Current Research Projects or Submissions Pending about the Programming Historian

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#721]
At #708 it was noted that it would be helpful to know what research projects people on the board are undertaking with the project. We were thinking about workshops, grants applied for, articles under review. We're intending for this issue to be open in perpetuity. Open to suggestions for how to go about maintaining this. Feel free to modify the text here based on what you'd like to see or to comment below with questions.

Outstanding Programming Historian Submissions

- [x] DH 2018
- [x] EADH 2018

**Comment by drjwbaker** [comment]
Thanks for opening @walshbr. Lets make it a standing agenda item for each call as well.

**Comment by alsalin** [comment]
May Update!
- 39 submissions so far
- All submissions so far consider themselves to be more advanced than novice, >4 (1-6)
- 2 non-academic positions 
- primary discipline: History
- Text analysis reigns supreme 26/39, data cleaning 25/39, GIS 1, data vis, 21, network analysis 11/39, web development 17/39, statistical analysis 1/39, VR 2/39
- People are finding PH through primarily social media and/or going directly to website (but is this because we are only marketing the survey on Twitter and the blog?)
- People generally us PH for reference and as a learning tool for the first time
- Improvement suggestions
-- making tutorials for global audience
-- more variations on a theme, ex python both structured and unstructured text
-- more traditional journal-like listing of lessons - can be difficult to tell how old a lesson is from browsing page
-- more advanced lessons x 2in python, more APIs to other databases, advanced AI for algorithmic historiography 
-- variety of technical levels for lessons x3, updating lessons
-- better search options x6
-- FR language lessons x2 :)
-- guides on what i need to learn to do X task more efficiently 
-- lessons in German x2 (also someone volunteered their services)
-- combine lessons into learning paths
-- combo of written and video tutorials
- for the most part lessons are easy to understand and get up and running
- instructions for authoring and reviewing for the most part clear
- things we could do better
-- open call for topics/techniques

**Comment by amsichani** [comment]
Hi @alsalin fab stuff! should we move this comment to #576?

**Comment by alsalin** [comment]
@amsichani ack! I had too many tabs open! sorry >.<

**Comment by arojascastro** [comment]
The deadline for the EADH conference is 18 June. Is anyone submitting a proposal? I want to write something about the Spanish translations, but I am open to co-author as well. The topic should be about "data in the Humanities"...

**Comment by jenniferisasi** [comment]
@arojascastro I was not going to submit anything myself (lack of time to do so) but I am willing to co-write something with you and, potentially, others about our translations and data. I'm thinking something along the lines of our impossibility to translate the tutorials in full due to data in other languages.

**Comment by arojascastro** [comment]
Thank you @jenniferisasi. That topic is super interesting and I am 100% in. We shall also provide some data as well because the main theme is "data in the humanities" so maybe the "untranslatability" may be a liminar case only? I'll create a Google Doc and then we can start drafting a proposal.

For the record: I am happy with collaborating and submitting any proposal with anyone - either they can travel to Ireland or not. However, when we discussed about the proposal for DH2018 it seemed that attendance was a condition sine qua non (issue #430).

What do you think?

**Comment by arojascastro** [comment]
I am analyzing the original lessons in order to get some data:

## Authors
- Name
- Gender
- Affiliation
- Status
- Research Field
- PubYear
- Place

## Editors
- Name
- Gender
- Affiliation
- Status
- Research Field
- PubYear
- Place

## Contents
- Title
- Topic
- Keywords
- Mentions
- Examples
- References
- Language (obviously English)
- PubYear

I also want to analyzie the *ideal* reader / user, but I am figuring out yet how to do that. Anyway, **I am wondering if somehone else has attempted to do something similar** -- if so we could share data  or merge data.

I am planning to do the same with the translators and translations editors. 

Any feedback?

**Comment by acrymble** [comment]
What's your research question?
And secondly, do you need ethical approval for your research?

**Comment by arojascastro** [comment]
My research question is about translation as a communication act. In order to assess translations I need to characterize the source authors and the source message. 

Why I need ethical approval? I am not publishing their personal data, only showing numbers.

**Comment by arojascastro** [comment]
I remember @acrymble you sent us some charts about editors weeks ago.

**Comment by acrymble** [comment]
It's generally up to your university's ethics board (assuming they do such things in Germany) to decide if you need ethical approval or not. You're dealing with living persons as research subjects, so they might think so. I merely raise it to suggest you check with them so you dont' get into trouble.

I can check if I still have those data you mention. Give me a few days.

**Comment by arojascastro** [comment]
Thanks. I will wait for your data if you want to share.

**Comment by amsichani** [comment]
@arojascastro @jenniferisasi  I am very keen to collaborate / contribute on a PH article for the EADH2018! I like also the topic of translation - multilingualism for pedagogy purposes. Lets move the discussion to a new ticket.

**Comment by arojascastro** [comment]
Cool @amsichani. We may discuss our ideas via email all three? From my point of view translation and multilinguism are different topics; there are different types of contributions (short papers, long papers and panels), so I am sure we will sort it out something.

**Comment by amsichani** [comment]
@arojascastro do we really need a separate gh issue or should we work directly on gDoc for the proposal?

**Comment by arojascastro** [comment]
I think on Gdoc. I'm sending you the link now.

**Comment by spapastamkou** [comment]
Hi all, Humanistica, the French-speaking association of Digital Humanities, fosters DH workshops on 17 October in Lille, France (as part of the dhnord2018 conference). @mpuren and I are interested in proposing a workshop on the FR version of the PH. The aim would be to make known it exists, work on finishing existing translations, for example by inviting reviewers (and respecting the usual procedure through use of github); and perhaps gather or at least discuss on ideas for new lessons. Could we count on your ideas, opinion or/and feedback on that? Thank you

**Comment by arojascastro** [comment]
Last update about EADH2018: Anna-Maria, Jennifer and I managed to author a proposal, that we submited yesterday - notification will be sent in some weeks. 

Now, replying to @spapastamkou - I think a workshop on Markdown, Github and maybe Pandoc can facilitate a lot collaboration because these are mainly the tecnologies that we use to edit and publish our lessons. On the other hand, Köln is not very far from Lille so if you think I can help somehow, let me know.

**Comment by spapastamkou** [comment]
@arojascastro @amsichani @mpuren on the Fr workshop, please find info here for the CFP https://www.meshs.fr/page/dhnord2018_aac
We could further  exchange on the form this workshop can take in the coming days. Thank you

**Comment by amsichani** [comment]
thanks @spapastamkou . Correct me if I am wrong, but the deadline for workshops' proposals was 31st May . Do you have any insights on this?

**Comment by spapastamkou** [comment]
Yes, we had presented a proposal with @mpuren in the original deadline but
after thought it was maybe premature, especially as we had not yet
discussed the idea with the rest of the team. So we told the organizers
that it was perhaps better not to count us in but they are really
interested in the workshop. This is why I posted. If we can agree on the
form, I think that the summer holidays really work for us at the time
being:)

**Comment by amsichani** [comment]
Can you share in a new ticket this original proposal, so we can start discussing it there and see how it might evolve?

**Comment by spapastamkou** [comment]
Info and exchanges on Fr workshop are now on #944.

**Comment by amsichani** [comment]
Hey, just to let you know that our  (@arojascastro, @jenniferisasi + @amsichani ) long paper submission " Data science and the language question in digital humanities pedagogy: the example of Programming Historian" for [EADH2018](EADH2018) has been accepted !

**Comment by jenniferisasi** [comment]
María José, Antonio and I have submitted a paper proposal for [ACH 2019 Conference](http://ach2019.ach.org/): "Retos en la producción de tutoriales de HD en contextos hispanohablantes"

**Comment by amsichani** [comment]
just a quick update: @drjwbaker , @walshbr , @mariajoafana and I are preparing an article on PH and diversity for [Insights](https://insights.uksg.org) , to be submitted by Feb 2019/

**Comment by arojascastro** [comment]
I saw this cfp for Debates in DH with a focus on Pedagogy: https://www.briancroxall.net/2019/01/24/announcing-debates-in-dh-pedagogy/

We should send a proposal. Who is in? Deadline: 1 April

**Comment by arojascastro** [comment]
we need to update /research with our EADH talk

edit: I already updated
