### ISSUE TITLE
Display of translation vs. original published date

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#772]
This seems a bit confused right now in the Spanish lessons. I'll sort out what's going on and report back...

**Comment by arojascastro** [comment]
Maywe we can do:

- Publicado --> Publicado en inglés (published in English) 
- Modificado --> Traducido al español (Translated into Spanish)

Any thoughts? @jenniferisasi @jamotilla @mariajoafana

**Comment by jenniferisasi** [comment]
To keep with the style I would go along the lines of @arojascastro's suggestion but only one word each: Publicado, Traducido. Since they will carry different dates I think it's self-explanatory that it was published in English and then translated into Spanish?

**Comment by arojascastro** [comment]
True... unless we translate a tutorial from French... Otherwise:

- Publicado originalmente
- Traducido del inglés

Normally in books you can read the source language... but it is true that for us it is self-explanatory... I do not know.

**Comment by acrymble** [comment]
If these are publications (which I think they are), then the Publicado date should be the translation date, no?

**Comment by arojascastro** [comment]
So you suggest to remove when the English original was published and just to keep the translation date? I am not sure if I understand, but again in printed books you find both dates - when it was published originally and when the translation was released.

**Comment by jenniferisasi** [comment]
@arojascastro well, yes, if we translate from another language (I cannot translate from French, btw) let me reword: only one word each: Publicado, Traducido. Since they will carry different dates I think it's self-explanatory that it was published in another language (the original) and then translated into Spanish? 

@acrymble I see what you mean (both are publications), but I agree with Antonio that we need to have both dates and indicate clearly which one is the original and which one the translation as opposed to originals published in Spanish (that will carry the 'publicado' tag). In this manner, when/if the French team is formed they can also keep the same system.

**Comment by mdlincoln** [comment]
I tried implementing this, you can see a preview in #780 

Using one word only certainly simplifies the technical side of things, especially if I'm trying to design this to work with 3+ languages. I think it also gives the pertinent info: the original published lesson date, and the date of the translation the user is looking at right now.

(Ideally, the original lesson will have links going to its 1+ translations... but that's a different issue)

**Comment by arojascastro** [comment]
Cool. Thanks. Should we merge?

**Comment by drjwbaker** [comment]
Looks awesome. Great job all. When you are done, ping me and I can use this fresh new data to get the ES lessons listed on DOAJ #698

**Comment by mdlincoln** [comment]
Just to clarify for everyone, the metadata have always been there, we're just making it visible on the public HTML pages now.
