### ISSUE TITLE
corresponding author details

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#83]
As we need to revise or contact authors from time to time, I think we need to keep a list of contact details for a corresponding author who will field enquiries. This should be part of our long-term sustainability plan

**Comment by nabsiddiqui** [comment]
I can probably do this.

**Comment by acrymble** [comment]
I think we have most of it from past correspondence. What we'll have to decide is where to keep it. Presumably we want it private?

**Comment by wcaleb** [comment]
I think we should encourage authors to at least provide a website, Twitter feed, or email publicly in our `_data/authors.yml` directory so they can be contacted by readers as well as by editors. I can tweak the Jekyll template so that some sort of contact information is provided in the "about the author" box. This is pretty standard, I think, in journals nowadays, so unless someone has a strong reason for not wanting *any* contact link provided publicly (which seems unlikely to me), I think our default should be to make it publicly available.

**Comment by acrymble** [comment]
fine with me.

**Comment by wcaleb** [comment]
Is this something I could suggest to a Summer Fellow as a project? Or is @nabsiddiqui still willing to contact authors to get information? If so he could submit a Pull Request with an updated version of the `_data/authors.yml` file. Logistics may be worth discussion on next editorial Skype.

**Comment by acrymble** [comment]
This is over a year old. I suspect we don't need it if we haven't had any cause to do it. Reopen if needed.
