### ISSUE TITLE
Broken logo links on editorial team page

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#841]
I'm seeing github and twitter logos broken at [https://programminghistorian.org/project-team](https://programminghistorian.org/project-team). I know there is a some shuffling of files going on - eg at #826 - but not sure if this is connected. Happy to fix if someone points me the right way (I need to start getting more comfortable with our web deployment).

**Comment by walshbr** [comment]
Check out PR #842 @drjwbaker - it will take a second for the netlify preview to update. I think I got them fixed locally though. Sorry to not give you a chance to work on this! In trying to figure out where to point you it turned out to be a pretty easy fix. I'm happy to talk a bit more with you about the web deployment, if you'd like, though I'm certainly no expert.

**Comment by drjwbaker** [comment]
No worries. Thanks for the fix. Another time.

**Comment by mdlincoln** [comment]
Whoops, sorry for breaking that. Thanks @walshbr for fixing it.
