### ISSUE TITLE
Adding PH to Publons?

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#891]
I am not sure if this is relevant for the project, but I created a Publons profile in order to track my tasks as editor and journal reviewer: https://publons.com

My profile is empty because I still need to fill in: https://publons.com/author/1402241/antonio-rojas-castro#profile

 I would like to add *The Programming Historian* to **Editorial Board Memberships**, but it is not listed in their database. I was wondering if we could do something in order to be listed there. 

It may also be a good place to look for reviewers - if you search field, you can get a list of scholars that are supposed to review manuscripts. In any case, Publons is associated with ResearchID, but I do not know if a company is behind it like Academia.edu. Does anyone know more? Is it worth the effort?

**Comment by acrymble** [comment]
I don't know anything about it, but happy to hear more.

**Comment by arojascastro** [comment]
I can't find if this is a free service for publishers here: https://publons.freshdesk.com/support/solutions/articles/12000012231-what-is-publons-and-why-partner-with-us-

Should I contact them?

**Comment by acrymble** [comment]
what benefit do you see from it?

**Comment by arojascastro** [comment]
The only benefit is that I could list the Programming Historian in my profile. There's no free text where you can type the name of the journal, you can only select journals from their database. But we are not in their database :(

**Comment by acrymble** [comment]
This isn't somethign I'd personally find beneficial, but I recognize other people may. What would we need to do to get in their database (and stay in it)? Does it require maintenance work on our part?

**Comment by arojascastro** [comment]
I dunno know yet. I should contact and ask because their instructions are not clear.

**Comment by andrewtothemax** [comment]
Hi all,  Andrew Harrison here from Publons.  I've added [Programming Historian](https://publons.com/journal/91925/programming-historian) to our database so that you can add your peer reviews, editorial board memberships, and handling editor records for the journal to your Publons profiles.

If you would be interested in learning more about our reviewer recognition product (providing automated recognition to your reviewers) please contact us at partnerships@publons.com.

Thanks!

> It may also be a good place to look for reviewers - if you search field, you can get a list of scholars that are supposed to review manuscripts. 

We are also developing a more sophisticated reviewer search tool.  You can ask about that via the same address above.

> Publons is associated with ResearchID, but I do not know if a company is behind it like Academia.edu. Does anyone know more? Is it worth the effort?

Publons is a Clarivate Analytics company (hence the ResearcherID association).

**Comment by arojascastro** [comment]
Many thanks @andrewtothemax for adding the journal to your database and for the clarifications. I'll update my profile on Publons.
