### ISSUE TITLE
Conditional ISSN display based on page language

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#892]
Once we have a distinct ISSN for Spanish PH (re: #788), we need to

- [ ] make the footer display the correct ISSN depending on page language.
- [ ] About pages show correct ISSN per language

**Comment by acrymble** [comment]
Lets just have it display both and make it clear there ate two

**Comment by mdlincoln** [comment]
@acrymble I'm concerned that the "show them all simultaneously" solution breaks down once we have three with the French team?

**Comment by drjwbaker** [comment]
Agree with @mdlincoln. Footer for EN pages should display EN ISSN, footer for ES pages should display ES ISSN, et cetera.

**Comment by acrymble** [comment]
Just to be clear what I'm suggesting, it's a vertical listing of all of the project's ISSNs in the footer, looking something like this:

ISSN XXXX-XXXX (English)
ISSN XXXX-XXXX (Spanish)
ISSN XXXX-XXXX (French)

--

That would involve slightly redesigning the footer css because at the minute it is in a sentence. The advantage of this is it provides an easy way to put some extra links to the other language versions and highlights the way the project fits together.

**Comment by mdlincoln** [comment]
I see where you're coming from @acrymble - you are right that it can also help to make clear that there _are_ different ISSNs for the different languages. 

What about: listing all three ISSNs in the footer, but highlighting or **bolding** the one for the present page language? And/or adding text like `current page` next to the ISSN?

**Comment by acrymble** [comment]
English ISSN: 2397-2068
Spanish ISSN: 2517-5769

**Comment by mdlincoln** [comment]
Closed by #912
