### ISSUE TITLE
PH-Submissions and Search Results

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#896]
We've gotten a couple bug notices now from people who were reading the ph-submissions version of a lesson rather than the live, published version. re: #895 - Alicia Peaker found her way to the ph-submissions repo by doing a google search (our ph-submissions lesson was a top hit). Am I right in thinking that we want to hide the ph-submissions repo from search results so that people aren't pushed to old versions of our lessons? And, if so, what steps can we take to do that? Seems to me that we want to use that repository for the review process and archival purposes, but we don't want people to find that instead of the published texts if they're just coming in from google.

I've noticed this from the API lesson, which for whatever reason might be higher in google's search results. Other lessons might not be as much of an issue.

**Comment by mdlincoln** [comment]
Like, do we make the THIS ISN'T THE REAL PH banner even bigger? idk

**Comment by walshbr** [comment]
Ha - I was wondering if there was something like

<meta name="robots" content="noindex">

we could do for the ph-submissions site, but I'm not familiar enough with SEO to have any real recommendations. If not, then yeah we can just leave it.

**Comment by mdlincoln** [comment]
In all seriousness, the other possibility is to exclude the `/lessons/published` folder from the jekyll build, so that published lessons no longer have their drafts published on the ph-submissions website. This would mean you would need to look at the raw markdown file instead of a rendered html page if you wanted to go look at the early draft of a lesson. But it seems like we have far more users confused about ending up on draft lesson pages than we do users struggling to locate early draft lessons to consult them. I'd say just stop publishing HTML.

**Comment by mdlincoln** [comment]
As for hiding the still-under-review lessons, I suppose we can add a `robots.txt` that ought to stop Google from crawling the pages... I'll research it.

**Comment by walshbr** [comment]
Yeah I was thinking the latter

**Comment by mdlincoln** [comment]
Because `robots.txt` is a little tricky to establish with GitHub pages, I'm giving the robots `meta` tags a try: https://moz.com/learn/seo/robots-meta-directives

**Comment by drjwbaker** [comment]
To confirm, do this mean we keeping draft builds? I suspect they are useful for reviewer readability.

**Comment by mdlincoln** [comment]
In absence of further work on this, I'm closing.
