### ISSUE TITLE
Worldcat entry in Spanish

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#901]
Thanks to @amandavisconti we have a Worldcat entry for the project in English (http://www.worldcat.org/title/programming-historian/oclc/951537099). Does anyone have any library friends that could help us get one in Spanish as well?

**Comment by vgayolrs** [comment]
Yes, @acrymble , I know someone. Let me take this.

**Comment by mariajoafana** [comment]
So happy to see that @vgayolrs is back ;)

**Comment by acrymble** [comment]
@walshbr just a reminder from the last editorial call, you're going to look into whether or not your university can publish this worldcat entry, since @vgayolrs does not have a subscription.

**Comment by walshbr** [comment]
Yep yep - I talked with Amanda about this, and she gave me some things to follow up on. I'll report back.

**Comment by walshbr** [comment]
The metadata person who can help with this is out until next week, but we're going to work together on this. I'll update soon.

**Comment by vgayolrs** [comment]
Thanks @walshbr 
Good news. I am in contact with [COLMEX](www.colmex.mx) librarians (whose [library](http://www.worldcat.org/webservices/registry/Institutions/46331) has an OCLC subscription) and next Monday I will request the inclusion of a PH entry in Spanish and also in English (it is better to have several entries in different libraries, as they explain to me). Hope update sun.

**Comment by walshbr** [comment]
Good news - http://uva.worldcat.org/title/programming-historian-en-espanol/oclc/1061292935

Our cataloger had some corrections to send in on the English entry as well. It should be noted as well - we had no place of publication listed because, I assume, we don't really have an office anyway. Our cataloger suggested the "Authors" listed as sponsoring institutions based on current conversations about budget lines and where the servers live.

One question we had though - related to this issue but might bear breaking into its own ticket:

Technically our numbering system has the Spanish PH starting in 2016. But the first actual translations weren't released until 2017, and the blog post announcing the Spanish project launched in 2017. So, unless I'm missing something, the very first Spanish publications are currently listed as volume 2, with Spanish volume 1 being a phantom volume that doesn't exist. Is that intentional or something we want to keep? Or would it be easy enough to update the suggested citations to start numbering from 2017 instead? For the OCLC cataloging purposes, the librarian here listed it as starting in 2017.

**Comment by arojascastro** [comment]
You are right @walshbr about the Spanish numbering. The team was recruited by October 2016 but we didn't publish anything until 2017. Can we correct the numbering and the catalogue entry? It doesn't make any sense to have a phantom number 1.

**Comment by walshbr** [comment]
@mdlincoln - this would be a question for you since I didn't work on that aspect of the repo. It would cause an issue for anyone who happens to have cited the current volume numbering system in the last few months since we implemented it, but would probably be better to correct sooner rather than later if we do want to do so.

**Comment by vgayolrs** [comment]
Hi everybody:
On Monday, I asked the director of the COLMEX library to include PH in its catalog, so Colegio de México Library have incluide PH information as you can see in [this query](http://colmex-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?search_scope=52COLMEX_ALL&institution=52COLMEX&vid=52COLMEX_INST&query=title,contains,programming+historian).
 Hope there will be a register at WorldCat next to the one they [included at Virginia U](https://www.worldcat.org/title/programming-historian-en-espanol/oclc/1061292935&referer=brief_results).

**Comment by acrymble** [comment]
@drjwbaker does this affect #897 ?

**Comment by drjwbaker** [comment]
@acrymble I don't think so, unless WorldCat can link through to DOAJ.

On publication location, how easy is it for us to request changes? (I see that per what @walshbr says above, PH ES is listed as published in Brighton, which is fine for now but I'd like to think we can diversify..)

**Comment by walshbr** [comment]
@drjwbaker - I'm a librarian by coincidence rather than training, but my sense is that we'd just need a cataloging librarian to submit the changes. 

I think before there was actually no publication listed for the English listing, presumably because there is no real location for the project. We chose Brighton based on TBA conversations, as it seemed like this location was the only real, likely to be lasting-ish link to a particular location and institution rather than a particular person that we have at the moment. If there are other institutional links beyond simply the fact of having a board member at a place then we could include them. 

Edited to mention re: point 1 - I'm happy to just have our cataloging person update the location if we want changes. She said it was pretty easy re: the volume numbering to make changes.

**Comment by walshbr** [comment]
This can be closed, right @vgayolrs?

**Comment by acrymble** [comment]
Is this the entry? https://www.worldcat.org/title/the-programming-historian-en-espanol/oclc/7062703631&referer=brief_results

If so, do we need to add it to the main site under 'add us to your library catalogue'?

**Comment by arojascastro** [comment]
That's a review of the project: http://clionauta.hypotheses.org/16979

**Comment by walshbr** [comment]
This is the one my library put together - https://uva.worldcat.org/title/programming-historian-en-espanol/oclc/1061292935

**Comment by acrymble** [comment]
Thanks @walshbr.

So we need to add this to the /contribute pages:

https://programminghistorian.org/en/contribute
https://programminghistorian.org/es/contribuciones

But I think we need to wait for the French infrastructure page publication to be complete. So this will have to be on hold.
