### ISSUE TITLE
Replacement for ES first contact for translators and authors

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#934]
Hi,

I would like to step down from the role of "first contact" for authors and translators of the PH ES. I think that means finding someone else and replacing my name with his/hers in these pages:

- https://programminghistorian.org/es/contribuciones#%C3%BAnete-a-nuestro-equipo-de-revisores
- https://programminghistorian.org/es/guia-para-autores#traducir-o-proponer-una-lecci%C3%B3n-nueva

Additionally, the chosen person should take care of the list of pending translations and current assignments (an monitor that the deadlines are updated): https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md

Who would like to take this role?

**Comment by mariajoafana** [comment]
Hi, I can take the role starting in September, as right now I have plenty on my plate, mainly the preparation for the PH writing workshop on August. After this, I'll be happy to take the role. 
If you want to step down right away, I suggest that someone else volunteers.

**Comment by arojascastro** [comment]
I guess it could be a rotating role. So if someone is wanting to try for some months from now on, it would be great. If not, I'll wait until Maria can take it. It's up to you really.

**Comment by acrymble** [comment]
On the English team we have made the Managing Editor role (which is what this is) a September-September one-year thing. Up to you, but that might make it easier to coordinate, and gives people an idea of how long they're committing to something.

**Comment by arojascastro** [comment]
Yes, that's the name: "managing editor" rather than "first contact".

**Comment by jamotilla** [comment]
Hi, i can help with that, next semester i´ll only teach one course.

**Comment by arojascastro** [comment]
Oki doki, I can wait until September. No problem :)

**Comment by vgayolrs** [comment]
OK. I'll wait until the beginning of September to make the changes in the pages.

**Comment by acrymble** [comment]
Do we have a list of pages that need to be updated? @mariajoafana has agreed to take on this role this year (I think).

It looks like we need to update:

* https://programminghistorian.org/en/project-team
* https://programminghistorian.org/es/equipo-de-proyecto
* (the french equivalent of the above)
* https://programminghistorian.org/en/feedback
* https://programminghistorian.org/es/retroalimentacion
* (the french equivalent of the above)
* https://programminghistorian.org/en/contribute
* https://programminghistorian.org/es/contribuciones
* (the french equivalent of the above)
* https://programminghistorian.org/en/author-guidelines
* https://programminghistorian.org/es/guia-para-autores
* (the french equivalent of the above)

And Wikipedia:

https://en.wikipedia.org/wiki/Programming_Historian

Since we'll need this information next year, I'll also add it to the Wiki.

**Comment by acrymble** [comment]
I'm going to close this and open up a language neutral ticket because we have to update the above pages, but we know who is going to be taking over the new roles.
