### ISSUE TITLE
Proposal for a PH workshop during the DH Nord 2018 conference

### ISSUE THREAD

**Issue by mpuren** [programminghistorian/jekyll#944]
@amsichani @arojascastro @spapastamkou  This is the original version of a proposal for a workshop around the Programming Historian:

**Ressources en libre accès pour la formation et l'autoformation des historien•ne•s aux méthodes numériques**

**Objectifs**
La proposition de cet atelier part d'un constat : alors que les usages de documents et de données numériques de la part des historien.ne.s évoluent rapidement et vont croissants, leur formation ne suit pas au même rythme. Une des questions à considérer de ce point de vue est celle des ressources en français sur les méthodes numériques, et plus particulièrement celles destinées au premier chef aux historien.ne.s. On trouve en effet de nombreuses ressources en anglais, mais la mise à disposition de ressources francophones, accessibles en libre accès, permettrait de renforcer la communauté des humanités numériques françaises, de mieux tenir compte des besoins spécifiques des historien•ne•s en matière de numérique, mais aussi de fournir des ressources pour l'enseignement des humanités numériques en direction des historien•ne•s, et plus largement de la communauté francophone des sciences humaines et sociales. Cet atelier est ouvert à la participation de toute personne intéressée à contribuer activement à l'effort de multiplication des ressources francophones en libre accès, qui peuvent servir à la formation des historien.ne.s, mais aussi à ceux qui utilisent ce type de méthodes au sein de leurs disciplines respectives. En ce sens, il vise aussi à fédérer un travail commun qui peut s'organiser sur place autour d'actions spécifiques. Une des actions à envisager est celle de la traduction collaborative en français de parties du Programming Historian https://programminghistorian.org/ dont une édition francophone est en cours de préparation.
Durant l'atelier, il pourra s'agir:
- soit de la traduction de parties qui seront par la suite soumises à la relecture via Github sur l'espace du projet ;
- soit de la relecture de parties traduites. L'évaluation par les pairs ouverte étant le modèle suivi par le ProgHist, les contributeurs seront clairement identifiés. Cette action contribuerait à la mise en ligne prochaine de cette édition, et pourrait aussi repérer et lister les besoins en vue de la préparation de cours originaux dans l'avenir.
D'autres actions sont envisageables sur proposition des personnes qui participeront à l'atelier.

**Organisation**
Organisé dans le cadre du colloque DH Nord 2018, cet atelier a pour but d'accueillir des historien.ne.s, et plus largement des chercheur•se•s en sciences humaines et sociales. Les participants pourront être intéressés par le projet de traduction en français du Programming Historian, non seulement en vue de créer de nouvelles ressources ouvertes francophones, mais aussi de réfléchir sur les pratiques induites par la traduction collaborative. L'annonce de l'atelier sera non seulement diffusée via la manifestation, mais aussi via les listes DH francophone, e-NumHist, Quanti ou encore grâce au réseau de l'association Humanistica.

**Matériel nécessaire**
Chaque participant devra disposer d’un poste de travail.

**Durée envisagée**
3 heures

**Comment by spapastamkou** [comment]
I remind some elements about the context here. 
Humanistica, the French-speaking association of DH, hosts a series of workshops in Lille, France, on 17 October. The day is associated to the dhnord conference (15-16/10) but independently organised by the association. 
CFP ban be consulted here: https://www.meshs.fr/page/dhnord2018_aac#dhnord2018_ateliers
A very large proposal was presented (cf. supra) for a PH Fr workshop that actually allows to model it as we best think.

**Comment by spapastamkou** [comment]
Just an idea we can discuss on: since @amsichani and @arojascastro could very probably participate, the workshop could maybe look like smth like that: 
- intro to the PH (global and ES editions, short prez of the FR one) 
- prez of the way work is done on github for publication/translations of the lessons 
- organise with the participants reviews of translations of the lessons we can have from students of the Ecole des chartes. Depending on their level, perhaps emphasis could be be given on a github workshop as @arojascastro suggested?  
Please share your ideas

**Comment by acrymble** [comment]
I suppose the question is what do you want out of it? Do you want to attract reviewers? readers? authors? team members? do you want other people to adopt our github system? If we know the goal, maybe we can suggest more targeted ideas.

**Comment by amsichani** [comment]
I agree with @acrymble - we need to focus on a specific & well-structured task/goal, given that the workshop is only 3h.

**Comment by mpuren** [comment]
Our goal would consist in starting to create a strong French-speaking community around the project, and by doing so attracting new participants  - especially reviewers because we need to build and maintain an active and wide community of reviewers. 

Concerning Github, it was first mentioned in the proposal that some basic Github knowledge was a pre-requisite. But I deleted this sentence because it could seem scary for some of the possible participants - even if they were interested by the project.

**Comment by spapastamkou** [comment]
Sorry for my delay to contribute to this, here are some thoughts.
In lines with all above and the CFP objectives we could organize a translation workshop aiming to obtain reviews/corrections for the texts already prepared by the students of the Ecole des chartes (master Digital Technologies applied to History). In particular, translations of the following lessons are either entirely or almost ready:    

- Intro to Augmented Reality with Unity
- Intro to Linked Data
- Georeferencing in QGIS
- Understanding Regular Expressions
- Cleaning Data with OpenRefine
- Creating an Omeka Exhibit
- Generating an Ordered Data Set from an OCR Text File
- Preserving Your Research Data
- Editing Audio with Audacity
- Up and Running with Omeka.net
- Exploring and Analyzing Network Data with Python
- Web Mapping with Python and Leaflet
- Installing Omeka
- Python Introduction and Installation

We can associate Thibault Clérice @Chartes-TNAH, head of the master, and/or members of his team to the preparation of the workshop. A minima they provide the files of the texts, which is already essential:)  

So, roughly, the workshop could start with an intro to the PH, then continue with work on the reviews and end with publication of the results (if not immediately then shortly after the workshop). 

If you find the idea stands, we can then work to prepare precisely each part. Intro to the PH could be taken in charge by a small delegation (any volunteers @amsichani @acrymble @arojascastro @drjwbaker ?); I believe review tickets for these texts should be opened before the workshop by @mpuren and me; and perhaps publish a call for interest for the workshop? 

Do you think being familiar with github should definitely be a requirement ? How did you do in Bogotà (or other workshops)? If yes, the workshop could be really efficient; if not, could be more inclusive. Perhaps it could be stated that it is preferable for participants to already have a github account but that help could be provided during the workshop if it is not the case? Please share your views.    

What do you think? Please give it a thought and we can exchange when possible to you. Thank you in advance for your feedback.

**Comment by walshbr** [comment]
@spapastamkou - just a note about the "Intro to Augmented Reality with Unity." That one was retired recently because it doesn't work with the most recent distribution of Unity. We have an updated lesson with  a very similar name -  "Creating Mobile Augmented Reality Experiences with Unity" - that was peer reviewed on [a pull request](https://github.com/programminghistorian/jekyll/pull/974) pending some final tweaks. The text shouldn't change much or at all, though, so you might be better served working from that related lesson that is going to be released soon. Just wanted to make sure you had seen that!

**Comment by spapastamkou** [comment]
thank you very much, @walshbr, I was not aware of that. We'd better keep this lesson apart from the rest of the workshop then, to avoid complications, and work it directly with reviewers once the revised version will be ready.

**Comment by acrymble** [comment]
Thanks for these ideas @spapastamkou. It sounds like it will be very productive for your team.

I am not clear how much or what you hope participants will get out of it. Do they develop skills in translation? Are they doing it for academic credit? Or are they doing it because they want to help the project get off the ground?

It just needs to be clear to a participant if they're giving or taking (or both), so they can decide if they want to participate.

In terms of Github, I think it is easy enough to ask them to register for a free account beforehand. You can be there to help them with the logistics of using it.

I hope that's helpful.

**Comment by amsichani** [comment]
Hi all, thanks @spapastamkou for the ideas. In addition to what @acrymble notes, I d like to add a couple of thoughts

- correct me if I am wrong, but as the workshop is going to focus mainly on reviewing/finalising existing lessons' translations made by students, we need to have in place a concrete workflow for assessing these translations/submissions. It would be great to have some input here from the @programminghistorian/spanish-team , on how they deal with ES translations in terms of workflow (it might worth it to write down also some guidelines for lesson translation here) 

- As far as I can imagine, this is how a workflow might look like : you are opening on the PH/submissions a ticket "French translation of the lesson xxx"  (NB. before the workshop -you should have the beta version of the translation in hand) - students are reviewing the translation during the workshop LIVE on gh (this might be bit tricky - how many students are supposed to work simultaneously on the same translation?) - you are accepting the translation after the workshop - translation published with adequate credits  . If the students are willing to work on the translation without dealing with GH then you might need to set up a different infra / workflow in place, but I 'd be hesitant of using too many external services.

- I think it 'd make sense if you could make sure that by the workshop's date you 'll have the basic infra pages translated and the core part of the PH FR site up and running. This will facilitate the intro part of your workshop as well as your overall workings of the day, as you will be able to work but also test the FR environment. This by no means needs to stress you and @mpuren on your current work schedule, but you might want to take it into account and speed up things.

- IMHO  it would make your life easier if you work on your resources well before the workshop. By resources I mean both human resources and material ones, aka lessons. You need to know beforehand your audience (names) and make sure they are happy to work intensively (its only 3h!) on specific lessons. Some input from the recent Bogota workshop @acrymble @mariajoafana here might be useful on how you should communicate with your audience beforehand and what kind of prep you need to do. 

as I said, just thoughts - hope that's helpful. Do let me know if you need extra help.

**Comment by arojascastro** [comment]
We treat translations as tutorial submissions, that means, translators contact the managing editor proposing a translation, we assign it to her/him, we update de list of [pending translations](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md), and when we receive it, we open an issue where the reviewing process takes place, we assign an editor, we look for reviewers, etc. We adapted the guidelines for authors to include information about translations, so it became [Guidelines for authors and translators](https://programminghistorian.org/es/guia-para-autores). We argue that translations are adaptations to our community, that means that translators are second authors that can and actually do modify the original in order to make it work with Spanish resources and texts. 

I am giving a workshop in October in Barcelona: "Introduction to The Programming Historian en español workflow: sustainable writing with Markdown and versioning control with Github". I am teaching basically Markdown, a bit of Pandoc and Github. Why? Because I want the audience to know how we work and recruit authors and collaborators. I do not expect them to have a Github account but my aim is that they learn the basics so we start collaborating after the workshop. This approach may be helpful for your workshop in Lille.

**Comment by acrymble** [comment]
Having read @arojascastro 's comment, I wonder if it wouldn't be helpful to have done at least a couple of published lessons using the traditional system we have adopted, before trying to innovate? Are you confident you understand our system?

**Comment by amsichani** [comment]
many thanks for your input @arojascastro ! I wasn't aware of the subtle adaptation on the Author guidelines in order to include translators too; I do agree that this is the way to go and I can't second enough your statement "we argue that translations are adaptations to our community, that means that translators are second authors that can and actually do modify the original in order to make it work with Spanish resources and texts". 

BTW, is this the only "adaptation" you have made while building the ES infra , @programminghistorian/spanish-team ?  @programminghistorian/french-team , you should have a look on this, while building/translating the [FR infra](https://github.com/programminghistorian/jekyll/issues/836) directly from the EN.

**Comment by arojascastro** [comment]
Yes, I agree the change is very subtle... Actually, maybe it is a good chance to rethink about it and decide all if we want to separate the guidelines for authors and translators (so they have their own section). We decided not to because in the beginning we focused on translations rather than originals and they have more in common than differences. But maybe at this point of the project it would be good to differentiate them more clearly. In any case, it is another topic and should we create a separate issue.

**Comment by mariajoafana** [comment]
I agree with Antonio, maybe its time to separate the guidelines for authors and translators.

**Comment by arojascastro** [comment]
Anyone wants to open a separate issue to discuss? I think we can talk and reflect about the pros and cons. However, it means that someone will have to create two separate guidelines, rewrite the text, etc. Plus we will have some broken links. I do not want to lead the changes/conversation, so feel free to go ahead with me in the background (I am trying to work less and less).

**Comment by spapastamkou** [comment]
A big thanks to all of you for this extremely rich and useful feedback. It
helps a lot. I just take the major points one by one and add some
thoughts/infos.

- what participants will get out of the workshop - thanks @acrymble for
pointing to this: I think the main argument should be that participants
will contribute to something that would benefit to all: have
French-speaking tutorials of good quality available to everyone. The need
is very real for that and I hope it could be a good motivation together
with all other possible benefits (development of translation skills,
academic credit, participation to the project)

- concrete workflow for FR translations - thanks @amsichani and
@arojascastro for the detailed descriptions. The idea is to follow the
process followed by the ES team (one ticket for each translation with 2
reviewers). There is no reason to change the usual procedure, the only
specifity of the FR case is that there is already a corpus of translations
prepared by students of the ENC and we'd better go out find some reviewers
for these. Ideally, we should open the tickets with @mpuren before the
workshop and in concert with @PonteIneptique 's team so that the
corresponding student account for each translation gets credit for that (as
Thibault had already proposed). Also, launch a form of inscription for the
workshop where participants will declare which tutorial they wish to review
so that we do not go to the workshop blindly.


- for the ES adaptation of the author guidelines where translators are
included, I am actually aware as I check live pages both in EN and ES while
I work on the translation of the pages. If the author/translator combo
appears in ES in the pages that are ready, normally it is taken into
account but I should check again. Otherwise, it concerns mostly the page of
the author guidelines that will soon be ready (@mpuren works on it) so we
can take care to follow the ES formulation. If a separate ticket is open
for translator guidelines, I can follow and contribute but cannot be very
active at least immediately.

- just a personal note: somewhere around the end of August-beginning of
September I will be completely unavailable bcz I move into new house (exact
dates are not yet known, depend on en end of repair work under progress).
And the last week of September I am taken by a SNA summer school. So I will
do my best to finish with my pending translations before the end of this
month and to also prepare with @mpuren exactly the steps to take for the
preparation of the workshop, including contacts with the Ecole des chartes.
This would help me to work very punctually during September on these
issues, because otherwise it could be complicated.

Again, a big thanks to all for your input.

**Comment by spapastamkou** [comment]
Please note that I just opened #979 ticket that could be (in part) relevant
to the discussion on ES (and FR) adaptation of author guidelines.

**Comment by acrymble** [comment]
I won't be able to attend this I'm afraid. I have to be in the classroom that day.

Do you need any more feedback on this @mpuren and @spapastamkou or should we close this?

**Comment by amsichani** [comment]
I still need to confirm with my manager, but most probably I 'd be able to attend and help organising. @spapastamkou and @mpuren are you still interested in running this workshop and if yes, should we have a Skype meeting to discuss next steps? #girlspower

**Comment by spapastamkou** [comment]
Hey everyone, there has been a change of plans on behalf of the Humanisitca
association,  I got final confirmation today: finally, they will not host
workshops in the conference. However, this is not really a problem for our
PH workshop: the director of my establishment agrees that we host it
ourselves but this means that there will be a change in the date (which I
believe is more convenient for all of us). So, to sum up the situation: 1)
funding is available 2) I will have responsibility for the logistics of the
workshop 3) we could organize it for something like in the end of November
(or beginning of December). If you agree, we can close this ticket and, in
the basis of what we have exchanged here, I can propose dates and we fix
the one that is convenient for the largest number of us. I can do this in
the first week of October. If you prefer @amsichani, I would be glad to
agree together for the dates to propose during a skype with @mpuren and
outline the organisation of the workshop. I can make a doodle for a skype
in the first week of October (it is not possible for me before). Please let
me know and I will close this ticket tomorrow. (PS: on wednesday I start
moving out/moving in, so I will be really unavailable for some days to
come; and will be back in the office in October).

**Comment by spapastamkou** [comment]
I close this ticket and will come back on this subject in October. Thank you all for the ideas and help.
