### ISSUE TITLE
Creating network diagrams - Move Sample Datasets

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#961]
The sample data of the tutorial on Data extraction and network visualization is in the author's Google drive, and in the Spanish version is on my Google drive. For sustainability we should move this elsewhere. How do we move them to our repository?

This is the tutorial:
https://programminghistorian.org/en/lessons/creating-network-diagrams-from-historical-sources

These are the links for the sample data:
EN https://docs.google.com/spreadsheets/d/1LzbWsG73m74t3p6xE7lutfVWuOdzOIfN55FbhCCRZvk/edit#gid=77820913
ES https://docs.google.com/spreadsheets/d/1_RzqvgUs-q9fpnyc9MEH4FFYXmuGa2xOmzyEUax6kFk/edit#gid=0

**Comment by jenniferisasi** [comment]
Someone correct me if I'm wrong, but these need to be downloaded as CSV files and uploaded on the [jekyll/assets](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets) folder, updating the links both lessons.

**Comment by mdlincoln** [comment]
@jenniferisasi is correct! `/assets/creating-network-diagrams-from-historical-sources/FILE.csv` etc.

**Comment by acrymble** [comment]
Ok I've worked on this and I've made the updates on 
https://github.com/programminghistorian/jekyll/tree/issue-%23961

It's almost ready to go but I'm having trouble with the dataset file encoding. I tried downloading the datasets from google drive using the csv format (keeping with our open formats ethos). But this has caused problems on the Spanish versions of the files, because the accented characters (when opened in excel) become garbage characters. Apparently this is a mac issue with older versions of excel.

The problem does not occur if I download the file as an .xslx file.

Can someone suggest a solution so we can push these changes?

The files are in:

- https://github.com/programminghistorian/jekyll/tree/issue-%23961/assets/creating-network-diagrams-from-historical-sources

I also updated the text of the two lesson (EN/ES):

- https://github.com/programminghistorian/jekyll/blob/issue-%23961/en/lessons/creating-network-diagrams-from-historical-sources.md
- https://github.com/programminghistorian/jekyll/blob/issue-%23961/es/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas.md

**Comment by acrymble** [comment]
Possible solution: make the Spanish version of the dataset downloadable as a .xslx file, or someone with a windows machine can try to save the csv file with utf8 encoding.

**Comment by acrymble** [comment]
@mariajoafana you worked on the translation. Could you take a look at what I've attempted and see if you know a solution?

**Comment by mariajoafana** [comment]
I don't seem to be able to download the .csv files. I think that the easiest way is to view the dataset in raw and copy-paste it directly in Palladio or in Excel sheet and save it if desired
