### ISSUE TITLE
Editorial retention strategy

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#994]
Conversation starter. I'd love ideas on what we could do to try to retain our team members for as long as possible. We've got sabatticals, we have a consultative approach to decision making, we encourage people to pursue their interests.

If anyone has other ideas for making the project rewarding for editors over the long term, please share them so we can improve the environment we share.

**Comment by arojascastro** [comment]
This is an important conversation. From my point of view, what is starting to worry me a little is that contributing to the project requires a lot of time - time that I cannot invest on writing and publishing papers on the project itself. For me, a condition to keep working on it in the future will be that the experience allowed me to reflect, write and publish papers/articles. I do not know if someone else thinks the same?

**Comment by walshbr** [comment]
@arojascastro seems like we have sabbaticals for people to take time away from the project entirely. Maybe we should also think about a version of those that make space for the kind of research work you're describing? In other words, in addition to taking several months off just because you need several months off, we might explicitly encourage people to take sabbaticals with the aim of publishing / applying for grants related to the project. So something more like a traditional sabbatical in addition to the version we currently have.

**Comment by acrymble** [comment]
Sounds like what @arojascastro is saying is that he needs it to be more centrally linked to his job or his future. One possible way to do that for certain people (depending on their employment status) is to "buy" some of their time. Maybe 10% of their contract for a year. Then their employer immediately starts to see value in the project, and it frees up their time to do this during the working day. I don't know if that would cause tension though, if some people had this and others didn't. It would be more economically viable in certain countries (eg, in Latin America) where costs are lower.

**Comment by arojascastro** [comment]
Well, not exactly. I don't hold a teaching position at the moment. I am paid for developing projects, not for doing strict and conventional research. So my current employer doesn't care about my involvement in the PH - it is not relevant. However, I would stay longer if the project allowed me to write articles and organize scholarly events that permit me to apply for more "conventional" jobs - teaching and research - rather than project development. Does it make sense?

**Comment by acrymble** [comment]
Ok. Can you help us understand how it doesn't do that? I've been trying to encourage people to apply for grants for years, and no one seems to want to. Same with the research. Is there a sense that it's not what we want from the editorial team?

**Comment by arojascastro** [comment]
Mostly lack of time - that is why I'm taking a sabbatical now :)

**Comment by drjwbaker** [comment]
Thanks for starting this @acrymble. One thing I've been thinking off recently is the work that goes into taking a sabbatical: I feel after a year that I now fully **get** the project (technical, editorial, managerial, interpersonal), and I fear that taking time away would only lead to me losing track, and having to invest quite a bit of time in catching up. Which is to say that with our present setup if I had to make some tough decisions in the next year or so about what I work on, I'd rather leave PH than take a sabbatical. I *obviously* don't want to leave PH, so I'm wondering how we come to consensus about a third way: for example, editors with specific defined roles + involvement in all policy issues but who don't take on lesson editing duties for a bit whilst they take a half-step back. I sense that we kinda already do this, but if we could say "For the next 6 months is it okay that I don't edit lessons" and document that somewhere, then we can ensure fairness. I should say not editing lessons isn't the only thing we might agree folks could take a step back from, but I suspect getting involved in policy issues is a minimum engagement we'd expect from a semi-sabbaticaled editor.

**Comment by acrymble** [comment]
Related to @drjwbaker 's idea, maybe we need a clearer option that some people ONLY want to do editorial work, and want to leave these discussions to other people? They can certainly be time consuming.

--
Updated thought:

It's not just the discussions that are time consuming. Checking over pull requests (technical team), etc, is not for everyone. So having clearer roles so that people can opt into and out of tasks might make it a better experience, and lets us build a team that covers all of our needs.

**Comment by drjwbaker** [comment]
I enjoy our time consuming discussions 😃

**Comment by mdlincoln** [comment]
A few thoughts from your technical editor:

Over the last few year as we closed off a really major shift in the full redesign of the site and strengthening our editorial workflows, I've been deliberately trying to step back from solving every little technical problem, particularly WRT the most routine pull request work of publishing new lessons and fixing typos. While this was bumpy at first, I'm glad to see that more members of the editorial team seem comfortable initiating and completing this work without my intervention. Happily, I was able to pretty much ignore _PH_ for the last month while I was moving to a new city and new job, and nothing exploded! This is a good thing, not just for the editorial board broadly, but for my own mental health.

In the longer term, I am mindful of the continuing work brought up by the constant influx of "can we do this?" "what if we do that?" "wouldn't it be cool if?", a tempo of change that we discussed in part in #789. This is not to say that these ideas are without merit - for example, full text search (#1018) would be an excellent addition. But I'll also say right now that I will _not_ be building that, at least not within the next 6-8 months. Merging in the French translations will be a significant (but acceptable!) amount of work, and it's my most concrete priority and will easily consume the time I've earmarked for PH over the next few months. I'm perfectly happy with that calculus, and I hope that the team understands that it's not just me being dyspeptic! But more than that, I'd be very glad if other members of the board stepped up to work on doing first-draft implementations of these desired features _if_ they feel they are important enough to develop. I would of course be very happy to review and workshop those PRs with them, but I'd appreciate being able to take an editorial role rather than an authorial role on some of this technical work.

My other, non-technical concern is that I still see a pretty constant stream of changes being proposed to core pages like the editorial and author guidelines, even in light of our discussions with #789. The number of open issues and PRs appears to show an understandable strain on the Spanish team, and we're only going to compound this with new French versions of everything. Are we being realistic in our work estimates for these changes and edits to core pages? Should we be a bit more disciplined about letting things lie even when they're not completely ideal?

**Comment by drjwbaker** [comment]
Thanks for this @mdlincoln: I'm heartened that you see progress in our (though probably not my..) overall competence to run the site without your constant input, and concur on the concern over 'doing new things'. My sense of the latter is that a revised landing page (the redo of https://github.com/programminghistorian/jekyll/pull/914) should be our sole technical/design update for now.

On translation of core pages, I'm less close to this. I recall that early in the FR onboarding discussion we proposed parking any non-urgent updates until FR were ready, but this seems to have not been the direction we took. For example, we agreed to push on with https://github.com/programminghistorian/jekyll/issues/651 (which I agreed on) but perhaps we need to take stock of whether all the small changes you mention are sufficiently urgent and whether in turn addressing this might contribute to retention.

**Comment by amsichani** [comment]
Thanks all for your thoughts (BTW- I am also enjoying our time consuming discussions). I took some time to reflect on this .

In fact, if I m reading it correctly,  there is a twofold issue behind @arojascastro 's claim (and I would like somehow to insist on the first aspect):

1)How  can we formalise our PH editorial work and involvement in our CV and in our everyday professional/academic life in a way that it would count for (all types) of (traditional academic and alt-ac) jobs?
Even if career progression and digging into the academic market might vary between countries, institutional systems and from person to person, I d suggest that we might need to find/establish a way to evaluate & cleverly formalise it so that we got our backs covered,  esp for people currently struggling to get credit in their institutional environment for this type of (hybrid academic but not so unusual for DH) work. Eg. PH is a peer review OA journal, and editing such a type of journal is something people are usually placing on their signature or CVs. Are there other ways of making this work more explicit and more impact-driven ? I 'd personally say to try make your involvement visible in everyday terms to your working environment/community, eg stickers, small workshops on PH, original research outputs that link your research interests & PH  etc.
Given this, I am a bit skeptical on @arojascastro 's point: "I would stay longer if the project allowed me to write articles and organize scholarly events that permit me to apply for more "conventional" jobs - teaching and research - rather than project development". If we, with our PH hats on, are here also to creatively re-think about digital scholarship and pedagogy, we should invent / imagine how we could use our PH involvement in order to (help us) get any position we wish to, from conventional academic roles to dev start-ups 

2)What kind of working conditions/arrangements could we set up in order to fit various people's work roles/positions (traditional academic, research/teaching based or alt-ac)? 
This is also a very vague and subjective issue; as PH runs on a voluntary basis, is basically on each of us to find out her own way of working on the PH, customise it around job duties, other commitments etc. I second that it might be useful to have a variety of involvement's levels, between the full stack editor and leave status. I wouldn't recommend  to propose fixed levels/roles but to actively encourage our editors to feel free to propose their own level of engagement for certain periods, if needed so (eg. writing a research article on PH, organising a PH workshop, writing up a bid etc).

**Comment by amsichani** [comment]
An "informal mentoring scheme" from senior PH editors/colleagues to people (like me!) who feel that they need this type of support/guidance in order to formalise their PH involvement CV-wise or for their managers was proposed during our Skype meeting. I can't second this idea enough! 

Please feel free to volunteer here as a "mentor". Feel free to grab your mentor and ask for advise on this front, if needed, through a private email conversation.

**Comment by drjwbaker** [comment]
Without wishing to declare myself an expert on this, I'm happy to mentor fellow editors.

**Comment by walshbr** [comment]
One thing that was mentioned in passing (can't recall who said it unfortunately!) that I want to signal boost - the mentoring needed is probably geographically and institutionally specific. Libraries have different priorities from academic departments, and my situation in America would be different from elsewhere in the world. I'm happy to volunteer if someone is in a library, though also not sure how well I've managed this vs. the good fortune of my current reporting structure.

**Comment by acrymble** [comment]
What about a Wiki page where we can start to share some ideas and strategies that people can try with their various contexts? That would give us a way to record those ideas and close this ticket productively.

**Comment by acrymble** [comment]
I have made a Wiki page where I've added some of my ideas https://github.com/programminghistorian/jekyll/wiki

Please contribute to this so that we can have some rich advice for our teammates.
